### ISSUE TITLE
Unpublish does not work

### ISSUE THREAD

**Issue by PiLoT650** [MISP/PyMISP#1012]
Hello, i tried to unpublish events via misp.unpublish(ID)

evt_result = cytomicobj.misp.search(controller='events',  limit=1, deleted=False, published=True, pythonify=True)
for evt in evt_result:
print(evt['id'])
evt = cytomicobj.misp.get_event(event=evt['id'], pythonify=True)
result = cytomicobj.misp.unpublish(evt['id'] ) # UnPublish Event
print(result)

The result is success - but the event won't get unpublished.

`{'saved': True, 'success': True, 'name': 'Job queued', 'message': 'Job queued', 'url': '/events/publish/2998', 'id': '2998'}`

If you look at the url: events/_publish_ - shouldn't this be: events/_**UN**publish_?

EDIT: 
Is it maybe this?
https://github.com/MISP/PyMISP/blob/main/pymisp/api.py#L453
I tried changing line 453 in my local api.py file - but it still calls /events/publish.
Do i have to change this in another file - or am i wrong on this?

**Comment by PiLoT650** [comment]
Okey, thank you very much. It's  still trying "publish" not "unpublish" - fiddling arroung with reinstalling pymisp the right way - i guess.

**Comment by Rafiot** [comment]
if you cloned it, just run `pip install -e .` from the directory you installed it in.

**Comment by PiLoT650** [comment]
Thank you - it's working now - had to do it without -e - don't know why.

With -e i got this error:
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /var/www/MISP/PyMISP
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)

**Comment by Rafiot** [comment]
that error is probably because you need a newer pip. but if it works, all good.

I'll package a new release soon.
