### ISSUE TITLE
add_event behaves really unexpected, returning a description(?)

### ISSUE THREAD

**Issue by mrtzhsmnn** [MISP/PyMISP#1034]
## Expected Behavior
add_event should return a dict representing an event.
When running with `pythonify=True`, no Exception should occur.

## Current Behavior
Returns a dict not representing an event, also fails, when you try running it with `pythonify=True` for obvious reasons.
This is the response you get when running `add_event` without `pythonify=True`:
```
{
    "name": "/events/add API description",
    "description": "POST a MISP Event JSON to this API to create an Event. Contained objects can also be included (such as attributes, objects, tags, etc).",
    "mandatory_fields": [
        "info"
    ],
    "optional_fields": [
        "threat_level_id",
        "analysis",
        "distribution",
        "sharing_group_id",
        "uuid",
        "published",
        "timestamp",
        "date",
        "Attribute",
        "Object",
        "Shadow_Attribute",
        "EventTag"
    ],
    "url": "/events/add"
}
```

## Steps to Reproduce
```py
def _create_event(self, family:str) -> MISPEvent:
    """
    This method can be used to create an event
    :param family: the malwares family
    :type family: str
    :return: the freshly created MISPEvent
    """

    event = MISPEvent()
    
    event.info = "foo"
    event.distribution = 0
    event.threat_level_id = 2
    event.analysis = 1
    event.add_tag(f"family:{family}")
    event.publish()

    event = self.misp.add_event(event=event)

    print(event)    
    
    return event
```
1. Try creating an event with the method above 
2. get Dict (see above)

## Context (Environment)
Server version: MISP 2.4.159
PyMisp version: 2.4.173
### Edit (31.07.2023)
Tried the same with PyMisp version 2.4.159 (same release date as the MISP version)
Behaviour unchanged.

**Comment by Rafiot** [comment]
This is very odd, but the MISP version you're using is extremely old. Can you update it and give it a shot? (or try using a similarly old version of PyMISP)

**Comment by mrtzhsmnn** [comment]
I am sadly not the admin for our test environment, also the MISP version is not that old, (from May 30th 2022) are you sure this is the reason for the error?

I removed the currently installed PyMisp version and installed the `PyMisp 2.4.159`  version, (also from May 30th 2022).

The error persists and the behavior is unchanged.

**Comment by Rafiot** [comment]
The version you're using is as your pointing out over a year old, and [ridden with vulnerabilities](https://www.misp-project.org/security/) so you should absolutely update it.

With the code above, the error I'm getting is this one:

```python
{'errors': (403,
  {'saved': False,
   'name': 'Could not add Event',
   'message': 'Could not add Event',
   'url': '/events/add',
   'errors': {'Event': 'Received a published event that was empty. Event add process blocked.'}})}
```

Which makes sense. If I remove `event.publish()`, it works as expected and creates an event.

**Comment by mrtzhsmnn** [comment]
For me the error persists, no matter if I remove `event.publish()` or add an object with attributes, so that the event isn't empty anymore.

**Comment by Rafiot** [comment]
Okay. Can you ask the sysadmin of your test environment to update MISP, and let me know if you still have the issue? I cannot debug old MISP releases. It should work, but we might very well have had a bug at the time.

**Comment by mrtzhsmnn** [comment]
The problem is solved, I'm afraid to admit, that I tried using an `http` and not an `https` URL.

This somehow resulted in the issue above.

**Comment by saibamo** [comment]
> You saved me hours of debugging, thx a lot

Glad others can learn from my mistakes lol.
