### ISSUE TITLE
update_sharing_group does not update Sharing Group parameters

### ISSUE THREAD

**Issue by emuradov** [MISP/PyMISP#1049]
As part of some data organisation effort, I have been attempting to use the update_sharing_group function to make modification certain sharing groups. After making multiple attempts, I cannot get MISP to recognize the changes made to fields such as the name, description or UUID (I know UUIDs are not meant to be changes but this is just highlighting the problem).

Below is a small sample code I have made. This follows the same logic as one would use to change event info or something similar. Pull the specific object, make changes, use the update function.

```
sg = misp.get_sharing_group(sharing_group=id, pythonify=True)
sg.name= sg.name+" MODIFIED"
sg.description = sg.description+" MODIFIED"
result = misp.update_sharing_group(sharing_group=sg, sharing_group_id=id, pythonify=True)
sg = misp.get_sharing_group(sharing_group=id, pythonify=True)
print(sg, sg.description)
<MISPSharingGroup(name=Test_SG)> This is a test
```

Is there something that I am missing here or is this a problem on the PyMISP side?

**Comment by Rafiot** [comment]
Confirmed, I'm investigating.

If you want a quick and dirty fix you can do that:

```
sg = misp.get_sharing_group(sharing_group=id, pythonify=True)
result = misp.update_sharing_group({"name": "blah"}, sg, pythonify=True)
```

But your code should work too, so it is a bug on our side.

**Comment by Rafiot** [comment]
Or you just wait for the next release for PyMISP (very probably today).
