### ISSUE TITLE
event.add_attribute_tag doesn't change anything on the server

### ISSUE THREAD

**Issue by Dan-Vizor** [MISP/PyMISP#1052]
I'm trying to add an existing tag to an attribute with add_attribute_tag, the code runs without error however no changes are made to the event or attribute on MISP.

Am I missing something I need to do to push up the change?

**Comment by Dan-Vizor** [comment]
Update: Printing what add_attribute_tag returns shows the attribute with the tag added. Do I need to upload this in some way?

![Screenshot 2023-08-29 151534](https://github.com/MISP/PyMISP/assets/28623546/28b6f450-ea8c-4bdb-9535-c22bba2a6dfe)

**Comment by Rafiot** [comment]
yes, you need to use `update_event` from the PyMISP class. MISPEvent/MISPAttribute and alike are all in memory only.

If you need more support, please share a code snippet.

**Comment by Dan-Vizor** [comment]
thanks, it's working now
