### ISSUE TITLE
Maybe the "|" should be replaced by the new key?

### ISSUE THREAD

**Issue by adulau** [MISP/PyMISP#106]
https://github.com/MISP/PyMISP/blob/2bc0745fbf9db54adca649479802d0a9a6ec21f0/pymisp/tools/peobject.py#L109

**Comment by Rafiot** [comment]
https://github.com/MISP/PyMISP/blob/objects/pymisp/tools/peobject.py#L109

Done. Again, hate hate hate the two repositories... :)
