### ISSUE TITLE
assigning tags to attributes older than 'x' days

### ISSUE THREAD

**Issue by Moorocks** [MISP/PyMISP#1060]
Hi Team, 

I tried to write a custom script to check if tags can be assigned to attributes that were published today.

However it is not getting executed as expected.

Now i want to make this change and execute it to attributes older than 30 days.

-----Code------------------------------------------------------
``` python
import re
import os
import sys
import urllib3
import ssl
import base64
from pymisp import PyMISP, MISPEvent, MISPAttribute, pymisp_json_default, ExpandedPyMISP
from keys import misp_url, misp_key, misp_verifycert
from datetime import datetime,date
import hashlib

# Connect to MISP instance
api = ExpandedPyMISP(misp_url, misp_key, ssl=misp_verifycert)

# Get the current date
current_date = date.today().isoformat()

#Search for attributes created today
search_result = api.search(controller='attributes', datefrom=current_date, dateto=current_date)

# Check if the search was successful
if 'Attribute' in search_result:
    # Iterate over the search results
    for attribute in search_result['Attribute']:
        attribute_id = attribute['id']
        attribute_value = attribute['value']
        
        # Add a tag to the attribute
        api.tag(attribute_id, "expired")
        
        print(f"Added tag to attribute: ID={attribute_id}, Value={attribute_value}")
else:
    print("No attributes found for today.")

```

**Comment by Rafiot** [comment]
Few things:
* `datefrom` and `dateto` don't exist (should be `date_from` and `date_to`), and only for the events controller (not attributes)
* `date_from` and `date_to` are checking against the `date` field in the metadata of the event. It is set by the user. You probably want to use `timestamp` instead, and pass a tuple for an interval `(firstdate, lastdate)`
* depending on the role of the user you're using, you may not be able to create a new tag (make sure the "expired" tag exists on the platform).

And then, please look at the responses of the requests, they often contain messages if something goes poorly.
