### ISSUE TITLE
Please keep the changelog up to date

### ISSUE THREAD

**Issue by wagner-certat** [MISP/PyMISP#107]
The last two entries are
* %%version%% (unreleased)
* v2.4.71 (2017-04-11)

while the current release is 2.4.79

**Comment by adulau** [comment]
Thank you very much for the feedback. We forgot to update the one from the repository. 

https://github.com/MISP/PyMISP/commit/d29a3a9cc2378e070ae86bcef9b5c767101bad17

**Comment by wagner-certat** [comment]
If there is little interest in having a changelog, please just communicate it clearly. Thanks.

**Comment by wagner-certat** [comment]
The changes in 38a488c70c4fe19a0d0d6fafdf67074f54d980e4 and 8e50ee825b93f3f19f7d70a2eee41b9a89165e95 are candidates for a changelog for example

**Comment by wagner-certat** [comment]
It's again out of date
