### ISSUE TITLE
Misp_verifycert is not implemented into examples

### ISSUE THREAD

**Issue by ater49** [MISP/PyMISP#108]
Hi,

During test, I saw in examples that "misp_verifycert" (one of keys.py value) isn't used when calling PyMisp.

Could you update Examples files ?

**Comment by iglocska** [comment]
Hello,

Indeed, the example scripts are just meant as some examples to be used and modified - more of a starting point to get the users going on writing pymisp scripts. Feel free to play around with them, modify them and retro-fit them to suit your needs better!
