### ISSUE TITLE
PyMISP.search_index() is broken with MISP 2.4.80

### ISSUE THREAD

**Issue by beberlacrapule** [MISP/PyMISP#109]
Hi,

PyMISP.search_index() is broken when used on a MISP 2.4.80 (it always worked with prior versions). The bug seems to happen with any version of PyMISP (tried with 2.4.71 and after upgrade to 2.4.80).
Here's the message returned by MISP:
`The request has been black-holed`

Tried manually with curl, it's working.

**Comment by iglocska** [comment]
Please update your MISP to the latest commit, make sure you also update the submodule. This was fixed a few minutes ago and had to do with a new feature in cakephp - so we've reverted to the version before.

**Comment by beberlacrapule** [comment]
Great, Thanks

**Comment by iglocska** [comment]
No worries, sorry for the inconvenience.
