### ISSUE TITLE
Return value does not respect the parameter `expanded=True`

### ISSUE THREAD

**Issue by mateodurante** [MISP/PyMISP#1099]
https://github.com/MISP/PyMISP/blob/cb5f68a93226307f307fdda9ae6611046651d16d/pymisp/api.py#L2262

This line returns a simple value and does not respect the 'expanded=True' parameter. Anyway, it seems like it should raise an exception.

The issue is that when encountering an error connecting to MISP, such as:
```
  File "/opt/intelmq/.local/lib/python3.9/site-packages/pymisp/api.py", line 210, in __init__
    self._current_user, self._current_role, self._current_user_settings = self.get_user(pythonify=True, expanded=True)
  File "/opt/intelmq/.local/lib/python3.9/site-packages/pymisp/api.py", line 2263, in get_user
    raise Exception(str(user_j))
Exception: {'errors': (403, {'name': 'It is not possible to use this Auth key from your IP address', 'message': 'It is not possible to use this Auth key from your IP address', 'url': '/users/view/me'})}
```
It [encapsulates the raised error](https://github.com/MISP/PyMISP/blob/cb5f68a93226307f307fdda9ae6611046651d16d/pymisp/api.py#L212) preventing the generation of a descriptive exception raising this:
```
...
  File "/opt/intelmq/.local/lib/python3.9/site-packages/pymisp/api.py", line 212, in __init__
    raise PyMISPError(f'Unable to connect to MISP ({self.root_url}). Please make sure the API key and the URL are correct (http/https is required): {e}')
pymisp.exceptions.PyMISPError: Unable to connect to MISP (https://your.url/). Please make sure the API key and the URL are correct (http/https is required): not enough values to unpack (expected 3, got 1)
```

**Comment by Rafiot** [comment]
Good point regarding `expanded=True`, I'm updating the documentation accordingly.

And regarding the error message, I added a specific workaround that should properly bubble up the issue, thanks for the report!
