### ISSUE TITLE
New dependencies?

### ISSUE THREAD

**Issue by wagner-certat** [MISP/PyMISP#110]
The test suggest that pydeep and python-magic are new dependencies or at least recommended requirements. If they are, these package names should be mentioned in setup.py's `install_requires` or `extra_requires`.

And pydeep does not have a stable release, not a release and not on pypi. The latest release 0.2 is from 2013, 4 years ago. That supports up to python 2.6!

**Comment by Rafiot** [comment]
They are only recommended, And I'll update setup.py.

The only working version of pydeep is the one you get from the git repo: 
`pip install git+https://github.com/kbandla/pydeep.git`

**Comment by wagner-certat** [comment]
> The only working version of pydeep is the one you get from the git repo:

Which is a "not very satisfying" situation.

**Comment by Rafiot** [comment]
Well, the alternative would be to bundle it in pymisp, or not generating ssdeep hashes (again, it's optional).

**Comment by Rafiot** [comment]
(I didn't mean to close it)

**Comment by wagner-certat** [comment]
I opened kbandla/pydeep#16

**Comment by Rafiot** [comment]
And as we are at it: using the trunk of lief is currently required, the release 0.7 has a bunch of bugs that are fixed in 0.8 (to me released in the coming weeks).

**Comment by wagner-certat** [comment]
> And as we are at it: using the trunk of lief is currently required, the release 0.7 has a bunch of bugs that are fixed in 0.8 (to me released in the coming weeks).

Which software are you talking about?

**Comment by Rafiot** [comment]
This one : https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.7.0.dev.zip

--> https://lief.quarkslab.com/

**Comment by wagner-certat** [comment]
Ah, the other new dependency mentioned in the travis file.

If there's a working stable version, please add a version specifier with the minimum working version in the setup.py file.

**Comment by Rafiot** [comment]
There is no known working release yet, 0.8 isn't out.

I'll update the minimum working version as soon as it's available.

**Comment by Rafiot** [comment]
Done: https://github.com/MISP/PyMISP/blob/master/setup.py#L31
