### ISSUE TITLE
Bug: `update_event()` with `add_event_report()` doesn't add a report to existing Event

### ISSUE THREAD

**Issue by mdavis332** [MISP/PyMISP#1112]
MISP version: 2.4.178
PyMISP version: 2.4.178

## Steps to reproduce

```python
from pymisp import PyMISP

remote = 'http://misp-server:port'
token = 'api key'
verify_ssl = False

client = PyMISP(remote, token, verify_ssl)

# use existing event without a report
event_uuid = 1122
misp_event = client.get_event(event_uuid, pythonify=True)
# update local MISPEvent() obj w/ report
misp_event.add_event_report(name='test', content='test content')
# update event
result = client.update_event(misp_event)

# Verify on MISP instance that Event still doesn't have a report
```

However, if I'm adding a brand new event, the above steps with `result = client.add_event(misp_event)` (instead of `update_event`) work just fine to create a new Event with the expected report.

**Comment by Rafiot** [comment]
@mokaddem is it supposed to be possible over the API? It probably should, but before I start investigating, I refer ask you.

**Comment by mokaddem** [comment]
Did a fix regarding that endpoint in https://github.com/MISP/MISP/commit/618dbb64cf3d2f216da10b101b9c0ec38caf2b06.
Could you try again and report back if it still doesn't work? Thanks!

**Comment by Rafiot** [comment]
Great, thanks!
