### ISSUE TITLE
Enhancement: PyMISP API Custom HTTPS Adapters

### ISSUE THREAD

**Issue by malvidin** [MISP/PyMISP#1118]
To use Mutual TLS, something like [cedric-dufour/m2requests](https://github.com/cedric-dufour/scriptisms/blob/master/misc/m2requests.py) can be used, but it cannot be injected into the API easily. 

Adding an https_adapter option (even hiding it in kwargs) would make mutual TLS easier to implement in the PyMISP API.

```python
    def __init__(self, url: str, key: str, ssl: bool = True, debug: bool = False, proxies: Optional[MutableMapping[str, str]] = None,
              cert: Optional[Union[str, Tuple[str, str]]] = None, auth: Optional[AuthBase] = None, tool: str = '',
              timeout: Optional[Union[float, Tuple[float, float]]] = None,
              http_headers: Optional[Dict[str, str]]=None, https_adapter: Optional[requests.adapters.BaseAdapter] = None
              ):
        ...
        ... 
        self.__session = requests.Session()  # use one session to keep connection between requests
        if https_adapter is not None:
            self.__session.mount('https://', https_adapter())
```

vs. 

https://github.com/MISP/PyMISP/blob/190f82923687cebaf06138724e7c03239e529cb4/pymisp/api.py#L157-L176

**Comment by Rafiot** [comment]
I don't mind. Can you do a pull request?
