### ISSUE TITLE
Adding "indent" param to AbstractMISP.to_json()

### ISSUE THREAD

**Issue by infosec-intern** [MISP/PyMISP#113]
I keep getting the error `TypeError: Object of type 'MISPObject' is not JSON serializable` when running `print(json.dumps(misp_object, indent=2))`. Looks like there isn't a way to do a json.dumps() call on any MISPObject instances if I want to add extra indentation for prettier printing, I'll need to roll my own method instead (example below). It might be nice to have this functionality baked into the AbstractMISP class's to_json() function with an optional "indent" parameter. 

@Rafiot do you think it's worth it to add that in for an admittedly minor use case. If so, I can submit a PR.

Example:
```
    import copy
    misp_json = copy.deepcopy(misp_object)
    misp_json = misp_json.to_dict()
    for i, attr in enumerate(misp_json["Attribute"]):
        misp_json["Attribute"][i] = attr.to_dict()
    print(json.dumps(misp_json, indent=2))
```

Proposal:
```
print(misp_object.to_json(indent=2))
```

**Comment by Rafiot** [comment]
All the class inheriting from `MISPObject` (that mean `MISPEvent`, `MISPAttribute`, `MISPObject`, `MISPObjectAttribute`, `MISPObjectReference`) are jsonifiable if you do it this way:

```python
import json
from pymisp import MISPEvent, MISPEncode

my_misp_thing = MISPEvent()
# ....
json.dumps(my_misp_thing, cls=MISPEncode, indent=2)

```

**Comment by infosec-intern** [comment]
That's a much better solution. Thanks!
