### ISSUE TITLE
Email parsing for email-body attribute is broken from PyMISP v2.4.184 to v2.4.184.2

### ISSUE THREAD

**Issue by samitainio** [MISP/PyMISP#1150]
@Rafiot Something broke between PyMISP v2.4.183 and v2.4.184 in regards to the email-body parsing:

| PyMISP release version | Status |
|-|-|
| v2.4.183 | Working |
| v2.4.184 | Broken |
| v2.4.184.1 | Broken |
| v2.4.184.2 | Broken |

Email message was uploaded to MISP via the Python script available from examples/add_email_object.py

Here it is working correctly with the v2.4.183:
![Pymisp 2 4 183](https://github.com/MISP/PyMISP/assets/5585477/8806cb43-0498-4d0c-aec7-ab0e7f227578)

Here it is broken showing email headers instead of the email body with the v2.4.184 and I also tested with point releases:
![kuva](https://github.com/MISP/PyMISP/assets/5585477/83240806-784a-474c-b360-4eccc62bcb77)

I also tested to change the script examples/add_email_object.py to use: 
```
import pymisp
...
pymisp = pymisp.api.PyMISP(misp_url, misp_key, misp_verifycert, debug=True)
```

Instead of the deprecated - btw this is still in the main version of the example file should probably update it at some point:
```
from pymisp import ExpandedPyMISP
...
pymisp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert, debug=True)
```

But it had no effect on the email-body parsing.

**Comment by Rafiot** [comment]
Can you share a sample? The email test suite works, so it's odd: https://github.com/MISP/PyMISP/blob/main/tests/test_emailobject.py

**Comment by Rafiot** [comment]
Ok, I also have a difference between the two versions, but only related to the decoding of the body itself. I'm working on that and wait for a sample from you to investigate.

**Comment by Rafiot** [comment]
The issue I had is fixed by https://github.com/MISP/PyMISP/commit/e6cb8552c564fca4daeddd636ce9ca38cfa19117 - release later today.
