### ISSUE TITLE
PyMISP.toggle_warninglist() sends GET method

### ISSUE THREAD

**Issue by framontb** [MISP/PyMISP#1158]
I'm doing a simple script to test my new MISP installation.
What it does is toogle the 'enabled' state of a warninglist, like this:

```
from pymisp import PyMISP
from keys import misp_url, misp_key, misp_verifycert
from pprint import pprint

if __name__ == "__main__":

    pm = PyMISP(url=misp_url, key=misp_key, ssl=misp_verifycert, debug=True)

    #DISABLE WARNINGLIST 88
    result = pm.toggle_warninglist(88)    
    pprint(result)
```

The thing is, I get the followin error:
`
{'errors': 'This function only accepts POST requests.', 'saved': False}
`

The apache2 logs are pretty clear:
```
175.31.64.1 - - [20/Feb/2024:19:58:28 +0000] "GET /servers/getVersion HTTP/1.1" 200 3903 "-" "PyMISP 2.4.185 - Python 3.12"
175.31.64.1 - - [20/Feb/2024:19:58:29 +0000] "GET /users/view/me HTTP/1.1" 200 3374 "-" "PyMISP 2.4.185 - Python 3.12"
175.31.64.1 - - [20/Feb/2024:19:58:29 +0000] "GET /attributes/describeTypes.json HTTP/1.1" 200 23632 "-" "PyMISP 2.4.185 - Python 3.12"
175.31.64.1 - - [20/Feb/2024:19:58:29 +0000] "GET /warninglists/toggleEnable HTTP/1.1" 200 1280 "-" "PyMISP 2.4.185 - Python 3.12"
```

The `pm.toggle_warninglist(88)` method is sending a `GET` method in the request. I don't know why. Someone knows ?

-------------------------------------------------------
If I instead use the following script, all works fine:
```
relative_path = 'warninglists/toggleEnable'
warning_list_id=88
body = {
    "id": warning_list_id,
}

from pymisp import PyMISP

misp = PyMISP(misp_url, misp_key, misp_verifycert)
result = misp.direct_call(relative_path, body)
pprint(result)
```

Printed: `{'saved': True, 'success': '1 warninglist(s) disabled'}`

Apache Logs (see the POST):
```
175.31.64.1 - - [20/Feb/2024:20:17:53 +0000] "GET /servers/getVersion HTTP/1.1" 200 3903 "-" "PyMISP 2.4.185 - Python 3.12"
175.31.64.1 - - [20/Feb/2024:20:17:53 +0000] "GET /users/view/me HTTP/1.1" 200 3374 "-" "PyMISP 2.4.185 - Python 3.12"
175.31.64.1 - - [20/Feb/2024:20:17:54 +0000] "GET /attributes/describeTypes.json HTTP/1.1" 200 23632 "-" "PyMISP 2.4.185 - Python 3.12"
175.31.64.1 - - [20/Feb/2024:20:17:54 +0000] "POST /warninglists/toggleEnable HTTP/1.1" 200 1263 "-" "PyMISP 2.4.185 - Python 3.12"

```
-------------------------------------------------------
Client Versions:
* PyMISP 2.4.185
* Python 3.12
*  Windows 11 Pro

Server Versions:
* Ubuntu 22.04

**Comment by Rafiot** [comment]
This is a mysterious and very weird issue you're having here. The code hasn't been changing for the last 5 years, and I cannot reproduce it on my end (the request is a POST).

It is also passing fine in the test suite.

I have no idea where to start here. Maybe try other calls (like adding an event, that will also trigger a POST) and see if that works?

**Comment by framontb** [comment]
> This is a mysterious and very weird issue you're having here. The code hasn't been changing for the last 5 years, and I cannot reproduce it on my end (the request is a POST).
> 
> It is also passing fine in the test suite.
> 
> I have no idea where to start here. Maybe try other calls (like adding an event, that will also trigger a POST) and see if that works?

Thanks, I will try some more calls to figure out and report.

**Comment by framontb** [comment]
Finally I did some debugging, and figure out what's happening.
The parameter value `misp_url` was not the same for the two scripts.
The bad one pointing to `http` while the good one pointing to `https`.
When debugging I saw some weird redirections that lead me to my mistake.
The issue can be closed.

**Comment by framontb** [comment]
**Solved**: user bug (no PyMISP bug)

**Comment by framontb** [comment]
Solved: user bug (no PyMISP bug)
