### ISSUE TITLE
PyMISP.disable_warninglist() doesn't disable, but toggle instead

### ISSUE THREAD

**Issue by framontb** [MISP/PyMISP#1159]
I implemented the following script to test the `PyMISP.disable_warninglist()` method:

```
    with Misp(**data_task) as misp:

        # GET WARNINGLIST - "pm" stands for PyMISP
        wl = misp.pm.get_warninglist(warninglist_test_id, pythonify=True)
        print("*** Warninglist Initial state ***")
        pprint(f"Id: {wl.get('id')} | Name: {wl.get('name')} | Enabled: {wl.get('enabled')}")

        # ENABLE WARNINGLIST
        print("\n==> ACTION: Disable Warninglist ***\n")
        wl = misp.pm.disable_warninglist(warninglist=warninglist_test_id)

        # GET WARNINGLIST
        wl = misp.pm.get_warninglist(warninglist_test_id, pythonify=True)
        print("*** Warninglist Final state ***")
        pprint(f"Id: {wl.get('id')} | Name: {wl.get('name')} | Enabled: {wl.get('enabled')}")
```

The output of the script is like that:
```
$ test_misp_warninglist_disable

2024-02-21 14:09:14 - INFO - Start the execution of the task 'test_misp_warninglist_disable'
*** Warninglist Initial state ***
'Id: 123 | Name: Test| Enabled: False'

==> ACTION: Disable Warninglist ***

*** Warninglist Final state ***
'Id: 123 | Name: Test| Enabled: True'
```

Here, you can observe that the Warninglist was disabled at first, but was enabled after calling `PyMISP.disable_warninglist()`.

---------------------------------------------------------------------

The bug is in the method `PyMISP.disable_warninglist()` itself:

```
    def disable_warninglist(self, warninglist: MISPWarninglist | int | str | UUID) -> dict[str, Any] | list[dict[str, Any]]:
        """Disable a warninglist

        :param warninglist: warninglist to disable
        """
        warninglist_id = get_uuid_or_id_from_abstract_misp(warninglist)
        return self.toggle_warninglist(warninglist_id=warninglist_id, force_enable=False)
```

You can see the call `self.toggle_warninglist` with the param `force_enable=False`. What this `force_enable` param means is:
>:param force_enable: Force the warning list in the enabled state (does nothing if already enabled)

That is to say, it forces **enable** when _True_, but it doesn't force **disable** when _False_, and hence the method fails.
What it does at the end is a simple wrapper for `PyMISP.toggle_warninglist`.
In my view, when calling `PyMISP.disable_warninglist()` the final result should be the warninglist being disabled.

**Comment by Rafiot** [comment]
that is true... the `enabled` key is only passed if `True`. I'm changing that.
