### ISSUE TITLE
Is it possible to change the timestamp for an attribute programatically?

### ISSUE THREAD

**Issue by framontb** [MISP/PyMISP#1161]
Is it possible to change the timestamp field for an attribute programatically?
I think I tried everything without results. For example:

- misp.update_attribute(attribute)
- response = requests.put(url, headers=headers, data=json.dumps(data))

**Comment by Rafiot** [comment]
no, the timestamp is always set by the server. What you can change programmatically is first seen/last seen.

**Comment by framontb** [comment]
Thanks for the info !
