### ISSUE TITLE
Tag for v2.4.189?

### ISSUE THREAD

**Issue by mdavis332** [MISP/PyMISP#1198]
I believe a version is normally tagged to parallel what's released in the main MISP repo. I noticed they tagged a v2.4.189 for MISP but haven't seen the equivalent release yet for PyMISP. Will a PyMISP v2.4.189 be tagged?

**Comment by Rafiot** [comment]
It is generally the case, but there were no changes in PyMISP, so it's not really useful. Is there any reason you need that?

**Comment by mdavis332** [comment]
Hi @Rafiot, thanks for the quick reply. My build pipeline for MISP container and client containers that use PyMISP are usually pinned to a specific version which retrieves the git tree for that tag. So far that's worked for me but looks like I may need to make some changes if PyMISP version won't always be tagged for each MISP version.

**Comment by Rafiot** [comment]
Right, I see. So yeah, it is generally the case, but it's not required. 

Not sure it's possible for you, but the PyMISP version a specific MISP version expects is there: https://github.com/MISP/MISP/blob/2.4/requirements.txt#L9

**Comment by mdavis332** [comment]
I'll key off that then, thanks!
