### ISSUE TITLE
PyMISP and MISP version mismatch

### ISSUE THREAD

**Issue by mbell85** [MISP/PyMISP#1204]
Hello, 

I posted earlier with this issue but it got closed a little prematurely

"The version of PyMISP recommended by the MISP instance (2.4.188) is newer than the one you're using now (2.4.159). Please upgrade PyMISP."

I ran, as suggested:

`pip3 install --upgrade pymisp`

However, when exporting TIs, I'm still getting the same message.

Thanks!

**Comment by Rafiot** [comment]
What is your python version?
