### ISSUE TITLE
Error while having the newest version of PyMISP: " This class is deprecated, use PyMISP instead   warnings.warn('This class is deprecated, use PyMISP instead', FutureWarning"

### ISSUE THREAD

**Issue by ChonoOG** [MISP/PyMISP#1268]
Hi,

We are currently utilizing PyMISP in our Azure Pipelines and have encountered the following error:

`/usr/local/lib/python3.10/dist-packages/pymisp/__init__.py:67: FutureWarning: This class is deprecated, use PyMISP instead
  warnings.warn('This class is deprecated, use PyMISP instead', FutureWarning)`

Upon checking, the PyMISP version in use is 2.4.194, which I believe is the latest version, as I have also attempted to update it.

Could someone please assist me in understanding this error?

Thank you.

**Comment by Rafiot** [comment]
The script you're running is probably using `ExpandedPyMISP` when you should just be using `PyMISP`, the former is just an alias, and was used during the transition to Python 3.6+.

What you need to update is the script you're running, not the library.

**Comment by ChonoOG** [comment]
Just for clarification, we currently have the following code: `misp = pymisp.ExpandedPyMISP(config.misp_domain, config.misp_key, config.misp_verifycert, cert=config.misp_client_cert)` Are we supposed to remove the `ExpandedPyMISP` from that line and also use `import pymisp`?

**Comment by Rafiot** [comment]
you need to do `from pymisp import PyMISP` and then `misp = pymisp.ExpandedPyMISP(var1example, var2example, var3example, var4example)`
