### ISSUE TITLE
PyMISP patch level version strings cause warnings

### ISSUE THREAD

**Issue by RichieB2B** [MISP/PyMISP#128]
The PyMISP version string uses major.minor.misp-pl,pymisp-pl which causes the following warning:

```
The version of PyMISP recommended by the MISP instance (2.4.81) is older than the one you're using now (2.4.81.2). Please upgrade the MISP instance or use an older PyMISP version.
```

A simple solution would be to strip out the last (4th) pymisp-pl part of the version before comparing.

**Comment by Rafiot** [comment]
Fixed by:
