### ISSUE TITLE
HOWTO prevent pymisp 'CRITICAL Unknown error' logging huge JSON requests with failures

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#1286]
Hi @Rafiot -- it's been a while. Have a simple question when you get a minute... Thanks!

Is there a way for pymisp clients to prevent logging the full JSON sent to the server when a method fails. that content is basically sending back what the client data was which does not really help  to decipher the root cause and fills up our log files b/c we send huge useless data.  For example...
```
2024-08-21T08:46:02Z CRITICAL Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.195 - Python 3.11', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Cookie': 'CAKEPHP=imm7nqft123cs2g9svtr2f7ve5', 'Content-Length': '994071', 'content-type': 'application/json'}
Request body:
{"uuid": "80090cec-b22a-4582-9f8c-e14a26388879", "Object": [{ ...
... maybe 100s of MB
...
```

**Comment by Rafiot** [comment]
Yeah, fair, this is supposed to help you to figure out what happened (request/response) when a request returns something PyMISP cannot process, but the text of the response can be insanely long.

Right now, the only way is to disable all logging (this is a critical level log, so there is nothing else to do). I'll change that in the next PyMISP release to only print the complete response in the log in debug mode.
