### ISSUE TITLE
CHANGELOG installed to sitelib path

### ISSUE THREAD

**Issue by sebix** [MISP/PyMISP#1295]
https://github.com/MISP/PyMISP/blob/b360fd29b7ab300fa1f7dba9edd541149d55af8d/pyproject.toml#L30
causes the file CHANGELOG.txt to be installed directly into the sitelib path (e.g. `/usr/local/lib/python3.12/CHANGELOG.txt`)

**Comment by Rafiot** [comment]
I'm not sure what's the best way to fix that, besides not including it in the package? The change removes it from the wheel, but I'm not sure it solves the problem.

**Comment by Rafiot** [comment]
Closing it, feel free to reopen if needed.
