### ISSUE TITLE
Tag is not updated

### ISSUE THREAD

**Issue by nyx0** [MISP/PyMISP#1301]
__Steps to reproduce__:
The following script remove the `tlp:amber` tag from a test event, it adds `tlp:amber+strict` tag and update the event. However, there are no updates.

```
try:
    from pymisp import PyMISP, MISPEvent
except ImportError:
    print("[-] PyMISP module not found")
import os


MISP_URL = os.getenv("MISP_URL_INT")
API_KEY = os.getenv("MISP_API_KEY_INT")


def main() -> None:
    misp = PyMISP(MISP_URL, API_KEY, ssl=False)
    events: list[MISPEvent] = misp.search(
        eventinfo="test",
        tags=["tlp:amber"],
        limit=1,
        pythonify=True
    )
    for event in events:
        print(event, event.uuid)
        print(event.Tag)
        for tag in event.Tag:
            if tag.name == "tlp:amber":
                event.tags.remove(tag)
                break
        event.add_tag("tlp:amber+strict")
        print(event.Tag)
        misp.update_event(event.uuid, event, pythonify=True)


if __name__ == "__main__":
    main()
```

__Ouput__:
```
$ python3 misp_poc_tlp.py
<MISPEvent(info=test) ebf8bc7e-2239-41ff-b61b-4fee6ee52264
[<MISPTag(name=tlp:amber)>]
[<MISPTag(name=tlp:amber+strict)>]

$ python3 misp_poc_tlp.py
<MISPEvent(info=test) ebf8bc7e-2239-41ff-b61b-4fee6ee52264
[<MISPTag(name=tlp:amber)>]
[<MISPTag(name=tlp:amber+strict)>]
```

__Expected behaviour__:
When running the script a second time the event `test` should not have `tlp:amber` but `tlp:amber+strict` tag.

__Versions__:
pymisp: 2.4.198
MISP: v2.4.198 (ef48a1c69ed70395eaaa7513a53fbccacba66cae)

**Comment by Rafiot** [comment]
Yep, it makes sense: calling update on an event will only add things to an existing event: MISP expects to update an event from a partial one. For example if it gets list of tags that is a subset of the existing ones, it will only add the new tags, and not remove the missing ones.

The way to remove a tag from an existing event is to use [`untag`](https://pymisp.readthedocs.io/en/latest/modules.html#pymisp.PyMISP.untag).
