### ISSUE TITLE
add_file_object.py against some field is not creating some attribute in misp object

### ISSUE THREAD

**Issue by garanews** [MISP/PyMISP#131]
![image](https://user-images.githubusercontent.com/16938405/32318491-bbcd497c-bfb7-11e7-815a-f7d95c065ab4.png)

First file:
python3 add_file_object.py -e 6683-p /user/analyst/binaries/7baa0260b1e98a21762818aeea6b73c32a3b68787bedbc08aac276170cc55a50
misp file object created with no errors

Second file:
python3 add_file_object.py -e 6683 -p /user/analyst/binaries/fdab41ae51989ca6cf31071b8ec3b5ae9106466548b57b7faee38fcf52f32ead
misp file ojbect created with missing attributes and this error:

Traceback (most recent call last):
  File "add_file_object.py", line 41, in <module>
    response = pymisp.add_object(args.event, template_id, fo)
  File "/usr/local/lib/python3.4/dist-packages/pymisp/api.py", line 1628, in add_object
    return self._check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/pymisp/api.py", line 210, in _check_response
    response.raise_for_status()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://1.2.3.4/objects/add/6683/9

It seems that no issue with:
exe, pdf, dat.

Issue found with:
Jar files with mimetype: Java Jar file data (zip) 
Zip files with mimetype: Zip archive data, at least v1.0 to extract

**Comment by dadokkio** [comment]
The problem seems to be related to line 233 in mispevent.py that returns malware_filename with "\n"

```
self.malware_filename = unpacked.read().decode()
```

Just adding .strip() seems to resolve the issue

```
self.malware_filename = unpacked.read().decode().strip()
```

**Comment by Rafiot** [comment]
Wops, thanks for the hint, I'll fix it today.

**Comment by Rafiot** [comment]
@dadokkio thanks, this bug is also fixed.

@garanews: that should do: https://github.com/MISP/PyMISP/commit/75d96b2d7a89406997035a1715de7c3cbce2303b

**Comment by Rafiot** [comment]
Confirmed working :)
