### ISSUE TITLE
Release tags for >2.4.198

### ISSUE THREAD

**Issue by cudeso** [MISP/PyMISP#1311]
Hello,

The MISP 'core' tags for 2.4 are at 2.4.200. The last one for PyMISP is at 2.4.198.

Will PyMISP continue to release under the v2.4.x tag (even if code-wise it's similar as 2.5)? 
Some environments prefer to stick to releases based on the tags, and have only those releases were the exact same tag version exists in misp, misp-modules (latest is 2.4.199) and pymisp.

**Comment by Rafiot** [comment]
Hello,

That was not the plan, the PyMISP version expected by MISP is in the requirements.txt file: https://github.com/MISP/MISP/blob/2.4/requirements.txt#L10

And MISP 2.4.* supports PyMISP 2.5.* just fine.

**Comment by cudeso** [comment]
OK. The reason for asking:
Some envs pull the version of MISP, MISP-modules and PyMISP based on the tag. And the "text" (version) of the tag needs to be the same. In this case, only those with "v2.4.198" can be pulled, even if there is a new PyMISP version.

**Comment by Rafiot** [comment]
Fixed with dummy tags on HEAD, which solves the problem. I'll try to add the proper tags accordingly for the next releases.
