### ISSUE TITLE
Setting to_ids=False has no effect

### ISSUE THREAD

**Issue by c-goes** [MISP/PyMISP#132]
Maybe this is a bug in PyMISP: When adding an attribute to an object and setting this attribute the flag `to_ids` to `False` then the MISP does not set it to `False` when it is by default `True`.

**Comment by Rafiot** [comment]
Can you give more details on the code you're using to encounter this bug? Because it *should* work fine.

**Comment by c-goes** [comment]
I'm sorry for this. I found my mistake.
