### ISSUE TITLE
Upload files fails if file only contains null bytes

### ISSUE THREAD

**Issue by c-goes** [MISP/PyMISP#133]
Maybe a similar problem like https://github.com/MISP/MISP/issues/2610

Upload of .docx never fails with my test files
Upload of .dox files often fails with HTTP 500 Error

I don't know what causes this error

Here the MISP error.log

```
Request URL: /objects/add/47/9
Stack Trace:
#0 /opt/misp-server/misp/app/Lib/cakephp/lib/Cake/View/JsonView.php(107): View->_getViewFileName('Objects/json/ad...')
#1 /opt/misp-server/misp/app/Lib/cakephp/lib/Cake/Controller/Controller.php(963): JsonView->render(NULL, NULL)
#2 /opt/misp-server/misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /opt/misp-server/misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ObjectsController), Object(CakeRequest))
#4 /opt/misp-server/misp/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

**Comment by iglocska** [comment]
Could you describe the steps how we can reproduce it?

**Comment by c-goes** [comment]
`python -c 'import sys;sys.stdout.write("\x00"*192000)' > test.doc`

then upload: 

`python add_file_object.py -e 48 -p test.doc`

**Comment by c-goes** [comment]
This happens also for all kind of types of files like .ace or anything else

**Comment by Rafiot** [comment]
I did some changes in the code a couple of days ago. Did you try with the latest version on Github?

**Comment by Rafiot** [comment]
oh, sorry, I didn't see you mentioned the bug I assumed should have fixed it. I'll give it a try asap.

**Comment by c-goes** [comment]
Ok thanks. I would have written know that I tried it today again with newest PyMISP and MISP

**Comment by Rafiot** [comment]
Ok, I'll investigate it later today

**Comment by Rafiot** [comment]
Okay, so I can reproduce on put test instance, and I'm confused on what's going on.

This is the error message returned by MISP:
```python
{'code': 500, 'name': 'View file &quot;Objects/json/add.ctp&quot; is missing.', 
'message': 'View file &quot;Objects/json/add.ctp&quot; is missing.', 'url': '/objects/add/4906/35'}
```

But the object id 35 is in fact file on that instance, and I can use it for other objects.

**Comment by Rafiot** [comment]
It was related to the entropy, and some MySQL weirdness. This commit fixed it: https://github.com/MISP/MISP/commit/396eecd242984de7474af2542b1064a61beb1523

good catch!
