### ISSUE TITLE
MISP with fake certification and PyMISP

### ISSUE THREAD

**Issue by HoneyJack** [MISP/PyMISP#134]
Hi People, 
I have an issue to configure PyMISP and my instance of MISP. I am interested to use PyMISP. 

I have configured a MISP instance in an ubuntu machine. It works fine. Normal issues, but nothing critical. I was creating events for testing and users. Everything look ok. 
Then, in the same machine, I have installed PyMISP using
`pip3 install pymisp`

then I cloned the repository 

`git clone https://github.com/CIRCL/PyMISP.git && cd PyMISP`

`cd examples`
`cp keys.py.sample keys.py`
`vim keys.py`  # I put the URL and my auth key.

But when I tested if my URL and API keys are correct
`python3 last.py -l 10`

> Traceback (most recent call last):
>   File "/home/manati/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "/home/manati/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
>     self._validate_conn(conn)
>   File "/home/manati/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
>     conn.connect()
>   File "/home/manati/.local/lib/python3.5/site-packages/urllib3/connection.py", line 326, in connect
>     ssl_context=context)
>   File "/home/manati/.local/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
>     return context.wrap_socket(sock, server_hostname=server_hostname)
>   File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
>     _context=self)
>   File "/usr/lib/python3.5/ssl.py", line 752, in __init__
>     self.do_handshake()
>   File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
>     self._sslobj.do_handshake()
>   File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/manati/.local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
>     timeout=timeout
>   File "/home/manati/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/home/manati/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='misp.manatiproject.org', port=443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/manati/.local/lib/python3.5/site-packages/pymisp/api.py", line 113, in __init__
>     response = self.get_recommended_api_version()
>   File "/home/manati/.local/lib/python3.5/site-packages/pymisp/api.py", line 1197, in get_recommended_api_version
>     response = session.get(url)
>   File "/home/manati/.local/lib/python3.5/site-packages/requests/sessions.py", line 521, in get
>     return self.request('GET', url, **kwargs)
>   File "/home/manati/.local/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/manati/.local/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/manati/.local/lib/python3.5/site-packages/requests/adapters.py", line 506, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='misp.manatiproject.org', port=443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "last.py", line 41, in <module>
>     misp = init(misp_url, misp_key)
>   File "last.py", line 15, in init
>     return PyMISP(url, key, misp_verifycert, 'json')
>   File "/home/manati/.local/lib/python3.5/site-packages/pymisp/api.py", line 127, in __init__
>     raise PyMISPError('Unable to connect to MISP ({}). Please make sure the API key and the URL are correct (http/https is required): {}'.format(self.root_url, e))
> pymisp.exceptions.PyMISPError: Unable to connect to MISP (https://misp.manatiproject.org/). Please make sure the API key and the URL are correct (http/https is required): HTTPSConnectionPool(host='misp.manatiproject.org', port=443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))

I have checked the keys.py, and everything looks correct. 
I think, that there is a relationship with my instance of MISP where I am using a fake SSL certifcate. 

Could you help me with this issue, please? Thanks in advance!

**Comment by Rafiot** [comment]
So first of all, https://misp.manatiproject.org doesn't exists. Is it expected, is there a typo? 

If you want to connect to a MISP instance with a self signed certificate, you can set `misp_verifycert = False` in `key.py`

**Comment by HoneyJack** [comment]
it seems  working now after your suggestion.. Thanks!
Here screenshot of the console. 
> /home/manati/.local/lib/python3.5/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> /home/manati/.local/lib/python3.5/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> /home/manati/.local/lib/python3.5/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> []

**Comment by Rafiot** [comment]
Good, that's the expected outcome when you disable cert validation.

**Comment by maverickvn360** [comment]
In addition to this issue, is it possible to validate our self signed certificate for PyMISP?

**Comment by Rafiot** [comment]
You can do what the `requests` library allows you to do as described there: https://docs.python-requests.org/en/stable/user/advanced/#ssl-cert-verification

If it doesn't solve your question, please open a new issue.

**Comment by maverickvn360** [comment]
Got it,
Thanks ! 👍
