### ISSUE TITLE
search_index() assumes published = true as a default setting

### ISSUE THREAD

**Issue by iglocska** [MISP/PyMISP#135]
It looks like search_index() sets a default value for the published search parameter if the filter is not set.

What I did:
```
data = misp.search_index(misp, eventinfo='test')
```
What I expected:
`data` to contain all event metadata visible to me for any event that has test in its info field

What happened:
`data` contained all event metadata visibile to me for any event that has test in its info field that is already published

**Comment by Rafiot** [comment]
hmmm yeah, the call should be:
```python
data = misp.search_index(eventinfo='test')
```
not 
```python
data = misp.search_index(misp, eventinfo='test')
```

The header of the method is 
```python
def search_index(self, published=None, eventid=None, tag=None, datefrom=None,                   
                 dateuntil=None, eventinfo=None, threatlevel=None, distribution=None,           
                 analysis=None, attribute=None, org=None, async_callback=None, normalize=False):
```
so passing `misp` as first parameter makes `published` **True**. 

Or am I misunderstanding something?

**Comment by Rafiot** [comment]
I wasn't :p
