### ISSUE TITLE
Retrieve values from fixed id feed source [support]

### ISSUE THREAD

**Issue by 0xffca** [MISP/PyMISP#140]
I set up MISP recently and I am still fairly new to it, this is more a support request.
MISP version: 2.4.82
I activated the cybercrime-tracker feed and set "Target event": "Fixed Event" (eventid 1) and checked Delta Merge and scheduled a script to automatically fetch the feed, everything works fine.

Now I am trying to write a python script to fetch the latest updated values. If I do this:

 `from pymisp import PyMISP

from keys import misp_key
from keys import misp_url
from keys import misp_verifycert

import json

def init(url, key):
    return PyMISP(url, key, misp_verifycert, 'json')

misp = init(misp_url, misp_key)

misp_result = misp.search(eventid="1", last="12h")`

I do not get any results even though in the last 12h the event was updated. Can you please help me figuring out what am I do wrong?
Thank you!

**Comment by Rafiot** [comment]
Can you try by just passing `last="12h"`? And enable debug (pass `debug=True` to `PyMISP`).

**Comment by 0xffca** [comment]
Passing only last="12h" returns` {'response': []} ` without any error (passed debug=True as you suggested)

When retrieving all the values by searching for the id:
misp_result = misp.search(eventid="1")
The output looks like:
{'response': [{'Event': {'Attribute': [{'ShadowAttribute': [],
      'category': 'External analysis',
      'comment': '',
      'deleted': False,
      'disable_correlation': False,
      'distribution': '0',
      'event_id': '1',
      'id': '804472',
      'object_id': '0',
      'object_relation': None,
      'sharing_group_id': '0',
      '**timestamp': '1510736353**',
      'to_ids': True,
      'type': 'url',
      'uuid': '5a0c01e1-5eb0-4622-8979-570ebb36965a',
      'value': 'XX'},
      ......

The timestamp field is correct (15 November 2017 09:59:13 GMT+01:00) but for some reasons the 'last' parameter in misp.search is not retrieving it.

I also have another feed active setup to create new event on pull ("New Event Each Pull") and I am able to retrieve the correct information by using 'last' param. Don't know if it helps..
Thank you!

**Comment by Rafiot** [comment]
It is most probably because the event isn't published (it is a bug on our side), @iglocska is working on it.

**Comment by 0xffca** [comment]
Just tested and it is now working! 
Thanks a lot for the support, problem solved.
