### ISSUE TITLE
Replace python-magic

### ISSUE THREAD

**Issue by Rafiot** [MISP/PyMISP#148]
More details in this conversation: https://github.com/MISP/PyMISP/commit/8e50ee825b93f3f19f7d70a2eee41b9a89165e95

**Comment by wagner-certat** [comment]
There is progress on making both APIs compatible, see
* the debian-python mailinglist: https://lists.debian.org/debian-python/2018/01/threads.html (thread origins in Oct 17)
* https://github.com/ahupp/python-magic/issues/33#issuecomment-357605148
* https://github.com/ahupp/python-magic/issues/21#issuecomment-357605356

**Comment by Rafiot** [comment]
@wagner-certat I'm not sure about the status if this issue. What would be the best way to solve it for you?
