### ISSUE TITLE
how to set categories in file object 

### ISSUE THREAD

**Issue by garanews** [MISP/PyMISP#166]
We want to create an event with 2 different file objects related between them.
The first one is considered as payload delivery while the second one should be considered as artifact dropped.
At the moment we arrived at the following situation:

![aaaaa ng](https://user-images.githubusercontent.com/16938405/34555543-90cd8bb8-f132-11e7-9129-804a5e90147d.png)

We tried to use the _default_attributes_parameters in the make_binary_objects function but it seems that the category field is being cleaned (in the MISPObject __init__ function) and also we cannot specify a single category valid for all fields (eg entropy has only "other" as proposed category).
There is a valid way to achieve this?
Which fields we can override using _default_attributes_parameters parameter?

**Comment by Rafiot** [comment]
That should be fixed for most of the fields.

size and entropy won't be set to the "right" category, because they are supposed to be in the category "other". That would require changes sever side, but if we decide to go this way, the current python code will automatically adapt.

**Comment by garanews** [comment]
Confirmed working:

![image](https://user-images.githubusercontent.com/16938405/34559028-9cee1490-f140-11e7-8e1b-ed8dab1a3e40.png)
