### ISSUE TITLE
logging.basicConfig issue

### ISSUE THREAD

**Issue by cvandeplas** [MISP/PyMISP#170]
PyMISP defines the logging level when used as library.
```
./pymisp/__init__.py:9:logging.basicConfig(stream=sys.stderr, level=logging.WARNING, format=FORMAT)
```
This causes problems when other code using logging import pymisp as (if I understand it correctly)  the ```basicConfig()``` function can only be called once. 

Proposal: do not call the ```basicConfig()``` within PyMISPs code.

**Comment by cvandeplas** [comment]
@Rafiot , have you had time to look at this?

**Comment by Rafiot** [comment]
woops, forgot about it. Looking at it now.

**Comment by Rafiot** [comment]
That should be sorted out now, please let me know if you have any problem :)
