### ISSUE TITLE
Your user account is expecting a password change, please log in via the web interface and change it before proceeding.

### ISSUE THREAD

**Issue by juju4** [MISP/PyMISP#182]
Hello,

Since about 2 weeks, my ansible role  failed in travis at the task matching pymisp list users.
after some review, it seems that I'm asked to changed password
```
[0;31m    "msg": "non-zero return code", [0m

[0;31m    "rc": 1, [0m

[0;31m    "start": "2018-01-28 19:40:15.782466", [0m

[0;31m    "stderr": "WARNING [api.py:87 - __init__() ] Your user account is expecting a password change, please log in via the web interface and change it before proceeding.\nTraceback (most recent call last):\n  File \"./users_list.py\", line 23, in <module>\n    users_list = misp.get_users_list()\n  File \"/usr/local/lib/python3.5/dist-packages/pymisp/api.py\", line 1356, in get_users_list\n    return self._check_response(response)['response']\nKeyError: 'response'", [0m

[0;31m    "stderr_lines": [[0m

[0;31m        "WARNING [api.py:87 - __init__() ] Your user account is expecting a password change, please log in via the web interface and change it before proceeding.", [0m

[0;31m        "Traceback (most recent call last):", [0m

[0;31m        "  File \"./users_list.py\", line 23, in <module>", [0m

[0;31m        "    users_list = misp.get_users_list()", [0m

[0;31m        "  File \"/usr/local/lib/python3.5/dist-packages/pymisp/api.py\", line 1356, in get_users_list", [0m

[0;31m        "    return self._check_response(response)['response']", [0m

[0;31m        "KeyError: 'response'"[0m

[0;31m    ], [0m
```
https://api.travis-ci.org/v3/job/334448000/log.txt
https://travis-ci.org/juju4/ansible-MISP/builds/334447998

I checked recent commits of PyMISP and MISP but didn't see any obvious change related or maybe I failed to detect in the past.

Any way to setup admin account in cli to avoid this immediate expiry? mysql insert?
or should I skip pymisp testing?

Thanks

**Comment by Rafiot** [comment]
We do it this way for testing on travis: https://github.com/MISP/MISP/blob/2.4/.travis.yml#L100

The default admin account doesn't require an immediate password change.

**Comment by juju4** [comment]
Strange as I have the same thing
https://github.com/juju4/ansible-MISP/blob/devel/tasks/misp-key-file.yml#L9
and used to work or I believe so.
```
/var/www/MISP/app/Console/cake userInit -q | tee /var/www/MISP/.ht_key
# later
/var/www/MISP/app/Console/cake Password admin@admin.test \"admin_pass_to_change\"
# after create keys.py and call pymisp last or users_list and resulting with above message.
```
https://api.travis-ci.org/v3/job/334483990/log.txt

is the second command interfering with first?

**Comment by Rafiot** [comment]
@iglocska do you have an idea?

**Comment by juju4** [comment]
Sorry for the long delay. I did a lot of commit/revert this week-end and it seems the one at fault is
https://github.com/juju4/ansible-MISP/commit/a9342c28fe08010aedf68f9c48e291b956bf916c
which is a basic change of web user password from "admin" to "admin_pass_to_change" as mentioned above.

Why this change create issue is an interesting question
https://travis-ci.org/juju4/ansible-MISP/jobs/372822139#L4759
https://travis-ci.org/juju4/ansible-MISP/jobs/372835255

but it triggers in my kitchen-test verifiers:
```
"{\"name\":\"Your user account is expecting a password change, please log in via the web interface and change it before proceeding.\",\"message\":\"Your user account is expecting a password change, please log in via the web interface and change it before proceeding.\",\"url\":\"\\/sharing_groups\\/index.json\"}"
```
which maps https://github.com/MISP/MISP/blob/a2064201d4eabb8035b3a2a023d5b37451104b17/app/Controller/AppController.php#L327
and https://github.com/MISP/MISP/blob/2.4/app/Console/Command/PasswordShell.php
but I don't see how the difference of password leads to this error...

**Comment by Rafiot** [comment]
As it is pretty old, I'm closing this one, donot hesitate to open an other one if needed.
