### ISSUE TITLE
sighting_per_uuid does not allow to specify a timestamp

### ISSUE THREAD

**Issue by remg427** [MISP/PyMISP#184]
sighting_per_uuid takes only one argument i.e. the attribute uuid.
Is it possible to provide a timestamp like for set_sightings()?

**Comment by Rafiot** [comment]
If I understand your question right, you can do it by passing a `MISPSighting` with a UUID and a timestamp to `set_sightings`. Does it work for you?

**Comment by remg427** [comment]
Yes this is it. Thanks; no longer an issue
