### ISSUE TITLE
Is it possible to assign an expiration date to an attribute?

### ISSUE THREAD

**Issue by intoxe** [MISP/PyMISP#187]
Hello,

If i am not mistaken. The following methods: **set_sightings(sightings), sighting_per_id(attribute_id), sighting_per_json(json_file) and sighting_per_uuid(attribute_uuid)** only permit to confirm the validity of an attribute.

How can I inform the expiration date of an attribute with PyMisp?

Thank you

**Comment by Rafiot** [comment]
You can do it by passing a `MISPSighting` of type `Expiration` to `set_sightings`. 

Does it work for you?

**Comment by infosec-intern** [comment]
Is there an example of doing that, or a list of the sighting types somewhere? I have some old code that sets type=0, but I can't remember why I did that
