### ISSUE TITLE
error on add_generic_object

### ISSUE THREAD

**Issue by truckydev** [MISP/PyMISP#191]
Hi team,

I just see that there is some error when I try to add an object with pymisp. I use the sample in PyMIPS/example.
```python
python3 add_generic_object.py -e 810 -t email -l '[{"to": "undisclosed@ppp.com"}, {"to": "second.to@mail.com"}]'
```
The callback : 
```bash
Traceback (most recent call last):
  File "add_generic_object.py", line 32, in <module>
    misp_object.generate_attributes(json.loads(args.attr_list))
  File "/usr/local/lib/python3.5/dist-packages/pymisp-2.4.87.1-py3.5.egg/pymisp/tools/genericgenerator.py", line 16, in generate_attributes
    self.add_attribute(object_relation, value=value)
  File "/usr/local/lib/python3.5/dist-packages/pymisp-2.4.87.1-py3.5.egg/pymisp/mispevent.py", line 991, in add_attribute
    attribute.from_dict(object_relation=object_relation, **dict(self._default_attributes_parameters, **value))
  File "/usr/local/lib/python3.5/dist-packages/pymisp-2.4.87.1-py3.5.egg/pymisp/mispevent.py", line 806, in from_dict
    super(MISPObjectAttribute, self).from_dict(**dict(self, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/pymisp-2.4.87.1-py3.5.egg/pymisp/mispevent.py", line 164, in from_dict
    raise NewAttributeError('The type of the attribute is required.')
pymisp.exceptions.NewAttributeError: The type of the attribute is required.
```

**Comment by garanews** [comment]
the error "mispevent.py  line 806" is not matching the code https://github.com/MISP/PyMISP/blob/master/pymisp/mispevent.py
Can you check if your mispevent.py is updated?

**Comment by eCrimeLabs** [comment]
@garanews I can confirm I've just pulled the latest version and getting simular error
8c02e6eb65fb805ad95e3a9f50c2bc28ef1daa7e  /data/gitrepo/PyMISP/pymisp/mispevent.py


[parse_ot_logs_sample.txt](https://github.com/MISP/PyMISP/files/1864505/parse_ot_logs_sample.txt)

Gives error

Traceback (most recent call last):
  File "parse_ot_logs_sample.py", line 37, in <module>
    misp_obj.add_attribute(obj_relation, **{'value': value})
  File "/usr/local/lib/python3.6/dist-packages/pymisp-2.4.89-py3.6.egg/pymisp/mispevent.py", line 999, in add_attribute
    attribute.from_dict(object_relation=object_relation, **dict(self._default_attributes_parameters, **value))
  File "/usr/local/lib/python3.6/dist-packages/pymisp-2.4.89-py3.6.egg/pymisp/mispevent.py", line 814, in from_dict
    super(MISPObjectAttribute, self).from_dict(**dict(self, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/pymisp-2.4.89-py3.6.egg/pymisp/mispevent.py", line 164, in from_dict
    raise NewAttributeError('The type of the attribute is required.')
pymisp.exceptions.NewAttributeError: The type of the attribute is required.

**Comment by garanews** [comment]
I confirm both scripts are working:

![image](https://user-images.githubusercontent.com/16938405/38162573-7e20d61a-34e3-11e8-8c7f-f08e6f86e04a.png)

![image](https://user-images.githubusercontent.com/16938405/38162576-93dae46e-34e3-11e8-970d-00994bf98d84.png)

**Comment by eCrimeLabs** [comment]
@garanews: Are there any way to check all the versions you use, as I'm still getting the same errors even when I try to use the add_generic_object.py
```
Traceback (most recent call last):
  File "add_generic_object.py", line 37, in <module>
    misp_object.generate_attributes(json.loads(args.attr_list))
  File "/usr/local/lib/python3.6/dist-packages/pymisp-2.4.89-py3.6.egg/pymisp/tools/genericgenerator.py", line 16, in generate_attributes
    self.add_attribute(object_relation, value=value)
  File "/usr/local/lib/python3.6/dist-packages/pymisp-2.4.89-py3.6.egg/pymisp/mispevent.py", line 999, in add_attribute
    attribute.from_dict(object_relation=object_relation, **dict(self._default_attributes_parameters, **value))
  File "/usr/local/lib/python3.6/dist-packages/pymisp-2.4.89-py3.6.egg/pymisp/mispevent.py", line 814, in from_dict
    super(MISPObjectAttribute, self).from_dict(**dict(self, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/pymisp-2.4.89-py3.6.egg/pymisp/mispevent.py", line 164, in from_dict
    raise NewAttributeError('The type of the attribute is required.')
pymisp.exceptions.NewAttributeError: The type of the attribute is required.
```

**Comment by eCrimeLabs** [comment]
@garanews I've just tried to install a brand new linux pull the PyMISP and same error

**Comment by Rafiot** [comment]
How did you install pymisp? If you installed it from the repository, you need to run

```
git submodule init
git submodule update
```

**Comment by eCrimeLabs** [comment]
Thanks a lot @Rafiot after a 
cd PyMISP
git submodule init
git submodule update
sudo python3 setup.py install

It seemed to update somthing in objects :)

**Comment by eCrimeLabs** [comment]
however when I create my own object and attempt to add data there it will fail.
I've then tried adding the object definition to /usr/local/lib/python3.6/dist-packages/pymisp-2.4.89-py3.6.egg/pymisp/data/misp-objects/objects/ot-honeypot now there are no errors however data does not get in :)

**Comment by Rafiot** [comment]
you need to re-run `pip install .` every time you add or update an object. The alternative is to install the package in dev mode with this way: `pip install -I -e .` (it creates symlinks instead of copying the files over).

Can you try to add the file object on the server, in the known object templates? It should not be required, but let me know if it solves the problem.

**Comment by eCrimeLabs** [comment]
I've tried that as well and no luck it seem to be an issue in relation to own objects.

In the sample I've attached it seems to work perfect when the mail object are being used but the custom ot-honeypot fails, and indications are that it finds the object but then something goes awol :)

```
Traceback (most recent call last):
  File "parse_ot_logs_sample.py", line 44, in <module>
    misp_object.generate_attributes(json.loads(object_data))
  File "/data/gitrepo/PyMISP/pymisp/tools/genericgenerator.py", line 16, in generate_attributes
    self.add_attribute(object_relation, value=value)
  File "/data/gitrepo/PyMISP/pymisp/mispevent.py", line 999, in add_attribute
    attribute.from_dict(object_relation=object_relation, **dict(self._default_attributes_parameters, **value))
  File "/data/gitrepo/PyMISP/pymisp/mispevent.py", line 814, in from_dict
    super(MISPObjectAttribute, self).from_dict(**dict(self, **kwargs))
  File "/data/gitrepo/PyMISP/pymisp/mispevent.py", line 164, in from_dict
    raise NewAttributeError('The type of the attribute is required.')
pymisp.exceptions.NewAttributeError: The type of the attribute is required.
```

[parse_ot_logs_sample.py.txt](https://github.com/MISP/PyMISP/files/1866665/parse_ot_logs_sample.py.txt)

[definition.json.txt](https://github.com/MISP/PyMISP/files/1866668/definition.json.txt)

**Comment by Rafiot** [comment]
This error happen either when the whole object is unknown by PyMISP, or when one of the object relation (attribute in the object) doesn't match the one of the template (and then, it won't know the type expected by MISP core to use).

I won't look at it tonight, but I'll try to give it a shot tomorrow if you haven't already fixed it.

**Comment by p3tr0v** [comment]
I installed all pymisp and dependencies yesterday, its all up to date, and had this error 
![misp_error](https://user-images.githubusercontent.com/28512249/38325129-85c9ae40-3818-11e8-8619-0100fbbd0a66.png)

**Comment by Rafiot** [comment]
This error is because the string you're passing isn't valid json. Try to do that to validate your json:
`echo <json> | jq .`

**Comment by p3tr0v** [comment]
![json](https://user-images.githubusercontent.com/28512249/38370889-9a8367be-38c1-11e8-94c5-93567a78eac7.png)
Realy @Rafiot  ? are you sure? i picked this from the example!

**Comment by Rafiot** [comment]
So, I just tested the exact same command, and it worked just fine (no exception).

Can you give me your commit ID?

**Comment by p3tr0v** [comment]
I believe i found the error.
two issues:

first: i printed what argparse sending to json.loads, argparse replace double quotes to single quotes, like an image.

![misperr1](https://user-images.githubusercontent.com/28512249/38385192-a33f0d4c-38e7-11e8-8042-0c664e68bd6b.png)


when i paste _'[{"to": "undisclosed@ppp.com"}, {"to": "second.to@mail.com"}]'_ inside python script, works fine;

second, MISP dont accept personal objects. I copied _credit-card/definition.json_ to _myobject/definition.json_. Did some changes: **ALL** my type attributes are _'text'_; changed the name; generated new uuid with `uuidgen -r` ; and updated by browser the list objects.
when i ran the script, i had the error:
```

  File "C:\desenvolvimento\python\python3.6\lib\site-packages\pymisp\tools\genericgenerator.py", line 16, in generate_attributes
    self.add_attribute(object_relation, value=value)
  File "C:\desenvolvimento\python\python3.6\lib\site-packages\pymisp\mispevent.py", line 999, in add_attribute
    attribute.from_dict(object_relation=object_relation, **dict(self._default_attributes_parameters, **value))
  File "C:\desenvolvimento\python\python3.6\lib\site-packages\pymisp\mispevent.py", line 814, in from_dict
    super(MISPObjectAttribute, self).from_dict(**dict(self, **kwargs))
  File "C:\desenvolvimento\python\python3.6\lib\site-packages\pymisp\mispevent.py", line 164, in from_dict
    raise NewAttributeError('The type of the attribute is required.')
pymisp.exceptions.NewAttributeError: The type of the attribute is required.
```
I saw this line (164) , is:

` self.type = kwargs.pop('type', None)  # Required
        if self.type is None:
            raise NewAttributeError('The type of the attribute is required.')
        if self.type not in self.known_types:
            raise NewAttributeError('{} is invalid, type has to be in {}'.format(self.type, (', '.join(self._types))))`

He dont recognize text type from personal objects. The value of self.type is _None_
When i forced to text
` self.type = kwargs.pop('type', None)  # Required
        if self.type is None:
            self.type = "text"
            #raise NewAttributeError('The type of the attribute is required.')
        if self.type not in self.known_types:
            raise NewAttributeError('{} is invalid, type has to be in {}'.format(self.type, (', '.join(self._types))))`
He accepted my personal object.
