### ISSUE TITLE
ValidationError: Additional properties are not allowed ('Object' was unexpected)

### ISSUE THREAD

**Issue by rooterkyberian** [MISP/PyMISP#200]
`pymisp.MISPEvent(strict_validation=True).load(misp_export)` fails with `ValidationError: Additional properties are not allowed ('Object' was unexpected)` as MISP event schema does not define Object array.

**Comment by Rafiot** [comment]
Thanks for the hint, I'll look at it.

**Comment by Rafiot** [comment]
Note: The strict validation isn't working because the schema isn't up-to-date. The one in MISP/MISP is also outdated. Do we have an other one somewhere? 

cc @adulau @iglocska
