### ISSUE TITLE
MISP ERROR - "Failed to establish a new connection"

### ISSUE THREAD

**Issue by gitQuestions** [MISP/PyMISP#208]
Hi there,

Im trying to get data from my MISP suing the library PyMISP.

The library is already install and when executing the command (screenshot) I get a connection error. I´ve checked the MISP_URL and the MISP_KEY and they are the correct ones.

Can someone, PLEASE, help me????

![image](https://user-images.githubusercontent.com/37657672/37766366-076eab64-2dc7-11e8-85dc-697f187dd5d6.png)

:D

**Comment by Rafiot** [comment]
can you do `dig <domain>` on the same machine you're running the script on?

The error says it is unable to resolve the domain.

**Comment by gitQuestions** [comment]
Hi Rafiot,

"no servers could be reached". But the PING to the server works...

Thanks for the early response.

**Comment by SHSauler** [comment]
(1) Using `python3` will fix the "You are using python 2" message.
(2) Are you on the same machine running the script? Then you can use `localhost`. Otherwise you have to put the hostname into `/etc/hosts` so it can be resolved.

**Comment by gitQuestions** [comment]
That was the problem!

Now, im executing the file "mof.py" (https://github.com/xme/toolbox/blob/master/mof.py) to download some IOCs from MISP.  
![image](https://user-images.githubusercontent.com/37657672/37771766-e071980c-2dd8-11e8-96ba-ce8ecfeee119.png)
Seems that it runs correctly, but the created file doesnt have the IOCs information.
![image](https://user-images.githubusercontent.com/37657672/37771808-0a26b9de-2dd9-11e8-8421-f280a0decbe6.png)

ANY SUGGESTION?

I will continue working from that point.

Thank you!! :)

**Comment by Rafiot** [comment]
So 3 things:
1. the warnings can be ignored, you're simply connecting to a MISP instance without validating the certificate. I assume you're not in production.
2. The rulefile is empty because  you have no entries matching this line in your dataset: https://github.com/xme/toolbox/blob/master/mof.py#L47
3. This script isn't properly working in python3+, I did a PR to fix it.

**Comment by gitQuestions** [comment]
2. Using some "print()", I realize that the scripts didnt even enter in : **_Line 43 - for e in result['response']:_** .

3. It also doesnt work in python2.7. Could you tell me the meaning of "PR"?

Thank you so much!

**Comment by Rafiot** [comment]
2. try to print the result directly, it worrks for me
3. I don't know, I don't use python2.7 :) I can tell you that my changes work in python3. 

PR=Pull request, a change proposal in xme repository.

**Comment by gitQuestions** [comment]
I have used the new file you created (https://github.com/Rafiot/toolbox/blob/61ffa0091be12ea097ce6968f3acfec52c502736/mof.py) with Python3 and it still doenst downloading information from MISP... 

![image](https://user-images.githubusercontent.com/37657672/37818850-dfcc72b6-2e7b-11e8-8f1a-a0d33416acdb.png)

**Comment by SHSauler** [comment]
Or you don't have the necessary permissions (use a privileged auth key) to export them.

**Comment by gitQuestions** [comment]
I have tried with 3 files: **last.py, mof.py and get.py**

- Executing "get.py" I get an event information. Function called:
![image](https://user-images.githubusercontent.com/37657672/37824320-7c7f8fa2-2e8c-11e8-958b-e051be2172e8.png)

- Executing "last.py" I get "[]", not the information of the last X events. Function called
![image](https://user-images.githubusercontent.com/37657672/37824424-d7167804-2e8c-11e8-9209-624212b2fec0.png)

- Executing "mof.py" I also get "[]", not the informtion of all the events in the last X days. Function called:
![image](https://user-images.githubusercontent.com/37657672/37824454-f4595b2a-2e8c-11e8-9151-3c50ffeaf594.png)

I seems that the problem is in the two last functions...

Thank you.

**Comment by gitQuestions** [comment]
This is my profile:
![image](https://user-images.githubusercontent.com/37657672/37825039-dfb4197e-2e8e-11e8-9a3c-9131896b5d14.png)

These are my privileges:
![image](https://user-images.githubusercontent.com/37657672/37825061-f0c871e2-2e8e-11e8-8657-33c411e77b49.png)

**Comment by SHSauler** [comment]
Then @Rafiot seems correct and you have no events?

**Comment by gitQuestions** [comment]
Yes, I have 4 events:
![image](https://user-images.githubusercontent.com/37657672/37826161-ab27adde-2e92-11e8-8e92-54fd29ac6e43.png)

And the script is looking for event with the following catagories:
![image](https://user-images.githubusercontent.com/37657672/37826243-00f39020-2e93-11e8-84c9-1fbee5d6be3d.png)

The indicators sould match the query...

**Comment by gitQuestions** [comment]
I dont know to much about Python language. **Is this OK?:**

search() API function declaration: 
![image](https://user-images.githubusercontent.com/37657672/37829301-cc32938e-2e9e-11e8-918a-461e1a45420c.png)

search() in mof.py:
![image](https://user-images.githubusercontent.com/37657672/37829346-f6b9152e-2e9e-11e8-833c-8e11507116b1.png)

download_last() API function declaration:
![image](https://user-images.githubusercontent.com/37657672/37829374-12b3c724-2e9f-11e8-8e4c-dd81a3a19161.png)

download_last() in last.py:
![image](https://user-images.githubusercontent.com/37657672/37829439-46501876-2e9f-11e8-91dc-3b498334830a.png)

I think the problem is in the call of those functions (Both returns: "[]").

**Comment by Rafiot** [comment]
I know what's going on: your event isn't published.

**Comment by gitQuestions** [comment]
You are right. Sorry, this is the first time I use MISP... :)

**But** with that change, the script "last.py" works (Pictirue 1) but "mof.py" **doesnt still working**...

Picture 1:
 
![image](https://user-images.githubusercontent.com/37657672/37830021-83169d96-2ea1-11e8-935b-dcb31cf607e0.png)

![image](https://user-images.githubusercontent.com/37657672/37830043-94d45ee2-2ea1-11e8-8093-18d4ff9934df.png)

**Comment by gitQuestions** [comment]
FINALLY WORKS!!!!!!! The final problem was me and my lack of knowledge about MISP.

**# Thank you all of you for the support and advices.** 

Great community and owners.

**Comment by Rafiot** [comment]
Yes, because the attributes don't have the to_ids flag set.

**Comment by Rafiot** [comment]
excellent :)
