### ISSUE TITLE
How to generate the JSON list

### ISSUE THREAD

**Issue by makakin** [MISP/PyMISP#209]
Which .py file can generate the JSON list like the website: https://www.circl.lu/doc/misp/feed-osint gui or PyMISP

I tried last.py under example folder. However, seems generated different JSON format.

Thanks a lot.

**Comment by Rafiot** [comment]
Yep, the code is here: https://github.com/CIRCL/PyMISP/tree/master/examples/feed-generator

**Comment by makakin** [comment]
Thanks
