### ISSUE TITLE
Mix of python2 / python3

### ISSUE THREAD

**Issue by amuehlem** [MISP/PyMISP#214]
During the installation of MISP 2.4.89, I got an error stating PyMISP/examples/feed-generator-from-redis/fromredis.py can not be compiled. Having a look at the Python scripts in this directory I see a mix of /usr/bin/python and /usr/bin/python3 and it seems the fromredis.py should be compiled with python2 instead of python3. Shouldn't the call in fromredis.py not be changed to /usr/bin/python3?

```
  File "/var/www/MISP/PyMISP/examples/feed-generator-from-redis/fromredis.py", line 21
    print('sleeping [{}]\t{}'.format(temp_string, additional), end='\r', sep='')
                                                                  ^
SyntaxError: invalid syntax
```

Cheers
Andreas

**Comment by mokaddem** [comment]
Thanks for the report!
Fixed in #218
