### ISSUE TITLE
MISPObject: How to update MISPObject?

### ISSUE THREAD

**Issue by kar6** [MISP/PyMISP#225]
How do you update a MISPObject using PyMISP? 
The updates i need are:
- Update a value or comment of an Attribute within MISPObject
- Update comment of MISPObject

I've tried updating the value in JSON of MISP Event and do the update method, but i always got "An Internal Error Has Occurred".

**Comment by Rafiot** [comment]
Thank you for the question, turns our it was missing in PyMISP, and broken on MISP. 

We fixed it, but you will need to use the latest commit on MISP and PyMISP for it to work: 

```python
# Assuming misp_object is a MISPObject
# Assuming misp is a PyMISP

misp_object.comment = 'New object comment'

for a in misp_object.attributes:
    if a.value == value_you_search:
        a.comment = 'new comment'

misp.edit_object(misp_object)
```

**Comment by kar6** [comment]
I also tried the misp.add_object method for my updates and it also worked.

`# Assuming misp_object is a MISPObject
# Assuming misp is a PyMISP
# Assuming event is a MISPEvent

misp_object.comment = 'New object comment'

for a in misp_object.attributes:
    if a.value == value_you_search:
        a.comment = 'new comment'

misp.add_object(event_id=event['id'],
                                                      template_id=object_category_template['id'],
                                                      misp_object=misp_object)`

is this also recommended for updating a MISPObject?

**Comment by Rafiot** [comment]
It will work, yes. 

BTW, if you're using the latest commit of PyMISP, you don't need to pass the `template_id` anymore.

**Comment by kar6** [comment]
ok thank you for the help :)

**Comment by Rafiot** [comment]
sorry, I asked @iglocska and it *should not work*

**Comment by kar6** [comment]
when will it be pushed in stable branch?

**Comment by kar6** [comment]
yes, i'm just using the package for now

**Comment by Rafiot** [comment]
Ok, I can do a release now. But do not forget to update (git pull) MISP, the release 2.4.90 won't work.

If you want to wait, you can still use your current script until version 2.4.91 is released.

**Comment by kar6** [comment]
if i can still use add_object to update misp object until version 2.4.91, it's ok. Thank you :)
