### ISSUE TITLE
Sample upload without additional encryption

### ISSUE THREAD

**Issue by mohlcyber** [MISP/PyMISP#227]
Hi Guys,

is there any way to upload a malware sample without adding additional encryption?
I am upload malware samples to my MISP instance already zipped and pw protected.

`
path = '%s.zip' %taskid
    misp.upload_sample('%s.zip' %mainfile, path, eventid)
`

The uploads works fine so far. However when i download the file via the API i get the following error:

`    sample = misp.download_samples(event_id=eventid, all_samples=True)
  File "/usr/local/lib/python2.7/dist-packages/pymisp-2.4.89-py2.7.egg/pymisp/api.py", line 1173, in download_samples
    unzipped = BytesIO(archive.open(f['filename'], pwd=b'infected').read())
  File "/usr/lib/python2.7/zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named u'crypt.zip' in the archive" `

The reason is because the file is called crypt.zip.zip. 

I checked the admin settings already but couldn't find any option to disable the encryption.

Many thanks and all the best,
Martin

**Comment by Rafiot** [comment]
So it is a little bit more complicated that it looks: uploading a malware to MISP is doing quite a few things in the background.
By default, it takes the malware sample, puts it in a zip, rename the file to it's MD5 and creates a text file called `<MD5>.filename.txt` that contains the original filename. Finally, it creates a MISP object of type file containing more indicators (hashes, entropy, ssdeep, ... ).
If you have the expanded modules available, it will also create other objects for PE/ELF/Mach-O files.

Attaching a file already zipped & password protected makes it quite a bit more complicated.

We can look for alternatives, but I don't think we will support that in the defualt upload_malware method.

**Comment by Rafiot** [comment]
And one more thing: if you really want to do it this way, you can add the sample as attachment, and the binary won't be touched.

**Comment by mohlcyber** [comment]
Excellent thanks for you quick response. I created a quick workaround with filenames that seems to be working so far. 
I am trying to use the download_samples function right now to get the file samples back downloaded. Are there any examples how to download the files via the download_samples function?

I am getting the following response:
`(True, [[u'1008', u'CV_JANE_SMITH.DOC.zip', <_io.BytesIO object at 0x7f2da3805bf0>]])`

Are there any examples to write back as a file?

Many thanks and all the best,
Martin

**Comment by Rafiot** [comment]
Yes, the `<_io.BytesIO object at 0x7f2da3805bf0>` is the file you want to write down.

So you can do it this way:

```python 

eventid, filename, file_as_bytes = response[1]

with open(filename, 'wb') as f:
    f.write(file_as_bytes)
```

And you should be all good.

**Comment by mohlcyber** [comment]
Thanks for the prompt response. That helped definitely.
Getting now the following error message.

```
f.write(file_as_bytes)
TypeError: must be string or buffer, not _io.BytesIO
```
Looking around to find a solution.
Again thanks for all your help.

**Comment by Rafiot** [comment]
Sorry, I missed the `.read()`: 

```python
eventid, filename, file_as_bytes = response[1][0]

with open(filename, 'wb') as f:
    f.write(file_as_bytes.read())
```

**Comment by mohlcyber** [comment]
Awesome thanks Rafiot for all your support. Works perfect.
One observation. I wasn't be able to download files directly with the PyMISP libraries. 
I got the following error:

`KeyError: "There is no item named u'crypt.zip' in the archive"`

I changed the following lines in the api.py (line 1202):

```
        # Old format
        _#unzipped = BytesIO(archive.open(f['filename'], pwd=b'infected').read())_
        unzipped = BytesIO(archive.open(f['md5'], pwd=b'infected').read())
```
Which worked fine. Strange behaviour. Anyhow... thanks for all you support. The issue can be closed of course :).

**Comment by Rafiot** [comment]
yes, it is because the library expects malware samples to be in a zip file (with md5 as a filename) along with a text file containing the original file name.

I really don't recommend to upload the pre-zipped malware on MISP, as it is unclear for other people receiving your data how to handle it.
