### ISSUE TITLE
Finding unpublished event

### ISSUE THREAD

**Issue by ninSmith** [MISP/PyMISP#228]
Hi,

I'm looking for unpublished event and I tried ```misp.search(published=False)``` but it doesn't seem to work.

Am I missing something ?

FYI:

```
MISP 2.4.91
pymisp 2.4.90.1
python 3.5.2
ubuntu 16.04
```

Thanks

**Comment by Rafiot** [comment]
Hi,

it seems to work for me, besides the fact it times out because there are lots of unpublished events on out platform. Can you give me more details on what doesn't work?

**Comment by ninSmith** [comment]
On my side I only have published events.   

In the web UI I can see unpublished event (```Published: No```) from today.

But if I do ```misp.search(published=False, last='2d')``` the response contains only published events ( ```'published': True```).

My ultimate goal is to extract ids of unpublished event to publish them afterwards.

**Comment by Rafiot** [comment]
That bug was fixed.
