### ISSUE TITLE
PyMISP update_event

### ISSUE THREAD

**Issue by randomname13** [MISP/PyMISP#229]
update_event does not delete (deleted=1) removed attributes or tags (from JSON) in the MISP database

**Comment by Rafiot** [comment]
It is not supposed to. Delete only soft delete the attribute, meaning it is not visible on the web interface. It is consistent with deleting an attribute on the interface itself.

**Comment by randomname13** [comment]
Thanks for your answer, but should't the update_event at least soft delete the removed attributes from the JSON or how can I accomplish that?
