### ISSUE TITLE
Publish event timestamp

### ISSUE THREAD

**Issue by KeTePires79** [MISP/PyMISP#233]
Good morning ,

I have an issue with Pymisp.

When I try to change/add/delete the tag of any event via web, the event
goes to unpublished status. But,changing/adding/removing the tag via API
(pymisp) does not change the publishing status of that event.

Is that an error?
What would be the method to make these massive label changes through
Pymisp and change the publication status of each event?

Thank you very much in advance.

I look forward to hearing from you.

Greetings.

**Comment by Rafiot** [comment]
Sorry for the late answer.

So I'm assuming you're getting the event, adding a tag and pushing the whole event back up. I recommend you to use `PyMISP.tag([uu]id, tag)` that will do what you want.
