### ISSUE TITLE
Object insertion error with new object template

### ISSUE THREAD

**Issue by ogmasec** [MISP/PyMISP#242]
### Description
The function `add_object()` raise an error with a new object template:
`pymisp.exceptions.NewAttributeError: The type of the attribute is required.`
**This error only occurs with a new object template.**

**Object insertion**
`misp_object = GenericObjectGenerator('threatgrid-report')`
`misp_object.generate_attributes(attributeAsDict)`
`addObject = self.mispObject.add_object(eventId, 115, misp_object)`

**with `attributeAsDict` which contains:**

>  {'threat_score': 95, 'analysis_submitted_at': '2018-06-15T06:40:27', 'permalink': 'https://panacea.threatgrid.com/mask/samples/2e445ef5389d8b', 'heuristic_raw_score': 7.8385159793597, 'heuristic_score': 96, 'original_filename': 'juice.exe', 'id': '2e445ef5389d8b'}

### Object template:
> {
  "required": [
    "threat_score"
  ],
  "attributes": {
    "threat_score": {
      "description": "threat_score",
      "disable_correlation": true,
      "categories": [
        "External analysis"
      ],
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "heuristic_raw_score": {
      "description": "heuristic_raw_score",
      "disable_correlation": true,
      "categories": [
        "External analysis"
      ],
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "heuristic_score": {
      "description": "heuristic_score",
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "analysis_submitted_at": {
      "description": "Submission date",
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "original_filename": {
      "description": "Original filename",
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "permalink": {
      "description": "permalink",
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "id": {
      "description": "ThreatGrid ID",
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "iocs": {
      "description": "iocs",
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
	  "multiple": true,
      "misp-attribute": "text"
    }
  },
  "version": 5,
  "description": "ThreatGrid report",
  "meta-category": "misc",
  "uuid": "23b3576b-2e68-4a86-a103-68820daef1d5",
  "name": "threatgrid-report"
}
>

**Comment by Rafiot** [comment]
Yes, `generate_attributes` expects a list of attributes (as you can pass extra keys, such as "to_ids", or "disable_correlations"). 

This list of dicts will work: 
```python
attributeAsDict = [{'threat_score': 95}, {'analysis_submitted_at': '2018-06-15T06:40:27'}, {'permalink': 'https://panacea.threatgrid.com/mask/samples/2e445ef5389d8b'}, {'heuristic_raw_score': 7.8385159793597}, {'heuristic_score': 96}, {'original_filename': 'juice.exe'}, {'id':  '2e445ef5389d8b'}]
```

**Comment by adulau** [comment]
@Rafiot Just wondering, could we improve the output of the exception returned? to make it more clear.

**Comment by Rafiot** [comment]
Yeah, I need to force the parameter of  `generate_attributes` to be a list.

That's the kind of stuff you can do (if PyMISP knows the template):

```python
attributeAsDict = [{'threat_score': {value=95, to_ids=False}}, 
    {'analysis_submitted_at': '2018-06-15T06:40:27'}, 
    {'permalink': 'https://panacea.threatgrid.com/mask/samples/2e445ef5389d8b'}, 
    {'heuristic_raw_score': 7.8385159793597}, {'heuristic_score': 96}, 
    {'original_filename': 'juice.exe'}, {'id':  '2e445ef5389d8b'}]
```

**Comment by adulau** [comment]
@ogmasec Did this solve your issue?

**Comment by ogmasec** [comment]
It did, I just had to add the type:
`{'threat_score': {value=95, to_ids=False,type=text}}`

Thank a lot for you help.
Maybe this method deserve to be clarified a bit. Not easy to guess that we have to pass a list of dictionary with a dictionary as argument.

**Comment by Rafiot** [comment]
Yep, I'm marking it as such so I don't forget to add the documentation
