### ISSUE TITLE
why does this PyMISP.search() timeout

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#243]
2.4.92

I'm starting to play with some searches to experiment retrievals for an internal consumer from our MISP instance.

My goal will be to produce a blacklist of IPs based on some business rules, e.g. age, org, tags, to_ids, etc. -- TBD). So, I've started with something very simple and the search appears to timeout after 60 seconds.

Can you please help me refine this simple search to make it work so I can go further with playing?
```
(Pdb) reply = misp.search(org=21, date_from=1529625600, type_attribute='ip-dst')
*** simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(Pdb) 
```
And, this one which failed after 25 seconds:
```
(Pdb) reply = misp.search(controller='attributes', type_attribute=['ip-dst','ip-src'], date_from=df)
*** pymisp.exceptions.PyMISPError: Something bad happened on the server-side, but there was no response content to be decoded
(Pdb)
```

**Comment by github-germ** [comment]
i can do this restSearch with a browser and no timeout. returns lots
```https://localhost/attributes/restSearch/download/null/ip-dst/null/21/```
perhaps there's some timeout config that needs to be tuned for PyMISP client or server side?

**Comment by github-germ** [comment]
and why does this HTTP `restSearch` yield an empty `response` when there are many `attributes` within the `last 2d`?
```
https://localhost/attributes/restSearch/download/null/ip-dst/null/iSIGHT/null/null/null/2d/null/null/null

{
    "response": []
}
```
The db shows `many`:
```
MariaDB [misp]> select count(*) from attributes where type = 'ip-dst' and timestamp > 1529861536;
+----------+
| count(*) |
+----------+
|      115 |
+----------+
```
 `2d` for this test was epoch timestamp `1529861536` (Sunday, June 24, 2018 5:32:16 PM)

**Comment by github-germ** [comment]
@Rafiot -- can you take a look at this and set me straight on what I must be doing wrong: (1) `PyMISP.search()` timeout, (2) HTTP `restSearch` empty response. Thanks...

**Comment by GitHubMISPer** [comment]
I'm experiencing a similar issue even when I try the UI's "Search Attributes" page. If my query returns a lot of results (>7000 in my case), they still correctly display 60 attributes on a page. However, if I want to download the results as a CSV, XML, or JSON file it fails. 

The CSV was blank aside from the header line:
![image](https://user-images.githubusercontent.com/40214717/41935351-996b67da-7946-11e8-8c6c-ace0c2657ae1.png)

The XML and JSON failed with this 503 error:
![image](https://user-images.githubusercontent.com/40214717/41935472-0e5d6a70-7947-11e8-91f1-1c3a32cd3c46.png)

As mentioned in the 503 error, I don't think MISP is equipped to handle such large queries. This would explain why queries (no matter the method) don't return anything.

**Comment by github-germ** [comment]
Here's an HTTP `restSearch` with an HTTP 500 (note: there was no output to `error.log` nor `debug.log`):
```
$ cat ./attributes.restsearch.curl
curl \
--header "Authorization: **REDACTED**" \
--header "Accept: application/json" \
--header "Content-Type: application/json" \
--insecure \
--include \
--write-out 'HTTP-code=%{http_code} Time-total=%{time_total}\n' \
https://127.0.0.1/attributes/restSearch \
--data \
'
{
   'type': 'ip-dst',
   'org':  21,
   'last': '2d',
}
'
$ 
$ ./attributes.restsearch.curl
HTTP/1.1 500 Internal Server Error
Date: Tue, 26 Jun 2018 20:52:29 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
X-Powered-By: PHP/7.1.8
Set-Cookie: CAKEPHP=r0latka49hbvm1j5qvll6gmrvc; expires=Wed, 27-Jun-2018 20:52:29 GMT; Max-Age=86400; path=/; secure; HttpOnly
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

HTTP-code=500 Time-total=14.423
$ 
```

**Comment by github-germ** [comment]
got some help in gitter this morning.

1. input from @iglocska and @FloatingGhost pointed out that the HTTP 500 error example in https://github.com/MISP/PyMISP/issues/243#issuecomment-400459396 was due to invalid JSON. **my bad**. i will fix that and re-test.

2. the timeouts might could be due to not enough memory. @iglocska suggested increasing the `memory_limit` for a specific `role` and use that `role` for _large searches_ . this can be set with `administration -> list roles -> add / edit`. i will try this.

3. there may also be an issue that @Rafiot is aware of in the API for timestamp ranges. we'll see how my re-testing goes.

**Comment by github-germ** [comment]
Re-testing examples in this issue after feedback in https://github.com/MISP/PyMISP/issues/243#issuecomment-400695809

[key: OK='now works', NG='no good: still not working']

- OK: expanded `role` for user running the `PyMISP.search` from 1G to 10G for the test in https://github.com/MISP/PyMISP/issues/243#issue-335007725 and that now worked.
- NG: `restSearch` URL with `last` set to `2d` as in https://github.com/MISP/PyMISP/issues/243#issuecomment-400400531 still yields an empty response; whereas, setting `from` and `to` as `yyyy-mm-dd` for the same 2 days does return many attributes as it should.
- NG: The `List Attributes` followed by any of the `Download` clicks as per https://github.com/MISP/PyMISP/issues/243#issuecomment-400439724 still fails with HTTP 503 even after the memory for that user's role was increased to 10GB (from the default 1G). Could this be a global memory issue, i.e. our VM has 32GB and perhaps free mem is below the memory required in this test?
- NG: fixed my silly broken JSON in the curl test in https://github.com/MISP/PyMISP/issues/243#issuecomment-400459396 which queries on `last` an that still fails with an empty response (like above in `restSearch`), but does send an HTTP 200.
- OK: with the fixed JSON in the curl test in https://github.com/MISP/PyMISP/issues/243#issuecomment-400459396 but using `from` and `to` (and not `last`) the response has content.

**Comment by Rafiot** [comment]
It doesn't directly answer your problem, but still relevant to your interest: it is recommended to use `search_index` (if possible) in order to get the meta information of the events to search, and then, if needed, to get the events sequentially with the `get` call. 
It presented here: https://github.com/MISP/PyMISP/blob/master/docs/tutorial/Usage.ipynb

The problem of  `search` is that it will generate a huge JSON stream in memory and calling events one after the other will be a lot faster at the end. 

I'm currently travelling with very limited access to my computer so I'll get back to you regarding the other problems as soon as possible, unless @iglocska does it first.

**Comment by iglocska** [comment]
Will try to go through the issues tomorrow, but today I only have phone access.

**Comment by github-germ** [comment]
Thank you guys!

**Comment by github-germ** [comment]
@iglocska -- just for my planning, any iea when you might be able to get back this issue? thx!

**Comment by github-germ** [comment]
@Rafiot ... following up from https://github.com/MISP/PyMISP/issues/243#issuecomment-401599662

With `search_index()` how would I get all attributes of type `ip-dst` for the last 24 hours? Thanks...

**Comment by Rafiot** [comment]
You can do it this way:

```python
from pymisp import PyMISP
pm = PyMISP('URL', 'key')
pm.search(controller='attributes', type_attribute='ip-dst', timestamp='24h')
```
