### ISSUE TITLE
objects/add API doesn't work

### ISSUE THREAD

**Issue by allenxian** [MISP/PyMISP#244]
![image](https://user-images.githubusercontent.com/22782166/41829313-96b7fd62-786c-11e8-9643-17bd4e7f1bca.png)
![image](https://user-images.githubusercontent.com/22782166/41829324-a8ee187c-786c-11e8-95d5-73c98d48f938.png)

**Comment by Rafiot** [comment]
Does your user have the right to create tags?

**Comment by Rafiot** [comment]
Hmm, I see an object with the tag and the attribute

**Comment by allenxian** [comment]
MY account is admin，have the right to create tags。I still can‘t find what cause the 403 mistake。

**Comment by allenxian** [comment]
IT works fine。I think my misp-object was wrong。Thank you for for your patience。

**Comment by Rafiot** [comment]
I don't have enough information to confirm, but if it works fine now, I'll close the ticket.
