### ISSUE TITLE
get_all_tags limitations

### ISSUE THREAD

**Issue by cvandeplas** [MISP/PyMISP#245]
The `get_all_tags()` function has a number of limitations:
- it does not include the count of a tag if used on an attribute
- it does not handle the Galaxies like it does with Taxonomies:  The sub-keys with the details are not included. 
A tag from a Taxonomy contains:
```
{   "Taxonomy": {
        "description": "Vocabulary for Event Recording and Incident Sharing (VERIS)",
        "enabled": true,
        "expanded": "attribute:integrity:variety: Deface content",
        "id": "12",
        "namespace": "veris",
        "version": "2"
    },
    ...
    "name": "veris:attribute:integrity:variety=\"Defacement\"",
}
```
A tag from a Galaxy contains no subkeys related to the metadata:
```
{   "name": "misp-galaxy:tool=\"Plexor\"",
    ...
}
```

**Comment by Rafiot** [comment]
I'm going to close this one here, as PyMISP returns what MISP gives back.
