### ISSUE TITLE
Improve error handling in PyMISP side

### ISSUE THREAD

**Issue by Rafiot** [MISP/PyMISP#248]
i.e. when a list of attributes are added to an event, and some cannot be added, make it easier to access so the script can take better decisions.

**Comment by github-germ** [comment]
This may or may not be useful when designing changes in exception handling. @Rafiot had asked me to list some suggestions when I was experiencing HTTP 503 errors in #3318. That list is https://github.com/MISP/MISP/issues/3318#issuecomment-398163042

**Comment by github-germ** [comment]
@Rafiot -- do we still want to keep this issue open, i.e. might you still consider some of these suggestions now that the API has been refactored? Thx...

**Comment by github-germ** [comment]
Hi @Rafiot -- is there anything new for this? Thx!!

**Comment by Rafiot** [comment]
We did lots of refactoring on the search API.

Which error messages do you need improved?

**Comment by github-germ** [comment]
Hi @Rafiot ... I appreciate your follow-up reply.
- I had listed examples in MISP/MISP#3318
- And today, I hit an exception back from a `PyMISP.search()` that didn't provide info for me to understand more about the root cause. See MISP/PyMISP#308

**Comment by Rafiot** [comment]
There were lots of changes on MISP side, the error messages are now clearer. Closing.
