### ISSUE TITLE
KeyError 'name' surfaced when using add_named_attribute

### ISSUE THREAD

**Issue by chocologurt** [MISP/PyMISP#253]
Hi, 

I am using the method add_named_attribute to add attributes into MISP. However, I received the following error (attachment below). 

![capture](https://user-images.githubusercontent.com/24536927/43000994-33b76e20-8c56-11e8-8891-90cbc6ec1c3c.PNG)

Really appreciate any help that I can get.

**Comment by Rafiot** [comment]
Oh wow, this is super weird.

The attribute is properly added but the response from the server contains a MISPObject that doesn't contains the key `'name'`, and that's not supposed to happen.

Can you enable debug in PyMISP (add the `debug=True` key when you initialize the class), and send me the response of the server after `add_named_attribute`? It will be very long, and contains the auth key so you probably want to sanitize it.

**Comment by chocologurt** [comment]
Hi, 

After trying PyMISP with an older version of MISP, the error disappeared. Hopefully the error does not appear again. 

Thank you so much for replying promptly on Friday and sorry for the late reply!

**Comment by Rafiot** [comment]
No worries. PyMISP should work with the most recent version of MISP, if you have any issue, please let us know.

**Comment by chocologurt** [comment]
@Rafiot Hi again, I started inserting with MISP again and the error surfaced. I tried your suggestion and the output is in the attachment below. 
[FE_PyMISP_output.txt](https://github.com/MISP/PyMISP/files/2221634/FE_PyMISP_output.txt)

**Comment by Rafiot** [comment]
It could be an issue with this older instance of MISP (2.4.90?) that doesn't contain the `name` key:

```
      "Object": [
            {
                "comment": "",
                "meta-category": "file",
                "uuid": "42d2c76a-001a-4695-8d18-792b428dab22",
                "distribution": "5",
                "ObjectReference": [],
                "template_uuid": "688c46fb-5edb-40a3-8273-1af7923e2215",
```

It doesn't seem to be the case with newer versions of MISP, so can you try to update your MISP instance?
