### ISSUE TITLE
Search MISP for objects

### ISSUE THREAD

**Issue by cvandeplas** [MISP/PyMISP#254]
In some use-cases a tool will need to search by using data from a `MISPObject`. ( `id`, `uuid`, ...) 
(let's say you don't know the MISP Event info, only the object info)

I could not find a way to perform such a search in PyMISP. 
Thank you for considering this feature. (maybe in the `PyMISP.search()` ? )

**Comment by Rafiot** [comment]
Not sure it is possible on server side. @iglocska?

**Comment by Rafiot** [comment]
It is not supported by MISP.
