### ISSUE TITLE
Question: efficient PyMISP API client code to untag an attribute

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#258]
Give an `eventid`, what's the best way to `untag` a specific tag for a given attribute value that's within that `eventid`?

My use case is that we use 2 tags to denote a boolean whether an attribute is currently `active` or `inactive`. If there's another method to support this, let me know.

(Maybe I'm being dense not seeing how to do this now?)

Thanks!

**Comment by github-germ** [comment]
Perhaps related: can you provide some details on the use of the database column boolean, {{{attributes.deleted}}}, e.g. when {{{True}}} what effect does this have in the WebUI or when retrieving attributes in an event via the API (curl, python, ...)?

**Comment by github-germ** [comment]
ok, i have a solution, just let me know if this is the _best_ method please...
and also, still interested in use/behavior of `attributes.deleted`.

get attributes for the eventid with
```
r = search(
    controller='attributes'
    eventid=eventid,
    tags=['my-tag-name'],
    values=my_list_of_attr_values)
```
and then loop through each `attrList` getting the `uuid` and call
```
if 'response' in r and r['response']:
    for attr in r['response']['Attribute']:
        misp.untag(attr['uuid'], 'my-tag-name')
```

**Comment by Rafiot** [comment]
Hello, sorry for not answering immediately, yesterday was holiday in most of Europe.

As of today, ye, untag is the best/only way: the tags don't have the soft delete feature yet so you cannot do any differently.

**Comment by github-germ** [comment]
Thx for your reply. I did get this implemented with that method.

**Comment by github-germ** [comment]
@Rafiot  -- oops... can you  provide more insight to https://github.com/MISP/PyMISP/issues/258#issuecomment-412983593 re' the `attribute.deleted` boolean in the db.

**Comment by Rafiot** [comment]
the deleted flag means soft delete: the soft deleted attributes aren't visible in the UI, and aren't exported by default when you get an event via the API.
