### ISSUE TITLE
why isn't change_comment() working for me?

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#260]
i'm trying to use `change_comment` for the first time. it's not working, i.e. the attribute in the event where i apply the change when observed in the WebUI has not changed, nor if i retrieve the attribute again via PyMISP as below:

also, why did `change_comment` seemingly return all of my events -- notice the `len` is `4917` below.

here's an excerpt from a python debugger session:
```
(Pdb) print(newComment)
score:[5.7,2018081615],[7.8,2018081615]
(Pdb) print(attr['uuid'])
47fcf8f0-63af-4297-b21c-a6af79f2a7bb
(Pdb) print(attr)
{'id': '1031069', 'event_id': '14959', 'object_id': '0', 'object_relation': None, 'category': 'Network activity', 'type': 'ip-dst', 'to_ids': True, 'uuid': '47fcf8f0-63af-4297-b21c-a6af79f2a7bb', 'timestamp': '1534432498', 'distribution': '5', 'sharing_group_id': '0', 'comment': 'score:[5.7,2018081615]', 'deleted': False, 'disable_correlation': False, 'value': '1.0.128.131', 'Tag': [{'id': '1101', 'name': 'X-Force-Inactive', 'colour': '#ff0000', 'exportable': True, 'org_id': False, 'hide_tag': False, 'user_id': '0'}, {'id': '964', 'name': 'misp:threat-level="no-risk"', 'colour': '#b3b3b3', 'exportable': True, 'org_id': False, 'hide_tag': False, 'user_id': '0'}]}
(Pdb) print(attr['comment'])
score:[5.7,2018081615]
(Pdb) rc = misp.change_comment(attr['uuid'], newComment)
(Pdb) print(len(rc['response']))
4917
(Pdb) print(rc['response'][0])
{'id': '14962', 'org_id': '2', 'date': '2018-08-16', 'info': 'IBM X-Force 20180816 Malware', 'uuid': '5b759520-c3c4-4862-90dc-5d75496a006a', 'published': True, 'analysis': '0', 'attribute_count': '5', 'orgc_id': '22', 'timestamp': '1534432544', 'distribution': '0', 'sharing_group_id': '0', 'proposal_email_lock': False, 'locked': True, 'threat_level_id': '2', 'publish_timestamp': '1534432544', 'disable_correlation': False, 'extends_uuid': '', 'Org': {'id': '2', 'name': 'TIARE', 'uuid': '5a6a4161-b2e0-46b6-b12e-1bca0a6b037c'}, 'Orgc': {'id': '22', 'name': 'X-Force', 'uuid': '5afc45ad-54d4-47ec-9bb7-52bc0a670c7f'}, 'EventTag': [{'id': '50235', 'event_id': '14962', 'tag_id': '944', 'Tag': {'id': '944', 'name': 'X-Force', 'colour': '#a31d96'}}]}
(Pdb) revisedAttr = misp.search(controller='attributes', uuid='47fcf8f0-63af-4297-b21c-a6af79f2a7bb')
(Pdb) print(revisedAttr)
{'response': {'Attribute': [{'id': '1031069', 'event_id': '14959', 'object_id': '0', 'object_relation': None, 'category': 'Network activity', 'type': 'ip-dst', 'to_ids': True, 'uuid': '47fcf8f0-63af-4297-b21c-a6af79f2a7bb', 'timestamp': '1534432498', 'distribution': '5', 'sharing_group_id': '0', 'comment': 'score:[5.7,2018081615]', 'deleted': False, 'disable_correlation': False, 'value': '1.0.128.131', 'Tag': [{'id': '1100', 'name': 'X-Force-Active', 'colour': '#00ff00', 'exportable': True, 'org_id': False, 'hide_tag': False, 'user_id': '0'}, {'id': '967', 'name': 'misp:threat-level="high-risk"', 'colour': '#d60000', 'exportable': True, 'org_id': False, 'hide_tag': False, 'user_id': '0'}]}]}}
(Pdb)
(Pdb) print(revisedAttr['response']['Attribute'][0]['comment'])
score:[5.7,2018081615]
(Pdb) 
```

**Comment by github-germ** [comment]
@Rafiot -- should I be changing an attribute comment another way? Thx!!

**Comment by github-germ** [comment]
On Gitter...
```
Andras Iklody @iglocska 08:30
change_comment() is deprecated, please use update_attribute()
```

**Comment by github-germ** [comment]
using `update_attribute` did not revise the comment either :-(

**Comment by github-germ** [comment]
also tried passing a `MISPAttribute` to `update_attribute` and that doesn't work either.

**Comment by github-germ** [comment]
none of these 4 attempts work...
```
def reviseAttrComment(misp, attr, score, timestamp):
    '''
    TBD
    currently not working. see https://github.com/MISP/PyMISP/issues/260
    '''
    newComment = getComment(
        score        = score,
        timestamp    = timestamp,
        priorComment = attr['comment'])

    # 1
    #mispAttr = MISPAttribute()
    #mispAttr.from_dict(**attr)
    #r = misp.update_attribute(attr['uuid'], mispAttr)

    # 2
    #r = misp.update_attribute(attr['uuid'], {'comment': newComment})

    # 3
    #r = misp.update_attribute(attr['id'], {'comment': newComment})

    # 4
    r = misp.update_attribute(int(attr['id']), {'comment': newComment})

    if not 'response' in r or not r['response']:
        sys.stderr.write('reviseAttrComment failed for attr="%s" (id=%s), newComment="%s"'
           		% (attr['value'], attr['id'], newComment))
```

**Comment by github-germ** [comment]
@Rafiot -- what next on this one? thx...

**Comment by Rafiot** [comment]
This one works for me: `misp.update_attribute(194573, {'comment': 'bar'})`

Are you sure you have the permission? Also, this call returns an attribute, not a full event.

**Comment by iglocska** [comment]
If you use the same key and curl - does the same action work?

Post to:
```
/attributes/edit/[attribute_id]
```
Headers:
```
  Authorization: your_key
  Content-type: application/json
  Accept: application/json
```
Payload:
```
{"comment":"foo"}
```

**Comment by github-germ** [comment]
@iglocska -- curl also fails to update attr comment. let me know what to explore next. THANKS!!!

**Comment by github-germ** [comment]
@Rafiot + @iglocska -- would be helpful to make progress on this issue. Thx!

**Comment by iglocska** [comment]
Just tested it via curl with both an admin and a normal sync user. Works in both cases. curl command user:

```
root@iglocska-ThinkPad-T480:/var/www/MISP# curl -v -k --header 'Authorization: my_api_key' --header 'Accept: application/json' --header 'Content-Type: application/json' -X POST --data '{"comment": "foo2"}' http://localhost:5001/attributes/5b7c01b5-ee10-4825-bb7d-2f6f4df74d74

```

**Comment by github-germ** [comment]
@iglocska -- thx for testing! My environment is slightly different. My user is 'sync as tagger', and my org and orgc differ. Not sure if that's related to the problem. Have you had a chance to look at the details I posted in 
https://github.com/MISP/PyMISP/issues/260#issuecomment-415824889

Much appreciated. I can run more tests, grab more debug, etc. with your direction.

**Comment by iglocska** [comment]
Ah ok, you're trying to edit an event that you didn't create. That is not supported for any function not used by the sync mechanism as it's exclusively meant to be used for synchronisation. Again, as discussed before, if you want to use separate orgc_ids for different events internally - that's fine, but you'll have to use the appropriate users to edit them (= same orgc_id).

**Comment by github-germ** [comment]
Why can I update the event iteself, and tags for the same attr within that event running the same process, same code, same user?

**Comment by github-germ** [comment]
Were there changes made to support this setup originally as in https://github.com/MISP/PyMISP/issues/239 that need to be applied for update_attribute?

**Comment by iglocska** [comment]
You can update the event itself because you go through a function that is used by the sync (/events/edit). The attribute level edit is never used by the sync. Basically you can abuse the side effect of the sync mechanism to edit events via /events/edit with a sync user, but that's about it.

**Comment by github-germ** [comment]
Let me make sure I understand. If we need to arrange org/orgc differently as we do with our events that are ingested vua PyMISP, then we cannot edit the comment of attributes within, but we can tag/untag those attributes? If this is true, then is our use case flawed or can editing attributes be enhanced to support this? Thx again!

**Comment by github-germ** [comment]
I think I am following those "rules" for our use case. Are you saying that the root cause of my inability to change the attr comment is that the user has a sync role, and if I remove the sync role, I will be able to create/edit events and attributes within those events?

If so, here's the current user's role. What should I change?

![screen shot 2018-08-29 at 9 27 17 am](https://user-images.githubusercontent.com/8812009/44790653-d483ea00-ab6d-11e8-8752-27b954162aaa.png)

**Comment by iglocska** [comment]
If you remove the sync role you will not be allowed to break the ownership of data like you do currently.

1. If I create an event, the orgc will be my user's org. I can edit it any way I want.
2. If I see an event that has a different orgc (= not my event), I cannot edit it.

Rule #2 has an exception for sync users using some API calls (/events/edit) to make the synchronisation mechanism work.

**Comment by github-germ** [comment]
If a sync user can edit an event, then why not allow that user to edit an attr contained in that event?  Currently, that user can tag those same attributes. 

If this cannot change, then is there alternative method to accomplish my use case?  We want to store a history of the changes in score with that date (yyyymmddhh) for the life cycle of attributes received via an hourly feed, e.g. (5.7,2018010108),(3.4,2018042713), where we append as it changes. The attr.comment text (64k chars) seemed like a good place.

Open to other ideas. Thanks!!

**Comment by rommelfs** [comment]
I think that been answered in the last posts of @iglocska: it is an abuse of the sync mechanism.

The alternative way has also been outlined. Quote from earlier: "Please make sure that you create a user corresponding to the organisations of each of those feeds."

Please outline what is blocking you from doing it the correct way. Maybe we are missing an important aspect. Thanks.

**Comment by github-germ** [comment]
@iglocska + @rommelfs -- thanks to both of you for persisting through me being dense headed. indeed calling `update_attribute` as a user that's a member of the `orgc` that created the event and attribute within does work.

fyi prior references: 
- https://github.com/MISP/MISP/issues/3224
- https://github.com/MISP/PyMISP/issues/239

this now works for me. if i am still doing something "wrong" to get our desired use case, please let me know. THANKS AGAIN!

the **_TRICK_** is that with our use case (which i understand you deem unusual) is switching users. our initial ingestion and hourly updates are all done by one app: first creating and adding attributes, and then updating attributes and tags as needed as more info is aquired in a future hourly feed. hence, the **_TRICK_** is as follows (was confusing to me that i could `tag/untag` an attribute in an event created by a user in `org`, but to update the comment in that same attribute i need to be a user in `orgc`):

- for the initial `event_add` and subsequent `update_event` that have `add_attribute` and `tag/untag`, the app talks to PyMISP as a user in `org`.
- however, note that `add_event` creates with differing `org` (set to our internal analyst org name, i.e. "we" own this event even though it comes from a feed) and `orgc` (set to represent the feed creater, i.e. not "us").
- the _**TRICK**_ is then when there's a need to call `update_attribute` (which is via the `uuid` of the attribute, and not changed as part of a call to `update_event`) to revise a comment in a future feed update to an existing attr in an existing event that same single app needs to use a PyMISP connection for user in `orgc` (and not the usual one in `org`).
