### ISSUE TITLE
Publish PyPI wheel files

### ISSUE THREAD

**Issue by sim0nx** [MISP/PyMISP#264]
Hi,

Could you please consider publishing PyMISP in the wheel format on PyPI ?

See here for more information on wheel format and how to do that (2nd link):
https://wheel.readthedocs.io/en/stable/
https://packaging.python.org/guides/distributing-packages-using-setuptools/#wheels
https://pythonwheels.com/

TIA

**Comment by Rafiot** [comment]
That should be done (?)

**Comment by sim0nx** [comment]
thanks!
