### ISSUE TITLE
pymisp.update_event() event too big?

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#267]
Is there a limit to the number of attributes in an in-memory event passed to `pymisp.update_event()` (and `add_event()`)?

I had an update with 37k attributes to add to an existing MISP event, and got this error:
```
Exceptions=[PyMISPError('Unknown error: the res\
ponse is not in JSON.\nSomething is broken server-side, please send us everyt\
hing that follows (careful with the auth key):\nRequest headers:\n{\'User-Age\
nt\': \'PyMISP 2.4.93 - Python 3.6.4\', \'Accept-Encoding\': \'gzip, deflate\\
', \'Accept\': \'application/json\', \'Connection\': \'keep-alive\', \'Conten\
t-Length\': \'11698152\', \'Authorization\': \'<REDACTED_AUTH_KEY>', \'conten\
t-type\': \'application/json\'}\nRequest body:\n{\n  "E\
vent": {\n    "Attribute": [\n      {\n        "category": "Network activity"\
,\n        "comment": 
...
```

- This response included details for all 37k attributes in that event.
- Notie the `Content-Length`of the request is 11,6MB.
- It appears that all 37k are in the event in MISP now (not sure).
- My process has retries on PyMISP calls, and this failed on 4 attempts.
- The process then aborted and was not able to do the last step of adding a tag to those 37k attributes.

I will try batching these large updates, e.g. into 4k chunks and see if that works any better.

I'd appreciate your insight. Thanks.

**Comment by Rafiot** [comment]
Maybe. What is the limit for PHP on the server?

**Comment by github-germ** [comment]
from `php.ini`
```
memory_limit = 1024M
```

**Comment by Rafiot** [comment]
Which `php.ini`, the one in `/etc/php/<version>/apache2` or in `/etc/php/<version>/cli` ?

**Comment by github-germ** [comment]
```
$ grep memory_limit $(locate /php.ini$)
/etc/opt/rh/rh-php71/php.ini:memory_limit = 1024M
/opt/rh/rh-php71/register.content/etc/opt/rh/rh-php71/php.ini:memory_limit = 128M
$ 
```

**Comment by Rafiot** [comment]
Probably not a size issue then.

Please paste more of the error message: the snippet isn't enough to know what failed.

**Comment by github-germ** [comment]
HTTP 503 -- see the bottom section

```
[PyMISPError('Unknown error: the response is not in JSON.\nSomething is broken server-side, please send us everything that follows \
(careful with the auth key):\nRequest headers:\n{\'User-Agent\': \'PyMISP 2.4.93 - Python 3.6.4\', \'Accept-Encoding\': \'gzip, deflate\', \'Accept\': \'application/json\', \'Connection\': \'keep-alive\', \
\'Content-Length\': \'11698152\', \'Authorization\': \'DYSs12HOokWbk2awamfH2i6RhYvjr4LO4K82wV8w\', \'content-type\': \'application/json\'}\nRequest body:\n{\n  "Event": {\n    "Attribute": [\n      {\n    \
    "category": "Network activity",\n        "comment": "score:[10.0,2018082604]",\n        "disable_correlation": false,\n        "to_ids": true,\n        "type": "url",\n        "uuid": "5c9626ed-62ca-40\
76-b0e7-3f33020c4a48",\n        "value": "solicetud.review/d315e2q385s7wwa12g1kd5o3s5adn25ugdwxbhhsfi5bwbsridbhegsi5f10ky5q2h1t"\n      },\n      {\n        "category": "Network activity",\n        "commen\
t": "score:[10.0,2018082604]",\n        "disable_correlation": false,\n        "to_ids": true,\n        "type": "url",\n        "uuid": "187f2a70-994e-42f4-9774-7c680c223420",\n        "value": "squarecst.\
review/5936jc2x385r7pia12cxcd48kd15cm29nivbgtdrzf4vrfi5bwbsridbhegsi5w1h0w8t@n10hto"\n      },\n      {\n        "category": "Network activity",\n        "comment": "score:[10.0,2018082604]",\n        "dis\
able_correlation": false,\n        "to_ids": true,\n        "type": "url",\n        "uuid": "619accba-995b-48c0-a93d-3f031d513159",\n        "value": "bidlyobe.review/ac3793d0a20323e4e6.png"\n      },\n   \
   {\n        "category": "Network activity",\n        "comment": "score:[10.0,2018082604]",\n        "disable_correlation": false,\n        "to_ids": true,\n        "type": "url",\n        "uuid": "abce05\
8c-06f1-4c5a-94a2-47ed808dd038",\n        "value": "rbiee.com"\n      },\n      {\n        "category": "Network activity",\n        "comment": "score:[10.0,2018082604]",\n        "disable_correlation": fal\
se,\n        "to_ids": true,\n        "type": "url",\n        "uuid": "47f3e4bd-c577-4567-a85e-e26da0fdad01",\n        "value": "flattenbodys.trade/668-189-190-7549410"\n      },\n      {\n        "categor\
y": "Network activity",\n        "comment": "score:[10.0,2018082604]",\n        "disable_correlation": false,\n        "to_ids": true,\n        "type": "url",\n        "uuid": "dadd2ca3-245f-4693-b85c-82ed\
930de05a",\n        "value": "solicetud.review/4495c2d385o7zla11t1d4fjq5adg26mydbvfdrgwfi5bwbsridbhegsi6liv1v05o@bht"\n      },\n      {\n        "category": "Network activity",\n        "comment": "score:\
[10.0,2018082604]",\n        "disable_correlation": false,\n        "to_ids": true,\n        "type": "url",\n        "uuid": "b635a713-e2a3-4637-b911-0ef1347817b4",\n        "value": "oodob.bid/c803a44c2fe\
cbb49f5.png"\n      },\n      {\n        "category": "Network activity",\n        "comment": "score:[10.0,2018082604]",\n        "disable_correlation": false,\n        "to_ids": true,\n        "type": "url\
",\n        "uuid": "08bcd7d8-ed09-48ad-b062-3d06795c2981",\n        "value": "oodob.bid/db8bde5a5081c476ea.jpg"\n      },\n      {\n        "category": "Network activity",\n        "comment": "score:[10.0\
,2018082604]",\n        "disable_correlation": false,\n        "to_ids": true,\n        "type": "url",\n        "uuid": "96bf51cc-756f-46d9-8900-2b3aa67a41af",\n        "value": "gonefatscut.bid/44fb4daa76\
54574740.png"\n      },\n      {\n        "category": "Network activity",\n        "comment": "score:[10.0,2018082604]",\n        "disable_correlation": false,\n        "to_ids": true,\n        "type": "ur\
l",\n        "uuid": "d7a74288-f10f-454d-b71a-eb0c4c034ef4",\n        "value": "gonefatscut.bid/d6431a11c1bf14b45b.png"\n      },\n      {\n        "category": "Network activity",\n        "comment": "scor\
e:[10.0,2018082604]",\n        "disable_correlation": false,\n        "to_ids": true,\n        "type": "url",\n        "uuid": "42c4b750-a1ef-424a-a28a-e8f32ce20987",\n        "value": "www.curewcbd.com/da\
96a2p38z5lbl8911m1q_czbf6cr31tx6brtdhiwgs4vxfi5bwbsridbhegsi7p1z0nyo5hxyil"\n      },\n      {\n        "category": "Network activity",\n        "comment": "score:[10.0,2018082604]",\n        "disable_corr\
elation": false,\n        "to_ids": true,\n        "type": "url",\n        "uuid": "4f6dbd35-96f3-49d3-971a-11f96561d3b6",\n        "value": "www.beautyfacez.com/bab6q238lz5r8lo611wm1cv3qv6ab28pf4xxivyh8rd\
rdfdggihth4werix5p1t0m5p2yim"\n      },\n      {\n        "category": "Network activity",\n        "comment": "score:[10.0,2018082604]",\n        "disable_correlation": false,\n        "to_ids": true,\n   \
     "type": "url",\n        "uuid": "28b32efb-9e9c-44be-a6b1-af5cc4e3d7e6",\n        "value": "powerplusultra.faith/9061-619-768-447174487"\n      },\n      {\n        "category": "Network activity",\n   \
     "comment": "score:[10.0,2018082604]",\n        "disable_correlation": false,\n        "to_ids": true,\n        "type": "url",\n        "uuid": "81b106b0-ccc5-4653-9c1f-afc4ff6b4d45",\n        "value":\
 "www.turmericcures.com/6836t23l8_5g8w6o10dv1cr6b6bg22egdhhvbgfdggihth4werix7l1law0r6ptumyi"\n      },\n      {\n        "category": "Network activity",\n        "comment": "score:[10.0,2018082604]",\n    \
    "disable_correlation": false,\n        "to_ids": true,\n        "type": "url",\n        "uuid":

...

 },\n    "analysis": "0",\n    "attribute_count": "994",\n    "date": "2018-08-25",\n    "disable_correlation": false,\n    "distribution": "0",\n    "extends_uuid": "",\n    "id": "15171",\n    "info": "I\
BM X-Force URL Spam_URLs",\n    "locked": true,\n    "org_id": "2",\n    "orgc_id": "22",\n    "proposal_email_lock": false,\n    "publish_timestamp": "1535252983",\n    "published": true,\n    "sharing_gr\
oup_id": "0",\n    "threat_level_id": "2",\n    "uuid": "5b81d460-e080-47d9-9afd-069d496a006a"\n  }\n}\nResponse (if any):\n<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>503 Serv\
ice Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.\
</p>\n</body></html>\n',)]
```

**Comment by Rafiot** [comment]
That sounds like the webserver cannot handle the load:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head><title>503 Service Unavailable</title></head>
<body><h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
</p>
</body></html>
```

Are you hammering it with lots of queries? How is the I/O? What is the load on the machine?

**Comment by github-germ** [comment]
The process ingesting as above runs hourly. Most of the hours ran without an issue. However, this one with lots of new attributes in the event to update failed. Yes indeed, it looks like another cron that ingests from another data source and runs once a day was running at the same time (it can take a few hours to complete each day).

I've implemented both of these scripts to do 4 retries with backoff times of [2, 4, 16] when the MISP request fails. My log shows that the hourly (the one discussed in this issue) did step through the 4 attempts before aborting. The other daily script encountered no errors.

I've been concerned about hitting this condition where MISP cannot ingest due to load even when we've we spread our various ingestions to avoid as much concurrency as possible. Recall that I had an prior multi-threaded ingestion script triggering this situation and I had to disable the threading.

If indeed this is the condition we are encountering, what do you suggest?

Thanks...

**Comment by github-germ** [comment]
still wondering what you suggest for what i wrote in https://github.com/MISP/PyMISP/issues/267#issuecomment-416051308 above.

in the meantime...

i did refactor my code to segment calls to `add_event` or `update_event` with a large set of attributes contained in the event. it's tunable currently set to 4k chunks. so in the example of this 37k attribute set, that will now be 10 separate event add/update calls.

- **this is now deployed, but i am not confident it will help.**

once all 37k attributes are in the event in the MISP server, this is followed by 37k calls to either `tag` or `untag` based on a confidence factor for that attribute. 

- **QUESTION**: is there a "better" way to group attribute tag updates vs. the method above?

**Comment by github-germ** [comment]
@Rafiot -- as suspected, segmenting large events for ingestion does not appear to solve the issue of HTTP 503 which occurs when more than one process is ingesting into MISP at the same time. Is the theory is correct that it's due to MISP server overload, then this is becoming a major issue to our project. Hoping you can provide some suggestions. Thanks.

**Comment by Rafiot** [comment]
It can be lots of different problems, from the amount of correlations in the event you're pushing to the load of the machine, or even the disk being too slow provoking MySQL to choke. On which type of machine is your MISP instance running? How fast is the disk?

Using `tag` and `untag` is the recommended way, and isn't known to be slow.

**Comment by github-germ** [comment]
Granted, we are testing on a less powerful VM than our production host. We can try testing the two concurrent ingestion PyMISP processes on the production hardware, and it might work. However, we will keep adding more feed ingestions via PyMISP, and at some point, if not now, we will hit the load limit on our production server.

This leads to some initial questions:

1. What is the roadmap for scaling a MISP instance that has reached a load limit?
2. Can you point us to detail suggestions that might help determine the bottleneck? Perhaps focusing on growing that choke point is a temporary solution (e.g. faster disk, more powerful backend db). However, eventually a limit can still be hit.
3. Would it make sense to cache all the various feeds we import into JSON objects that are pending ingestion in a common file set. Then process them serially at some _quiet_ server time so all PyMISP API (or curl) ingestions are basically single threaded? This could be a lot of work as it's counter to our current architecture.
4. What else...?

**Comment by github-germ** [comment]
> Using tag and untag is the recommended way, and isn't known to be slow.

Yes, tag/untag is reasonably fast. However, the one event that triggered this issue has 37k attributes that needed to be tagged. Is there no way to tag the attributes added to the in-memory `MISPEvent` vs. having to `add/update` the event followed by 37k separate `tag/untag` calls in a loop.

In light of hitting MISP core server load limits, would be nice to do as above, or send a list of `tag/untag` data in one PyMISP API request.

**Comment by iglocska** [comment]
Just a question: Do you want to tag all 37k attributes with the same tag?...

**Comment by github-germ** [comment]
Yes. We are using estimative-language to map confidence scores received in data feeds. For this particular feed and those new attributes in that event all 37k were to get the same tag initially based on their score. That tag could be removed and replaced with another est-lang tag if the score changes over time.

**Comment by github-germ** [comment]
And re’ the questions of scalability I had also posted https://github.com/MISP/MISP/issues/3563

**Comment by iglocska** [comment]
Why not set the tag on the event level?...

**Comment by github-germ** [comment]
The estimative-language tag relates to the current state of the attribute within the tag. Eg an event with a large set of IP attributes where each individual IP state represented by the tag changes over time—every attribute could have varying tags.

**Comment by github-germ** [comment]
@Rafiot when you get some time our team is eager to address our growth plan. See https://github.com/MISP/PyMISP/issues/267#issuecomment-416314314

Thx.

**Comment by github-germ** [comment]
FYI, ran tests now on our production hardware: IBM 3650, RH7.4, 32cpu, 64GB RAM. simply adding attributes into an existing event fails with HTTP 503.
- No other PyMISP ingestion apps running.
- The PyMISP API app is single-threaded.
- You may recall that I added batching large attr sets. This hourly feed had the batch size set to 4k attrs (there were 7 batches). Failed on the first batch.
- I also have PyMISP retry logic -- the failure was after 4 attempts with back-off as 2, 4, 16 secs after the first attempt.
- I will now test with 1K batches and back-off set to (2,16,32).

These performance issues feel like a guessing game. This is becoming a real obstacle for us. Hoping you can shed some light. I don't think I am violating any use of the API, but it's certainly possible.

Thanks for helping!!

**Comment by github-germ** [comment]
did some tuning and so far this app is running without error on a test host with the same hardware as our production.

HOWEVER, certainly there is a load issue to be explored further as we are only starting to roll out feed ingestion into that hardware configuration. Being that our VM albeit with less resources is failing, I anticipate we will hit the same problem with our production hardware someday (soon).

So a plrey to my prior post in 
https://github.com/MISP/PyMISP/issues/267#issuecomment-416314314 would be greatly appreciated.

**Comment by rommelfs** [comment]
Thank you for the feedback. @Rafiot probably won't be able to reply within the next two weeks. 
Would you already update us what and how you tuned and what the load issue is? Where is the load issue? IO? Database? I think that would already help.

**Comment by github-germ** [comment]
@rommelfs ... _what the load issue is?_

Thx for your reply. What's the best way to collect load data while running my PyMISP app to try to isolate the bottleneck(s)?

**Comment by rommelfs** [comment]
Instead of hypothetical talk and helping you to troubleshoot a Linux system, would you publish your PyMISP script and test data and we try to understand and figure out ourselves what you're triggering on your side.

**Comment by github-germ** [comment]
I understand your request; however, unfortunately I am not in a position where I can share my code at this point (I'm consulting to a large company that has strict policies that would take considerable effort to get permission granted to share this app and datasets).

The core issues of the MISP server hitting "load limits" with HTTP 503 responses is not new. Also, my script is doing nothing special. I have had other code that can produce the same result (and have created prior issues).

And this problem has been acknowledged by @Rafiot -- so I think waiting for him, and perhaps somebody educating me on how to look for the system choke points would be real helpful.

Thanks!!

**Comment by rommelfs** [comment]
"The core issues of the MISP server hitting "load limits" with HTTP 503 responses is not new. Also, my script is doing nothing special. I have had other code that can produce the same result (and have created prior issues)." 

Does it mean this is a duplicate of another issue? Can we merge?

You mention @Rafiot, but you don't seem to reply to his questions, like for the load.

If there is code posted in another issue that can be used to reproduce, why are you not just pointing to it instead of telling us about your corporate policies?

**Comment by github-germ** [comment]
Hello again @rommelfs . I realize I am likely frustrating you. Not my intent. Sorry.

I guess you are referring to @Rafiot questions in 
https://github.com/MISP/PyMISP/issues/267#issuecomment-416258808 -- I did answer some of that, and then I asked for some help on how I could collect load info to help isolate the bottleneck. I thought maybe someone here could shed some tips. I guess you are indicating that I should seek that knowledge elsewhere. Will do.

In general, sharing code from my position is not viable right now. And I can certainly understand your frustration over that. However, If I get some time, I will attempt to write some simple code that can reproduce the same symptoms and share that. I'm on a tight schedule so not sure when that will happen just yet.

Here's some prior related issues if you want to browse:
- https://github.com/MISP/MISP/issues/3305
- https://github.com/MISP/MISP/issues/3563
- #262 
- https://github.com/MISP/MISP/issues/3361
- https://github.com/MISP/MISP/issues/3264

Thanks for your patience!

**Comment by github-germ** [comment]
> However, If I get some time, I will attempt to write some simple code that can reproduce the same symptoms and share that.

OK, I wrote a rather simple script that reproduces HTTP 503 errors when calling `add_event` with a large number of attributes.

Hoping this will help you suggest next steps to isolating root cause.

**MANY THANKS!**

Here's what I see as the exception:
```
exception="Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.93 - Python 3.6.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '3808944', 'Authorization': 'jXCVYyyJIzeMmNspsheiLvd1mOYy4mHgNvSfGvOW', 'content-type': 'application/json'}
Request body:
{
  "Event": {
    "Attribute": [
      {
      ...
      }
  }
}
Response (if any):
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>

"
```

To run the script:
1. Paste in a valid user auth key on line 32:
```
    27 mispCreds = \
    28 {
    29     'local':
    30     {
    31         'url':  'https://localhost/',
    32         'key':  'USER_AUTH_KEY_HERE',
    33     },
    34 }
```
2. Then simply execute. On my host, this throws as above 10,000 attributes in the event being added, e.g.
```
$ python3 ./mispLoadTest.py 10000
...
```

Btw, there was no output in ```/var/www/MISP/app/tmp/logs/*.log``` when this failed. 


[mispLoadTest.py.txt](https://github.com/MISP/PyMISP/files/2386038/mispLoadTest.py.txt)

**Comment by github-germ** [comment]
The large `add_event` times out after 60 seconds. Wondering if this is a config issue. Spun that question out to #276

**Comment by github-germ** [comment]
BRAVO !!

MISP/PyMISP 2.4.96 along with tuning the Apache timeout as per 
https://github.com/MISP/PyMISP/issues/267#issuecomment-429659228

Full set of tuning changes made are on 
https://github.com/MISP/PyMISP/issues/276#issuecomment-429659952

### T H A N K   Y O U
