### ISSUE TITLE
why does update_attribute set the event published False

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#269]
As you likely recall from #260, I have code that revises the comment of an existing attribute in an event where `published` is `True`. after I call `update_attribute` as below the parent event `published` becomes `False`. I only noticed this in the WebUI when I observed that the `Published` indicators for many events were going from a checkmark to an `X`.

**Is there something I can do to prevent this behavior?** (I really don't want to do an `update_event` afterwards as I am already challenging the server with many API requests in this app.)

```
# set timestamp+1 so MISP doesn't throw error
# 'Attribute could not be saved: Attribute in the request
#  not newer than the local copy.'
attrDict = {'comment': newComment, 'timestamp': int(time.time()+1}
misp.update_attribute(attribute_id = attrId, attribute = attrDict)
```

**Comment by Rafiot** [comment]
You can call `fast_publish`: https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L421

**Comment by github-germ** [comment]
> `fast_publish`

OK, that's good to know. I will use it if there's no other solution.

My question is what is causing the event's `published` state to toggle to `False`? Is there a way to isolate what is doing this? Right now, my app, which is ingesting 100s/1000s of IOCs into 15 or so events per hour, is somehow causing `published` to go `False`.

Thx.

**Comment by iglocska** [comment]
It's not somehow causing it - any edit to an event will unpublish it.
That's by design.

**Comment by github-germ** [comment]
Ah, that makes sense. So, I assume this includes `updte_event`, and what about for attrs within the event, e.g. `tag/untag` or `attribute_update`. Anything else? Just trying to figure out the optimal place to call `fast_publish`. Thx...

**Comment by github-germ** [comment]
Oops: and... this is the same app with the `org/orgc` arrangement. I get the following error from `fast_publish` when attempting with the user authkey for either `org` or `orgc`:
```
{
  'name': 'You don&#039;t have the permission to do that.',
  'message': 'You don&#039;t have the permission to do that.',
  'url': '/events/publish/2654',
  'errors': ['You don&#039;t have the permission to do that.']
}
```

`error_log`:
```
 #5 {main}
2018-09-04 16:58:50 Error: [MethodNotAllowedException] You don't have the permission to do that.
Request URL: /events/publish/2654
Stack Trace:
#0 [internal function]: EventsController->publish('2654')
#1 /var/www/MISP_2.4.94/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP_2.4.94/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP_2.4.94/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP_2.4.94/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

**Comment by iglocska** [comment]
What does the role of the user look like?

**Comment by github-germ** [comment]
```
MariaDB [misp]> select email,org_id,role_id from users where email like 'api.x%';
+----------------------------+--------+---------+
| email                      | org_id | role_id |
+----------------------------+--------+---------+
| api.x-force.orgc@local.net |     22 |       7 |
| api.x-force@local.net      |      2 |       7 |
+----------------------------+--------+---------+
2 rows in set (0.01 sec)

MariaDB [misp]> select * from roles where id=7\G;
*************************** 1. row ***************************
                      id: 7
                    name: Sync user as tagger
                 created: 2018-05-10 13:39:55
                modified: 2018-06-27 14:51:02
                perm_add: 1
             perm_modify: 1
         perm_modify_org: 1
            perm_publish: 1
           perm_delegate: 1
               perm_sync: 1
              perm_admin: 0
              perm_audit: 0
               perm_full: NULL
               perm_auth: 1
         perm_site_admin: 0
      perm_regexp_access: 0
             perm_tagger: 1
           perm_template: 0
      perm_sharing_group: 1
         perm_tag_editor: 1
           perm_sighting: 1
    perm_object_template: 0
            default_role: 0
            memory_limit: 10240M
      max_execution_time: 600
restricted_to_site_admin: 0
        perm_publish_zmq: 1
```

**Comment by github-germ** [comment]
@iglocska -- what should i look at next to get this one resolved. then i can move onto writing a new ingestion app to another premium feed API. (learning a lot on the fly -- it's all good!)... thx.

**Comment by github-germ** [comment]
Hi @iglocska ... what next for this one? Thx!!

**Comment by github-germ** [comment]
Duh, resolved... the issue went away when i called `fast_publish` with the `PyMISP` connection using the user that is a member of `orgc`.
