### ISSUE TITLE
Return hash instead of filename when downloading samples

### ISSUE THREAD

**Issue by SHSauler** [MISP/PyMISP#270]
Apologies if this was discussed before. Since this is a change to the current implementation, I did not make a PR without prior discussion.

Currently when enriching over multiple samples from an event, the byte-object has to be hashed after retrieval to determine which sample it is, e.g. to associate it with the enrichment results.

`PyMISP.download_samples()` should return `(True, [event_id, md5, sample_bytes])` instead of `(True, [event_id, filename, sample_bytes])` to uniquely identify the returned sample.

![double_trouble](https://user-images.githubusercontent.com/8420509/45028521-b3c40480-b045-11e8-9ffa-92011b8c9208.PNG)

Link to affected source:
https://github.com/MISP/PyMISP/blob/515857c37cce1e63b71c5b2a9650c4f6bcb973e0/pymisp/api.py#L1244

**Comment by Rafiot** [comment]
Yeah, that's a good point, and definitely a bug. We can change it directly.

**Comment by SHSauler** [comment]
Thanks @Rafiot. Before I make a PR, another question:  In olden times the malware samples did not contain hashes. For the legacy reasons there is the else-clause: https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L1253

Now several options:
* Hashing the unhashed samples in the else case
* Maintaining current functionality and adding a parameter to `download_samples` that allows `hash_filename`.

**Comment by SHSauler** [comment]
Didn't want to close this!
