### ISSUE TITLE
MISP search from the server side

### ISSUE THREAD

**Issue by nalzaid** [MISP/PyMISP#275]
Hi,, 

How can I search the MISP based on events attributes from the server side? 

My current solution is not practical because I use shell_exec("") in the php code that will execute search.py from the terminal (shell command)

Here is my php code: 
 ```
<?php

if (isset($_POST["query"]))
{
  $output = shell_exec('python search.py -a -p values -s' . $_POST["query"]);
  echo $output;
}
?> 
```

This code will search the MISP using the user's query, it will retrieve all the events that have this query as an attribute.
 I need another way to handle the search by not using shell_exec

**Comment by Rafiot** [comment]
Duplicate: https://github.com/MISP/MISP/issues/3681
