### ISSUE TITLE
large add_event POST timesout after 60 seconds

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#276]
this is spun out from #267 

Not sure, but maybe this issue of large `POST`s via `add_event` yielding HTTP 503 after 60 seconds is due to a configuration issue.

looking for advice on resolving `HTTP 503` when `POST`ing with `add_event` with large number of attributes. we see this error in apache log (nothing in MISP logs). occurs after 60 secs. suspected it was one of the php or apache settings. increased the php 60 sec timeouts to 300, but still times out after 60.
```
==> misp.local_error.log <==
[Mon Sep 17 13:46:56.437835 2018] [proxy_fcgi:error] [pid 27987] (70007)\
The timeout specified has expired: [client ::1:44912] AH01075: \
Error dispatching request to :
```
we are running an old apache httpd 2.4.6 -- wondering if this is the culprit, i see that there was a timeout hardcoded up until 2.4.8, but that bug talks about 30 secs.

would appreciate any help.
THANKS!

(i also see that newer apache sends HTTP 504 with a timeout. we see 503 of course with our old version.)

**Comment by Rafiot** [comment]
Yes, you can configure that: https://stackoverflow.com/questions/3829403/how-to-increase-the-execution-timeout-in-php#3829437

Which file did you edit?

**Comment by github-germ** [comment]
i think this tuning might resolve this issue. there may be more here than needed. will let my app, which runs hourly ingestions, soak for a day or so, and report back.

added to `httpd.conf`:
```
#  without these settings defaults to 60 seconds: increase to 15 minutes
Timeout 900
ProxyTimeout 900
```
and these changes to `php.ini`:
```
;max_execution_time = 300
max_execution_time = 900
...
;max_input_time = 60
max_input_time = 900
...
#memory_limit = 4096M
memory_limit = 8G
...
post_max_size = 50M
post_max_size = 256M
...
;upload_max_filesize = 50M
upload_max_filesize = 256M
```

**Comment by github-germ** [comment]
BRAVO !!

2.4.96 plus tuning changes above in Apache and PHP and very large `add_event` is no longer timing out.

Many thanks!
