### ISSUE TITLE
get_all_tags() only returns 50 results (first page)

### ISSUE THREAD

**Issue by morallo** [MISP/PyMISP#28]
When invoking PyMISP get_all_tags, only the first 50 results are returned (first page).

The REST api would allow you to get subsequent pages with the `tags/index/page:n` URL, but there is no way to specify it in PyMISP.

Is there any workaround? Any way to get the details for a specific tag?

**Comment by Rafiot** [comment]
@iglocska: do you have an idea?

**Comment by iglocska** [comment]
It is weird, it should return all.

**Comment by Rafiot** [comment]
It now returns them all (tested with `PyMISP/examples/tags.py`)
