### ISSUE TITLE
search_all return nothing

### ISSUE THREAD

**Issue by l3m0ntr33** [MISP/PyMISP#289]
In some scripts i was used to play with "search_all" method to search for event info my MISP Instance.
Since i upgraded from MISP 2.4.93 to MISP 2.4.95 i noticed some problems in my automated imports even after upgraded to latest pymisp release.

-> I figured out that "search_all" don't work anymore. Result always empty if i search for an attribute value or an event info. Like : {'response': []}

-> If i use instead "search_index" with "eventinfo" parameter it works and return me correspondind events.

These tests have been made with pymisp (2.4.96) and my MISP instance is 2.4.95.

**Comment by adulau** [comment]
Could you upgrade to 2.4.96 ? A lot of bug were fixed for the API search.

**Comment by Rafiot** [comment]
We did a lot of changes in the search API, I'm closing this one, don't hesitate to open an other issue if needed.
