### ISSUE TITLE
should dateutil module be a hard requirement?

### ISSUE THREAD

**Issue by nbareil** [MISP/PyMISP#29]
In pymisp/misp_event.py:

```python
 11 try:
 12     from dateutil.parser import parse
 13 except ImportError:
 14     pass
```

But it is used like it must exists.

```python
345     def set_date(self, date, ignore_invalid=False):
346         if isinstance(date, basestring) or isinstance(date, unicode):
347             self.date = parse(date).date()
348         elif isinstance(date, datetime.datetime):
349             self.date = date.date()
350         elif isinstance(date, datetime.date):
351             self.date = date
```

I can fix that, but what would you prefer?
- Modify `set_date()` behavior with a `has_dateutil`
- Make a successful import mandatory?

**Comment by Rafiot** [comment]
Hmmm yeah, that would make sense. I'm not sure why I did it that way at the time...

**Comment by Rafiot** [comment]
It is already mandatory: https://github.com/MISP/PyMISP/blob/master/setup.py#L30

The reason you have the try - except - pass is because `import pymisp` is in `setup.py` before you actually install the dependencies so `pip install . ` will fail.
