### ISSUE TITLE
"change_distribution" method request for existing events

### ISSUE THREAD

**Issue by faustus25** [MISP/PyMISP#294]
Is there a way to update the distribution of an existing event seeing as there is no '"change_distribution" method available?

It would be good to edit an existing event's distribution similar to these methods below:
````
change_analysis_status() (pymisp.PyMISP method)
change_comment() (pymisp.PyMISP method)
````
Have tried update_event but have no luck

Want to do the following:

# Default distribution level:
# your_organization = 0
# this_community = 1
# connected_communities = 2
# all_communities = 3

````
misp.change_distribution({'Event':event}, distribution=1)
````
What is the alternative way to do this?

**Comment by Rafiot** [comment]
I just added the method. 

In the meantime, if updating pymisp on the HEAD (not on pip yet) isn't an option, you can do the same thing as the method in your own code.

**Comment by Rafiot** [comment]
Hmmm right, I need to figure that one out: everything in aping is only python 3.6+.

Getting an error when installing/updating is awkward. How did you get that error?

**Comment by faustus25** [comment]
It occurred when I tried to install pymisp via pip (v3.5)

The current way to get the updated pymisp version I need is cloning the PyMISP repo within MISP and then installing but MISP doesn't recognize it:

```
PyMISP:… Not installed or version outdated.
&
PYMISP library version…Incorrect pymisp version installed, found 0, expecting >2.4.93
```
PyMISP at v2.4.96

**Comment by Rafiot** [comment]
What is the exact command you're running? 

I cannot get anything saying `byte-compiling`, and don'þ get the error.

**Comment by faustus25** [comment]
I think I ran the command under an upgraded version of "pip v18.1" and then rolled back to v9.0.3 due to compile issues. (All under python3.5)

```
pip install pymisp
```
