### ISSUE TITLE
Addition to "Tag" method

### ISSUE THREAD

**Issue by faustus25** [MISP/PyMISP#297]
A request to add event ID as parameter to "tag" method as I have to use the deprecated "add_tag" method to pass event ID:

Current:
```
tag(uuid,tag)
Tag an event or an attribute
```

Proposed:
```
tag(event,uuid,tag)
```

I have to add the tags as follows:

```
/usr/local/lib/python3.5/dist-packages/pymisp/api.py:2281: DeprecationWarning: Call to deprecated function add_tag.

  def add_tag(self, event, tag, attribute=False):

/ / / / / / 
misp.add_tag({'Event': event} , "Cuckoo")
```

**Comment by Rafiot** [comment]
I'm unsure what you mean here, sorry.

is `event` a full event? If yes, you can get the uuid by doing `event['uuid']` and use the new method.

**Comment by faustus25** [comment]
I am passing 'event' as the value for processing the event modification rather than 'uuid' but the new "tag" method doesn't accept 'event' only 'uuid' hence why I use the old 'add_tag' method which accepts 'event'

````
for event in result['response']:
    print(event['id'])
    misp.add_tag({'Event': event} , "Cuckoo")
    misp.change_distribution({'Event': event}, distribution=2)
````
I would like to combine the new "tag" method that uses 'uuid' with the other methods such as "change_distribution/threat_level/analysis_status" methods which only pass 'event'. Using "add_tag" allows this so if you can demonstrate how I can incorporate 'tag' method that would be appreciated.

````
    misp.tag({'Event':uuid}, "Cuckoo")
    misp.tag({'Event':uuid}, "tlp:green")
    misp.change_distribution({'Event': event}, distribution=2)
````
How can the above be passed for 'uuid'?

**Comment by Rafiot** [comment]
Yes, the new `tag`method expects a `uuid` and not an event object. 
What I don't understand why you don't want to pass the UUID directly to the tag method. You have it in the Event Object anyway.

What is the problem with this code? 

```python
for event in result['response']:
    print(event['id'])
    misp.tag(event['uuid'], "Cuckoo")
    misp.change_distribution({'Event': event}, distribution=2)
```

**Comment by faustus25** [comment]
It works as you have described! I was passing 'uuid' in the same format as 'Event':event, so my error.

For my own understanding, what's the advantage of passing the 'uuid' rather than 'id'?

**Comment by Rafiot** [comment]
I'd say that UUID is less error prone. You can be sure that a uuid will be unique across every MISP instance and every types object in MISP. An ID will not so in case you have some complex code and run batches in the background, you may not notice immediately a bug in your code and could potentially endup tagging the wrong thing.
