### ISSUE TITLE
api.change_threat_level returning AttributeError:

### ISSUE THREAD

**Issue by Bumble0b33** [MISP/PyMISP#298]
### Env
Using Python 3.6.6 on Ubuntu 18.04 Server

### Expected behavior
Update event with new threat level:

event = api.change_threat_level(11, threat_level_id=1)

### Actual behavior
Getting an error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 462, in change_threat_level
    e = self._make_mispevent(event)
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 275, in _make_mispevent
    e.load(event)
  File "/usr/local/lib/python3.6/dist-packages/pymisp/mispevent.py", line 462, in load
    if json_event.get('response'):
AttributeError: 'int' object has no attribute 'get'

**Comment by Rafiot** [comment]
yes, the method expects a full event, not an event id.

I'll change that.

**Comment by Bumble0b33** [comment]
Using the event id would make it easier to update. I'll see if I can change it when I've got more time. Thanks

**Comment by Bumble0b33** [comment]
I tried with the event, getting a response not in JSON:

CRITICAL [api.py:236 - _check_response() ] Unknown error: the response is not in JSON.
**Request headers:**
{'User-Agent': 'PyMISP 2.4.96 - Python 3.6.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '761', 'Authorization': 'xxxxxxxxxxxxxxxxxxxxxxxxx', 'content-type': 'application/json'}
Request body:
{
  "Event": {
    "Org": {
      "id": "1",
      "name": "X Industries",
      "uuid": "5bd91f46-d93c-4fd5-a871-4e030a00020f"
    },
    "Orgc": {
      "id": "1",
      "name": "X Industries",
      "uuid": "5bd91f46-d93c-4fd5-a871-4e030a00020f"
    },
    "analysis": "0",
    "attribute_count": "0",
    "date": "2018-11-15",
    "disable_correlation": "0",
    "distribution": "0",
    "event_creator_email": "test@test.test",
    "id": "18",
    "info": "Testing threat level",
    "locked": "0",
    "org_id": "1",
    "orgc_id": "1",
    "proposal_email_lock": "0",
    "publish_timestamp": "1542254704",
    "published": false,
    "sharing_group_id": "0",
    "threat_level_id": "1",
    "uuid": "5becf070-7d90-4468-bfc4-098a0a00020f"
  }
}

**Comment by Rafiot** [comment]
And what does the response look like?

**Comment by Bumble0b33** [comment]
Response (if any):
{'name': 'An Internal Error Has Occurred.', 'message': 'An Internal Error Has Occurred.', 'url': '/events/5becf070-7d90-4468-bfc4-098a0a00020f'}
