### ISSUE TITLE
add "return only event id" or limit results in search

### ISSUE THREAD

**Issue by garanews** [MISP/PyMISP#299]
When a search returns many data, the returned json is truncated resulting not valid.
This happens also returing json with flag metadata set to True.
Limiting the results or returning only the event id could resolve the issue.

**Comment by winklerrr** [comment]
Were you aware of the `search_index()` method? Maybe this already solves your problem.

**Comment by dadokkio** [comment]
the suggestion made by @winklerrr resolved the issue in our case. Days that was failing with search (with data range and metadata flag) worked properly with search_index even if the search was - a lot - slower than before.

For ExpandedPyMISP you mean aping.py, right?
If you need someone to test limit functionality next week we should be able to find thousand of events that need to be deleted :)

**Comment by Rafiot** [comment]
We did a lot of changes in the search API, I'm closing this one, don't hesitate to open an other issue if needed.
