### ISSUE TITLE
Add `uuid` as object attribute

### ISSUE THREAD

**Issue by winklerrr** [MISP/PyMISP#300]
I'm using pylint to check my code.
My code works and looks like this:

    event_dict = misp.get(event_id)['Event']
    event: MISPEvent = MISPEvent()
    event.from_dict(**event_dict)

    misp.tag(event.uuid, event_tag)

But pylint still shows me the following error message:

> Instance of 'MISPEvent' has no 'uuid' member [E1101]

Could you please add `uuid` as attribute to the `MISPEvent` or maybe directly to `AbstractMisp` to cover all the other classes as well? (I'm not sure if every object should have a uuid but I think you know what I'm trying to say.)
Or is there another convenient way to retrieve the uuid of the event?

**Comment by Rafiot** [comment]
Oo an existing event you get from MISP *must* have an UUID, there is no way around as far as I know.
Can you print the dictionary and check?

**Comment by winklerrr** [comment]
I think you didn't understand my problem:
The event has the `uuid` attribute and everything works **fine**.

The problem here is the linter (in my case: `pylint`). The linter thinks there is no attribute called `uuid` because it can't find any line like `self.uuid` in the constructor or as class member.

**Comment by Rafiot** [comment]
The class attributes are dynamically created (https://github.com/MISP/PyMISP/blob/master/pymisp/abstract.py#L125), so pylint won't find it.

In your case you're passing an existing event you receive from a MISP instance so the event you receive must have a uuid key. and the cote you're running should work when you disable pylint.

**Comment by winklerrr** [comment]
My code worked from the beginning on but it shows me a warning. 
I just wanted to let you know, that some linters may have problems with that dynamic code generation.

It sounds like you don't have plans to change that. That's good to know so I can add some pylint exceptions to my code. Thanks for your help!

**Comment by Rafiot** [comment]
Oh, right, makes sense.

I'm not sure if I can do it in a way that makes pylint happy, but if there is one, I'd be interested.
