### ISSUE TITLE
pymisp.get_csv uses deprecated api

### ISSUE THREAD

**Issue by marcnil815** [MISP/PyMISP#314]
The pymisp.get_csv function uses the deprecated api. The api is broken at the moment (filters do not work).

**Comment by marcnil815** [comment]
New API works fine. Should have been clearer. The function called here: https://github.com/MISP/PyMISP/blob/master/examples/get_csv.py
Uses the old API. That's all :)

**Comment by Rafiot** [comment]
Oh, right, thank you, I'll fix it :)
