### ISSUE TITLE
misp_get_event(eventid) doesn't return tags for event

### ISSUE THREAD

**Issue by vegardw** [MISP/PyMISP#32]
I'm using PyMISP to to do some processing on events in MISP

As part of the data I'm processing I would like to have the tags for the event(s), but the json returned from misp_get_event() doesn't have the tags.

I'm using the following code:
```
misp = PyMISP("https://%s/" % misp_server, misp_key, False, 'json')
source_event = misp.get_event(source_id)
```

I see that get_stix_event() have an tags parameter to include tags, but since I use json for everything else I would like to avoid rewriting the code to use STIX instead of json

**Comment by Rafiot** [comment]
Which version of MISP are you using? It works for me on 2.4.56.

**Comment by vegardw** [comment]
Using 2.4.56 as well.

Have done some more testing, I get the tags for some events, but not for other.

I made a simple test event with two tags and one attributes, at the tags are returned. But when I try it with one of the other events in the db, I get no tags. 

Will do some more testing and see if I can pinpoint what is different with the events where I don't get the tags. But it seems to be a MISP problem, not PyMISP

**Comment by Rafiot** [comment]
Could it be because some tags aren't exportable?

@iglocska you may want to be in the loop for this one :)

**Comment by vegardw** [comment]
Yep, that was it. The events in question only had tags that were not exportable. 

I had set the tags as not exportable because they were for internal use in my organisation. Didn't think of how that would impact the processing I would do via the API.

So, user error on my part :)

**Comment by Rafiot** [comment]
Well, it is a good question, we can discuss if they should be in the export or not, or maybe as a flag.

**Comment by adulau** [comment]
I think the best would be to have a flag to overwrite the export of non-exportable flags via the API. There is an issue opened for this case: https://github.com/MISP/MISP/issues/1394
