### ISSUE TITLE
to_ids argument values in ExpandedPyMISP.search are different than MISPEvent.add_attribute

### ISSUE THREAD

**Issue by jochman** [MISP/PyMISP#320]
ExpandedPyMISP.search and MISPEvent.add_attribute are both taking to_ids as a parameter.
ExpandedPyMISP.search's to_ids defined as a bool type, MISPEvent.add_attribute's defined as 0/1. 

to_ids parameter type should be the same in all functions. To reserve BC I suggest that MISPEvent.add_attribute's to_ids will support both 0/1 and bool.

**Comment by Rafiot** [comment]
Until last month, to_ids in search was accepting `exclude` so it was not possible to make it a bool.

Now, exclude has been removed, so I updated accordingly.
