### ISSUE TITLE
Cannot unpublish an event

### ISSUE THREAD

**Issue by befrankt** [MISP/PyMISP#323]
Hi I have the following code... it can publish an event fine (set the value to True), but it can't seem to unpublish (using the value False); it will still publish... It seems the misp.publish function simply published regardless of what the value is... how can I get around this? The aim is to end up with a python script that can unpublish events...
```

#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pymisp import PyMISP
from keys import misp_url, misp_key, misp_verifycert
import argparse
import os
import json


def init(url, key):
    return PyMISP(url, key, misp_verifycert, 'json')

    result = m.get_event(event)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Get an event from a MISP instance.')
    parser.add_argument("-e", "--event", required=True, help="Event ID to get.")
    parser.add_argument("-t", "--tag", required=True, type=int, help="Attribute ID to modify.")

    args = parser.parse_args()

    misp = init(misp_url, misp_key)

    event = misp.get_event(args.event)
    print(event)
    misp.publish(args.event,False)
    print(event)

```

**Comment by tomking2** [comment]
Hi @befrankt 

Take a look at the following lines of code:
https://github.com/MISP/PyMISP/blob/c48009f56c6796e00ec484cfcfbf9e7463309b3a/pymisp/api.py#L469-L473

You are passing False into the `alert` parameter, which determines if an email should be sent informing uses of the published event.

Currently there is no `unpublish` endpoint, unless you are using the MISPEvent class to represent a MISP event

How about the following snippet?
```python

#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pymisp import PyMISP
from keys import misp_url, misp_key, misp_verifycert
import argparse
import os
import json


def init(url, key):
    return PyMISP(url, key, misp_verifycert, 'json')

    result = m.get_event(event)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Get an event from a MISP instance.')
    parser.add_argument("-e", "--event", required=True, help="Event ID to get.")
    parser.add_argument("-t", "--tag", required=True, type=int, help="Attribute ID to modify.")

    args = parser.parse_args()

    misp = init(misp_url, misp_key)

    event = misp.get_event(args.event)
    print(event)
    event['Event']['published'] = False
    # The updated event must have a higher timestamp.
    # Either use the following to set the timestamp of the time it was unpublished, 
    # or use the commented out line which simply increases epoch time by 1
    event['Event']['timestamp'] = str(int(time.time()))
    # event['Event']['timestamp'] = str(int(event['Event']['timestamp'])+1)
    event = misp.update_event(event['Event']['id'], args.event)
    print(event)

```

**Comment by Rafiot** [comment]
Yes, or this code should work. The timestamp key is the tricky bit. 
You can either:
* change it as it is done in the example
* remove it completely (`event['Event'].pop('timestamp')`)
* load the json event into a MISPEvent and use `unpublish()` (the timestamp key will be automatically removed), and push the event pack to MISP
* If you're using python 3.6+, you can use ExpandedPyMISP instead of PyMISP and the return of get() is already a MISPEvent and you can use unpublish(), and push the event pack to MISP

Please reopen if needed.
