### ISSUE TITLE
AttributeError: 'MISPObject' object has no attribute 'template_uuid'

### ISSUE THREAD

**Issue by winklerrr** [MISP/PyMISP#326]
There was a bug (described [here](https://github.com/MISP/PyMISP/issues/315), introduced with PyMISP version `2.4.97`) in the api which occurred when calling the function:

    get_object_template_id(object_uuid)

This bug was fixed with [this](https://github.com/MISP/PyMISP/commit/486017d345dbb5dd127d06a2e9ae28336604c928) commit (`486017d345dbb5dd127d06a2e9ae28336604c928`, from 9th December, 2018).

So I installed the newest version of PyMISP that includes that bug fix commit (latest commit I used is: `c18981b960cfdf3c208aeb006887b6c361c18bd8`, from 28th January, 2019) with

    pip3 uninstall pymisp
    pip3 install https://github.com/MISP/PyMISP/archive/c18981b960cfdf3c208aeb006887b6c361c18bd8.zip

Now the bug seems to be fixed but another one occurred: 
To call the function mentioned above a `object_uuid`  parameter must be given.
This `object_uuid` needs to be the uuid of the template for which the id (called `template_id`) should be returned. The `template_id` is then needed to attach a object created with that template to MISP.

In version `2.4.96` it was possible to receive the uuid of a template from a `MISPObject` itself:

    misp_object = MISPObject("valid_template_name", standalone=False)
    template_uuid = misp_object.template_uuid 
    template_id = api.get_object_template_id(template_uuid)
    api.add_object(event.id, template_id=template_id, misp_object=misp_object)

When calling `misp_object.template_uuid` an `AttributeError` gets raised:

    AttributeError: 'MISPObject' object has no attribute 'template_uuid'

I double checked with the original code from `MISPObject` if this attribute was renamed or removed or something and for example in the function [`from_dict()`](https://github.com/MISP/PyMISP/blob/c18981b960cfdf3c208aeb006887b6c361c18bd8/pymisp/mispevent.py#L1012) the attribute `template_uuid` is still used...

So is there a way to receive this attribute?
Or is there a possibility to attach a `MISPObject` to MISP without knowing it's `template_id`?

**Comment by Rafiot** [comment]
I think I know hat is happening: in the archive (https://github.com/MISP/PyMISP/archive/c18981b960cfdf3c208aeb006887b6c361c18bd8.zip), doesn't have the object templates in `pymisp/data/misp-objects`, so the helpers in MISPObject fail.

The recommended way if you're not in prod is to clone PyMISP, update the submodules and work directly in the dev environment.

When you're in prod, install the package from PyPi and it contains all the required files.
I'll generate a new package (2.4.101) now.

**Comment by Rafiot** [comment]
(pip[3] install pymisp should work fine now, I released 2.4.101)

**Comment by winklerrr** [comment]
Cool thanks!
Just in case someone has a similiar problem, here the workaround I found:

Instead of using `misp_object.template_uuid`, fetch all templates with `get_object_templates_list()` and look for the template you need:

    templates = api.get_object_templates_list()["response"]
    for template in templates:
        if template["ObjectTemplate"]["name"] == "valid_template_name":
            template_id = template["ObjectTemplate"]["id"]
            break

    api.add_object(event.id, template_id=template_id, misp_object=misp_object)

**Comment by winklerrr** [comment]
So I tested with `2.4.101` and it seems like that something else now doesn't work:

    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/pymisp/api.py", line 232, in _check_response
        json_response = response.json()
      File "/usr/lib/python3.6/site-packages/requests/models.py", line 866, in json
        return complexjson.loads(self.text, **kwargs)
      File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

    During handling of the above exception, another exception occurred:

      File "path/to/my_file.py", line line_number, in method_name
        api.add_object(event.id, template_id=template_id, misp_object=misp_object)
      File "/usr/lib/python3.6/site-packages/pymisp/api.py", line 2264, in add_object
        return self._check_response(response)
      File "/usr/lib/python3.6/site-packages/pymisp/api.py", line 237, in _check_response
        raise PyMISPError(everything_broken.format(response.request.headers, response.request.body, response.text))
