### ISSUE TITLE
events/edit API readds deleted attributes already returned by a search

### ISSUE THREAD

**Issue by mike1703** [MISP/PyMISP#33]
Steps to reproduce:
- fetch an event (with id: event_id) with my_event = misp.search()
- delete some attributes from event_id
- add an attribute with misp.add_attribute(my_event, <attribute>)
=> the deleted attributes are recreated as they are still included in my_event

workaround:
set my_event['Event']['Attribute'] = [ ] before adding any new attributes.

possible fixes:
- create a different API which supports deltas which can be uploaded in one go
- on adding an attribute do not resend the old attributes

**Comment by Rafiot** [comment]
Just to make sure you use the same path I'd be using (pseudocode):
```
misp = PyMISP(...)
e = misp.search('foobar')
# delete attributes from e 
misp.add_named_attribute(e, ...)
```

You're right, all the deleted attributes will be back. I *think* the easy and clean fix is to set the attributes list to `[]` in `add_named_attribute`.

**Comment by mike1703** [comment]
I am deleting them with `misp.delete_attribute(attribute_id)`.
The problem is that the following code in `_send_attributes` just takes your event `e`, parses it (so it is based on the event MISP returned to me as a result for the search, adds my new attributes and updates the event. Old attributes are still sent with the event. `e.attributes = attributes` would be a fix. I just don't know if it will break something else.
https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L378
```
e = MISPEvent(self.describe_types)
            e.load(event)
            e.attributes += attributes
            response = self.update_event(event['Event']['id'], json.dumps(e, cls=EncodeUpdate))
```

**Comment by Rafiot** [comment]
I'll work on a fix asap. Expect it to be fixed early next year.
