### ISSUE TITLE
Using parameters to call the api returns an error but works inside a URL? 

### ISSUE THREAD

**Issue by briglewis** [MISP/PyMISP#330]
I'm trying to call the api to get events published in the last day and it returns an internal error:

b'{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\\/attributes\\/restSearch\\/?returnFormat=json&amp;publish_timestamp=1d"}'

--- The code I am using is below - if I append the parameters to the URL it returns everything as it should but not when I specify parameters in a dictionary - any idea why?

``
url3 = 'https://misppriv.circl.lu/attributes/restSearch/'
 
 #make a dicitonary of params    
 params = {
          "returnFormat": "json",
          "publish_timestamp": "1d"
          
         }
 r = requests.get(url3,headers=headers, params=params)
 
 print(r.content)
 ``

This appended URL code works:

``

url2 = 'https://misppriv.circl.lu/attributes/restSearch/returnFormat:json/tags:!tlp:amber|/publish_timestamp:2d'

r = requests.get(url2,headers=headers)

print(r.content)

``

Thanks!

**Comment by iglocska** [comment]
Indeed, option 2 is the correct way of doing it as described on the automation page:

![image](https://user-images.githubusercontent.com/3668672/52196218-5255cb00-285b-11e9-97ad-00699fac2300.png)

Since you are using Python anyway, also consider using PyMISP to make your life easier.
