### ISSUE TITLE
Permissions after upgrading PyMISP

### ISSUE THREAD

**Issue by gitnorty** [MISP/PyMISP#332]
After upgrading to the latest version, the permissions don't appear to be correct; some of our scripts which were working are complaining about permission issues.

Here are the upgrade steps taken:

1. cd /var/www/MISP
2. git fetch
3. git checkout tags/$(git describe --tags `git rev-list --tags --max-count=1`)
4. git submodule update --init --recursive
5. cd /var/www/MISP/PyMISP
6. python3 setup.py install --prefix /usr

[root@md2nj08ta PyMISP]# python3 setup.py install --prefix /usr
running install
running bdist_egg
running egg_info
writing pymisp.egg-info/PKG-INFO
writing dependency_links to pymisp.egg-info/dependency_links.txt
writing requirements to pymisp.egg-info/requires.txt
writing top-level names to pymisp.egg-info/top_level.txt
reading manifest file 'pymisp.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pymisp.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
.
.  TRUNCATING OUTPUT
.
Using /usr/lib/python3.6/site-packages
Searching for certifi==2018.4.16
Best match: certifi 2018.4.16
Adding certifi 2018.4.16 to easy-install.pth file

Using /usr/lib/python3.6/site-packages

Searching for idna==2.6
Best match: idna 2.6
Adding idna 2.6 to easy-install.pth file

Using /usr/lib/python3.6/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /usr/bin

Using /usr/lib/python3.6/site-packages
Finished processing dependencies for pymisp==2.4.101

I see 2.4.101 is installed:

[root@md2nj08ta PyMISP]# ls -ld /usr/lib/python3.6/site-packages/pymisp*
drwxr-xr-x 4 root root 36 Feb  4 15:57 /usr/lib/python3.6/site-packages/pymisp-2.4.101-py3.6.egg

But a lot of the files under this directory are only readable/executable by root:

[root@md2nj08ta PyMISP]# ls -lR /usr/lib/python3.6/site-packages/pymisp-2.4.101-py3.6.egg/ |grep -- --- | head
-rw-r----- 1 root root     1 Feb  4 15:57 dependency_links.txt
-rw-r----- 1 root root  6896 Feb  4 15:57 PKG-INFO
-rw-r----- 1 root root   193 Feb  4 15:57 requires.txt
-rw-r----- 1 root root 12764 Feb  4 15:57 SOURCES.txt
-rw-r----- 1 root root     7 Feb  4 15:57 top_level.txt
-rw-r----- 1 root root   9241 Feb  4 15:57 abstract.py
-rw-r----- 1 root root  9178 Feb  4 15:57 schema.json
-rw-r----- 1 root root  8561 Feb  4 15:57 schema-lax.json
-rw-r-----   1 root root 2283 Feb  4 15:57 schema_objects.json
-rw-r-----   1 root root 1121 Feb  4 15:57 schema_relationships.json

[root@md2nj08ta PyMISP]# ls -lR /usr/lib/python3.6/site-packages/pymisp-2.4.101-py3.6.egg/ |grep -- --- | wc -l
155

Am I missing a step somewhere, or is there some other issue that is causing the permissions not to be set correctly?

Please let me know if any additional output is required? 

Thanks!

**Comment by Rafiot** [comment]
No, there is nothing else to do. What is the error message?

**Comment by gitnorty** [comment]
Here's an example of an error when running ingest:

PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.6/site-packages/pymisp-2.4.101-py3.6.egg/pymisp/abstract.py'
+ return 1
user@misp-Lab1:/data/misp/area1/data/hourly/results ls -ld /usr/lib/python3.6/site-packages/pymisp-2.4.101-py3.6.egg
drwxr-xr-x 4 root root 36 Jan 31 16:11 /usr/lib/python3.6/site-packages/pymisp-2.4.101-py3.6.egg
user@misp-Lab1:/data/misp/area1/data/hourly/results ls -l /usr/lib/python3.6/site-packages/pymisp-2.4.101-py3.6.egg/pymisp/abstract.py
-rw-r----- 1 root root 9241 Jan 31 16:11 /usr/lib/python3.6/site-packages/pymisp-2.4.101-py3.6.egg/pymisp/abstract.py
user@misp-Lab1:/data/misp/area1/data/hourly/results

**Comment by Rafiot** [comment]
I have no idea about the permissions on your system and cannot tell you what went wrong here.

The simplest way to get around it is to use a python virtual environment and run your scripts in it. 

If you don't want to do that, I recommend you to check the permissions you're running your scripts with. As you installed everything as root, you may need to run them as root too (and be aware that it may come with security issues).

**Comment by gitnorty** [comment]
One interesting thing to point out; even though I ran step 4 above "git submodule update --init --recursive".  For some reason the latest version of PyMISP wasn't pulled down.  It required me running it separately to pull down PyMISP 2.4.102:

BEFORE, when running "git submodule update --init --recursive" under /var/www/MISP:

[root@md2nj08ta MISP]# head -1 PyMISP/pymisp/__init__.py
__version__ = '2.4.101'

AFTER running "git submodule update --init --recursive" under /var/www/MISP/PyMISP:

1. mv PyMISP/ PyMISP_Orig
2. git clone https://github.com/MISP/PyMISP.git && cd PyMISP
3. git submodule update --init --recursive

[root@md2nj08ta MISP]# head -1 PyMISP/pymisp/__init__.py
__version__ = '2.4.102'

Then upon installing 2.4.102, the permissions appeared to be correct, without requiring a virtual environment:

[root@md2nj08ta Upgrade_Captures]# ls -lR /usr/lib/python3.6/site-packages/pymisp-2.4.102-py3.6.egg/ |grep -- ---

[root@md2nj08ta Upgrade_Captures]# ls -lR /usr/lib/python3.6/site-packages/pymisp-2.4.102-py3.6.egg/ |grep -- --- |wc -l
0

However, I did notice that PyMISP 2.4.101 wasn't removed:

[root@md2nj08ta PyMISP]# ls -ld /usr/lib/python3.6/site-packages/pymisp-2.4.10*
drwxr-xr-x 4 root root 36 Feb  4 15:57 /usr/lib/python3.6/site-packages/pymisp-2.4.101-py3.6.egg  
drwxr-xr-x 4 root root 36 Feb  4 17:02 /usr/lib/python3.6/site-packages/pymisp-2.4.102-py3.6.egg

Thanks again for any information/suggestions you can provide!

**Comment by Rafiot** [comment]
I guess it is because you're doing that:
`git checkout tags/$(git describe --tags git rev-list --tags --max-count=1)`
And PyMISP *as a submodule of MISP* was bumped after the tagging.

Note that it never matters, as PyMISP is still compatible and was going to be updated later on on next tagged release of MISP so there is no reason for you to proceed to any further steps.

So right now, do you still have permissions errors? And if yes, which *exact command* are you running? Under which user? And what are the permissions of the files in `/usr/lib/python3.6/site-packages/pymisp*`?

**Comment by gitnorty** [comment]
Thank you for the feedback Rafiot!  So if I understand correctly the order of when the projects/sub-projects were updated as to when they'll be seen as updated with regards to a specific tag of the main project?  Good to know the releases are compatible.

After I ran the 'git clone' for pymisp then I saw the latest version of PyMISP being retrieved.  After install, the permission issues appear to be resolved; currently we aren't experiencing any ingest issues after upgrading to 2.4.102 for MISP and PyMISP.

The permissions are:

[root@md2nj08ta Upgrade_Captures]# ls -l /usr/lib/python3.6/site-packages/pymisp-2.4.102-py3.6.egg/
total 0
drwxr-xr-x 2 root root 130 Feb  4 17:02 EGG-INFO
drwxr-xr-x 5 root root 159 Feb  4 17:02 pymisp
[root@md2nj08ta Upgrade_Captures]# ls -l /usr/lib/python3.6/site-packages/pymisp-2.4.102-py3.6.egg/pymisp/
total 208
-rw-r--r-- 1 root root   9241 Feb  4 17:02 abstract.py
-rw-r--r-- 1 root root  26540 Feb  4 17:02 aping.py
-rw-r--r-- 1 root root 110454 Feb  4 17:02 api.py
drwxr-xr-x 3 root root     94 Feb  4 17:02 data
-rw-r--r-- 1 root root   1114 Feb  4 17:02 exceptions.py
-rw-r--r-- 1 root root   2010 Feb  4 17:02 __init__.py
-rw-r--r-- 1 root root  48149 Feb  4 17:02 mispevent.py
drwxr-xr-x 2 root root    187 Feb  4 17:02 __pycache__
drwxr-xr-x 3 root root   4096 Feb  4 17:02 tools

[root@md2nj08ta Upgrade_Captures]# ls -l /usr/lib/python3.6/site-packages/pymisp-2.4.102-py3.6.egg/pymisp/data/misp-objects/
total 16
drwxr-xr-x 116 root root 4096 Feb  4 17:02 objects
drwxr-xr-x   2 root root   29 Feb  4 17:02 relationships
-rw-r--r--   1 root root 2283 Feb  4 17:02 schema_objects.json
-rw-r--r--   1 root root 1121 Feb  4 17:02 schema_relationships.json

The permissions for 2.4.101 were changed; I had 'chmod' them to get the ingests working until we were able to figure out a way to resolve it properly...

**Comment by Rafiot** [comment]
When you pull the new taged release, and run `git submodules update`, you get the submodules at the status they're when the tag was set. That's like a snapshot where all the components are at a point where they're known-working together. Manually pulling the submodules to different releases may cause issues.

When you say "`git clone` for pymisp", you mean `git pull`, right? 

The permissions (in term of which user own the files) of everything in the MISP directory depends on the user that did the pull. If you run pull as root, the owner of the updated or new files will be root. In that case, it is totally possible you have a mix of files owned by root, and files owned by which ever other user did the pull before. It has nothing to do with the changes we made on our side.
And when you have a mix of owners for the files in the MISP sub-directories, it is of course recommended to normalize it.

**Comment by Rafiot** [comment]
Well. It depends what you want to do, and currently, I have no idea what your goal is so that's a bit difficult to answer anything helpful besides explaining how git works.

When you update MISP, the submodule PyMISP will be updated.

The documentation in PyMISP is what you need to do when installing PyMISP, which might be useful for you or not.

If you run `git submodule update` in PyMISP repository you will update... the submodules of PyMISP (misp-objects), which are useful for other things.



So let's step back and tell me what you're trying to do and I'll try to answer.

**Comment by gitnorty** [comment]
As new releases of MISP and PyMISP are released, we'd like to upgrade them accordingly.  

As you described previously, since PyMISP was updated after MISP; MISP 2.4.102 was still pointing to PyMISP 2.4.101.  

However, after upgrading to MISP 2.4.102; I was checking things out and saw that PyMISP 2.4.102 was also available, thus I also wanted to update to the latest verson for PyMISP.  

Hope this helps to clarify things.  But long story short, when upgrading to the latest version of MISP/PyMISP, what are the recommended steps?  

Thanks again for all your help!

**Comment by Rafiot** [comment]
I checked with my colleagues and we're doing a couple of changes so you do not have to install PyMISP anymore (it is used by the STIX2 import/export module), the normal way of installing & updating MISP over the web interface will take care of all that.

Thank you for the report.

**Comment by gitnorty** [comment]
Thanks for the information about the web updates; does this mean the CLI support will be phased out?  I've never used the web interface to update; but if we use this method, does this address all of the steps in the '/var/www/MISP/INSTALL/UPDATE.txt'?  Looks like it could function as a script; but wasn't clear what is being called when running the update via the Web UI.

**Comment by Rafiot** [comment]
The web interface is a safe wrapper that runs a bunch of commands you can also run in the CLI, and this safe wrapper will add a few more scripts that will take care of updating the python dependencies.

I just updated the update documentation to mark at not-recommended.

**Comment by gitnorty** [comment]
Thanks for all the valuable feedback; I'll give the update a try on the next go around from the WebUI!

**Comment by Rafiot** [comment]
You will probably need to first fix permissions in order to allow the apache user to read/write files under `/var/www/MISP`

**Comment by gitnorty** [comment]
It doesn't appear that the permissions under section 5.01 of the installation document 'https://github.com/MISP/MISP/blob/v2.4.101/docs/xINSTALL.rhel7.md' are sufficient?  I only see read and execute; can you recommend the necessary permissions?  Or would it just be a recursive change to add write to all files and folders for the group permissions under /var/www/MISP?

**Comment by Rafiot** [comment]
They should, but if you have a permission error when running the update via the web interface, it is probably because we missed something.
