### ISSUE TITLE
check_warninglist(value) not working when passed a string to it which exist in the warning list

### ISSUE THREAD

**Issue by shanto12** [MISP/PyMISP#334]
I am not sure whether i am doing it the right way but when i pass a string value to it which exist in the warninglist it says not found.

**Comment by Rafiot** [comment]
What is the error message you get?

**Comment by shanto12** [comment]
the response object thats returned always say Not Found. Which I believe
means that the string passed to it is not present in the whitelists. First
of all are we supposed to pass string as input here?

**Comment by Rafiot** [comment]
Are the warning lists enabled?

This code works for me:
```python
from pymisp import PyMISP
pm = PyMISP('URL', 'API')
pm.check_warninglist('2606:4700:4700::1001')

# {'2606:4700:4700::1001': [{'id': '90', 'name': 'List of known IPv6 public DNS resolvers'}]}

pm.check_warninglist(['2606:4700:4700::1001'])

# {'2606:4700:4700::1001': [{'id': '90', 'name': 'List of known IPv6 public DNS resolvers'}]}
```
