### ISSUE TITLE
ExpandedPyMISP.search_sighting isn't returning any sighting

### ISSUE THREAD

**Issue by jochman** [MISP/PyMISP#336]
I'm trying to use `search_sighting` but it's not working. when trying to pull sighting from event (that, in fact, exist). same happens when I try to search for `attribute`.
input (exact as in the examples):
`misp.search_sightings('attribute', {'id': 2465, 'include_attribute': 1})`
output:
`Something went wrong (404): {'name': 'Not Found', 'message': 'Not Found', 'url': '/sightings/restSearch/attribute'}`

input:
`misp.search_sightings('event', {'id': 624, 'include_event': 1})`
output:
`Something went wrong (404): {'name': 'Not Found', 'message': 'Not Found', 'url': '/sightings/restSearch/event'}`

and, when trying to pull all sightings in the last 30 days:
input:
`misp.search_sightings({'publish_timestamp': '30d'})`
output:
`ValueError: context has to be in attribute, event`

All of the inputs are copied from the documentation.
any idea?

**Comment by Rafiot** [comment]
Woops, sorry for that, the documentation of ExpandedPyMISP wasn't generated...

Here is the documentation (it changed between PyMISP and ExpandedPyMISP to sanitize a bit the options): https://pymisp.readthedocs.io/modules.html#pymisp.ExpandedPyMISP.search_sightings

**Comment by jochman** [comment]
Still not working. I tried to use simple sighting search in the API, but I couldn't find anything in the official documentation.
https://www.circl.lu/doc/misp/automation/#sightings-api - can only add sightings, not search for.
I tried also using the PyMISP class, same results:
input:
`misp.search_sightings('event', {'id': 624})`
output:
`{'name': 'Not Found', 'message': 'Not Found', 'url': '/sightings/restSearch/event', 'errors': ['Not Found']}`

**Comment by Rafiot** [comment]
ExpandedPyMISP works for me:

```python
In [2]: from pymisp import ExpandedPyMISP

In [3]: pm = ExpandedPyMISP('http://127.0.0.1:8080', '<KEY>')

In [4]: pm.search_sightings(publish_timestamp='30d')
Out[4]: 
[{'Sighting': {'id': '9',
   'attribute_id': '178584',
   'event_id': '1240',
   'org_id': '1',
   'date_sighting': '1549552366',
   'uuid': '5c5c4aee-f460-43a6-ae39-062f0a00020f',
   'source': '',
   'type': '0',
   'value': '8.8.8.8'}}]

In [6]: pm.search_sightings(context='event', context_id=1240) 
Out[6]: 
[{'Sighting': {'id': '9',
   'attribute_id': '178584',
   'event_id': '1240',
   'org_id': '1',
   'date_sighting': '1549552366',
   'uuid': '5c5c4aee-f460-43a6-ae39-062f0a00020f',
   'source': '',
   'type': '0',
   'value': '8.8.8.8'}}]

In [7]: pm.search_sightings(context='attribute', context_id=178584)
Out[7]: 
[{'Sighting': {'id': '9',
   'attribute_id': '178584',
   'event_id': '1240',
   'org_id': '1',
   'date_sighting': '1549552366',
   'uuid': '5c5c4aee-f460-43a6-ae39-062f0a00020f',
   'source': '',
   'type': '0',
   'value': '8.8.8.8'}}]
```

Using PyMISP, you're right, the documentation is wrong, I'm fixing it now:

```python

In [10]: pm = PyMISP('http://127.0.0.1:8080', 'E36iZ8hr31XIcWfqU4NGniwhMuvYRngip6O1dC9T')

In [14]: pm.search_sightings('event', context_id=1240) # or pm.search_sightings('event', **{'context_id': 1240})
Out[14]: 
{'response': [{'Sighting': {'id': '9',
    'attribute_id': '178584',
    'event_id': '1240',
    'org_id': '1',
    'date_sighting': '1549552366',
    'uuid': '5c5c4aee-f460-43a6-ae39-062f0a00020f',
    'source': '',
    'type': '0',
    'value': '8.8.8.8'}}]}

In [15]: pm.search_sightings(**{'publish_timestamp': '30d'})
Out[15]: 
{'response': [{'Sighting': {'id': '9',
    'attribute_id': '178584',
    'event_id': '1240',
    'org_id': '1',
    'date_sighting': '1549552366',
    'uuid': '5c5c4aee-f460-43a6-ae39-062f0a00020f',
    'source': '',
    'type': '0',
    'value': '8.8.8.8'}}]}


```
