### ISSUE TITLE
Feature Request: PyMISP bulk tag/untag attributes within an event

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#337]
_Note: This was originally posted to https://github.com/MISP/MISP/issues/3985 and a mass edit tag feature was implemented. However, my original use case was for PyMISP. Hence, the repost here._

**Use-Case**
* Event with 1000s of attributes (some over 100k)
* Need to tag/untag all or a subset of attributes within that event
* Currently, PyMISP requires tag/untag each attribute with separate API calls

**Feature-Request**
* Add a bulk method to tag/untag a batch of attributes within an event or a list attributes not associated with a specific event with a single API call

**Prior discussion from  https://github.com/MISP/PyMISP/issues/267#issuecomment-41631631**

* @github-germ commented on Aug 27
   * Using tag and untag is the recommended way, and isn't known to be slow. Yes, tag/untag is reasonably fast. However, the one event that triggered this issue had 37k attributes that needed to be tagged. Is there no way to tag the attributes added to the in-memory MISPEvent vs. having to add/update the event followed by 37k separate tag/untag calls in a loop.
   * In light of hitting MISP core server load limits, would be nice to do as above, or send a list of tag/untag data in one PyMISP API request.

* @iglocska commented on Aug 28
   * Just a question: Do you want to tag all 37k attributes with the same tag?

* @github-germ commented on Aug 28
   * Yes. We are using estimative-language to map confidence scores received in data feeds. For this particular feed and those new attributes in that event all 37k were to get the same tag initially based on their score. That tag could be removed and replaced with another est-lang tag if the score changes over time.

* @iglocska commented on Aug 28
   * Why not set the tag on the event level?

* @github-germ commented on Aug 29
   * The estimative-language tag relates to the current state of the attribute within the tag. Eg an event with a large set of IP attributes where each individual IP state represented by the tag changes over time—every attribute could have varying tags.

**Comment by Rafiot** [comment]
Well, as it isn't exposed on MISP side, I cannot do much yet either ;)

**Comment by github-germ** [comment]
Understood. Just wanted the placeholder. I've implemented what I needed, but this would be much better when available. Thanks!!

**Comment by Rafiot** [comment]
Absolutely!

**Comment by github-germ** [comment]
Any chance of escalating this bulk tagging feature request?

It's become as real issue for us with our various PyMISP apps ingesting form feeds, tagging attributes for our IOC Life-cycle, and then our TTL age-out nightly sweeps.

My original PR on [MISP/MISP#3985](https://github.com/MISP/MISP/issues/3985) was closed when the feature was available in the WebUI. However, my use case therein was intended for PyMISP.

> Well, as it isn't exposed on MISP side, I cannot do much yet either ;)
Do we need another MISP issue created to make progress?

Many Thanks!!

**Comment by Rafiot** [comment]
I'm no sure about the priority of that specific feature (my guess is not super high). @iglocska anything to say about that?

**Comment by iglocska** [comment]
Not super high is correct.

Priority list:
- bugs that need fixing asap
- paid features by organisations willing to support us fast tracking their issue
- features that a large portion of the community requests
- features that block the development of certain other high prio features
- features that are really cool
- features that are only requested by single/few organisations and are QoL fixes

**Comment by iglocska** [comment]
2+3 are interchange-able of course.

**Comment by github-germ** [comment]
### Question
Is there any way with PyMISP, to search on an Event retrieving a **subset** of Attributes (perhaps by attribute timestamp or an attribute tag), revising only those Attributes in memory by adding tags, then updating the Event with only those revised Attributes?

We may be missing that _aha_ moment, but it seems like we'd need to pull the full list of event attributes to do this. This is a performance issue with events with large attribute count.

### Our Use Case
We have a use case where we bring in a premium feed via the Default Feed delta merge fetch. We then follow that with our tagging policies via PyMISP. This works quite well except for one feed with lots of new attributes every hour -- the process of tagging for example each of 3-7k attributes individually takes more than an hour, and when the next hour's fetch starts the fetch fails with
```
[PDOException] SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
```

### Another Solution
If we were able to define more that one Tag for a Default Feed Event, that would solve our challenge, e.g. see https://github.com/MISP/MISP/issues/2063#issuecomment-627478087

**Comment by Rafiot** [comment]
So if I understand what you're trying to do, it should be possible to use the search method with `controller="attributes", eventid="<eventID>", timestamp="1d"` to only get the attributes that have been updated in the last day, in that event. You could also use the tag filter. 
Or at least, that should be working this way.

**Comment by github-germ** [comment]
Thx @Rafiot ... Yes, retrieving the subset list is fine. However, once I have that list of `MISPAttribute` how do I update the Event after tagging them all in memory? (As I said, it may be something obvious I'm missing). What I do now, is call `PyMISP.tag` individually for each of those `MISPAttribute` but we see >3K in the list taking over an hour to complete (in some cases a few hours when we have even more in that hours' feed).

**Comment by Rafiot** [comment]
So from the top of my head, there is one thing that could work: 
1. `search(controller="event", eventid=id, metadata=True)` <= give you the MISPEvent without any attribute
2. you get the list of MISPAttributes as said in the comment above
3. Iterate over that list, add the tags
4. When the attribute good to go, do MISPEvent.add_attribute to add the attribute in the empty event you got in step **1**
5. When you're done with the list of the attribute, update the MISPEvent with `PyMISP.update_event`

**Comment by github-germ** [comment]
_Aha_ `metadata=True` is the magic. Will report back on this manana. Many thanks!!

**Comment by github-germ** [comment]
Super. The bulk tagging of attributes within an in-memory meta `MISPEvent`, followed by `pymisp.update_event` is showing at least a 30-fold performance gain in early test measurements. THANKS A TON!!

**Comment by Rafiot** [comment]
Excellent, thank you for the feedback!
