### ISSUE TITLE
misp.search does not work anymore

### ISSUE THREAD

**Issue by cgi1** [MISP/PyMISP#338]
Hi,

we used the `misp.search` function for abount six month without any problems. After upgrading MISP to version 1.10x we are now getting the following error:

<img width="1211" alt="grafik" src="https://user-images.githubusercontent.com/18695252/52482080-970d9900-2bb0-11e9-850e-03408eca3c22.png">

Have there been changes in the MISP WebAPI which are not included into PyMISP yet? Or why is the code broken?

Thanks and BR!

Versions:
PyMISP 2.4.102 (newest)
MISP 2.4.102 (newest)

**Comment by cgi1** [comment]
Even more precisly: The issue happens here:

<img width="877" alt="grafik" src="https://user-images.githubusercontent.com/18695252/52482717-4c8d1c00-2bb2-11e9-9fcf-27a3d4d7be52.png">

Backend (MISP instance) is returning `404` for `'https://[.....]/events/restSearch/download'`

**Comment by iglocska** [comment]
Are you sure it's the latest version? I haven't tried pymisp but MISP is
working correctly with download as the first parameter.

**Comment by cgi1** [comment]
@iglocska Yes it is 2.4.102

**Comment by Rafiot** [comment]
It works for me too.

Can you try to enable debug (pass `debug=True` to PyMISP), and re-run your call.

It will most probably be very verbose, but the call should look like that:

```
DEBUG [api.py:154 - _prepare_request() ] POST - http://127.0.0.1:8080/events/restSearch
DEBUG [api.py:156 - _prepare_request() ] {"returnFormat": "json", "enforceWarninglist": true, "to_ids": true}
```

**Comment by cgi1** [comment]
Code with debug flag:

```

    """ connect to MISP instance """
    misp = PyMISP(misp_url, authkey, False, 'json', debug=True)
    """ do search for MISP PyMISO issue #338"""
    test = misp.search(controller='events', enforceWarninglist=True, to_ids=True)
```

Output:

```

DEBUG [api.py:154 - _prepare_request() ] POST - https://{...}/events/restSearch/download
DEBUG [api.py:156 - _prepare_request() ] {"enforceWarninglist": true, "to_ids": true}
DEBUG [api.py:178 - _prepare_request() ] {'User-Agent': 'PyMISP 2.4.102 - Python 3.6.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '44', 'Authorization': '12345', 'content-type': 'application/json'}
DEBUG [api.py:270 - _check_response() ] {
    "name": "Invalid output format.",
    "message": "Invalid output format.",
    "url": "/events/restSearch/download",
    "errors": [
        "Invalid output format."
    ]
}
```

**Comment by iglocska** [comment]
In addition to that, /events/restSearch/download not working was a bug in MISP core - the issue was fixed feb 5 on HEAD via https://github.com/MISP/MISP/commit/890a0f19856817d4cfd94dd382030e3fbae6137f

Updating MISP to the latest version on HEAD should resolve this without a need to update PyMISP.

**Comment by cgi1** [comment]
@iglocska @Rafiot @adulau: Ok come on guys.. I showed the complete trace how the code of the central `search` function has been broken. This is currently in use in the latest release packages. One of you (PyMISP or MISP) needs to release in order to have a working combination using the officially released sources.

**Comment by cgi1** [comment]
Closed. Working with latest releases.
