### ISSUE TITLE
update_attribute responses with 200, but does not change value

### ISSUE THREAD

**Issue by fabrei** [MISP/PyMISP#339]
I already read [this issue](https://github.com/MISP/PyMISP/issues/260) but when I want to update an attribute I get a 200 response, but nothing changes.

I am using the MISP test VM and I am using the admin user account for it. 

Here is the debug output: 

`In [175]: misp.update_attribute(313200, '[{"value": "1234"}]')

DEBUG [api.py:154 - _prepare_request() ] POST - http://localhost:8080/attributes/313200
DEBUG [api.py:156 - _prepare_request() ] [{"value": "1234"}]
DEBUG [api.py:178 - _prepare_request() ] {'Content-Length': '19', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'User-Agent': 'PyMISP 2.4.102 - Python 2.7.13', 'Connection': 'keep-alive', 'content-type': 'application/json', 'Authorization': 'my-key'}
DEBUG [api.py:270 - _check_response() ] {
    "response": {
        "Attribute": {
            "category": "Network activity",
            "comment": "",
            "uuid": "95f65ecf-f2eb-4dee-8613-13435494c9e2",
            "event_id": "1365",
            "timestamp": "1549811107",
            "to_ids": false,
            "value": "9876",
            "disable_correlation": false,
            "distribution": "5",
            "type": "port",
            "id": "313200"
        }
    }
}
Out[175]: 
{u'response': {u'Attribute': {u'category': u'Network activity',
   u'comment': u'',
   u'disable_correlation': False,
   u'distribution': u'5',
   u'event_id': u'1365',
   u'id': u'313200',
   u'timestamp': u'1549811107',
   u'to_ids': False,
   u'type': u'port',
   u'uuid': u'95f65ecf-f2eb-4dee-8613-13435494c9e2',
   u'value': u'9876'}}}`

As you can see, I want to change the value from 9876 to 1234. The event was created with `misp.new_event()`. I have also tried to take the hole attribute object as a it comes from my event search, update the timestamp and value, but this does not work either and I get the same output. When I use the hole event object from my event search, change the event timestamp, change the value and timestamp in the attribute and then use `misp.update_event()` it works fine.

Any ideas?

**Comment by fabrei** [comment]
Ok, I found out, that `misp.update_attribute()` is working for me, when I use `attr = misp.get_attribute(<attr_uuid>)`, change the values of the returned object `attr` (e.g. `attr['value'] = 4321`) and then call `misp.update_attribute(<attr_uuid>, attr)`. 

Still now, I don't know why the other solution does not work for me..

**Comment by Rafiot** [comment]
The following work for me: 
```python
misp.update_attribute(313200, {"value": "1234"})
# instead of 
misp.update_attribute(313200, '[{"value": "1234"}]')
```

**Comment by fabrei** [comment]
> The following work for me:
> 
> ```python
> misp.update_attribute(313200, {"value": "1234"})
> # instead of 
> misp.update_attribute(313200, '[{"value": "1234"}]')
> ```
Oh yes, for me too! Didn't try it without brackets..thanks :)

**Comment by Rafiot** [comment]
Happy to help! :)
