### ISSUE TITLE
Error in VM while running test

### ISSUE THREAD

**Issue by datatern** [MISP/PyMISP#340]
![vm-error-screenshot](https://user-images.githubusercontent.com/47346493/52565949-4d31e680-2e2e-11e9-93c9-b3043b48298b.png)

While running these commands on VM as well as on Ubuntu terminal, the following error are occuring(refer screenshot).

Command: 
`nosetests-3.4 --with-coverage --cover-package=pymisp,tests --cover-tests tests/testlive_comprehensive.py
`

**Comment by Rafiot** [comment]
The test case doesn't have a URL pre-configured, that's the error message you get.

The easiest way to run that script is to create a file called `keys.py` that contains a variable `url` and a variable `key` in the `tests` directory.
