### ISSUE TITLE
Defining withAttachments equal to False via restSearch API  still returns a base64 attachment

### ISSUE THREAD

**Issue by raw-data** [MISP/PyMISP#344]
Hi,

While extracting misp events via the restSearch API interface, I started observing:
- cpu and memory spikes
- disk filling up

Putting the instance under monitoring I could observe the /tmp/ folder getting filled with phpXXXXXX files. 
Checking few files confirmed the json content, each storing query response issued via PyMISP.

- MISP version: 2.4.102
- PyMISP version: 2.4.102

Query example:
```
misp_url = 'xxxx'
misp_key = 'xxxx'
misp_verifycert = False
relative_path = '/events/restSearch'

body = {    
    "returnFormat": "json",
    "withAttachments": "False",
    "from": "2019-01-01",
    "to": "2019-02-01",
    "tags": ["tag1", "!tag2"]
}

misp = PyMISP(misp_url, misp_key)
r = misp.direct_call(relative_path, body)

for event in r['response']:
    # do stuff
```
Even if the parameter **withAttachments** was set to **False**, the results returned by MISP stored the base64 encoded attachment anyway.
The same behavior can be quickly tested also via the embedded REST client in MISP.

If **withAttachments** is completely removed from the query, no encoded attachment is returned.
```
body = {    
    "returnFormat": "json",
    "from": "2019-01-01",
    "to": "2019-02-01",
    "tags": ["tag1", "!tag2"]
}
```
As a result, also the /tmp/ folder doesn't get polluted, instead every php temp file is created and disposed on the fly (? as soon as MISP internal tasks are completed ?).

**Comment by Rafiot** [comment]
I think I know what is happening here. Try passing the following:

```python
body = {    
    "returnFormat": "json",
    "withAttachments": False,  # instead of "False"
    "from": "2019-01-01",
    "to": "2019-02-01",
    "tags": ["tag1", "!tag2"]
}
```

**Comment by raw-data** [comment]
Checking the suggested solution, with the MISP (2.4.102) REST client UI, returned the following

```
{"name":"Invalid JSON input. Make sure that the JSON input is a correctly formatted JSON string. This request has been blocked to avoid an unfiltered request.","message":"Invalid JSON input. Make sure that the JSON input is a correctly formatted JSON string. This request has been blocked to avoid an unfiltered request.","url":"\/events\/restSearch"}
```

**Comment by Rafiot** [comment]
So, you have two options here:

```python
misp_url = 'http://127.0.0.1:8080/events/restSearch'
misp_key = 'HRizIMmaxBOXAQSzKZ874rDWUsQEk4vGAGBoljQO'
misp_verifycert = False
relative_path = ''
body = '''{
    "returnFormat": "json",
    "eventid": 1198,
    "withAttachments": 0
}'''

from pymisp import PyMISP

misp = PyMISP(misp_url, misp_key, misp_verifycert)
misp.direct_call(relative_path, body)

```

```python
misp_url = 'http://127.0.0.1:8080/events/restSearch'
misp_key = 'HRizIMmaxBOXAQSzKZ874rDWUsQEk4vGAGBoljQO'
misp_verifycert = False
relative_path = ''
body = {
    "returnFormat": "json",
    "eventid": 1198,
    "withAttachments": False
}

from pymisp import PyMISP

misp = PyMISP(misp_url, misp_key, misp_verifycert)
misp.direct_call(relative_path, body)

```

(Both work on the VM, I tested)

**Comment by raw-data** [comment]
Hi @Rafiot , sorry for the delay in answering, you're right, it works. It might be there is another issue with the MISP REST client UI, but I am still at 2.4.102 and maybe we don't have this behavior in the latest version. Thank you for checking.

**Comment by Rafiot** [comment]
Yep, there was a bug in the REST client UI, it should be fixed now.
