### ISSUE TITLE
search returns str instead of dict

### ISSUE THREAD

**Issue by jochman** [MISP/PyMISP#345]
I've encountered a problem where I'm searching for a specific hash (`02475e29bd0816b697cad5b55cdf897a`) the search is returning `str` instead of `dict`.
The string looks like a JSON Object but when using json.loads() I'm getting an error.
`raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 278748 column 1 (char 10513228).

I could only run the response in json.loads=(json.dumps(response)) to get the appropriate dict.

let me know if needed further information.

**Comment by Rafiot** [comment]
Can you share the exact query you're doing?

**Comment by jochman** [comment]
`misp.search(value="02475e29bd0816b697cad5b55cdf897a")` nothing special or too complex.

**Comment by jochman** [comment]
> Can you share the exact query you're doing? (which method you're using, and all the parameters)

`misp.search(value="02475e29bd0816b697cad5b55cdf897a")` nothing special or too complex.
It does returns a big response.

**Comment by Rafiot** [comment]
It works fine for me... Can you enable debug (pass `debug=True` to PyMISP)? and show me the requests/responses you're getting?

Just making sure: which versions of MISP and PyMISP are you using?

**Comment by jochman** [comment]
I've installed new MISP instance (it's only for tests) and I'm using pymisp 2.4.99.
I'll try to reproduce again (have new instance with no contents in it)

**Comment by Rafiot** [comment]
I see in the issue referenced that you get a 500. That generally means that MISP breaks on something. I'm closing here and we should investigate on MISP side.
