### ISSUE TITLE
Error installing on Python 3.4

### ISSUE THREAD

**Issue by RichieB2B** [MISP/PyMISP#349]
Is it time for me to upgrade to Pyhton 3.6?
```
*** Error compiling '/tmp/pip-build-rj9aedd5/pymisp/pymisp/aping.py'...
  File "/tmp/pip-build-rj9aedd5/pymisp/pymisp/aping.py", line 72
    logger.error(f'Something went wrong ({response.status_code}): {error_message}')
                                                                                 ^
SyntaxError: invalid syntax
```

**Comment by FloatingGhost** [comment]
These are [format strings](https://www.python.org/dev/peps/pep-0498/) introduced in python3.6

So yeah, you'll need to

Python3.4 is 5 years old at this point

**Comment by Rafiot** [comment]
So in theory, aping shouldn't be called at all is your python version is below 3.6. What is the command you ran to get that error message?

**Comment by RichieB2B** [comment]
That sound about right, we have been using MISP for almost 5 years. :-)

The error was with the `pip3 install pymisp`
I just switched to rh-python36, no problems there.

**Comment by Rafiot** [comment]
Excellent, that's the best possible outcome :) Now, you can also use ExpandedPyMISP, and everything will still work on 2020 :)
