### ISSUE TITLE
"Could not add object" error with custom template object

### ISSUE THREAD

**Issue by nyx0** [MISP/PyMISP#353]
When I'm trying to push a custom object to MISP I had the following error:
```
m_object = pymisp.MISPObject(
    name=object_name,
    strict=True,  # same result with False as well
    misp_objects_path_custom=m_objects_path
)

[adding attributes here]

misp.add_object(event_id=ev_id, misp_object=m_object)

[REDACTED]

DEBUG [api.py:270 - _check_response() ] {
    "name": "Could not add object",
    "message": "Could not add object",
    "url": "/objects/add/424/",
    "errors": [
        "No valid template found to edit the object.",
        "403"
    ]
}
```
I removed the object on the MISP server but the UUID is the same (saw a related issue)

**Comment by Rafiot** [comment]
So, a few things to look at:
* What happen if you change the UUID of the object you're pushing?
* What happen if you add the object template you're using locally on the MISP instance you're pushing to?

@iglocska any other ideas?

**Comment by nyx0** [comment]
* I pushed the object to the MISP instance and tried again -> same error
* I modified the uuid of the local object that im using -> same error

**Comment by aschuster99** [comment]
Are you using a version of pymisp later then 2.4.96? If so, please downgrade to 2.4.96 (pip3 install pymisp==2.4.96) and check if that solves your problem.

**Comment by Rafiot** [comment]
pymisp 2.6.96 is pretty old, and I would really not use it. Is there any chance you share a code sample that fails? Because it works for me, and I assume I changed a thing I'm not using and yould rather not have you stuck with an old version that will definitely start failing on other things in the future.

**Comment by Rafiot** [comment]
.... or maybe it doesn't anymore. To me, it looks like a bug in MISP core. poke @iglocska 

```python
from pymisp import ExpandedPyMISP
from pymisp import MISPObject

user_defined_obj = MISPObject(name='test_object_template', strict=True, misp_objects_path_custom='../../tests/mispevent_testfiles')

user_defined_obj.add_attribute('member3', value='foo')
user_defined_obj.add_attribute('member1', value='baz')

print(user_defined_obj.to_json())

misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert, debug=True)
misp.add_object(1204,user_defined_obj)
```

```python
{'errors': (403,
  {'name': 'Could not add object',
   'message': 'Could not add object',
   'url': '/objects/add/1204/',
   'errors': 'No valid template found to edit the object.'})}
```

**Comment by Rafiot** [comment]
But that approach will work (push the full event with the object instead of just the object): 

```python
from pymisp import ExpandedPyMISP
misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert)

me = misp.get(1204)

me.add_object(user_defined_obj)
misp.update_event(me)
```

I'm not sure it is expected, but in the meantime, just get and push the full event.

**Comment by Rafiot** [comment]
(this issue has been fixed in MISP)
