### ISSUE TITLE
add_event overwrite event_creator_email

### ISSUE THREAD

**Issue by 8ear** [MISP/PyMISP#355]
He Guys,
I'm beginner of pymisp and i wrote a script which get an event from one misp and pushes to another (new) misp.
But everytime the user I take at the new misp overwrite the event_creator_email. Which I want to use from the original one.
Is this a bug?
Do I need any switch or any other to prevent this?

Kind regards

**Comment by Rafiot** [comment]
Yes, it is expected: the event creator email is forced by the platform when you go from the API. You can either setup a synchronization link between the two instances, or use the email address you expect on the destination side.
