### ISSUE TITLE
upload a custom json file to MISP

### ISSUE THREAD

**Issue by kknagesh** [MISP/PyMISP#356]
Hello, I have a custom json from a vendor which i need to upload to MISP. is there a way where i can upload to MISP. The custom json has different attributes for example ip , host name etc.

**Comment by Rafiot** [comment]
You need to map the indicators from the vendor file to MISP format. I'm not sure to understand your question. 
Maybe you can share the file?

**Comment by kknagesh** [comment]
The issue what we are noticing right now is we are successfully uploading the STIX 1.2 to the MISP using a Taxii-Server. However any feeds which are less than STIX1.2 (says STIX 1.1 , 1.1.1) we are not able to upload.

**Comment by Rafiot** [comment]
We will need much more details than that: the whole STIX / TAXII / v1 / v2 infrastructure is totally insane and there is basically no chance we can help you unless you share file samples with us.

**Comment by kknagesh** [comment]
Hello, Initially the issue was we are not able to upload the a stix 1.1 or 1.1.1 . Hence we are planning to upload that as a json. 

I am attaching the sample stix file here. when i upload tried to upload this in the MISP, i am able to only view the observables part not the indicator or any thing else. I am trying to upload using MISP Taxii Server installed on our server.
please feel free to change the extension of this file to xml before you upload in the MISP

[test.txt](https://github.com/MISP/PyMISP/files/2927171/test.txt)

**Comment by Rafiot** [comment]
Just making something crystal clear: STIX JSON is totally different from MISP JSON, it is like saying they are all text files. Even if accurate, it is not relevant to the problem.

@chrisr3d: can you have a look at the file?

**Comment by chrisr3d** [comment]
@kknagesh Can you by any chance tell me if you have anything in the following log file ?

YOUR_PATH_TO_MISP/app/tmp/logs/exec-errors.log
