### ISSUE TITLE
Memory usage with MISPEvent.load() with a lot of objects / attributes

### ISSUE THREAD

**Issue by l3m0ntr33** [MISP/PyMISP#360]
Hello,

Similar issue with https://github.com/MISP/PyMISP/issues/304

I have a performance issue when try to load an event with 4300 objects containing a total 38600 attributes .... my 2Gb of RAM are totally used by python in the first seconds and load "never" returned even after some minutes.

I did not take a look in detail to the code fix but do you think its possible to have the same improvement for events containing a lot of objects ?

Thanks a lot

**Comment by l3m0ntr33** [comment]
I made some memory profiling
``
#################################

Line #    Mem usage    Increment   Line Contents
================================================
   454   45.266 MiB   45.266 MiB       @profile
   455                                 def load(self, json_event, validate=False):
   456                                     """Load a JSON dump from a pseudo file or a JSON string"""
   457   45.266 MiB    0.000 MiB           if hasattr(json_event, 'read'):
   458                                         # python2 and python3 compatible to find if we have a file
   459                                         json_event = json_event.read()
   460   45.266 MiB    0.000 MiB           if isinstance(json_event, (basestring, bytes)):
   461                                         if OLD_PY3 and isinstance(json_event, bytes):
   462                                             json_event = json_event.decode()
   463                                         json_event = json.loads(json_event)
   464   45.266 MiB    0.000 MiB           if json_event.get('response'):
   465                                         event = json_event.get('response')[0]
   466                                     else:
   467   45.266 MiB    0.000 MiB               event = json_event
   468   45.266 MiB    0.000 MiB           if not event:
   469                                         raise PyMISPError('Invalid event')
   470   78.855 MiB   78.855 MiB           self.from_dict(**event)
   471   78.855 MiB    0.000 MiB           if validate:
   472                                         jsonschema.validate(json.loads(self.to_json()), self.__json_schema)



Filename: /home/hrifflet/_DEV/mailtomisp/venv/lib/python3.6/site-packages/pymisp/mispevent.py

Line #    Mem usage    Increment   Line Contents
================================================
   489   45.266 MiB   45.266 MiB       @profile
   490                                 def from_dict(self, **kwargs):
   491   45.266 MiB    0.000 MiB           if kwargs.get('Event'):
   492   45.266 MiB    0.000 MiB               kwargs = kwargs.get('Event')
   493                                     # Required value
   494   45.266 MiB    0.000 MiB           self.info = kwargs.pop('info', None)
   495   45.266 MiB    0.000 MiB           if self.info is None:
   496                                         raise NewEventError('The info field of the new event is required.')
[...]
    551   45.465 MiB    0.000 MiB           if kwargs.get('Tag'):
   552   45.465 MiB    0.000 MiB               for tag in kwargs.pop('Tag'):
   553   45.465 MiB    0.000 MiB                   self.add_tag(tag)
   554   45.465 MiB    0.000 MiB           if kwargs.get('Object'):
   555   78.984 MiB    0.000 MiB               for obj in kwargs.pop('Object'):
   556   78.984 MiB    0.914 MiB                   self.add_object(obj)
   557   78.984 MiB    0.000 MiB           if kwargs.get('Org'):
   558   78.984 MiB    0.000 MiB               self.Org = MISPOrganisation()
   559   78.984 MiB    0.000 MiB               self.Org.from_dict(**kwargs.pop('Org'))
   560   78.984 MiB    0.000 MiB           if kwargs.get('Orgc'):
   561   78.984 MiB    0.000 MiB               self.Orgc = MISPOrganisation()
   562   78.984 MiB    0.000 MiB               self.Orgc.from_dict(**kwargs.pop('Orgc'))
   563
   564   78.984 MiB    0.000 MiB           super(MISPEvent, self).from_dict(**kwargs)
``

**Comment by l3m0ntr33** [comment]
profiling for add_object
```
Line #    Mem usage    Increment   Line Contents
================================================
   680   78.281 MiB   78.281 MiB       @profile
   681                                 def add_object(self, obj=None, **kwargs):
   682                                     """Add an object to the Event, either by passing a MISPObject, or a dictionary"""
   683   78.281 MiB    0.000 MiB           if isinstance(obj, MISPObject):
   684                                         misp_obj = obj
   685   78.281 MiB    0.000 MiB           elif isinstance(obj, dict):
   686   78.281 MiB    0.000 MiB               misp_obj = MISPObject(name=obj.pop('name'), strict=obj.pop('strict', False),
   687   78.281 MiB    0.000 MiB                                     default_attributes_parameters=obj.pop('default_attributes_parameters', {}),
   688   78.281 MiB    0.000 MiB                                     **obj)
   689   79.098 MiB    0.922 MiB               misp_obj.from_dict(**obj)
   690                                     elif kwargs:
   691                                         misp_obj = MISPObject(name=kwargs.pop('name'), strict=kwargs.pop('strict', False),
   692                                                               default_attributes_parameters=kwargs.pop('default_attributes_parameters', {}),
   693                                                               **kwargs)
   694                                         misp_obj.from_dict(**kwargs)
   695                                     else:
   696                                         raise InvalidMISPObject("An object to add to an existing Event needs to be either a MISPObject, or a plain python dictionary")
   697   79.098 MiB    0.000 MiB           self.Object.append(misp_obj)
   698   79.098 MiB    0.000 MiB           self.edited = True
   699   79.098 MiB    0.000 MiB           return misp_obj

```

**Comment by l3m0ntr33** [comment]
And the last one memory profile for ```MISPObject.from_dict```
```
Filename: /home/hrifflet/_DEV/mailtomisp/venv/lib/python3.6/site-packages/pymisp/mispevent.py

Line #    Mem usage    Increment   Line Contents
================================================
  1009   78.141 MiB   78.141 MiB       @profile
  1010                                 def from_dict(self, **kwargs):
  1011   78.141 MiB    0.000 MiB           if kwargs.get('Object'):
  1012                                         kwargs = kwargs.get('Object')
  1013   78.141 MiB    0.000 MiB           if self._known_template:
  1014                                         if kwargs.get('template_uuid') and kwargs['template_uuid'] != self.template_uuid:
  1015                                             if self._strict:
  1016                                                 raise UnknownMISPObjectTemplate('UUID of the object is different from the one of the template.')
  1017                                             else:
  1018                                                 self._known_template = False
  1019                                         if kwargs.get('template_version') and int(kwargs['template_version']) != self.template_version:
  1020                                             if self._strict:
  1021                                                 raise UnknownMISPObjectTemplate('Version of the object ({}) is different from the one of the template ({}).'.format(kwargs['template_version'], self.template_version))
  1022                                             else:
  1023                                                 self._known_template = False
  1024
  1025   78.141 MiB    0.000 MiB           if 'distribution' in kwargs and kwargs['distribution'] is not None:
  1026   78.141 MiB    0.000 MiB               self.distribution = kwargs.pop('distribution')
  1027   78.141 MiB    0.000 MiB               self.distribution = int(self.distribution)
  1028   78.141 MiB    0.000 MiB               if self.distribution not in [0, 1, 2, 3, 4, 5]:
  1029                                             raise NewAttributeError('{} is invalid, the distribution has to be in 0, 1, 2, 3, 4, 5'.format(self.distribution))
  1030
  1031   78.141 MiB    0.000 MiB           if kwargs.get('timestamp'):
  1032   78.141 MiB    0.000 MiB               if sys.version_info >= (3, 3):
  1033   78.141 MiB    0.000 MiB                   self.timestamp = datetime.datetime.fromtimestamp(int(kwargs.pop('timestamp')), datetime.timezone.utc)
  1034                                         else:
  1035                                             self.timestamp = datetime.datetime.fromtimestamp(int(kwargs.pop('timestamp')), UTC())
  1036   78.141 MiB    0.000 MiB           if kwargs.get('Attribute'):
  1037   79.031 MiB    0.000 MiB               for a in kwargs.pop('Attribute'):
  1038   79.031 MiB    0.324 MiB                   self.add_attribute(**a)
  1039   79.031 MiB    0.000 MiB           if kwargs.get('ObjectReference'):
  1040                                         for r in kwargs.pop('ObjectReference'):
  1041                                             self.add_reference(**r)
  1042
  1043                                     # Not supported yet - https://github.com/MISP/PyMISP/issues/168
  1044                                     # if kwargs.get('Tag'):
  1045                                     #    for tag in kwargs.pop('Tag'):
  1046                                     #        self.add_tag(tag)
  1047
  1048   79.031 MiB    0.000 MiB           super(MISPObject, self).from_dict(**kwargs)
```

**Comment by Rafiot** [comment]
Out of curiosity, what is the size of the plain json you get from MISP? That one is a bit more tricky to solve but I may be able to improve it a bit.

**Comment by Rafiot** [comment]
Do you have any news on that?

**Comment by Rafiot** [comment]
Closing for now, please let me know if you have more info.
