### ISSUE TITLE
Updating Objects

### ISSUE THREAD

**Issue by Bumble0b33** [MISP/PyMISP#364]
Is it possible to update the attributes in an object or add new attributes to it?

**Comment by Rafiot** [comment]
Yes, it is.

Can you give me more details on what you're trying to do? There are examples in the doc/tutorial directory.

**Comment by Bumble0b33** [comment]
I'm trying to add attributes to a specific object: for example add a new destination IP for an existing domain-ip object for an existing event

**Comment by Rafiot** [comment]
I just added a test: https://github.com/MISP/PyMISP/commit/35b4f3f852ad1dd2fc082654edbef74ce417dc6a

And it works for me. One thing that may be causing a problem is if the original object is created with a template more recent than the one used by PyMISP. Can you check the response from the server?

**Comment by Bumble0b33** [comment]
Apologies for the delay, I'm actually stuck at converting an event from a dictionary. I get an error when I get an event with attributes and try to convert it: 
event = misp.get_event(3)
event = pymisp.MISPEvent()
event.from_dict(**event_dict)

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/****/venv/lib/python3.6/site-packages/pymisp/mispevent.py", line 523, in from_dict
    self.add_attribute(**a)
File "/****/venv/lib/python3.6/site-packages/pymisp/mispevent.py", line 656, in add_attribute
    attribute.from_dict(type=type, value=value, **kwargs)
File "/****/venv/lib/python3.6/site-packages/pymisp/mispevent.py", line 197, in from_dict
    raise NewAttributeError('{} is invalid, to_ids has to be True or False'.format(self.to_ids))
pymisp.exceptions.NewAttributeError: 0 is invalid, to_ids has to be True or False
```
using ExpandedPyMISP gives me the same result. I can see that `kwargs.get('Attribute')` is a dictionary in a list. Was just wondering if it was just a problem on my end.

**Comment by Rafiot** [comment]
Nope, that was a bug, I fixed it. Thank you for the report.
