### ISSUE TITLE
PyMISP no longer uses HTTP_PROXY and HTTPS_PROXY environment variables

### ISSUE THREAD

**Issue by RichieB2B** [MISP/PyMISP#365]
Before PyMISP v2.4.82 it used the get() and post() functions of the python requests library. These are wrappers for the request() function which calls merge_environment_settings() which supports the HTTP_PROXY and HTTPS_PROXY environment variables.

Since PyMISP v2.4.82 it uses the send() function of the python requests library. This function never calls merge_environment_settings() so the HTTP_PROXY and HTTPS_PROXY environment variables are not used. This not a bug of the send() function, but [working as designed](https://github.com/kennethreitz/requests/issues/3190).

I know a PyMISP object can be created with a proxies parameter, but I just wanted to document the change in behavior.

**Comment by Rafiot** [comment]
Woops, good point, I'll just add the call as described here: https://github.com/kennethreitz/requests/issues/2807#issuecomment-147095885

**Comment by RichieB2B** [comment]
Thanks for the quick fix!
