### ISSUE TITLE
Probable problem : Export PDF LayoutError: Flowable to large

### ISSUE THREAD

**Issue by Vincent-CIRCL** [MISP/PyMISP#368]
If you get a "LayoutError: Flowable to large" or "Table cell too large vertically" using Export PDF, it is due to reportlab library, which is not handling table with text contains in a cell, if the text is too long to print the cell on a single page.

Please see (for example) this answer on their mailing list to see how it is a true problem on their side : 
https://pairlist2.pair.net/pipermail/reportlab-users/2010-May/009529.html and https://groups.google.com/forum/#!topic/reportlab-users/wlIN3Fsg2VA
which states : 
![image](https://user-images.githubusercontent.com/47740166/54336834-80ce7f00-462d-11e9-852c-88d3676a26b8.png)

ExportPDF module tries to cut your text (dichotomy way) until it estimates that it will fit on the page. Unfortunately, the dichotomy is limited in depth. If your text is **really** long, or if the estimation is wrong (a lot of \n characters, special characters, ..) it _may_ fail. 
Catching the error is nor possible, as it is thrown at building time (the last step of the PDF processing) and so could occurs from anywhere, not only too long paragraphs.

It seems there is no official or correct workaround.

**Comment by Rafiot** [comment]
I'll close this one for now.
