### ISSUE TITLE
Search Attribute

### ISSUE THREAD

**Issue by deni3dAcc3ss** [MISP/PyMISP#373]
v2.4.102 (e880b6a458eab68330e688ec3b20ca5dcbff6c9a) 

I am having an issue with attribute search. I have implemented via shell/curl as well as the pymisp and do receive the same results.

> 
> attributes = misp.search(controller='attributes', type_attribute='domain', tags=sstags, to_ids=1, pythonify=True)
> #attributes = misp.search(controller='attributes', type_attribute='domain', tags=sstags, to_ids=1, pythonify=False)
> 
> for attribute in attributes:
>     print(attribute['value'])
> 

`TYPE='domain'
TAG='tag1&&tag2'
TO='null'
FROM='null'
LAST='null'
EVENTID='null'
ALLOWNONIDS='false'

curl  -k -H "Authorization:$APIKEY" "$BASEURL/attributes/text/download/$TYPE/$TAG/$EVENTID/$ALLOWNONIDS/$FROM/$TO/$LAST" > $TYPE.attr
`

The implementation is based upon an example from the documentation: https://<misp url>/attributes/text/download/all/tag1&&tag2&&!tag3

In my query I have two tags, tag1 which I have applied to events and tag2 which I want to apply to specific attributes within events (which have tag1). The application of the tags and (re)publishing of the events work. However, when I search, I receive attributes who have tag2 or tag1, all the attributes returned have tag1 through inheritance, tag2 is direct application. 

The issue is that the query returns attributes that have tag1 or tag2 not tag1 and tag2.

 Is there a way to perform a search where only attributes which have both tag1 and tag2 are returned this is what I had believed the && meant, (true && true) vs (true || false), the latter is true to MISP implementation, which seems to contradict other standard logic implementations.

It this a bug? Should not the only attributes which are returned have both tag1 and tag2?

Thanks

**Comment by g4l4drim** [comment]
I guess it's an open issue on MISP and a future feature ? look at  https://github.com/MISP/MISP/issues/2416 and https://github.com/MISP/PyMISP/issues/316

**Comment by Rafiot** [comment]
You should very much not use the URL parameters approach, please use search instead.
