### ISSUE TITLE
Disable correlation for attribute

### ISSUE THREAD

**Issue by migueltubia** [MISP/PyMISP#38]
Hi,
we have developed a script to create events and add attributes to them from an external source.
Now, we'd like to disable correlation on some attributes inside the script, but we cannot find anything in the API to do it.
Is this possible?
Thanks!!!
M.

**Comment by FloatingGhost** [comment]
Hm, it should be possible, but I'm not able to get it to work - I'll try and figure out why, and get back to you with a solution :)

**Comment by FloatingGhost** [comment]
Ok, it was a bug in MISP itself!

Run a quick `git pull` and try this:
```python
test_event = pymisp.new_event(info="No correlation")
pymisp.add_named_attribute( test_event, "ip-src", "8.8.8.8", disable_correlation=True )
```

should work:tm:

**Comment by migueltubia** [comment]
Thanks a lot for your help!!! I also noticed that pip installed on my computer an old version of pymisp.
After upgrading both of them (misp & pymisp), now it's working :)
Regards!!
