### ISSUE TITLE
Example of Joe sandbox report to compare pe fields

### ISSUE THREAD

**Issue by chrisr3d** [MISP/PyMISP#388]
[light_json_report_fixed.zip](https://github.com/MISP/PyMISP/files/3140995/light_json_report_fixed.zip)

**Comment by chrisr3d** [comment]
[misp_event.zip](https://github.com/MISP/PyMISP/files/3141063/misp_event.zip)

**Comment by Rafiot** [comment]
Guess: `rawaddr` in joesandbox is `offset` in lief: https://lief.quarkslab.com/doc/latest/api/python/pe.html#lief.PE.Section.offset

**Comment by Rafiot** [comment]
TODO: add new entries in the file generator.
