### ISSUE TITLE
Support for client certificates

### ISSUE THREAD

**Issue by dspruell** [MISP/PyMISP#39]
We utilize a MISP instance where MISP is protected by SSL/TLS and requires client certificate auth, i.e.

```
<Directory /var/www/MISP/app/webroot>
    SSLVerifyClient require
    ...
```

If I'm not mistaken, it is the case that a remote client using PyMISP cannot currently interact with this MISP REST API. Would it be possible to add support for supplying client certificate data in PyMISP to interact with such deployments?

Noteworthy that this seems fairly simplistic using Requests: http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification. 

In our use case we'd have various PyMISP clients configured with a user settings file and would add such parameters (key and certificate files, or simply combined key+cert file) in there.

**Comment by adulau** [comment]
It should work out-of-the-box since August 2016, https://github.com/CIRCL/PyMISP/blob/f593ce69f87a2f1c3c1752f0a9c714d418069853/pymisp/api.py#L77 

https://media.readthedocs.org/pdf/pymisp/master/pymisp.pdf

You can set the cert argument to the PyMISP method. Feel free to reopen if you have any issue

**Comment by dspruell** [comment]
Thanks! I missed this I think partly because of laziness on my side
(didn't look hard enough) and partly because the documentation [1]
linked from https://github.com/MISP/PyMISP/blob/master/README.md must
be out of date. Should the documentation link ("PyMISP API
documentation is available") be updated to point to the latest file on
readthedocs.org instead?

[1] http://www.circl.lu/assets/files/PyMISP.pdf

On Wed, Jan 18, 2017 at 12:29 AM, Alexandre Dulaunoy
<notifications@github.com> wrote:
> It should work out-of-the-box since August 2016,
> https://github.com/CIRCL/PyMISP/blob/f593ce69f87a2f1c3c1752f0a9c714d418069853/pymisp/api.py#L77
>
> https://media.readthedocs.org/pdf/pymisp/master/pymisp.pdf
>
> You can set the cert argument to the PyMISP method. Feel free to reopen if
> you have any issue
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Darren Spruell
phatbuckett@gmail.com

**Comment by adulau** [comment]
Good point. I'll update the README.
