### ISSUE TITLE
Python 3.7 deprecation warning Using or importing the ABCs from 'collections'

### ISSUE THREAD

**Issue by hhyyrylainen-abusesa** [MISP/PyMISP#390]
When running pymisp with Python 3.7.3 I get this warning:
```
/Users/hhyyrylainen/.virtualenvs/projekti/lib/python3.7/site-packages/pymisp/abstract.py:78: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    class AbstractMISP(collections.MutableMapping):
```

This is both with the latest version from PyPI and directly from master branch (`pip install --upgrade git+git://github.com/MISP/PyMISP.git@master`)

**Comment by Rafiot** [comment]
Good catch, thank you! For some reason, I don't see the deprecation warning and that worries me a bit...

It will be fixed in a few min.

**Comment by hhyyrylainen-abusesa** [comment]
I'm still getting that warning after updating from master. I think it's because this line:
```
class AbstractMISP(collections.MutableMapping):
```
Should be:
```
class AbstractMISP(MutableMapping):
```

**Comment by Rafiot** [comment]
.... sorry for that, it's fixed now.

**Comment by hhyyrylainen-abusesa** [comment]
Can confirm it's fixed now. Thanks.
