### ISSUE TITLE
If advanced_extraction is used in upload_sample, file is not saved

### ISSUE THREAD

**Issue by geekscrapy** [MISP/PyMISP#392]
Hi, just seeing if this is a bug or as expected.

I am wanting to upload multiple files to a particular event as per the example below. If I use ```advanced_extraction=False``` the file is added as an object and the file is also available for download (encrypted).
If ```advanced_extraction=True``` is used, additional analysis is completed against the file (ssdeep, mimetype etc.) which is what I would like, but the file is not available for download.

```pymisp.upload_sample(filename=binary_name, filepath_or_bytes=binary_path, event_id=response['Event']['id'], advanced_extraction=True)```

It would also be useful if this function returned the created object_id :)

**Comment by Rafiot** [comment]
That should be fixed now.
