### ISSUE TITLE
Bug/Addition: API Add Object doesn't add Tags

### ISSUE THREAD

**Issue by DragonDev1906** [MISP/PyMISP#396]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug/Addition
| OS version (server)       | 
| OS version (client)       | Windows 10
| PHP version               | 7.2.10
| MISP version / git hash   | 2.4.98
| Browser                   | Firefox

### Expected behavior
Add Object should add the Tags given in the JSON Message.

### Actual behavior
Add Object adds the Attributes but no Tags are added.

### Steps to reproduce the behavior
- Create an Event
- Execute the following REST Query to:
Post `/objects/add/<event_id>/32` using the REST client
~~~json
{
  "Attribute": [
    {
      "Tag": [
        {
          "name": "SomeTag"
        }
      ],
      "category": "Payload delivery",
      "disable_correlation": false,
      "object_relation": "md5",
      "to_ids": true,
      "type": "md5",
      "uuid": "06cfd142-fc69-408e-91b5-604e0fd88f28",
      "value": "55555555555555555555555555555555"
    }
  ],
  "distribution": "5",
  "name": "test",
  "sharing_group_id": "0",
  "template_uuid": "688c46fb-5edb-40a3-8273-1af7923e2215",
  "template_version": "15",
  "uuid": "75154c31-1628-453e-938e-6ea2634df0b6"
}
~~~
- The Attribute in the Object won't have any Tags
- The Response doesn't have any Tags either

Alternatively:
- Create an Event
- Use the following Python Code to add the Object using PyMISP
~~~python
from pymisp import PyMISP, MISPObject, MISPTag
import json

m = PyMISP('<url>', '<key>')

event_id = 255
template_file_uuid = '688c46fb-5edb-40a3-8273-1af7923e2215'
template_file_version = 15
template_id = 32

tag = MISPTag()
tag.name = "SomeTag"

obj = MISPObject('test')
obj.template_version = template_file_version
obj.template_uuid = template_file_uuid
att = obj.add_attribute('md5', value='5'*32, Tag=[tag], type='md5')

print('\nObject:')
print(obj.to_json())

print('\nAttribute:')
print(att.to_json())

response = m.add_object(event_id, misp_object=obj, template_id=template_id)
print('\nResponse:')
print(json.dumps(response, indent=4, sort_keys=True))

~~~
- The Attribute in the Object won't have any Tags
- The Object and Attribute (in python) have Attributes (as seen in stdout) but the response from add_object does not.

#### REST Query / MISPObject.to_json()
~~~json
{
  "Attribute": [
    {
      "Tag": [
        {
          "name": "SomeTag"
        }
      ],
      "category": "Payload delivery",
      "disable_correlation": false,
      "object_relation": "md5",
      "to_ids": true,
      "type": "md5",
      "uuid": "06cfd142-fc69-408e-91b5-604e0fd88f28",
      "value": "55555555555555555555555555555555"
    }
  ],
  "distribution": "5",
  "name": "test",
  "sharing_group_id": "0",
  "template_uuid": "688c46fb-5edb-40a3-8273-1af7923e2215",
  "template_version": "15",
  "uuid": "75154c31-1628-453e-938e-6ea2634df0b6"
}
~~~

#### REST Response / PyMISP Response from add_object
~~~json
{
  "Object": {
    "id": "950",
    "name": "file",
    "meta-category": "file",
    "description": "File object describing a file with meta-information",
    "template_uuid": "688c46fb-5edb-40a3-8273-1af7923e2215",
    "template_version": "15",
    "event_id": "255",
    "uuid": "75154c31-1628-453e-938e-6ea2634df0b6",
    "timestamp": "1543909103",
    "distribution": "5",
    "sharing_group_id": "0",
    "comment": "",
    "deleted": false
  },
  "Attribute": [
    {
      "id": "45979",
      "event_id": "255",
      "object_id": "950",
      "object_relation": "md5",
      "category": "Payload delivery",
      "type": "md5",
      "value1": "55555555555555555555555555555555",
      "value2": "",
      "to_ids": true,
      "uuid": "06cfd142-fc69-408e-91b5-604e0fd88f28",
      "timestamp": "1543909103",
      "distribution": "5",
      "sharing_group_id": "0",
      "comment": "",
      "deleted": false,
      "disable_correlation": false,
      "value": "55555555555555555555555555555555"
    }
  ]
}
~~~

**Comment by Rafiot** [comment]
Few questions:

* Is the tag already on the system? Or is it a new one?
* Is the user allowed to create a tag? And to use that tag?

**Comment by kfinny** [comment]
I'm also seeing this issue.  In my case, the tags are already present.  As a workaround, I'm using `PyMISP.tag(attribute_uuid, tag_name)` on the relevant attributes to add the tags after creating the object.  I use the returned object and find the attributes based on value (e.g. sha256) then get the uuid to add tags.  This works, so does not appear to be a permission issue.

Here is my code
`        for attribute in self.event.Attribute:
            if attribute.type == 'sha256':
                if attribute.value not in self.lookup:
                    # going to convert this to an object
                    obj = MISPObject('file', strict=True, standalone=True)
                    a = obj.add_attribute('sha256',
                                      **{'value': attribute.value,
                                         'category': attribute.category,
                                         'comment': attribute.comment,
                                         'disable_correlation': attribute.disable_correlation,
                                         'distribution': attribute.distribution,
                                         'sharing_group_id': attribute.sharing_group_id,
                                         'timestamp': attribute.timestamp,
                                         'to_ids': attribute.to_ids,
                                         'Tag': attribute.Tag})
                    print(a.to_json())
                    # ADDING WORKAROUND TO POPULATE TAGS
                    o = self.misp.add_object(self.event.id, obj)
                    uuid = o.Attribute[0].uuid
                    for tag in attribute.Tag:
                        self.misp.tag(uuid, tag.name)
                    self.lookup[attribute.value] = o`

**Comment by DragonDev1906** [comment]
"Is the tag already on the system? Or is it a new one?"
I think I have tried both (not quite sure though).

"Is the user allowed to create a tag? And to use that tag?"
As kfinny mentioned: "This works, so does not appear to be a permission issue.".
I can create tags so it is not a permission problem.

"SteveClement transferred this issue from MISP/MISP on 23 May"
This must be an issue in MISP itself because it is independent of PyMISP because it can be replicated using the REST client from MISP (without using PyMISP).

**Comment by doomedraven** [comment]
extendedmisp and pymsip MISP 2.4.117.2 and issue persist

```
DEBUG [aping.py:2192 - _prepare_request() ] POST - http://X/tags/add                                                                                                                              
2019-12-02 14:57:36,201 [pymisp] DEBUG: POST - http://X/tags/add                                                                                                                                  
DEBUG [aping.py:2194 - _prepare_request() ] <MISPTag(name=testme hard)                                                                                                                                      
2019-12-02 14:57:36,201 [pymisp] DEBUG: <MISPTag(name=testme hard)                                                                                                                                          
DEBUG [aping.py:2219 - _prepare_request() ] {'User-Agent': 'PyMISP 2.4.117.2 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': 
'23', 'Authorization': 'X', 'content-type': 'application/json'}                                                                                                      
2019-12-02 14:57:36,202 [pymisp] DEBUG: {'User-Agent': 'PyMISP 2.4.117.2 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '23', 'Authorization': 'X', 'content-type': 'application/json'}                                                                                                         
DEBUG [aping.py:2166 - _check_response() ] {'Tag': {'id': '68', 'name': 'testme hard', 'colour': '#3b5b3f', 'exportable': True, 'org_id': '0', 'user_id': '0', 'hide_tag': False, 'numerical_value': None}}
2019-12-02 14:57:36,438 [pymisp] DEBUG: {'Tag': {'id': '68', 'name': 'testme hard', 'colour': '#3b5b3f', 'exportable': True, 'org_id': '0', 'user_id': '0', 'hide_tag': False, 'numerical_value': None}}    {'Tag': {'id': '68', 'name': 'testme hard', 'colour': '#3b5b3f', 'exportable': True, 'org_id': '0', 'user_id': '0', 'hide_tag': False, 'numerical_value': None}}
```

**Comment by doomedraven** [comment]
what worked is `self.misp.tag(event["uuid"],tag)`

```
                event = MISPEvent()
                event.distribution = distribution
                event.threat_level_id = threat_level_id
                event.analysis = analysis
                event.info = "{} {} - {}".format(info, malfamily, results.get('info', {}).get('id'))
                event = self.misp.add_event(event, pythonify=True)
                self.misp.tag(event["uuid"],tag)
```

**Comment by Rafiot** [comment]
* `ExpandedPyMISP.add_tag()` will create a new tag on the MISP instance, if the user has the tagger rights. This tag won't be attached to any event.
* `MISPEvent.add_tag()` will add a tag **locally** to the MISPEvent you're working on. In order to have that that on the remote event, you need to either create the event with `ExpandedPyMISP.add_event()` or `ExpandedPyMISP.update_event()`. **Note**: if the tag doesn exists on the platform, and youŕe used doesn't have the tagger rights, the tag will be discarded.
* `ExpandedPyMISP.tag()` will attach a tag to an event or an attribute

**Comment by doomedraven** [comment]
Thanks for so detailed explanation
