### ISSUE TITLE
Event with float timestamp could not be loaded

### ISSUE THREAD

**Issue by klapeyron1** [MISP/PyMISP#397]
Couldn't import json file as pymisp.mispevent.MISPEvent from [here](https://feeds.inthreat.com/osint/misp/)
Looks like it has 'timestamp' format as float, so 
pymisp/mispevent.py:237 fails because it do not recognizes float timestamp
Suggestion:
`self.timestamp = datetime.datetime.fromtimestamp(int(float(ts)), datetime.timezone.utc)`

**Comment by Rafiot** [comment]
Yes, it doesn't follow the standard and they need to fix their feed.
