### ISSUE TITLE
Upgrade urllib3 to urllib3<1.25,>=1.23 because py2neo fails

### ISSUE THREAD

**Issue by SteveClement** [MISP/PyMISP#399]
Dear

On an automated install I got the following error:

```
ERROR: py2neo 4.3.0 has requirement urllib3<1.25,>=1.23, but you'll have urllib3 1.25.3 which is incompatible.
```

Currently the following is in Pipfile.lock:

https://github.com/MISP/PyMISP/blob/583fb6592495ea358aad47a8a1ec92d43c13348a/Pipfile.lock#L279

https://github.com/MISP/PyMISP/blob/583fb6592495ea358aad47a8a1ec92d43c13348a/Pipfile.lock#L407

**Comment by Rafiot** [comment]
I think that's solved now.
