### ISSUE TITLE
Update in VM

### ISSUE THREAD

**Issue by SteveClement** [MISP/PyMISP#400]
error: Your local changes to the following files would be overwritten by checkout:
	tests/testlive_comprehensive.py

**Comment by Rafiot** [comment]
Hmmmm right, makes sense, I forgot about it... :/ 
https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.sh#L861

The fix is to use the file keys.py. I'll try to fix that later today.

**Comment by Rafiot** [comment]
(the hotfix being to do a force pull, which in the case of the VM should not be a problem)

**Comment by SteveClement** [comment]
Ok, as it is now documented here, this issue is closed for me.

**Comment by Rafiot** [comment]
Well, I'm doing to reopen it, so I don't forget to fix it.

**Comment by Rafiot** [comment]
Fixed.
