### ISSUE TITLE
Query enrichment / enrich event endpoints

### ISSUE THREAD

**Issue by iglocska** [MISP/PyMISP#407]
This might be implemented already, in case not, could we get these mapped too?

**Comment by Rafiot** [comment]
Hmmm where can I find the doc for that? I cannot find anything on the REST api that matches "enrich"

**Comment by slonix** [comment]
Hi, it would be really nice to have an API for enriching events in MISP...

**Comment by DarkZatarra** [comment]
Currently it can be done only from command line as far as I've seen

**Comment by Rafiot** [comment]
Yes, CLI only at this point.
