### ISSUE TITLE
Add a feed using PyMISP, but some field values are missing

### ISSUE THREAD

**Issue by Applenice** [MISP/PyMISP#411]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | Ubuntu
| MISP version / git hash   | MISP_v2.4.109@08e7ca3
| PyMISP version       | v2.4.106

### Expected behavior
Successfully add feed through PyMISP

### Actual behavior
Use PyMISP to add feeds but missing fields

### Steps to reproduce the behavior
The following operations are performed in the  virtual machine(https://www.circl.lu/misp-images/latest/).

I am trying to automate with PyMISP，View the example: 
https://github.com/MISP/PyMISP/blob/master/examples/add_feed.py

I did a simple test:
```Python
def main():
    source_format = "freetext"
    feed_url = "https://onlytest.com/test.txt"
    name = "test add feed"
    input_source = "network"
    provider = "Only"

    misp = init(misp_url, misp_key)
    response = misp.add_feed(source_format=source_format, url=feed_url, name=name, input_source=input_source, provider=provider)
    print(response)
```
But the returned result shows that some fields are missing, the value of name, url, and provider is null.：
```
{'Feed': {'id': '58', 'name': '', 'provider': '', 'url': '', 'rules': None, 'enabled': False, 'distribution': '0', 'sharing_group_id': '0', 'tag_id': '0', 'default': False, 'source_format': 'freetext', 'fixed_event': True, 'delta_merge': False, 'event_id': '0', 'publish': False, 'override_ids': False, 'settings': '[]', 'input_source': 'network', 'delete_local_file': False, 'lookup_visible': False, 'headers': None, 'caching_enabled': False, 'force_to_ids': False}}
```
I have debug, but not found the problem, how to solve this problem?

**Comment by Rafiot** [comment]
And is the feed added on the web interface?

**Comment by Applenice** [comment]
> And is the feed added on the web interface?
The field is the same as mentioned earlier，added feeds in the web interface works fine.

**Comment by Applenice** [comment]
> And is the feed added on the web interface?

The field is the same as mentioned earlier，added feeds in the web interface works fine.

**Comment by Applenice** [comment]
Find related issues in the MISP repository:  https://github.com/MISP/MISP/issues/4142

Use the add_feed.py example, data is:
```
  {
    "source_format": "misp",
    "url": "https://thisisjustatest.org",
    "name": "add test feed",
    "input_source": "network",
    "provider": "test"
  }
```
As mentioned earlier, the returned results show that some fields are missing.

Modify part of the code, data is:
```
{
  "Feed":
  {
    "source_format": "misp",
    "url": "https://thisisjustatest.org",
    "name": "add test feed",
    "input_source": "network",
    "provider": "test"
  }
}
```
Normal work at this time, the data is submitted correctly, no fields are missing.

**Comment by Rafiot** [comment]
Sorry for the late answer, I escalated the issue to MISP, as it seems to be a bug in the core.

**Comment by Applenice** [comment]
> Sorry for the late answer, I escalated the issue to MISP, as it seems to be a bug in the core.

Thanks for the reply, yes, the template in the REST client is the same problem.

**Comment by Applenice** [comment]
https://github.com/MISP/PyMISP/blob/b8b384a3c3cde7abafd8a0259bad0940d8a37f83/pymisp/api.py#L2173

https://github.com/MISP/PyMISP/blob/b8b384a3c3cde7abafd8a0259bad0940d8a37f83/pymisp/api.py#L2145

I think PyMISP and REST Client have problems building data, waiting for core verification.

**Comment by Rafiot** [comment]
With the changes of this week, I'm able to properly ad a feed (with ExpandedPyMISP)
