### ISSUE TITLE
openioc importer ignores some mappings given in the mapping dictionary

### ISSUE THREAD

**Issue by 3c7** [MISP/PyMISP#412]
The openioc importer ignores the subtypes of `RouteEntryItem/Destination`. Importing openioc files given by some security vendors lead to a loss of IOCs that way. #409 fixes that and maps `RouteEntryItem/Destination/String` to `hostname` instead of `url`.

**Comment by Rafiot** [comment]
We're not using openioc much, so if it works for you, I'm merging. Thank you!
