### ISSUE TITLE
Passing multiple values into MISPObject

### ISSUE THREAD

**Issue by jochman** [MISP/PyMISP#413]
I'm trying to send multiple IPs in `ExpandedPyMISP.add_object`.
I'm creating a new DomainIPObject but I can't figure out how to pass multiple values into 'ip' field.

I already tried passing:
List of IPs `["ip1", "ip2"]`
List of dict of ips `[{"ip":"ip1"}, {"ip":"ip2"}]`
and the str version of those object with json.dumps.

what I'm doing wrong?

**Comment by Rafiot** [comment]
That would be the way to do it:
```python
ip_dom = MISPObject('domain-ip')                                                
ip_dom.add_attribute('domain', value='google.fr')                               
ip_dom.add_attributes('ip', {'value': '10.8.8.8', 'to_ids': False}, '10.9.8.8') 
ip_dom.add_attributes('ip', '11.8.8.8', '11.9.8.8')                             
ExpandedPyMISP.add_object(ip_dom)
```

**Comment by jochman** [comment]
Is there any way to use if in one call with DomainIPObject?

**Comment by Rafiot** [comment]
I forgot about this class... :man_facepalming: 

Yes, the example is here: https://github.com/MISP/PyMISP/blob/master/tests/testlive_comprehensive.py#L949
