### ISSUE TITLE
disable_correlation on object without effect

### ISSUE THREAD

**Issue by rommelfs** [MISP/PyMISP#416]
disable_correlation via pymisp on attribute add on object instance has no effect

**Comment by rommelfs** [comment]
the mistake was in my code, thanks for pointing to it.

**Comment by Bumble0b33** [comment]
Hey @rommelfs , how did you fix this? I have the same issue - my code sample is as below but on the interface correlation is disabled. 
```
objct = event.add_object(name='email', comment='Test')
objct.add_attribute("to-display-name", value="James Doe")
```
I checked the [object definition](https://github.com/MISP/misp-objects/blob/master/objects/email/definition.json) and 'disable_correlation' is not defined so I'm assuming the default is False

**Comment by Rafiot** [comment]
The default for "to-display-name" is to have the correlation **enabled** (see below)

![Screenshot_20190726_103251](https://user-images.githubusercontent.com/248875/61938177-c7939480-af90-11e9-895c-e4413e6722cd.png)


If you pass `disable_correlation=True`, the correlation will be disabled.

**Comment by Bumble0b33** [comment]
The issue is that on MISP, correlation shows as disabled when I send in an attribute in an object.

**Comment by Rafiot** [comment]
In Sascha's case, it wasn't.

In order to go further, I'll need a sample code more complete than what you gave us (and you should open a new issue).
