### ISSUE TITLE
add_attribute_tag

### ISSUE THREAD

**Issue by deralexxx** [MISP/PyMISP#42]
Can we think about a method called add_attribute_tag, which will be a wrapper for

header will most likely be: 

def add_tag(self, attribute_id, tag):
           add_tag(attribute_id,tag,attribute=True)

Concerns or other ideas?

**Comment by Rafiot** [comment]
I'm not sure to understand your message :/

The idea is to have a way to only pass an UUID and a tag, and let MISP find out what we want to tag (event, attribute, user, org, ...). It is fairly high on @iglocska's todolist ;)

**Comment by Rafiot** [comment]
I just added this one: https://github.com/MISP/PyMISP/commit/1556c901ef186a786d5279287199d53fde8b5128 

it is the recommended way to do tagging from now on.
