### ISSUE TITLE
AttributeError: 'ExpandedPyMISP' object has no attribute 'update_sharing_group'

### ISSUE THREAD

**Issue by zeroq** [MISP/PyMISP#424]
- Recent PyMISP code issues a deprecation warning: `DeprecationWarning: Call to deprecated method change_sharing_group. (Use ExpandedPyMISP.update_sharing_group)`
- But ExpandedPyMISP does not have function to `update_sharing_group` yet
- Unfortunately deprecated function also does not work anymore, because of: `AttributeError: 'MISPEvent' object has no attribute 'SharingGroup'`

**Comment by Rafiot** [comment]
That was a bad copy paste, the method to use is `change_sharing_group_on_entity`. And the issue with the deprecated method was an other bug, and this method never worked right...

Both issues are now fixed, thanks!
