### ISSUE TITLE
Provide method to `attachClusterToEvent`

### ISSUE THREAD

**Issue by cgi1** [MISP/PyMISP#43]
Provide a method to attach `galaxies` using the API.

<img width="441" alt="bildschirmfoto 2017-01-26 um 11 09 47" src="https://cloud.githubusercontent.com/assets/18695252/22327551/13e02878-e3b8-11e6-82cc-ea3e1683c1b8.png">
<img width="731" alt="bildschirmfoto 2017-01-26 um 11 09 33" src="https://cloud.githubusercontent.com/assets/18695252/22327552/13e20ea4-e3b8-11e6-988a-fb22149f3333.png">

**Comment by Rafiot** [comment]
Doc/code: https://github.com/MISP/MISP/blob/e28cf5c17af87232ef762dccea5c7af1c7924e2f/app/Controller/GalaxiesController.php#L100

**Comment by Rafiot** [comment]
This can be mage by attaching a tag like that: 
`misp-galaxy:threat-actor="APT 29"`

With `APT 29` being the primary name. This will be changed soon to allow passing a synonym, and then, I'll create a helper in the API.
