### ISSUE TITLE
misp.search issue - 'Invalid output format.', 'url': '/attributes/restSearch/servers/getPyMISPVersion.json'

### ISSUE THREAD

**Issue by befrankt** [MISP/PyMISP#432]
Hi there, since MISP 2.4.111 (I tried with 2.4.112 as well) I am having the following issue when I run a PyMISP query:

ERROR [aping.py:72 - _check_response() ] Something went wrong (404): {'name': 'Invalid output format.', 'message': 'Invalid output format.', 'url': '/attributes/restSearch/servers/getPyMISPVersion.json'}
WARNING [api.py:103 - __init__() ] 404
ERROR [aping.py:72 - _check_response() ] Something went wrong (404): {'name': 'Invalid output format.', 'message': 'Invalid output format.', 'url': '/attributes/restSearch/attributes/describeTypes.json'}
Count: 0
{'Attribute': []}
Process finished with exit code 0`

This is my code which was previously working (The "date" value I am using wasn't working which was fixed in 2.4.111):

--------
```
from pymisp import ExpandedPyMISP
from pprint import pprint
AUTHKEY = "redacted"
URL = "https://192.168.1.103"
import os
import json
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)



def print_result(result):
    flag_printed = False
    if isinstance(result, list):
        print("Count: %s" % len(result))
        flag_printed = True
        for i in res:
            if 'Event' in i and 'Attribute' in i['Event']:
                print("  - Attribute count: %s" % len(i['Event']['Attribute']))
    elif isinstance(result, dict):
        if 'Attribute' in result:
            print("Count: %s" % len(result['Attribute']))
            flag_printed = True
        elif 'Event' in result and 'Attribute' in result['Event']['Attribute']:
            print("Attribute count: %s" % len(result['Event']['Attribute']))
            flag_printed = True
    if flag_printed:
        print('----------')
    pprint(result)


misp_url = URL + '/attributes/restSearch/'
relative_path = ''

body = {
    "returnFormat": "json",
    "debug":True,
    # "eventid": 13,
    # "limit": 1,
    "date": "[100d,200d]"
}

misp = ExpandedPyMISP(misp_url, AUTHKEY, False)
res = misp.direct_call(relative_path, body)
print_result(res)
```

**Comment by iglocska** [comment]
Just a guess: 

```
body = {
"returnFormat": "json",
"debug":True,
# "eventid": 13,
# "limit": 1,
"date": "[100d,200d]"
}
```

`"debug":True` is not valid JSON. Try `"debug":true`

**Comment by iglocska** [comment]
Never mind, just read through the rest definitely not correct what I wrote.

**Comment by iglocska** [comment]
{'name': 'Invalid output format.', 'message': 'Invalid output format.', 'url': '/attributes/restSearch/servers/getPyMISPVersion.json'}

The URL there is invalid. No idea how that happened, will have a look.

**Comment by iglocska** [comment]
OK, just had a look:

`misp_url = URL + '/attributes/restSearch/'`

This will mean that on this call:

`misp = ExpandedPyMISP(misp_url, AUTHKEY, False)`

PyMISP will use https://path/to/your/instance/attribute/restSearch as the baseurl, which is obviously incorrect.

**Comment by iglocska** [comment]
instead leave misp_url as this:

```
misp_url = URL
```

and change relative_path = '' to

```
relative_path = '/attributes/restSearch/'
```
