### ISSUE TITLE
Upload Event Object with attachment

### ISSUE THREAD

**Issue by garrit-schroeder** [MISP/PyMISP#437]
Hello,

how do i upload an MISP Object?

 obj = MISPObject("file")
        obj.add_attribute("attachment", value=base64.b64encode(attachment.payload)) ### does not work
        obj.add_attribute("filename", attachment.filename)
        obj.add_attribute("md5", attachment.md5)
        obj.add_attribute("sha1", attachment.sha1)
        obj.add_attribute("sha256", attachment.sha256)
        event.add_object(obj)

How do i add the payload of an attribute?

Cheers and thanks.

**Comment by garrit-schroeder** [comment]
Payload is in bytes
Error Message:

TypeError: Object of type 'bytes' is not JSON serializable

**Comment by garrit-schroeder** [comment]
Sorry. Just got it working.

 obj.add_attribute("attachment", value='whoami.exe', data=attachment.payload, expand='binary')

**Comment by EduardoSartorii** [comment]
Hi @garrit-schroeder  What would this code snippet be?

`data = attachment.payload`

I have the same problem.
