### ISSUE TITLE
add_tag(event...) is broken!

### ISSUE THREAD

**Issue by deralexxx** [MISP/PyMISP#44]
If you pass an event to add_tag, it will get an index error because: 

https://github.com/MISP/PyMISP/commit/2bcc4163adbe825aff5c9189c402da8c5e3da5c4

```
to_post = {'request': {'Event': {'id': event['Event']['id'], 'tag': tag}}}
```

was changed to:
```
 +            to_post = {'request': {'Event': {'id': event['id'], 'tag': tag}}} 
```

So there is a missing ['Event']

Will create a PR for it. For remove_tag it is okay.

**Comment by Rafiot** [comment]
No, this change is expected in order to be consistent with the attributes. 

This is the expected way to set a tag on an event: https://github.com/MISP/PyMISP/blob/master/examples/addtag.py#L36

**Comment by deralexxx** [comment]
hm than it is breaking every script that is been using pymisp before, that is somehow odd :/

**Comment by FloatingGhost** [comment]
It works just fine  like
```python
p = PyMISP(..)
e = p.new_event(info="taggo")
p.add_tag(e["Event"], "tlp:white")
```

It's looking for the `id` field, which is in `Event` :)

**Comment by FloatingGhost** [comment]
so yeah, as @Rafiot's link shows

**Comment by deralexxx** [comment]
yeah but this is just introduced, before it was expecting only the event.
Of course the new way works if you pass the right value, but:

a) it is not easy to understand if the parameter is called "event" but expects event["Event"]
b) breaks all scripts that are around

**Comment by FloatingGhost** [comment]
Okie, I've pushed a commit that allows for old-style `add_tag(event)` to be used, without breaking anything (I hope :^) ) - that should work for you :)

**Comment by deralexxx** [comment]
yes, looks good, thank you so much @FloatingGhost

**Comment by FloatingGhost** [comment]
Is ok, have fun <3

**Comment by Rafiot** [comment]
Well done, thank you very much :)
