### ISSUE TITLE
Error when creating MISPObject instances

### ISSUE THREAD

**Issue by robbyFux** [MISP/PyMISP#440]
...  
File "/usr/local/lib/python3.7/site-packages/pymisp/mispevent.py", line 1273, in add_attribute
    attribute.from_dict(object_relation=object_relation, **dict(self._default_attributes_parameters, **value))
  File "/usr/local/lib/python3.7/site-packages/pymisp/mispevent.py", line 1037, in from_dict
    raise NewAttributeError("The type of the attribute is required. Is the object template missing?")
pymisp.exceptions.NewAttributeError: The type of the attribute is required. Is the object template missing?

PyMisp-Version = 2.4.113

The following code generates the error. The same code is working under the Misp version <= 2.4.112 without errors.

from pymisp import MISPObject
vtobject = MISPObject(name="virustotal-report")
vtobject.add_attribute("first-submission", value="2019-08-01 12:00:00")
print(vtobject)

**Comment by Rafiot** [comment]
I forgot to release pymisp 2.4.113 on PyPi, so I assume you run it from the repository. Have you initiated and updated the submodules? The error you get is when PyMISP doesn't know the templates.

I'll release pymisp 2.4.113 on PyPi asap, when you install it from there, the templates are packaged.

**Comment by robbyFux** [comment]
I installed with pip the version 2.4.113 from the GitHub repo. Probably the Template-Package was not installed. Ok, I'm waiting for the PyPi version.

**Comment by Rafiot** [comment]
PyMISP 2.4.113 is on PyPi.
