### ISSUE TITLE
search_logs not working

### ISSUE THREAD

**Issue by carnak** [MISP/PyMISP#443]
Currently installed version… v2.4.113 (3b555ec2c78e50bce4b7006bbe0c4ac4cdaeb48f) 

When invoking the ExpandedPyMISP method "search_logs", system console returns following error:

MISPServerError: Error code 500:
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/admin\/logs\/index"}

/var/www/MISP/app/tmp/logs/error.log shows following:

2019-08-27 07:15:32 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Log.ip' in 'field list'
Request URL: /admin/logs/index
Stack Trace:
#0 /disk2/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /disk2/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Log`.`i...', Array)
#2 /disk2/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Log`.`i...', Array, Array)
#3 /disk2/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Log`.`i...', Array)
#4 /disk2/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(Log), Array)
#5 /disk2/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('all', Array)
#6 /disk2/var/www/MISP/app/Controller/LogsController.php(119): Model->find('all', Array)
#7 [internal function]: LogsController->admin_index()
#8 /disk2/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(LogsController), Array)
#9 /disk2/var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /disk2/var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(LogsController), Object(CakeRequest))
#11 /disk2/var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

**Comment by iglocska** [comment]
That is weird. Did you enable IP logging for the logging system by changing the config file by any chance?

**Comment by Rafiot** [comment]
Did you enable the setting on the MISP interface?

**Comment by Rafiot** [comment]
And what happen if you swap it to true?

**Comment by Rafiot** [comment]
Yeah, and it doesn't make much sense either.

I tried with and without the option enabled, and it works for me, so this is weird. Do you have anything in the logs on the web interface?

**Comment by Rafiot** [comment]
I don't think it is a MySQL problem per-se, but your error is probably related to the size of the response.

So you have two options:
* Increase the ram allowed to your user/that PHP can use systemwide 
* Wait for that bug to be fixed https://github.com/MISP/MISP/issues/4872 (pagination)
