### ISSUE TITLE
Add a galaxy cluster tag to an event or attribute

### ISSUE THREAD

**Issue by crowjams** [MISP/PyMISP#445]
I tried adding a connector tag to an event/attribute via the api but it does not seem to automatically add a cluster to an event/attribute.

misp = ExpandedPyMISP(misp_url,misp_key,misp_verifycert)
misp.tag("xxxx-xxxx-xx-xxx-xxxxxxxx","misp-galaxy:mitre-XXXX-XXXX='xxxx- xxxx'")

Anyone have any method to add a cluster tag to an event/attribute?
Im using the MISP_v2.4.112 version.

**Comment by Rafiot** [comment]
So what could be going wrong here is if the tag doesn't exist on the instance yet, and user of `misp_key` isn't allowed to create a tag, MISP will reject the call. 

What is the response from the server?
