### ISSUE TITLE
adding a tag to multiple attributes

### ISSUE THREAD

**Issue by dac26** [MISP/PyMISP#446]
Hi, I am a noob and I was wondering if it is possible to add a tag to multiple attributes when these are being created and added to an event, instead of waiting for them to be created and use their uuid, because if they are a lot I don't want to start calling a lot the function:

def tag(self, uuid, tag):
        """Tag an event or an attribute"""
        if not self._valid_uuid(uuid):
            raise PyMISPError('Invalid UUID')
        url = urljoin(self.root_url, 'tags/attachTagToObject')
        to_post = {'uuid': uuid, 'tag': tag}
        response = self._prepare_request('POST', url, json.dumps(to_post))
        return self._check_response(response)

I was wondering if anyone knows if it is possible to add a tag like it was a comment, because that's how I am identifying currently the attributes like so:

 misp.add_hashes_payload_delivery(parEvent, filename=None, md5=md5, sha1=sha1, sha256=sha256, ssdeep=None,
                                     **comment="VirusTotal"**, distribution=None)

    for k, v in engineFindings.items():
        name = 'Engine: ' + k + ' - Result: ' + str(v)
        event = misp.add_engine_result(parEvent, name=name, **comment="VirusTotal"**, distribution=None)

**Comment by Rafiot** [comment]
It depends how you create the attributes, but if you use `MISPEvent` or `MISPAttribute`, you have a `add_tag` method that does exactly that.

**Important point**: `MISPEvent` or `MISPAttribute` create the event or the attribute in memory locally. You need to POST it to MISP with `add_event` or `add_attribute`.

Also, I see you're using `PyMISP`. At this point, I strongly recommend you to use `ExpandedPyMISP`, PyMISP is deprecated and will go away in Q1 2020.

**Comment by lemmou** [comment]
add_tag needs the id of the attribute. How we can return the id of a created attribute ?
For example the following scenario: create an attribute then tag id with a tag ?

**Comment by Rafiot** [comment]
Which `add_tag` are you talking about? `add_tag` in `MISPEvent` and in `MISPAttribute` doesn't. `ExpandedPyMISP.tag` requires an (UU)ID.

**Comment by lemmou** [comment]
Yes i am using PyMisp.
Do you have any solution to return the id of the created attribute ?

**Comment by Rafiot** [comment]
Can you please use the `ExpandedPyMISP`instead?

I strongly recommend you to look at this tutorial file: https://github.com/MISP/PyMISP/blob/master/docs/tutorial/FullOverview.ipynb
It will make your life a lot easier.

**Comment by lemmou** [comment]
Thank you professor

**Comment by ClaraMS** [comment]
I I'm facing the same issue, I'm writing here as the post is still open.
I'm trying to add a tag either to an attribute or to the whole event, but none is working.
I tried the following;
```
api = ExpandedPyMISP('my-url', 'my-key', ssl=False, debug=None, proxies=None, cert=None)
event = api.new_event(0,4,0,("My Event"))

def create_attribute(type,value,category,comment):
    attribute = MISPAttribute()
    attribute.type = type
    attribute.value = value
    attribute.category = category
    attribute.comment = comment

    return attribute

Attribute:
        misp_attribute = create_attribute('malware-type', str(['Category']),'Payload delivery','')
        api.add_attribute(event,misp_attribute)
        api.tag(misp_attribute,"tlp:white",attribute=True)

Object:

misp_object = MISPObject('file', standalone=False)
misp_object .add_attribute('filename', type='filename',
                         value='whatever.exe',
                         Tag=[{'name': 'tlp:white'}])

event.add_object(misp_object )
res = misp.update(event)

Event:

api.add_tag(e["Event"], "tlp:white")
```
I'm not getting any error message, simply the tag is not showing up at MISP.

Thank you 
Clara

**Comment by Rafiot** [comment]
2 things to check there:
* does the tag "tlp:white" already exists on MISP? Check on `https://<domain>/tags/index/searchall:tlp:white`
* if not, you have two options:
  * enabling the taxonomy tlp: Search it on this page: `https://<domain>/taxonomies/index` (maybe on page 2)
  * Allow your user to create (`Tag Editor`) or set (`Tagger`) tags. Check user type here: `https://<domain>/admin/roles/index`

if everything seems to be working, please let me know.

**Comment by ClaraMS** [comment]
Yes, It exists:
![imagen](https://user-images.githubusercontent.com/24474498/70907129-566c8080-2008-11ea-9786-02db75d6e9c6.png)

**Comment by Rafiot** [comment]
And is the user allowed to tag? `Tagger` role.

**Comment by ClaraMS** [comment]
Yep, I'm using admin user btw but I've checked just in case.

If I put a print on that, this is what I get:

`    response = api.add_tag(event['Event'], "tlp:white")
    print("RESPONSE:" + str(response))
`
"RESPONSE:<MISPTag(name=)"

**Comment by ClaraMS** [comment]
Hi, 

Any update about this issue?

**Comment by Rafiot** [comment]
Oh, right, the tag should be visible in the response.

Does the tag already exist on the MISP instance? Is the answer is no, it probably mean that the user doesn't have the `Tag Editor` role and isn't allowed to create it.
Other wise, pelase check if your user has the `tagger` role.

**Comment by ClaraMS** [comment]
Yes, the tag exists and the user has the Tag Editor role as I've answered already ...

**Comment by Rafiot** [comment]
waaait, I gave you the wrong method...

you want to use `api.tag(e["Event"], "tlp:white")`... Sorry for that.

**Comment by ClaraMS** [comment]
If I use that method it returns the following:
"Traceback (most recent call last):
  File "misp_python.py", line 144, in <module>
    response = api.tag(event['Event'], "tlp:white")
  File "C:\Python36\lib\site-packages\pymisp\aping.py", line 2051, in tag
    uuid = misp_entity.uuid
AttributeError: 'dict' object has no attribute 'uuid'"

And then, if I change that for   api.tag(event, "tlp:white")
I'm getting an internal server error:
"Traceback (most recent call last):
  File "misp_python.py", line 144, in <module>
    response = api.tag(event, "tlp:white")
  File "C:\Python36\lib\site-packages\pymisp\aping.py", line 2056, in tag
    return self._check_response(response, expect_json=True)
  File "C:\Python36\lib\site-packages\pymisp\aping.py", line 2149, in _check_response
    raise MISPServerError(f'Error code 500:\n{response.text}')
pymisp.exceptions.MISPServerError: Error code 500:
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/tags\/attachTagToObject"}"

**Comment by Rafiot** [comment]
Right, I assume your 1st parameter is of type MISPEvent, and not dict, there is a missing test here to accept a dict and get the UUID properly

It should work if you pass that instead: `event['Event']['uuid']`

**Comment by ClaraMS** [comment]
Ok, that's it, thank you! :)

**Comment by Rafiot** [comment]
\o/ thank you for your patience!
