### ISSUE TITLE
Upload files

### ISSUE THREAD

**Issue by lemmou** [MISP/PyMISP#447]
I need to upload some files, ransom notes files or some reports to my MISP. I found that i can upload files only by the example upload.py. The problem that all loaded files has a label malware sample despite that there are not malware sample.
Any solution to upload normapl file using the PyMISP ?

Thanx

**Comment by Rafiot** [comment]
I updated the upload example script, it allows you to do it more easily, and it uses the new version of the API.

**Comment by lemmou** [comment]
Thank you professor for your update.
But compared to the previous version, in the new version i have a new error:



`.../MISP$ python3 UploadNew.py -u 'new.txt' -e 57 --is-malware
Traceback (most recent call last):
  File "UploadNew.py", line 52, in <module>
    misp.add_attribute(args.event, a)
  File "/usr/local/lib/python3.6/site-packages/pymisp/aping.py", line 376, in add_attribute
    new_attribute = self._prepare_request('POST', f'attributes/add/{event_id}', data=attribute)
  File "/usr/local/lib/python3.6/site-packages/pymisp/aping.py", line 2076, in _prepare_request
    if data:
  File "/usr/local/lib/python3.6/site-packages/pymisp/abstract.py", line 191, in __len__
    return len(self.to_dict())
  File "/usr/local/lib/python3.6/site-packages/pymisp/mispevent.py", line 298, in to_dict
    to_return['data'] = base64.b64encode(self.data.getvalue()).decode()
AttributeError: 'PosixPath' object has no attribute 'getvalue'
`

**Comment by Rafiot** [comment]
can you try without the quote around the file name?

**Comment by lemmou** [comment]
Doesn't work , the same error !!

**Comment by Rafiot** [comment]
Did you update PyMISP from git? Or from PyPi? The version on PyPI won't work.

**Comment by lemmou** [comment]
Sorry, I didn't updated anything.
I will updated.
Thx

**Comment by Rafiot** [comment]
:+1:
