### ISSUE TITLE
ExpandedPyMISP.add_attribute(event, attributeList) question

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#457]
2.4.114 using `ExpandedPyMISP`

I am trying to pass a list of `MISPAttribute` to `ExpandedPyMISP.add_attribute` to add to an existing event. The return is simply `{'Attribute': []}` and no attributes in the list have been added to that event.

My goal was to benchmark adding a large number of new attributes to an existing event comparing:
1. pulling the the event into memory and adding the attributes to that event in memory with `mispEvent.add_attribute` and then doing `misp.update_event`

vs.

2. constructing the list of attributes, and just doing `misp.add_attribute`

Can you help me see what I am doing incorrectly please. `misp.add_attribute` reports nothing added and that's true when looking in the WebUI. (for this test, the attr list has only one item)

```
(Pdb) print(mispAttrList)
[<MISPAttribute(type=('url',), value=('https//misp.load.test.com/1',))]
(Pdb) print(addedMispEvent['Event']['id'])
137062
(Pdb) list 127,130
127  	        r = misp.add_attribute(
128  	            event     = addedMispEvent['Event']['id'],
129  	            attribute = mispAttrList)
130 B->	        if isinstance(r, dict) and 'errors' in r:
(Pdb) print(r)
{'Attribute': []}
(Pdb)
```

**Comment by Rafiot** [comment]
This line look super weird:
`[<MISPAttribute(type=('url',), value=('https//misp.load.test.com/1',))]`

That should be how the print look like:
`[<MISPAttribute(type=url, value=https//misp.load.test.com/1)]`

So I assume the parameters you're passing to create the MISPAttribute are broken.

Can you give me the output of

```
print(mispAttrList[0].to_json())
```

**Comment by github-germ** [comment]
Thanks for looking at this...
```
(Pdb) print(mispAttrList[0].to_json())
{
  "category": [
    "Network activity"
  ],
  "comment": "1",
  "to_ids": [
    true
  ],
  "type": [
    "url"
  ],
  "uuid": "1494b8d0-d426-4e4c-876e-473b0695a7b2",
  "value": [
    "https//misp.load.test.com/1"
  ]
}
```

**Comment by Rafiot** [comment]
yeah, the lists in `category`, `to_ids`, `type`, and `value` are definitely wrong.

In order to help, I'll need to see how you create the attribute.

**Comment by github-germ** [comment]
[mispAddAttribute.py.txt](https://github.com/MISP/PyMISP/files/3642516/mispAddAttribute.py.txt)

**Comment by Rafiot** [comment]
yeah right, get rid of the commas at the end of the lines here:
```
            mispAttr.category = 'Network activity',
            mispAttr.value    = 'https//misp.load.test.com/%s' % (attr),
            mispAttr.type     = 'url',
            mispAttr.to_ids   = True,
            mispAttr.comment  = str(attr)

```

**Comment by github-germ** [comment]
ok, allowing lists in `add_attribute` is apparently a nice convenience with no performance gain. DONE.

```
 ./mispAddAttribute.py 4 true
successfully added event_id=161007 with numAttr=4, secs=0.3
$ ./mispAddAttribute.py 4 false
successfully added event_id=161008 with numAttr=4, secs=0.2
$ ./mispAddAttribute.py 1000 false
successfully added event_id=161009 with numAttr=1000, secs=24.9
$ ./mispAddAttribute.py 1000 true
successfully added event_id=161010 with numAttr=1000, secs=25.9
$ ./mispAddAttribute.py 5000 false
^Psuccessfully added event_id=161011 with numAttr=5000, secs=133.9
$ ./mispAddAttribute.py 5000 true
successfully added event_id=161012 with numAttr=5000, secs=132.7
$
```
