### ISSUE TITLE
inconsistent returns from ExpandedPyMISP.add_attribute

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#459]
Would it be possible to have one consistent format returned from `ExpandedPyMISP.add_attribute`? It seems to vary depending on whether the `attribute` argument is a `list` of not, and based on the mix of successes and failures in the case of a `list`.

I've observed the following 3 cases:

1. when only including one attribute for `add_attribute`:
```
  {
    'errors':
    (
      403,
      {
       	'name': 'Could not add Attribute',
        'message': 'Could not add Attribute',
        'url': '/attributes/add',
        'errors':
        {
          'value':
          [
            'A similar attribute already exists for this event.'
          ]
	}
      }
    )
  }
```

2. with multiple attrs, and all failures
```
  {
    'errors':
    (
      403,
      {
        'name': 'Could not add Attribute',
        'message': 'Could not add Attribute',
        'url': '/attributes/add',
	'errors':
	{
          'attribute_0':
          {
            'value':
            [
              'A similar attribute already exists for this event.'
            ]
          },
	  ...
        }
      }
    )
  }
```

3. with multiple attrs, some succeed, others fail
```
  {
    'Attribute:
    {
      'id': ...,
      ...
    },
    'AttributeTag: [],
    'errors':
    {
      'attribute_0':
      {
       	'value':
	[
          'A similar attribute already exists for this event.']
	]
      },
      ...
    }
  }
```

**Comment by Rafiot** [comment]
Case 1 and 2 are working as expected, case 3 was already fixed some times ago (tag is embedded in the attribute).

The output if pretty consistent, if you pass a list, you receive a list in the output. Please let us know if you want something different.

**Comment by github-germ** [comment]
It would just be nice if there was one normalized return no matter if calling with a list of a single attribute. Makes the code testing the return to detect and react much simpler.

**Comment by Rafiot** [comment]
well, we cannot break the existing output because other people already rely on it.

If you pass `pythonify=True`, you will get something easier to test against.

But I have no good news here, if you add a list of attributes, your test case will have to expect a list of responses, if you pass a single parameter, it will get a single response.

**Comment by github-germ** [comment]
Understood. Thx for the info!!
