### ISSUE TITLE
Help creating, using a custom MISPObject via PyMISP

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#477]
Where can I find documentation to help me write a PyMISP script to define and then use a custom MISP Object to ingest data from a file. Want to drive everything in a script (i.e. is that possible without doing any WebUI clicks?)...

1. Create a custom MISP Object via PyMISP
1. Instantiate that `MISPObject` template by name
1. Populate that template `MISPObject`
1. Add that `MISPObject` to an event

-- o --

Followup question: If we create a template in the WebUI and can see it on `https://localhost/templates/view/8` for example, other than populating an existing Event in the WebUI with that template, where else can it be used, e.g. can it be added locally to the MISP-known template object list, can it be utilized anywhere else on the WebUI (e.g. add feed), how about from PyMISP?

THANKS!!

**Comment by Rafiot** [comment]
There are quite a few options, and you can find examples here: https://github.com/MISP/PyMISP/blob/master/docs/tutorial/FullOverview.ipynb

PyMISP supports all templates from misp-objects, and you can use your own user defined templates too (see link above).

If you need more details, please give me a few more information about what you what to do, especially the current format of the data you want to import.

**Comment by github-germ** [comment]
@Rafiot ... Thanks for your swift reply!

We are flexible on finding the best method to accomplish this. We are exploring what's possible and what's not as we build the design. Thanks for assisting...

**Our Use Case**
* We have an input CSV which we need to ingest into an event as a list of MISP Objects.
* We'd prefer that that MISP Object be defined in `misp-objects` (vs. a PyMISP runtime object defined on each execution).
   * Would prefer to create that `misp-object` via PyMISP, but can do manually if that's the only way -- just need a few more instruction details (see below).
   * Want that object to then be accessible by name in PyMISP apps that will ingest from a feed.
   * Would be cool if that known object could then be used  in Event View `Populate from...` in the WebUI.
   * Would be nice if that object could also be used in `Add Feed` -- future feature?

**Questions**
1. Where are the instructions to install our own `misp-object` and make it available in both the WebUI and PyMISP?
   * e.g. I see how to create the `definition.json`. Do we just `mkdir /var/www/MISP/app/files/misp-objects/objects/OUR-CUSTOM-OBJECT/` and put the `definition.json` in there?
1. Is there a way to create a custom object from PyMISP or must it basically be done manually as above?
1. When we do `Add template` in the WebUI is there a way to add that to the known `misp-objects` and then accessible by name in PyMISP?

### T H A N K S !!

**Comment by github-germ** [comment]
OK, read `mispevent.py` and I have a prototype working. Seemed liked reading your code was the only way to connect the dots. :-)

Of course, I'll take you feedback when you have time. Thanks.

**Comment by Rafiot** [comment]
Oh. Never mind, it is a valid category. I totally missed that.

So I think MISP doesn't select a default category from the list in the object template (if provided), when the object is created over the API. That list is displayed on the web interface.

So what I need to do is to add that feature in PyMISP. I'll try to implement that asap, but no promises, as we have hack.lu next week and I'm pretty busy.

The way to go right now for you is to pass the category `Attribution` when you call `add_attribute`, it will work as well.

**Comment by github-germ** [comment]
> So what I need to do is to add that feature in PyMISP. I'll try to implement that asap, but no promises, as we have hack.lu next week and I'm pretty busy.

Take your time. We can wait. Thanks!

**Comment by github-germ** [comment]
thanks again!!
