### ISSUE TITLE
MITRE Mapping via API

### ISSUE THREAD

**Issue by mohlcyber** [MISP/PyMISP#479]
Hi Guys,
quick question. I wrote an integration between the McAfee Advanced Threat Defense that pushed threat intel to MISP (https://github.com/mohlcyber/OpenDXL-ATD-MISP). Just updated the integration to use the newest PyMISP libraries.
As part of the analysis result I am also receiving MITRE techniques. I would like to use the MITRE information i receive from McAfee ATD also in MISP. Is there any API expose to add the MITRE techniques to a MISP event? I couldn't find anything in the libs as well as in the examples. I would like to highlight the findings here:
 
<img width="1253" alt="Screenshot 2019-10-15 at 11 39 53" src="https://user-images.githubusercontent.com/25227268/66820204-8633d500-ef40-11e9-86ba-425949f3ac1e.png">

Any ideas? Many thanks and all the best,
Martin

**Comment by Rafiot** [comment]
Internally, the ATT&CK matrix is using the tags the same way the galaxies do, so that's the way to go: Use the tag and attach it. But it definitely misses helpers.

**Comment by mohlcyber** [comment]
Excellent thanks, That helped. I just released a new version on my Github that includes the MITRE galaxy tagging. Thanks again for your support.
