### ISSUE TITLE
PyMISP / MISP version mismatches

### ISSUE THREAD

**Issue by carnak** [MISP/PyMISP#481]
Hello - I first want to thank those who created, and continue to enhance MISP, as it is an incredibly enabling platform that all in our industry should be using / supporting.

Back to subject issue - I have updated our MISP instance to v2.4.117, but it seems the latest version of PyMISP available on github is version 2.4.114, as of today.  My issue with this scenario is that my PyMISP scripts constantly warn like so:

WARNING [aping.py:81 - __init__() ] The version of PyMISP recommended by the MI)SP instance (2.4.117) is newer than the one you're using now (2.4.114). Please upgrade PyM
ISP.

Yet when I try to update PyMISP, pip responds with:

$ pip3 install --trusted-host pypi.org --trusted-host files.pythonhosted.org --upgrade pymisp
Requirement already up-to-date: pymisp in /usr/lib/python3.6/site-packages (2.4.114)

I have python scripts that echo out information of interest while running, but it is difficult to find the results I am looking for, as they are intermixed with all of these warnings, e.g.:

added attribute from ego_node to common_attributes - zz.bdstatic.com for node: 34971
added attribute from ego_node to common_attributes - zz.connextra.com for node: 34971
added attribute from ego_node to common_attributes - zz44smpc.micpn.com for node: 34971
added attribute from ego_node to common_attributes - zzmibqlk.github.stackblitz.io for node: 34971
WARNING [aping.py:81 - __init__() ] The version of PyMISP recommended by the MI)SP instance (2.4.117) is newer than the one you're using now (2.4.114). Please upgrade PyM
ISP.
added edge: krakow.pl for network: n/a
added common_attribute edge krakow.pl for node: 19571
WARNING [aping.py:81 - __init__() ] The version of PyMISP recommended by the MI)SP instance (2.4.117) is newer than the one you're using now (2.4.114). Please upgrade PyM
ISP.
added edge: 1fichier.com for network: n/a
added common_attribute edge 1fichier.com for node: 220
WARNING [aping.py:81 - __init__() ] The version of PyMISP recommended by the MI)SP instance (2.4.117) is newer than the one you're using now (2.4.114). Please upgrade PyM
ISP.
added edge: mybestdc.com for network: n/a
added common_attribute edge mybestdc.com for node: 34622
WARNING [aping.py:81 - __init__() ] The version of PyMISP recommended by the MI)SP instance (2.4.117) is newer than the one you're using now (2.4.114). Please upgrade PyM
ISP.
WARNING [aping.py:81 - __init__() ] The version of PyMISP recommended by the MI)SP instance (2.4.117) is newer than the one you're using now (2.4.114). Please upgrade PyM
ISP.
found domain|ip: captainblack.pro|178.159.36.91
WARNING [aping.py:81 - __init__() ] The version of PyMISP recommended by the MI)SP instance (2.4.117) is newer than the one you're using now (2.4.114). Please upgrade PyM
ISP.

Hope all of that makes sense, and this is not a big problem, just a minor irritant.

p.s. - Is the MISP team coming to the states this year, or maybe next for training events?  I would love to attend your MISP training events, but don't want to travel far.

Thanks!!!
Alan

**Comment by Rafiot** [comment]
Woops, right, I forgot to bump the package on pypi. Doing it now.

**Comment by Rafiot** [comment]
Done now, pymisp v 2.4.117 is on pypi.
