### ISSUE TITLE
Export event  in JSON enclosed in an 'Event' key

### ISSUE THREAD

**Issue by gallypette** [MISP/PyMISP#489]
Hi,

Is see [here](https://github.com/MISP/PyMISP/blob/87fd06a8893feafaffd461d6d611be4d02e5a4a2/pymisp/mispevent.py#L542) that the Event key is stripped when loading a json event from MISP.

But to_json does not add it back. It would be useful to have a function to add it back because when creating a feed for MISP, MISP can not import the feed's events without it.

**Comment by Rafiot** [comment]
Hmmm The problem is that every other method strips that, and re-adding it now is going to break every code written in the last 3-4 months.

That should be added in the script creating the feed.
