### ISSUE TITLE
[Tests] Add test for DB schema diagnostic

### ISSUE THREAD

**Issue by mokaddem** [MISP/PyMISP#492]
PR #5002 introduce a Database schema diagnostic.
I could be great to have a unit test for this one during the installation process to spot inconsistency between the expected schema and the actual one.
The endpoint is 
```
GET
/servers/dbSchemaDiagnostic
Content-Type: application/json
```

**Comment by Rafiot** [comment]
On a broader note: would it make sense to have a test suite that doesn't touch the data in MISP, but just run a bunch of sanity checks against an instance we could ask people to run when they have problems?

This one seems to be a good one to have in it, but what are the other ones? Right now, I'm thinking  of checking if workers are running for example.
@iglocska that one is also relevant for you.

**Comment by iglocska** [comment]
Yeah, that's kind of what the diagnostic page does along with its output.
Bunch of sanity checks / detection of misconfigurations.

**Comment by Rafiot** [comment]
The advantage of the script is that it could generate a text they can send us. But we could have something similar on the diagnostic page that doesn't contains everything as it does now.

**Comment by iglocska** [comment]
I mean that was the intent of the diagnostic page's download feature. It
does however include some things we may want to sanitise, but that's
exactly why it's there, we've used it in the past as something they can
just dump and send to us directly. Modules kind of messed with that as they
may include API keys and the like these days.
