### ISSUE TITLE
Clarification on the "deleted" keyword arg to the search function

### ISSUE THREAD

**Issue by fhightower** [MISP/PyMISP#493]
Hi! According to the documentation (https://pymisp.readthedocs.io/modules.html#pymisp.PyMISP.search), adding the `deleted` keyword argument to the `PyMISP.search` function "also return[s] the deleted attributes".

When I read this, I expected the `deleted` keyword (as shown in the example code below) to return *both* deleted *and also* existing (non-deleted) attributes

```python
from pymisp import PyMISP
misp = PyMISP(url, key, False, 'json')

response = misp.search(
    last='365d',
    deleted=True
)
```

When I run a search like this ^, however, it does not return existing attributes; only the deleted ones.

So, when the documentation describes the deleted keyword as one which "also return[s] the deleted attributes", does the "also return" mean that I should expect the existing attributes and also the deleted ones **or** does the "also return" mean that a query with the `deleted` keyword returns event data and also the deleted attributes?

**Comment by iglocska** [comment]
That behaviour was changed a while ago sounds like the documentation is outdated. Pass [0, 1] as the value for the deleted filter and it will return both deleted and not deleted data.

**Comment by fhightower** [comment]
Thank you for the quick response @iglocska !

That works:

```
response = misp.search(
    last='365d',
    deleted=[0, 1]
)
```

Would you like me to keep this issue open to update documentation?

**Comment by fhightower** [comment]
I'm working with an older pymisp version (around `2.4.95.1`) and have encountered a similar issue with the `published` flag in `PyMISP.search` function.

If you want to return both published _and_ unpublished events, you need to do:

```python
from pymisp import PyMISP
misp = PyMISP(url, key, False, 'json')

response = misp.search(
    last='365d',
    published=[0, 1]
)
```

**Comment by fhightower** [comment]
Also, don't keep this issue open for me. I'm only keeping it open in case documentation needs to be updated. If not, feel free to close it.

**Comment by iglocska** [comment]
Thanks for the feedback, will close it. The documentation in MISP directly should reflect this already since the initial report, but if we run into new issues with it being confusing we'll think about how to improve the documentation to make it a bit more obvious.
