### ISSUE TITLE
Is it possible to get explanation of Threat Level, Distribution, and Analysis levels

### ISSUE THREAD

**Issue by todonaki** [MISP/PyMISP#494]
From the documentation, I see that the levels for each of the attributes we are setting are as follows:

> threatlevel – Threat level(s) (1,2,3,4) | str or list
> distribution – Distribution level(s) (0,1,2,3) | str or list
> analysis – Analysis level(s) (0,1,2) | str or list

For example, I've from the documentation that threatlevel (threat_level_id) is mapped as follows:

> 0 = high
> 1 = medium
> 2 = low
> 3 = undefined

Is it possible to get what each of the levels mean for distribution, and analysis?

I've searched all of the documentation and cant seem to find anything that explains.  I'd like to get a more comprehensive explanation l that I can share with others in my organisation who are using PyMISP to add events to our feed.

**Thank you!**

**Comment by Rafiot** [comment]
You can find the documentation here: https://www.circl.lu/doc/misp/using-the-system/#creating-an-event.

Note that `threatlevel` and `analysis` can be considered as deprecated in favor of the tags, which are lot more flexible.

**Comment by todonaki** [comment]
Thank you very much for that Rafiot.
