### ISSUE TITLE
Advanced extraction in ExpandedPymisp

### ISSUE THREAD

**Issue by AndersonLT** [MISP/PyMISP#496]
How do i upload a sample with advanced extraction in the new API ? i usually used upload_sample with advanced_extraction=True, how do i do this now ?

**Comment by mokaddem** [comment]
Hey,
To upload sample you can use ``MISPEvent.add_attribute`` with the ``expand='binary'`` key

**Comment by Rafiot** [comment]
Is it implemented in MISP yet? If not, you also need to run (it requires lief): 
https://github.com/MISP/PyMISP/blob/b1818b1751021fc82805524706352b0a8eb77249/pymisp/mispevent.py#L832

**Comment by mokaddem** [comment]
Well, it's coming from there
https://github.com/MISP/PyMISP/blob/c5dfa9b5090de50d782f1903455a4d4b604c072e/tests/testlive_comprehensive.py#L1068
https://github.com/MISP/PyMISP/blob/11d7ede2a27e8087470d3ca92c2f627f4d251330/pymisp/api.py#L1016

**Comment by Rafiot** [comment]
Yes, because it was supposed to be implemented at some point. I'm not sure if it was.

**Comment by mokaddem** [comment]
Oh I see. I thought that it was already working due to the deprecate notice..

**Comment by Rafiot** [comment]
It was supposed to be implemented that week, originally.

@iglocska is upload_sample on the deprecated list? Or should I update that?

**Comment by AndersonLT** [comment]
Using @Rafiot issue fixed that, i will close this issue for now.
