### ISSUE TITLE
Search results differences between PyMISP and ExpandedPyMISP

### ISSUE THREAD

**Issue by andurin** [MISP/PyMISP#497]
Hi,

I'll try to get all Events which have a specific Tag and of course I tried using ExpandedPyMISP but it serves me "all" events, not only the expected one which I tagged.

ExpandedPyMISP differs in that way that nearly all allowed parameters will be set. Why and which is the one that invalids my wanted tags Filter?

Using PyMISP:
```
In [18]: events = misp.search('events', tags="OpenCTI:Import")                                                                                                                                                     
/ipython:1: DeprecationWarning: Call to deprecated method search. (Use ExpandedPyMISP.search) -- Deprecated since version 2.4.111.
DEBUG [api.py:155 - _prepare_request() ] POST - http://misp.example.com/events/restSearch
DEBUG [api.py:157 - _prepare_request() ] {"tags": ["OpenCTI:Import"], "returnFormat": "json"}
DEBUG [api.py:183 - _prepare_request() ] {'User-Agent': 'PyMISP 2.4.117.2 - Python 3.7.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '52', 'Authorization': 'LOLOMAT', 'content-type': 'application/json'}
```

Above gives me exactly one Event - as expected.

Now using ExpandedPyMISP:

```
In [21]: events = misp.search('events', tags="OpenCTI:Import")                                                                                                                                                     
DEBUG [aping.py:2192 - _prepare_request() ] POST - http://misp.example.com/events/restSearch
DEBUG [aping.py:2194 - _prepare_request() ] {'returnFormat': 'json', 'page': None, 'limit': None, 'value': None, 'type': None, 'category': None, 'org': None, 'tags': 'OpenCTI:Import', 'quickFilter': None, 'from': None, 'to': None, 'eventid': None, 'withAttachments': 0, 'metadata': 0, 'uuid': None, 'published': None, 'enforceWarninglist': 0, 'deleted': None, 'includeEventUuid': 0, 'includeEventTags': 0, 'sgReferenceOnly': 0, 'eventinfo': None, 'searchall': None, 'requested_attributes': None, 'includeContext': 0, 'headerless': 0, 'includeSightings': 0, 'includeCorrelations': 0}
DEBUG [aping.py:2219 - _prepare_request() ] {'User-Agent': 'PyMISP 2.4.117.2 - Python 3.7', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '267', 'Authorization': 'LOLOMAT', 'content-type': 'application/json'}
```

Regards,
Hendrk

**Comment by Rafiot** [comment]
Can you tell me which version of PyMISP you're using, please? Because the `None` entries should be removed: https://github.com/MISP/PyMISP/blame/master/pymisp/aping.py#L2200
And that was added 4 months ago.

**Comment by andurin** [comment]
2.4.117.2

Am 20. November 2019 14:28:59 MEZ schrieb "Raphaël Vinot" <notifications@github.com>:

**Comment by Rafiot** [comment]
Oh, right, ok, the debug message is not what is sent to the server (the `None` entries are removed after the print).

Can you try to do that : `events = misp.search('events', tags=["OpenCTI:Import"])`, just in case?

**Comment by andurin** [comment]
Just wrap the Filter in a list? I'm not sure, but i think i did it during my tests. Will recheck tomorrow.

**Comment by Rafiot** [comment]
It is clearly a thing that should be handled by PyMISP/MISP, but I'm curious if that solves it.

**Comment by andurin** [comment]
Erm... restarted all of my test env to give it to a clean state - what should I say? Works as expected.

I'm using the same code as yesterday so as a Supporter I would say a typical: "Problem with narrowing disappeared."

Sorry for the noise.

**Comment by Rafiot** [comment]
No problem, please let us know if the problem occurs reappears.
