### ISSUE TITLE
setup: python >= 3.6 not explicitly required

### ISSUE THREAD

**Issue by wagner-certat** [MISP/PyMISP#501]
I just noticed that the python version requirement (>= 3.6) is *not* in the packages' metadata despite it is required in the current versions. For docs see: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

```python
python_requires='>=3.6',
```

This is missing in various already released versions, but can still be applied for those too. The entry as the advantage that for users running older python versions pip installed the latest compatible version instead of a broken one (raising SyntaxErrors).

Also: Reading the changelogs I could not determine the last version compatible with python < 3.6. I would have expected a clear changelog message for such a change.

**Comment by Rafiot** [comment]
The latest version is still compatible with Python 2.7. The incompatible classes (ExpandedPyMISP for example) are not importable and will raise an ImportError. If you get a syntax error, it's because I need to make more classes not importable.

**Comment by wagner-certat** [comment]
```python
    from pymisp.tools import feed_meta_generator
  File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/pymisp/tools/feed_meta_generator.py", line 19
    hashes += [f'{h},{event.uuid}' for h in event.attributes_hashes('md5')]
                                 ^
SyntaxError: invalid syntax
```
same for python 3.5

**Comment by Rafiot** [comment]
Ok, I assumed this line was doing the trick: https://github.com/MISP/PyMISP/blob/master/pymisp/tools/__init__.py#L24

I'll find an other solution then, but it is expected that this method *requires* python 3.6+.

**Comment by wagner-certat** [comment]
> Ok, I assumed this line was doing the trick:

You would need to hide the complete `feed_meta_generator` module, or call it differently.

**Comment by Rafiot** [comment]
oh, right

**Comment by Rafiot** [comment]
Fixed: https://github.com/MISP/PyMISP/commit/4fed55a09ded9f0007c92c52a67bb21282dfc567
