### ISSUE TITLE
Could not add Attribute (add_attribute)

### ISSUE THREAD

**Issue by ClaraMS** [MISP/PyMISP#503]
Hi, 

I'm trying to add multiple events to misp with multiple attributes and misp objects but when I try to add 2 or more attributes with the same value fails with the following error:

> ERROR [aping.py:2158 - _check_response() ] Something went wrong (403): {'name': 'Could not add Attribute', 'message': 'Could not add Attribute', 'url': '/attributes/add', 'errors': {'value': ['A similar attribute already exists for this event.']}}

This happens too with duplicated attributes in MISPObjects:

> ERROR [aping.py:2158 - _check_response() ] Something went wrong (403): {'name': 'Could not add object', 'message': 'Could not add object', 'url': '/objects/add/1757/', 'errors': 'Could not save object as at least one attribute has failed validation (text). {"uuid":["The UUID provided is not unique"]}'}

This is part of my code:

```
def create_attribute(type,value,category,comment):
    attribute = MISPAttribute()
    attribute.type = type
    attribute.value = value
    attribute.category = category
    attribute.comment = comment

    return attribute
api = ExpandedPyMISP('https://x.x.x.x.', 'xxxx', ssl=False, debug=None, proxies=None, cert=None)
 event = api.new_event(0,4,0,("[Event]"+ " " + "Event example))

# for loop
api.add_attribute(event,create_attribute('other',str(key['Name']),'Artifacts dropped',str('DELETED')))
misp_object = MISPObject('file', standalone=False)
misp_object.add_attribute('path', value=str(key['sources'][source]['@process']))
misp_object.add_attribute('filename', value=str(key['@desc']))
misp_object.add_attribute('text', value=str(key['sources'][source]['$']))
misp_object.add_attribute('text', value=str('null'))

response = api.add_object(event,misp_object)

# outside the for loop 
add_event = api.add_event(event)

```

This code is inside a for loop, thats the reason why I have and want repeated attributes, some of them have different categories or comments even if the value is the same.

I've checked this issue which looks similar to mine: https://github.com/MISP/MISP/issues/3897 
But the issue is not a warning now, is an ERROR causing the attribute not being added to the event, so none of those examples are valid anymore.

I'm using the last version of PyMisp and python 3.6
Maybe I'm not using it the right way :/

**Comment by Rafiot** [comment]
So you can't have the same value for multiple attributes in the same MISP event, it doesn't makes much sense in the MISP datamodel, so it's not supported (and will not be). I'd recommend to use tags in that case, but can you give me more details on what you're trying to accomplish, please? Maybe there is an other approach.

For the second error, it complains about the UUID being the same, my guess is that you create a MISPObject somewhere outside of the loop, and add the same one multiple time, but to be sure, I'll need to see more of your code. Can you add more of your script in this issue, please?

**Comment by ClaraMS** [comment]
Ok so it is not supported, then there is no other option than search for an alternative.

There are some cases in which we will want to repeat an attribute name, for example in a yara rule or in a dropped file . 
We have a json with different information about malware samples that we want to share in MISP to correlate with other samples already uploaded.

For example, we have the following information : 
 signature name: Sample reads its own file content
 process name: %USERPROFILE%\Desktop\backup.exe

And then that same process will appear in other signatures or as a dropped file. In this point it fails as the process name is already in MISP as part of a yara rule or as part of a dropped file or simple as the filename.
This happens also because we have different sources of data for the same sample like different output from sandboxes but they all refer to the same sample.

So I'm thinking about adding the process name as a Tag as you suggested or as a comment to the attribute for example.

The error for the UUID is already solved thank you!

**Comment by Rafiot** [comment]
Oh, right, I see.

Soo, for the yara rules, I'd recommend to create yara objects, and maybe for a dropped file, a file object? You can have attributes with the same value if they are in different objects.

Would that work for you?

**Comment by ClaraMS** [comment]
I think thats the problem I'm having here, when it tries to add an object with an attribute with the same value as other in the event it fails:

> 
ERROR [aping.py:2158 - _check_response() ] Something went wrong (404): {'name': 'Event already exists, if you would like to edit it, use the url in the location header.', 'message': 'Event already exists, if you would like to edit it, use the url in the location header.', 'url': '/events'}

But if it should be possible to have attributes with the same value in different objects then I'm probably doing something wrong in my code.

**Comment by Rafiot** [comment]
I think you're calling `add_event` instead of `update_event`(MISP is complaining that the UUID of the event already exists).

**Comment by ClaraMS** [comment]
Oh, I see... OK I think now I have more clear the purpose of some of the functions of PyMISP and what can I do or can not.

Thank you very much for your help! :)

**Comment by Rafiot** [comment]
You're welcome!
