### ISSUE TITLE
STIX 1.x XML import via WebUI fail after update to v2.4.119

### ISSUE THREAD

**Issue by mrdthomas** [MISP/PyMISP#504]
Hello,

After updating PyMISP from v2.4.113 to v2.4.119, importing STIX 1.x XML files fail with following error in browser:

> Could not import STIX document: Issues executing the ingestion script or invalid input. Please check whether the dependencies for STIX are met via the diagnostic tool.

When checking exec-errors.log the following error is reported:

> WARNING [__init__.py:56 - <module>() ] Unable to load pymisp properly: No module named 'deprecated'
> Traceback (most recent call last):
>   File "/var/www/MISP/app/files/scripts/stix2misp.py", line 39, in <module>
>     from pymisp.mispevent import MISPEvent, MISPObject, MISPAttribute
>   File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 15, in <module>
>     from deprecated import deprecated
> ModuleNotFoundError: No module named 'deprecated'

The issue was first noticed after updating MISP from MISP 2.4.111 to MISP 2.4.119. 

Then a STIX import test was performed on a MISP 2.4.113 instance with PyMISP 2.4.113 with success. After updating PyMISP to the latest version, STIX imports fail. 

So it seems that updating MISP to the latest version or only updating PyMISP causes this error.

Any assistance would be appreciated.

**Comment by Rafiot** [comment]
That's what the error message says: you need to install the `deprecated` package (as listed in the package: https://github.com/MISP/PyMISP/blob/master/setup.py#L44).

Then it will work again.

**Comment by mrdthomas** [comment]
Thank you! I will do that as soon as I can.

**Comment by mrdthomas** [comment]
After getting deprecated installed I am now able to import some STIX files but others fail with the following UnicodeDecodeError in exec-errors.log:

> /var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'VocabList' object.
>   warnings.warn(msg)
> /var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'str' object.
>   warnings.warn(msg)
> /var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'datetime' object.
>   warnings.warn(msg)
> TOUMarking:TermsOfUseMarkingStructureType
> Traceback (most recent call last):
>   File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1446, in <module>
>     main(sys.argv)
>   File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1441, in main
>     stix_parser.build_misp_event(event)
>   File "/var/www/MISP/app/files/scripts/stix2misp.py", line 87, in build_misp_event
>     self.build_misp_dict(event)
>   File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1206, in build_misp_dict
>     self.parse_external_observable(self.event.observables.observables)
>   File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1317, in parse_external_observable
>     attribute_type, attribute_value, compl_data = self.handle_attribute_type(properties, title=title)
>   File "/var/www/MISP/app/files/scripts/stix2misp.py", line 229, in handle_attribute_type
>     return self.attribute_types_mapping[xsi_type](*args)
>   File "/var/www/MISP/app/files/scripts/stix2misp.py", line 632, in handle_pe
>     pe_uuid = self.parse_pe(properties)
>   File "/var/www/MISP/app/files/scripts/stix2misp.py", line 645, in parse_pe
>     header_object = MISPObject('pe-section', misp_objects_path_custom=_MISP_objects_path)
>   File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 1299, in __init__
>     self._set_template(kwargs.get('misp_objects_path_custom'))
>   File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 1362, in _set_template
>     self._known_template = self._load_template_path(self.misp_objects_path / self.name / 'definition.json')
>   File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 1335, in _load_template_path
>     self._definition = self._load_json(template_path)
>   File "/var/www/MISP/PyMISP/pymisp/abstract.py", line 110, in _load_json
>     data = load(f)
>   File "/usr/lib/python3.6/json/__init__.py", line 296, in load
>     return loads(fp.read(),
>   File "/var/www/MISP/venv/lib/python3.6/encodings/ascii.py", line 26, in decode
>     return codecs.ascii_decode(input, self.errors)[0]
> **UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2310: ordinal not in range(128)**



I've tried various methods of searching for non-ASCII in this [US-CERT](https://www.us-cert.gov/sites/default/files/publications/MAR-10135536-8.v2.stix.xml) XML STIX file with no luck.

Any idea what I could be missing?

Thanks in advance.

**Comment by bernhardreiter** [comment]
It seems pymisp does not like the non-ascii files in the object templates

data/misp-objects/objects/pe-sect
ion/definition.json has
```json
   "offset": {
      "description": "Section’s offset",
      "disable_correlation": true,
      "ui-priority": 1,
      "misp-attribute": "hex"
    },
    "virtual_address": {
      "description": "Section’s virtual address",
      "disable_correlation": true,
      "ui-priority": 1,
      "misp-attribute": "hex"
    },
    "virtual_size": {
      "description": "Section’s virtual size",
```
the aprostroph of "Section’s" is the problematic character. (I don't know why or why this special template is used. You could try to remove the three chars)

**Comment by Rafiot** [comment]
This is very weird, because it works for me:

```
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import json

In [2]: with open('definition.json') as f:
   ...:     a = json.load(f)
   ...:     

In [3]: a
Out[3]: 
{'requiredOneOf': ['text',
  'name',
  'md5',
  'sha1',
  'sha224',
  'sha256',
  'sha384',
  'sha512',
  'sha512/224',
  'sha512/256'],
 'attributes': {'md5': {'description': '[Insecure] MD5 hash (128 bits)',
   'ui-priority': 1,
   'misp-attribute': 'md5',
   'recommended': False},
  'sha1': {'description': '[Insecure] Secure Hash Algorithm 1 (160 bits)',
   'ui-priority': 1,
   'misp-attribute': 'sha1',
   'recommended': False},
  'sha224': {'description': 'Secure Hash Algorithm 2 (224 bits)',
   'ui-priority': 0,
   'misp-attribute': 'sha224',
   'recommended': False},
  'sha256': {'description': 'Secure Hash Algorithm 2 (256 bits)',
   'ui-priority': 1,
   'misp-attribute': 'sha256'},
  'sha384': {'description': 'Secure Hash Algorithm 2 (384 bits)',
   'ui-priority': 0,
   'misp-attribute': 'sha384',
   'recommended': False},
  'sha512': {'description': 'Secure Hash Algorithm 2 (512 bits)',
   'ui-priority': 1,
   'misp-attribute': 'sha512'},
  'sha512/224': {'description': 'Secure Hash Algorithm 2 (224 bits)',
   'ui-priority': 0,
   'misp-attribute': 'sha512/224',
   'recommended': False},
  'sha512/256': {'description': 'Secure Hash Algorithm 2 (256 bits)',
   'ui-priority': 0,
   'misp-attribute': 'sha512/256',
   'recommended': False},
  'ssdeep': {'description': 'Fuzzy hash using context triggered piecewise hashes (CTPH)',
   'ui-priority': 0,
   'misp-attribute': 'ssdeep'},
  'entropy': {'description': 'Entropy of the whole section',
   'disable_correlation': True,
   'ui-priority': 0,
   'misp-attribute': 'float'},
  'name': {'description': 'Name of the section',
   'disable_correlation': True,
   'sane_default': ['.rsrc', '.reloc', '.rdata', '.data', '.text'],
   'ui-priority': 1,
   'misp-attribute': 'text'},
  'size-in-bytes': {'description': 'Size of the section, in bytes',
   'disable_correlation': True,
   'ui-priority': 1,
   'misp-attribute': 'size-in-bytes'},
  'offset': {'description': 'Section’s offset',
   'disable_correlation': True,
   'ui-priority': 1,
   'misp-attribute': 'hex'},
  'virtual_address': {'description': 'Section’s virtual address',
   'disable_correlation': True,
   'ui-priority': 1,
   'misp-attribute': 'hex'},
  'virtual_size': {'description': 'Section’s virtual size',
   'disable_correlation': True,
   'ui-priority': 1,
   'misp-attribute': 'size-in-bytes'},
  'text': {'description': 'Free text value to attach to the section',
   'disable_correlation': True,
   'ui-priority': 1,
   'misp-attribute': 'text',
   'recommended': False},
  'characteristic': {'description': 'Characteristic of the section',
   'sane_default': ['read', 'write', 'executable'],
   'ui-priority': 0,
   'misp-attribute': 'text'}},
 'version': 3,
 'description': 'Object describing a section of a Portable Executable',
 'meta-category': 'file',
 'uuid': '198a17d2-a135-4b25-9a32-5aa4e632014a',
 'name': 'pe-section'}
```

**Comment by Rafiot** [comment]
And for sake of completeness, with python 3.6:

```
$ (git::master) python3
Python 3.6.10 (default, Dec 19 2019, 23:04:32) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> with open('definition.json') as f:
...     a = json.load(f)
... 
>>> a
{'requiredOneOf': ['text', 'name', 'md5', 'sha1', 'sha224', 'sha256', 'sha384', 'sha512', 'sha512/224', 'sha512/256'], 'attributes': {'md5': {'description': '[Insecure] MD5 hash (128 bits)', 'ui-priority': 1, 'misp-attribute': 'md5', 'recommended': False}, 'sha1': {'description': '[Insecure] Secure Hash Algorithm 1 (160 bits)', 'ui-priority': 1, 'misp-attribute': 'sha1', 'recommended': False}, 'sha224': {'description': 'Secure Hash Algorithm 2 (224 bits)', 'ui-priority': 0, 'misp-attribute': 'sha224', 'recommended': False}, 'sha256': {'description': 'Secure Hash Algorithm 2 (256 bits)', 'ui-priority': 1, 'misp-attribute': 'sha256'}, 'sha384': {'description': 'Secure Hash Algorithm 2 (384 bits)', 'ui-priority': 0, 'misp-attribute': 'sha384', 'recommended': False}, 'sha512': {'description': 'Secure Hash Algorithm 2 (512 bits)', 'ui-priority': 1, 'misp-attribute': 'sha512'}, 'sha512/224': {'description': 'Secure Hash Algorithm 2 (224 bits)', 'ui-priority': 0, 'misp-attribute': 'sha512/224', 'recommended': False}, 'sha512/256': {'description': 'Secure Hash Algorithm 2 (256 bits)', 'ui-priority': 0, 'misp-attribute': 'sha512/256', 'recommended': False}, 'ssdeep': {'description': 'Fuzzy hash using context triggered piecewise hashes (CTPH)', 'ui-priority': 0, 'misp-attribute': 'ssdeep'}, 'entropy': {'description': 'Entropy of the whole section', 'disable_correlation': True, 'ui-priority': 0, 'misp-attribute': 'float'}, 'name': {'description': 'Name of the section', 'disable_correlation': True, 'sane_default': ['.rsrc', '.reloc', '.rdata', '.data', '.text'], 'ui-priority': 1, 'misp-attribute': 'text'}, 'size-in-bytes': {'description': 'Size of the section, in bytes', 'disable_correlation': True, 'ui-priority': 1, 'misp-attribute': 'size-in-bytes'}, 'offset': {'description': 'Section’s offset', 'disable_correlation': True, 'ui-priority': 1, 'misp-attribute': 'hex'}, 'virtual_address': {'description': 'Section’s virtual address', 'disable_correlation': True, 'ui-priority': 1, 'misp-attribute': 'hex'}, 'virtual_size': {'description': 'Section’s virtual size', 'disable_correlation': True, 'ui-priority': 1, 'misp-attribute': 'size-in-bytes'}, 'text': {'description': 'Free text value to attach to the section', 'disable_correlation': True, 'ui-priority': 1, 'misp-attribute': 'text', 'recommended': False}, 'characteristic': {'description': 'Characteristic of the section', 'sane_default': ['read', 'write', 'executable'], 'ui-priority': 0, 'misp-attribute': 'text'}}, 'version': 3, 'description': 'Object describing a section of a Portable Executable', 'meta-category': 'file', 'uuid': '198a17d2-a135-4b25-9a32-5aa4e632014a', 'name': 'pe-section'}
```

**Comment by bernhardreiter** [comment]
@Rafiot same here, it is very strange. Same test results here on the other case with `intelmq-event`. Maybe it is a Python defect or related to one. It seems to happen in a C implementation of fp.read() which somehow calls `codecs.ascii_decode` by mistake. However I do not have a running system I could examine. I did see this behaviour on an ubuntu system once.

**Comment by Rafiot** [comment]
Yeah, I've seen issues like that in the past, but not recently, and I'd like to figure out what is causing it (I'm obviously fine with changing the template to an ascii quote).

**Comment by Rafiot** [comment]
Could that be the problem: https://github.com/docker-library/python/issues/13

**Comment by bernhardreiter** [comment]
@Rafiot Good catch, my suggestion after some reading now is to add the encoding parameter to the open call for the json template reader, as json as of RFC8259 is UTF-8. This would make the code more explicit about what it is expecting from the json template files.

**Comment by Rafiot** [comment]
Yes and no, I'd rather have the systems configuring their encoding properly, because I'm pretty sure that it will cause other issues in other parts of the code (python or not). So failing like that is a good hint that you should configure the locale on your system.

The only thing I would do at a global level in PyMISP is checking the locale and hard failing on import if it is not properly configured.

**Comment by bernhardreiter** [comment]
@Rafiot  a non UTF locale would be okay and correct for a GNU system to have, but reading of the JSON file still had to expect UTF-8. So doing this global level check may not be correct as not all files and file name will have to assume UTF-8.

**Comment by wagner-certat** [comment]
IMHO If pymisp needs UTF-8, it should be set explicitly rather than relying on ENV variables (I had the same issue in IntelMQ)
I guess the relevant code is https://github.com/MISP/PyMISP/blob/3ee08b9c2634e132ec7d5b15aba9d6c940ee34c6/pymisp/abstract.py#L49
Use the encodings parameter you can set utf-8, see also https://docs.python.org/3/library/functions.html?highlight=open#open

**Comment by Rafiot** [comment]
Well, right, but we also need to make sure the system it runs on supports UTF-8 then, ant that check need to happen on import.

**Comment by bernhardreiter** [comment]
> Well, right, but we also need to make sure the system it runs on supports
> UTF-8 then

No, a system could be running on latin1 and still use JSON files
(which are in UTF-8). Couldn't it? ;)

**Comment by wagner-certat** [comment]
I guess the fix is https://github.com/MISP/PyMISP/commit/eff7146b3c4a981c9e13fa9a4c403950dfddd503#diff-94c97d63bf9b8aa6f518ab65f1eb4df9?

**Comment by Rafiot** [comment]
Yes, sorry, I didn't tag it.
