### ISSUE TITLE
feed-generator/generate.py - KeyError: '_hashes'

### ISSUE THREAD

**Issue by AndreC10002** [MISP/PyMISP#506]
Trying to export a feed from a MISP instance using the example script feed-generator/generate.py.  First, found out it only works with Python > 3.6.  It would be nice to document that.

Got Python 3.6.9 and PyMISP installed, but now I see the following error:

$ python3.6 generate.py

Traceback (most recent call last):
  File "generate.py", line 71, in <module>
    hashes += [[h, e.uuid] for h in e_feed.pop('_hashes')]
KeyError: '_hashes'

The settings.py file is correctly configured. I believe the script is able to reach MISP.  Couldn't figure out why '_hashes' isn't a valid key for e_feed.

**Comment by AndreC10002** [comment]
Although the issue I'm reporting is when executing the script using Python 3.6, for reference purposes - perhaps others are experiencing same issues - here are the error messages produced when executing the script with Python < 3.6:

Using Python: 3.5.3:

  File "generate.py", line 25
    with open(os.path.join(outputdir, f'{event["uuid"]}.json'), 'w') as f:
                                                            ^
SyntaxError: invalid syntax

And on Python 3.4.2:

  File "generate.py", line 56
    events = misp.search(metadata=True, limit=200, **filters, pythonify=True)
                                                            ^
SyntaxError: invalid syntax

**Comment by AndreC10002** [comment]
Forgot to mention I'm running MISP v2.4.119.

**Comment by Rafiot** [comment]
Note that starting in January, every Python library will have a hard dependency on Python 3.6. We're discarding everything older than that (basically ubuntu 18.04 LTS is our baseline).

Not having this key is very weird. Could it be that you have events without exportable attributes? The Patch I just pushed should solve that

**Comment by AndreC10002** [comment]
Thank you for the quick response.
I'm wondering if I have a bigger problem here, because now I get the following error:

Traceback (most recent call last):
  File "generate_new.py", line 73, in <module>
    manifest.update(e_feed.pop('_manifest'))
KeyError: '_manifest'

**Comment by AndreC10002** [comment]
The MISP instance has +300k events.  AFAIK all of them have attributes.  They are all tagged and I'm filtering like this:

filters = {'published':'true','tag':'_my_tag_'}

The only other thing I see, and I believe it is totally unrelated to this issue, is the script complaining about SSL although we use a LetsEncrypt certificate:

/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:1004: InsecureR
equestWarning: Unverified HTTPS request is being made. Adding certificate verifi
cation is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanc
ed-usage.html#ssl-warnings
  InsecureRequestWarning,

**Comment by AndreC10002** [comment]
Am I right to assume PyMISP doesn't require the export plugin or any others to be enabled?

**Comment by AndreC10002** [comment]
Server logs look clean:

[23/Dec/2019:21:38:00 +0000] "GET /servers/getPyMISPVersion.json HTTP/1.1" 200 2923 "-" "PyMISP 2.4.119.1 - Python 3.6"
[23/Dec/2019:21:38:00 +0000] "GET /servers/getVersion.json HTTP/1.1" 200 2961 "-" "PyMISP 2.4.119.1 - Python 3.6"
[23/Dec/2019:21:38:00 +0000] "GET /users/view/me HTTP/1.1" 200 5178 "-" "PyMISP 2.4.119.1 - Python 3.6"
[23/Dec/2019:21:38:01 +0000] "GET /attributes/describeTypes.json HTTP/1.1" 200 21879 "-" "PyMISP 2.4.119.1 - Python 3.6"
[23/Dec/2019:21:38:01 +0000] "POST /events/restSearch HTTP/1.1" 200 290367 "-" "PyMISP 2.4.119.1 - Python 3.6"
[23/Dec/2019:21:38:02 +0000] "GET /events/view/5df52d19-8840-4b90-b97b-2672ac110002 HTTP/1.1" 200 8468 "-" "PyMISP 2.4.119.1 - Python 3.6"

**Comment by AndreC10002** [comment]
And the event it is trying to pull look healthy to me
![temp](https://user-images.githubusercontent.com/4982521/71381905-a36dcb00-25a3-11ea-9366-00e58930df83.png)

**Comment by Rafiot** [comment]
Okay, I'm an idiot.

I didn't test the generator since the last change and it was simply broken. The last commit should fix it, sorry for that.

**Comment by AndreC10002** [comment]
Confirmed it works.
Thank you very much.  You were a life saver!  Much appreciated.
Cheers!
