### ISSUE TITLE
feed-generator/generate.py - not observing the filter clause

### ISSUE THREAD

**Issue by AndreC10002** [MISP/PyMISP#507]
In tests, I've found that the script isn't filtering events according to the 'filters' clause from settings.py.  Feed files are created with events sorted by date and not observing tag filtering.

filters = {'published':'true','tag':'_my_tag_'}

**Comment by Rafiot** [comment]
Can you try again with:
``` python
filters = {'published': True,'tags': ['my_tag']}
```

Just in case.

**Comment by AndreC10002** [comment]
It worked in a quick test.  I'll do some more extensive ones and let you know in case something isn't working.

Once again, thank you very much!
