### ISSUE TITLE
PyMISP.search_logs(created=...) does not seem to filter results by date

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#512]
Would like to use the `created` arg in `pymisp.search_logs` to filter query results for a range of dates. Wasn't sure if it supports a range (i.e. to/from). I did try a specific date string, but that appears to be ignored (setting `created` to any date or not passing `created` always gets the same result length): see below.

Guidance appreciated on how to to get this to work.

* **MySQL**
```
MariaDB [misp]> select count(*) from logs where created = '2019-12-31 00:20:11' and action='add' and model='Attribute';
+----------+
| count(*) |
+----------+
|        3 |
+----------+
```
* **PyMISP** output from code snippet below:
   * `search_logs(Attribute): count=177608`
```
result = misp.search_logs(
    created = '2019-12-31 00:20:11',
    model   = 'Attribute',
    action  = 'add')
print('search_logs(Attribute): count=%d' % (len(result)))
```

**Comment by github-germ** [comment]
Also, are the args passed to `search_logs` `AND`-ed when producing the query results?

**Comment by Rafiot** [comment]
I'll pass that one to @iglocska.

**Comment by github-germ** [comment]
@iglocska -- HNY Andras!! Am I doing something wrong to get the `created` arg in `search_logs()` to work? Thx...

**Comment by github-germ** [comment]
My own issue resolved after reading `LogsController.php` with for example:
```
search_logs(created=('2020-01-13 00:00:00', '2020-01-13 19:00:00'), ... )
```
