### ISSUE TITLE
Tags not returned in Search

### ISSUE THREAD

**Issue by imidoriya** [MISP/PyMISP#516]
I'm trying to get a list of the Event tags to be included with the search return, but can't seem to get it.  The `include_event_tags` doesn't appear to do anything.  I'm not looking for the `tags` filter.  The tags are returned when `metadata=True`, but that limits the query to returning only metadata.  Due to the size, I'd also like to avoid pythonify event.tags.
```
events = misp.client.search(
    include_event_tags=True,
    tags="tlp:amber",
    limit=100
)
```

Is there an easy way to get the search return to include something like `{"Tag": [{'id': '3', 'name': 'tlp:amber', 'colour': '#FFC000', 'exportable': True, 'user_id': '0'}]}`

**Comment by di-iode** [comment]
I just update misp 2.4.108 to 2.4.200, and i have the same problem. Before with 2.4.108, when i used `include_event_tags ` i got event_tag. But with 2.4.120, i din't get its.

**Comment by Rafiot** [comment]
Hmmm I just did a fast test using the REST Client on the MISP interface:
```json
{
    "limit": 5,
    "tags": ["tlp:amber"]
}
```

And the Tag key is in the response (and I tested the same thing using PyMISP and it worked too).

**Comment by di-iode** [comment]
I don't test with key `tags` but just with `value`

**Comment by Rafiot** [comment]
Still, that's the same code path.

Can you show the whole query you're doing?

**Comment by di-iode** [comment]
I try to ad key `tags` and a value of a tag.
it find a attribut but don't show the event tag :(

**Comment by Rafiot** [comment]
and on MISP, that event has a tag, right? Because it will also match on tags at the attribute level.

**Comment by imidoriya** [comment]
I can confirm that I get the EventTag using the REST.  I'll try to reproduce code for PyMISP.  I ended up just querying the database directly with SQL to get the job done.

**Comment by di-iode** [comment]
`reponse=m.search(controller='attributes',return_format='json',value=['213ca4db4c2abd3b631da00c299d75ef'], includ_event_tag=True)`
for exemple

**Comment by di-iode** [comment]
> 
> 
> and on MISP, that event has a tag, right? Because it will also match on tags at the attribute level.

Yes the event has a tag
I try to search a value, i got a response but don't show event tag
I try to seach a value and a tag (event tag), i got a response but don't show event tag
I try to search just with tag (a event tag), i got response but don't show event tag

**Comment by di-iode** [comment]
for information in MISP 2.4.108, no problem, just with 2.4.120

**Comment by Rafiot** [comment]
oh, right, you're on the attribute controller, I tested on the event controller (as it was done in the example above).

I'll have a look at that tomorrow, but this might be a question for @iglocska or @mokaddem.

**Comment by di-iode** [comment]
I'm sorry, i read my post and see that i write the reverse that i see ... 

with `return_format='json'` it's work 
with `return_format='csv'` it's don't work

**Comment by Rafiot** [comment]
So it works for us. The key to use is `include_context`. Can you give it a try?

One reason it may fail for you is if the tags are non-exportable.

**Comment by chrisinmtown** [comment]
FWIW we had a similar problem,see #645, an event was tagged, we search for the event, we found the event, but the result had an empty tag list.  Finally we realized that particular tag on the vent was not exportable, so the tag was not included in the search result; only exportable tags are sent back.

**Comment by Rafiot** [comment]
Yep, that's true. Confusing, but true. The non-exportable tags aren't returned on the API. It may be a feature request to open in MISP.
