### ISSUE TITLE
events/restSearch API error after updating MISP to 2.4.120

### ISSUE THREAD

**Issue by goodlandsecurity** [MISP/PyMISP#525]
I just updated MISP to 2.4.120 and now I get this error when trying to reach events/restSearch api. 

Can/will provide additional information as needed. 

Stderr: CRITICAL [aping.py:67 - _check_response() ] Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.120 - Python 3.7.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '44', 'Authorization': '#{API_KEY}', 'content-type': 'application/json'}
Request body:
{"returnFormat": "json", "value": "8.8.8.8"}
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/restSearch"}

**Comment by iglocska** [comment]
It seems to work fine on the instances that I've tried, that could also indicate a memory exhaustion issue for example. Could you try the following?

Run the same query again and right after check your error log in /var/www/MISP/app/tmp/logs/error.log

The error should be in there.

**Comment by goodlandsecurity** [comment]
Thank you for the fast reply. Here is the error we see, 

#15 {main}
2020-01-22 13:01:04 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Attribute.first_seen' in 'field list'
Request URL: /events
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Attribu...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Attribu...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1564): DboSource->fetchAll('SELECT `Attribu...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1398): DboSource->_fetchHasMany(Object(Event), 'SELECT `Attribu...', Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1257): DboSource->queryAssociation(Object(Event), Object(Attribute), 'hasMany', 'Attribute', Array, Array, true, Array, 2, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Event), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#8 /var/www/MISP/app/Model/Event.php(2135): Model->find('all', Array)
#9 /var/www/MISP/app/Controller/EventsController.php(2004): Event->fetchEvent(Array, Array)
#10 [internal function]: EventsController->add()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}

**Comment by mokaddem** [comment]
Hey. It seems that there was an issue during the update. Could you give the result of this page ``/servers/dbSchemaDiagnostic`` ?
Thanks a lot!

**Comment by goodlandsecurity** [comment]
Looks like the Database did not upgrade with the MISP update. 
![Screen Shot 2020-01-22 at 7 34 13 AM](https://user-images.githubusercontent.com/41647202/72898416-add9cc80-3ce9-11ea-867e-8425766ab46d.png)

**Comment by mokaddem** [comment]
Can you check that your workers are (especially the `prio` and the `update` one) or up and running in
``/servers/serverSettings/workers`` ? If not, could you please ``restart all workers``? I suspect that the worker diagnostic incorrectly detect them as running and thus not triggering the update.

**Comment by goodlandsecurity** [comment]
The update worker and the scheduler worker were both down. I restarted all workers and now we are good! 

Thank you so much for your help!
