### ISSUE TITLE
PyMISP event export and import example

### ISSUE THREAD

**Issue by Tubbs10** [MISP/PyMISP#533]
Could someone please be able **to provide an example** using PyMISP of how to export events with all attributes from specific time range (or last day or last two days etc.) and then import them to another MISP instance as new events?

I've tried to solve this for a long time now without success as I find the documentation not very clear on this and it's getting very frustrating.

Thank you so much.

**Comment by Rafiot** [comment]
So first of all, a few questions about what youŕe trying to do:
* which time range are you talking about? Publication date of the events? Last update of the event? Date in the event metainfo?
* You want to copy data from one MISP instance to an other. Is it something you want to do often? Or one shot? If you want to do it often, you probably want to use the feed generator instead.

Code wise, you want to use the `search` method. The interval will be passed to either `publish_timestamp`, `timestamp`, or `date_from` / `date_to`. The response will be a list of events.

You can then use the `add_event` method, iterate through that list, and post them on your new MISP instance.

Note that you will need to use `update_event` if that same event was already present on the MISP instance (that problem is handled automatically if you use the feed system).

**Comment by Tubbs10** [comment]
Good question, forgot to mention that. So the time range I'm talking about is the publication date of the events.

I'd be really interested in seeing an actual working example of the export and then the import part of the code for that particular export as I have not managed to find anything for it?

For example the load_csv.py that is in /var/www/MISP/PyMISP/examples does not work together with get_csv.py because the CSVLoader in load_csv.py wants a template defined and when using the file template (-n file) it doesn't match with format the get_csv.py made.

Commands ran:
MISP1:
python3 get_csv.py -f /var/www/MISP/app/tmp/exportfile.csv
--
_copy exportfile.csv from MISP1 to MISP2_
--
MISP2:
python3 load_csv.py -n file -p /var/www/MISP/app/tmp/exportfile.csv

Error:
Traceback (most recent call last):
  File "load_csv.py", line 56, in <module>
    objects = csv_loader.load()
  File "/usr/local/lib/python3.7/dist-packages/pymisp/tools/csvloader.py", line 44, in load
    raise Exception(f'{fieldname} is not a valid object relation for {self.template_name}: {allowed_fieldnames}')
Exception: uuid is not a valid object relation for file: ['md5', 'sha1', 'sha224', 'sha256', 'sha384', 'sha512', 'sha512/224', 'sha512/256', 'ssdeep', 'authentihash', 'size-in-bytes', 'entropy', 'pattern-in-file', 'text', 'malware-sample', 'attachment', 'filename', 'path', 'fullpath', 'tlsh', 'certificate', 'mimetype', 'state', 'file-encoding', 'imphash']

**Comment by Rafiot** [comment]
Sooo, it's not working because it's not made for that at all. The CSV importer will create MISP objects out of a CSV file, not out of a MISP export. What you're trying to do is losing a lot of data and is generally a terrible idea, so don't do that.

The format you want to use for that is the default MISP JSON. 

I'm not going to write a full script, because that sounds like a homework you  should be doing yourself, but here is a pseudo code:

```python

misp_src = Pymisp(<connection parameters>)
misp_dst = Pymisp(<connection parameters>)

events = misp_src.search(publish_timestamp='2020-01-01')  # returns a list of events published after that timestamp

for e in events:
  misp_dst.add_event(e)
```

Note that it will take every event your user has access to on the source instance, and post them on the destination instance. Anything you're not allowed to do do on the destination instance (i.e. post an event with an organization that isn't yours, will be modified, so you have to be *very* careful with that)

**Comment by Tubbs10** [comment]
Ok, you got me on the right track so thanks for that.
I'm able to get json export with last.py script but import does not work.
This is what I'm trying to do:

> last.py

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pymisp import ExpandedPyMISP
from keys import misp_url, misp_key, misp_verifycert, misp_client_cert
import argparse
import os


# Usage for pipe masters: ./last.py -l 5h | jq .
# Usage in case of large data set and pivoting page by page: python3 last.py  -l 48h  -m 10 -p 2  | jq .[].Event.info

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Download latest events from a MISP instance.')
    parser.add_argument("-l", "--last", required=True, help="can be defined in days, hours, minutes (for example 5d or 12h or 30m).")
    parser.add_argument("-m", "--limit", required=False, default="10", help="Add the limit of records to get (by default, the limit is set to 10)")
    parser.add_argument("-p", "--page", required=False, default="1", help="Add the page to request to paginate over large dataset (by default page is set to 1)")
    parser.add_argument("-o", "--output", help="Output file")

    args = parser.parse_args()

    if args.output is not None and os.path.exists(args.output):
        print('Output file already exists, aborted.')
        exit(0)

    if misp_client_cert == '':
        misp_client_cert = None
    else:
        misp_client_cert = (misp_client_cert)

    proxies={'http': None, 'https': None}

    misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert, cert=misp_client_cert, proxies=proxies)
    result = misp.search(publish_timestamp=args.last, limit=args.limit, page=args.page, pythonify=True, return_format='json')

    if not result:
        print('No results for that time period')
        exit(0)

    if args.output:
        with open(args.output, 'w') as f:
            for r in result:
                f.write(r.to_json() + '\n')
    else:
        for r in result:
            print(r.to_json())

```
I get the export with command:
`python3 last.py -l 1d -o /tmp/export.json`

Then moving the file from MISP1 to MISP2 but when trying to import with below script:

> import_json.py

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from pymisp import PyMISP, MISPAttribute, MISPEvent, ExpandedPyMISP
from keys import misp_url, misp_key, misp_verifycert, misp_client_cert
import json

proxies={'http': None, 'https': None}
misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert, cert=misp_client_cert, debug=False, proxies=proxies)

with open('/tmp/imported/export.json', 'r') as f:
    for e in f:
        event = json.loads(e)
        misp.add_event(event)

```
When running the script
`python3 import_json.py`

I'm getting the following errors:
```
ERROR [aping.py:2169 - _check_response() ] Something went wrong (403): {'name': 'Could not add Event', 'message': 'Could not add Event', 'url': '/events/add', 'errors': []}
ERROR [aping.py:2169 - _check_response() ] Something went wrong (403): {'name': 'Could not add Event', 'message': 'Could not add Event', 'url': '/events/add', 'errors': []}
ERROR [aping.py:2169 - _check_response() ] Something went wrong (403): {'name': 'Could not add Event', 'message': 'Could not add Event', 'url': '/events/add', 'errors': []}
ERROR [aping.py:2169 - _check_response() ] Something went wrong (403): {'name': 'Could not add Event', 'message': 'Could not add Event', 'url': '/events/add', 'errors': []}
ERROR [aping.py:2169 - _check_response() ] Something went wrong (403): {'name': 'Could not add Event', 'message': 'Could not add Event', 'url': '/events/add', 'errors': []}
ERROR [aping.py:2169 - _check_response() ] Something went wrong (403): {'name': 'Could not add Event', 'message': 'Could not add Event', 'url': '/events/add', 'errors': []}
ERROR [aping.py:2169 - _check_response() ] Something went wrong (403): {'name': 'Could not add Event', 'message': 'Could not add Event', 'url': '/events/add', 'errors': []}
ERROR [aping.py:2169 - _check_response() ] Something went wrong (403): {'name': 'Could not add Event', 'message': 'Could not add Event', 'url': '/events/add', 'errors': []}
```

These were in apache logs but nothing in debug.log for example:
```
127.0.0.1 - - [04/Feb/2020:15:50:55 +0200] "GET /servers/getPyMISPVersion.json HTTP/1.1" 200 538 "-" "PyMISP 2.4.119.1 - Python 3.7"
127.0.0.1 - - [04/Feb/2020:15:50:55 +0200] "GET /servers/getVersion.json HTTP/1.1" 200 576 "-" "PyMISP 2.4.119.1 - Python 3.7"
127.0.0.1 - - [04/Feb/2020:15:50:55 +0200] "GET /users/view/me HTTP/1.1" 200 2818 "-" "PyMISP 2.4.119.1 - Python 3.7"
127.0.0.1 - - [04/Feb/2020:15:50:55 +0200] "GET /attributes/describeTypes.json HTTP/1.1" 200 19345 "-" "PyMISP 2.4.119.1 - Python 3.7"
127.0.0.1 - - [04/Feb/2020:15:50:55 +0200] "POST /events HTTP/1.1" 403 646 "-" "PyMISP 2.4.119.1 - Python 3.7"
127.0.0.1 - - [04/Feb/2020:15:50:55 +0200] "POST /events HTTP/1.1" 403 646 "-" "PyMISP 2.4.119.1 - Python 3.7"
127.0.0.1 - - [04/Feb/2020:15:50:55 +0200] "POST /events HTTP/1.1" 403 646 "-" "PyMISP 2.4.119.1 - Python 3.7"
127.0.0.1 - - [04/Feb/2020:15:50:55 +0200] "POST /events HTTP/1.1" 403 646 "-" "PyMISP 2.4.119.1 - Python 3.7"
127.0.0.1 - - [04/Feb/2020:15:50:55 +0200] "POST /events HTTP/1.1" 403 646 "-" "PyMISP 2.4.119.1 - Python 3.7"
127.0.0.1 - - [04/Feb/2020:15:50:55 +0200] "POST /events HTTP/1.1" 403 646 "-" "PyMISP 2.4.119.1 - Python 3.7"
127.0.0.1 - - [04/Feb/2020:15:50:55 +0200] "POST /events HTTP/1.1" 403 646 "-" "PyMISP 2.4.119.1 - Python 3.7"
127.0.0.1 - - [04/Feb/2020:15:50:55 +0200] "POST /events HTTP/1.1" 403 646 "-" "PyMISP 2.4.119.1 - Python 3.7"
127.0.0.1 - - [04/Feb/2020:15:50:55 +0200] "POST /events HTTP/1.1" 403 646 "-" "PyMISP 2.4.119.1 - Python 3.7"
127.0.0.1 - - [04/Feb/2020:15:50:56 +0200] "POST /events HTTP/1.1" 403 646 "-" "PyMISP 2.4.119.1 - Python 3.7"

```

Any ideas what could be wrong?

Thank you in advance.

**Comment by Rafiot** [comment]
So one thing, from the top of my head:

`for e in f:` <= that iterate line by line in the file, which doesn't makes sense. Write each MISP event in a single file, and iterate through the files will be better.

**Comment by Tubbs10** [comment]
Hmm.. I'll try that but I still get a proper response when I for example print only uuid's instead of trying to add event to misp.

Like this:
```
with open('/tmp/imported/export.json', 'r') as f:
    for e in f:
        event = json.loads(e)
        print(event['uuid'])
```
and it will give me a list of all events uuids in that file and with `print(event['attribute_count'])` it'll list how many attributes there are per event so at least it looks that events are correctly parsed and there shouldn't be an issue there when trying to add event.

**Comment by Rafiot** [comment]
The error message you're getting is weird. Normally, you should have a proper error message.

 You're adding the event on a *different* MISP instance, right?

**Comment by Tubbs10** [comment]
I agree. Yes it is a different instance so that's not the problem.

**Comment by Rafiot** [comment]
you get a 403, so there is some kind of permission issue.

Can you try to get one single event from instance A and import it in instance B with the UI?

**Comment by Tubbs10** [comment]
I tried this with one event that has 38 attributes and get the same error. When adding an event from file with only one attribute it seems to works fine.

**Comment by Rafiot** [comment]
So, from the web interface, you get an event from instance A in JSON format, upload it on instance B, and it fails?

That's weird, and not PyMISP related. Is that event sharable? If you can share publicly here, please do, otherwise, please send it to info@circl.lu, with a reference to this issue.

**Comment by Wachizungu** [comment]
Can you check you are not exceeding your PHP max upload filesize?
Should be setting in your PHP config

**Comment by Tubbs10** [comment]
I figured this out and you should be able to reproduce this.

So I get this error:
`ERROR [aping.py:2169 - _check_response() ] Something went wrong (403): {'name': 'Could not add Event', 'message': 'Could not add Event', 'url': '/events/add', 'errors': []}`

when trying to add same event that has once already been there but deleted at some point. When I'm adding completely new events it works without any issues. For me it looks that there might be somekind of database glitch or something. Could this be a bug?

**Comment by Rafiot** [comment]
Ahh, no, that's expected, but the error message could probably be better (cc @iglocska): When you delete an event, its UUID is added in the blacklist (`https://<MISP>/eventBlacklists`). If you delete the UUID from that list, you can add the event again.

**Comment by Tubbs10** [comment]
Ok,

So that's it then. Thank you so much for your support! I'll leave the working code here still in case someone finds it useful.

For json export last.py from /var/www/MISP/PyMISP/examples/ can be used

> last.py
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pymisp import ExpandedPyMISP
from keys import misp_url, misp_key, misp_verifycert, misp_client_cert
import argparse
import os


# Usage for pipe masters: ./last.py -l 5h | jq .
# Usage in case of large data set and pivoting page by page: python3 last.py  -l 48h  -m 10 -p 2  | jq .[].Event.info

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Download latest events from a MISP instance.')
    parser.add_argument("-l", "--last", required=True, help="can be defined in days, hours, minutes (for example 5d or 12h or 30m).")
    parser.add_argument("-m", "--limit", required=False, default="10", help="Add the limit of records to get (by default, the limit is set to 10)")
    parser.add_argument("-p", "--page", required=False, default="1", help="Add the page to request to paginate over large dataset (by default page is set to 1)")
    parser.add_argument("-o", "--output", help="Output file")

    args = parser.parse_args()

    if args.output is not None and os.path.exists(args.output):
        print('Output file already exists, aborted.')
        exit(0)

    if misp_client_cert == '':
        misp_client_cert = None
    else:
        misp_client_cert = (misp_client_cert)

    proxies={'http': None, 'https': None}

    misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert, cert=misp_client_cert, proxies=proxies)
    result = misp.search(publish_timestamp=args.last, limit=args.limit, page=args.page, pythonify=True, return_format='json')

    if not result:
        print('No results for that time period')
        exit(0)

    if args.output:
        with open(args.output, 'w') as f:
            for r in result:
                f.write(r.to_json() + '\n')
    else:
        for r in result:
            print(r.to_json())
```

For importing the events from that file, import_json.py needs to be created.

> import_json.py
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from pymisp import PyMISP, MISPAttribute, MISPEvent, ExpandedPyMISP
from keys import misp_url, misp_key, misp_verifycert, misp_client_cert
import json
import argparse

# Usage: python3 import_json.py -i <json_file>

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Import events from json file.')
    parser.add_argument("-i", "--input", required=True, help="Input file")
    args = parser.parse_args()

    if misp_client_cert == '':
        misp_client_cert = None
    else:
        misp_client_cert = (misp_client_cert)

    proxies={'http': None, 'https': None} # For proxy configuration if needed
    misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert, cert=misp_client_cert, debug=False, proxies=proxies)

    if args.input:
        with open(args.input, 'r') as f:
            for e in f:
                event = json.loads(e)
                misp.add_event(event)
```

**Comment by Rafiot** [comment]
Thank you very much!

**Comment by cudeso** [comment]
Doing misp.add_event on a downloaded MISP event (via the UI, saved MISP-JSON format) 
```
event = json.loads(e)
misp.add_event(event)
```
now returns
```
ERROR [api.py:3195 - _check_response() ] Something went wrong (403): {'saved': False, 'name': 'Could not add Event', 'message': 'Could not add Event', 'url': '/events/add', 'errors': {'Event': {'info': ['valueNotEmpty']}}}
```

This is PyMISP 2.4.138 with MISP 2.4.139. Editing the exported JSON and removing `{"response": [` fixes the problem: import of a downloaded event works via add_event.

Not sure if this is related to PyMISP or MISP (output format changed?).

**Comment by Rafiot** [comment]
if I'm not mistaken, the `response` key was removed a very, very long time ago (we're talking way over a year, iirc)

**Comment by cudeso** [comment]
I'm using MISP 2.4.139.
The response key is present in both MISP XML and MISP JSON "Download as..."

**Comment by Rafiot** [comment]
ok, no idea then, @iglocska did something change recently?

**Comment by iglocska** [comment]
Unless I'm mistaken of course, will test it just in case

**Comment by iglocska** [comment]
Going back as far as 2.4.115 this seems to be the case.

**Comment by chrisinmtown** [comment]
So the import and export are now symmetric, is that what you are saying?  It appears that export wraps its output with { "Response": ..} but the import feature does not recognize it, only accepts an input without "Response".  This is worth documenting carefully because it violates my expectations -- IMHO export should produce an output that can be fed straight back to import.
