### ISSUE TITLE
Feed Generator in 2.4.120 not working in certain python environments 

### ISSUE THREAD

**Issue by cbboggs** [MISP/PyMISP#536]
In a Ubuntu 18.04 desktop environment, with both python2.7 and python3.6 installed (as is default currently), I'm unable to run the example feed generator script (generate.py) in the latest builds of pymisp (2.4.120) using python3.  I receive the error `Unable to export in the feed format, _fields_for_feed is missing.`

If I downgrade to pymisp 2.4.119.1, then it works fine.

I verified that I'm executing with python3 - so I'm unsure what is causing the problem.

Just as confusing to me, the only success I've had running the feed generator with the latest version of pymisp has been in a brand new Ubuntu 18.04 Server install, fresh MISP install (using install.sh) and within the MISP venv.   If I try to duplicate the venv's Python versions and dependencies elsewhere and run feed generator, it still gives the same error.

**Comment by Rafiot** [comment]
Can you try with the HEAD of the repository (master branch), please? I fixed a few things since the release of 2.4.120 and that's very probably one of them.

**Comment by cbboggs** [comment]
Hmm, I have not tried that before..  Running the commands from the readme to clone and install the latest,
```
git clone https://github.com/MISP/PyMISP.git && cd PyMISP
git submodule update --init
pip3 install -I .[fileobjects,neo,openioc,virustotal]
```

the pip3 install results in
```
Processing /home/boggs/pymisp/PyMISP
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-owcylvr6-build/setup.py", line 7, in <module>
        import pymisp
      File "/tmp/pip-owcylvr6-build/pymisp/__init__.py", line 28, in <module>
        from .tools import AbstractMISPObjectGenerator  # noqa
      File "/tmp/pip-owcylvr6-build/pymisp/tools/__init__.py", line 4, in <module>
        from .peobject import PEObject, PESectionObject  # noqa
      File "/tmp/pip-owcylvr6-build/pymisp/tools/peobject.py", line 28, in <module>
        class PEObject(AbstractMISPObjectGenerator):
      File "/tmp/pip-owcylvr6-build/pymisp/tools/peobject.py", line 30, in PEObject
        def __init__(self, parsed: Optional[lief.PE.Binary]=None, filepath: Optional[Union[Path, str]]=None, pseudofile: Optional[BytesIO]=None, standalone: bool=True, **kwargs):
    NameError: name 'lief' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-owcylvr6-build/
```

**Comment by Rafiot** [comment]
hm, right, I may not have noticed that because lief was already installed on my side.

Try to do 

`pip3 install lief` 

and then 

`pip3 install -I .[fileobjects,neo,openioc,virustotal]`

**Comment by Rafiot** [comment]
if that solves it, I need to fix something

**Comment by cbboggs** [comment]
Installed lief, but now it's failing to build pydeep.
```
Building wheels for collected packages: pydeep, py2neo, validators, neobolt, neotime
  Running setup.py bdist_wheel for pydeep ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-sopzdkhs/pydeep/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpkuqbxls1pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'pydeep' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include/ -I/usr/include/python3.6m -c pydeep.c -o build/temp.linux-x86_64-3.6/pydeep.o
  pydeep.c:2:10: fatal error: fuzzy.h: No such file or directory
   #include <fuzzy.h>
            ^~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pydeep
```
I think we can get by using the older version for now, I just wanted to make sure the issue wasn't just something with our setup.   I'd be glad to test further, but it seems like building the latest master might be too troublesome :)

**Comment by adulau** [comment]
You are missing the dev part of libfuzzy 

`apt-get -y install libfuzzy-dev`

**Comment by cbboggs** [comment]
Oops, should have been able to discern that from the missing fuzzy.h but didn't want to assume.

That fixed the build errors, and also the issue with the feed generator.   Thanks!  I guess we'll keep an eye out for an updated pip package so we can update our environment.

**Comment by cbboggs** [comment]
verified resolved in the latest pypi package.

Thanks much!
