### ISSUE TITLE
Negative wildcard attribute tag search

### ISSUE THREAD

**Issue by sustefil** [MISP/PyMISP#537]
Hi!

I am trying to build a query for searching attributes which do **not** have a wildcarded tag.. so far I have been experimenting with `search` and `build_complex_query` methods, but no success.. can you give me a hint how to do it please?

I need something like this:
```
tag_query = misp.build_complex_query(not_parameters=['%score%'])
misp.search(controller='attributes', category='Network activity', tags=tag_query)
```

**Comment by Rafiot** [comment]
@iglocska do you have an idea?

**Comment by mokaddem** [comment]
The ``tags`` parameter can be used like that in the MISP API
```
"tags": {
    "AND": ["tlp:green", "Malware"],
    "NOT": ["%ransomware%"]
}
```

**Comment by sustefil** [comment]
Ah great, It indeed works, I was wrongly evaluating the result, thank you!
