### ISSUE TITLE
peobject.py references optional lief object

### ISSUE THREAD

**Issue by sebix** [MISP/PyMISP#538]
https://github.com/MISP/PyMISP/blob/70dca1d4087cd6e30f2d3403dbc997d3eb2bab26/pymisp/tools/peobject.py#L30
https://github.com/MISP/PyMISP/blob/70dca1d4087cd6e30f2d3403dbc997d3eb2bab26/pymisp/tools/peobject.py#L122

lief is an optional dependency and the import in peobject.py is optional too. `But lief.PE.Binary` is referenced as type for arguments

**Comment by Rafiot** [comment]
I moved it to the required dependencies, because it's pretty reliable now a days. Any reason not to? 

I'm assuming people use recent OSs, since we force python 3.6+

**Comment by wagner-certat** [comment]
> I moved it to the required dependencies

Why is the import in the file optional then?

**Comment by Rafiot** [comment]
Oh, right, that's a mistake, thank you for pointing it out.

**Comment by grolinet** [comment]
I can't really understand, why to add this dependency. It bloats up the installation in my opinion. In most cases lief is not really needed (if you just want to add some Events, or query a MISP instance).

**Comment by baderj** [comment]
The _lief_ dependency also breaks pymisp in docker images based on Alpine. Even if you add ``cmake``, ``make`` and ``gcc`` (which weren't required before), the build fails because the current release of _lief_ does not support Python 3.8, see this issue https://github.com/lief-project/LIEF/issues/373.

**Comment by Rafiot** [comment]
The developer says it works well on linux and macosx, and we do not (and will never) support windows.

But sure, I can skip it.

**Comment by baderj** [comment]
It doesn't work on linux with Python 3.8, e.g., Alpine 3.11.3. There is a fix for lief, but it is not in the current release. So you need to install lief from the github repo, then pymisp can be installed.

**Comment by Rafiot** [comment]
Right. Well, alpine is fun.

I'll make the dependency optional.

**Comment by Rafiot** [comment]
Can you give the HEAD a try? It should be optional again.

**Comment by baderj** [comment]
> Can you give the HEAD a try? It should be optional again.

Yes, works perfectly. Thanks a lot.

**Comment by Rafiot** [comment]
Great, I pushed a new package on PyPi
