### ISSUE TITLE
Tags with trailing spaces being matched by 'search_index' for trimmed string

### ISSUE THREAD

**Issue by ChilliSec** [MISP/PyMISP#539]
Greetings MISP masters!

I've got a Python script that is searching for events containing 'old' tags, adding 'new' tags and then removing the 'old' tags (in effect a search and replace) to apply some consistency across our events...
```
events = misp.search_index(tags=[old_tag])
    for event in events:
        event_uuid = event['uuid']
        misp.tag(event_uuid,new_tag)
        misp.untag(event_uuid,old_tag)
```
Whilst this mostly works, I've been pulling what's left of my hair out trying to work out what's going on with a couple of tags that appear to fail the 'untag' process... it turn's out that the tags have trailing spaces but are being matched by a search string that doesn't have the trailing space(s).

For example, 'search_index' for "**Threat tlp:White**" matches on "**Threat tlp:White** " (one trailing space) and therefore causes the 'untag' "**Threat tlp:White**" (no trailing space) to understandably fail...

> ERROR [api.py:2178 - _check_response() ] Something went wrong (405): {'name': 'Invalid Tag.', 'message': 'Invalid Tag.', 'url': '/tags/removeTagFromObject'}

Whilst I can work around this by editing the tags in MISP and trimming the trailing spaces (I've already dumped a list of offending tags), am I doing something wrong with my search or is it possible to enforce a strict match on the 'search_index' to stop this behavior? 

Cheers!

Edit: 
```
pip show PyMISP
Name: pymisp
Version: 2.4.121.1
Summary: Python API for MISP.
```

**Comment by Rafiot** [comment]
So yeah, the attachTagToObject method in the controller trims the tag (https://github.com/MISP/MISP/blob/2.4/app/Controller/TagsController.php#L943), so that's a problem for the `tag` and `untag` methods.

Search index returning "Threat tlp:White" and "Threat tlp:White " could be a bug. @iglocska any idea?

**Comment by ChilliSec** [comment]
Thanks @Rafiot - I think the best way for me to proceed is to fix/trim the dozen or so tags and then try to catch the error in the future. Whilst a couple of the offending tags are in-house, the majority have been ingested from others (along with some with multiple leading spaces). They seem to be displayed correctly within MISP so it's only when you 'Edit' the tag or list them via a script that the spaces show up... I wonder if there was some anomaly in the past that allowed these to be created or if it is over zealous space-bar mashing ;-)

If `tag `and `untag ` trim maybe the Tag UI should also trim tags when they're created?

Thanks again and keep up the good work MISP team!

**Comment by Rafiot** [comment]
Oh yeah, definitely, the tags should be trimmed on creation, that's a good point.
