### ISSUE TITLE
disappearance "attribute" in fonction "search_index"

### ISSUE THREAD

**Issue by di-iode** [MISP/PyMISP#540]
Hello,
I use habitually pymisp 2.4.65 (not good!!).
I juste updated it and i have a problem.
Now, the function "search_index" don't accepts the parameter "attribute" like in version 2.4.65.

What is the good practis to search fastly and easilyan attribut ? 

Thank for your help

**Comment by Rafiot** [comment]
Oh wow, the attribute key, I don't even remember it existed.

You can use the `search` method, and the `value` parameter and it will search for attributes.

**Comment by di-iode** [comment]
You can see by yourself :

extract of api.py (pymisp 2.4.65)

```
def search_index(self, published=None, eventid=None, tag=None, datefrom=None,
                     dateuntil=None, eventinfo=None, threatlevel=None, distribution=None,
                     analysis=None, attribute=None, org=None):
        """Search only at the index level. Use ! infront of value as NOT, default OR

        :param published: Published (0,1)
        :param eventid: Evend ID(s) | str or list
        :param tag: Tag(s) | str or list
        :param datefrom: First date, in format YYYY-MM-DD
        :param dateuntil: Last date, in format YYYY-MM-DD
        :param eventinfo: Event info(s) to match | str or list
        :param threatlevel: Threat level(s) (1,2,3,4) | str or list
        :param distribution: Distribution level(s) (0,1,2,3) | str or list
        :param analysis: Analysis level(s) (0,1,2) | str or list
        :param org: Organisation(s) | str or list
        """
```

**Comment by di-iode** [comment]
Thank you, I will test `search`, i want just the name of event and not all information.

**Comment by Rafiot** [comment]
you can pass `metadata=True` and you will only get the metadata of the event.

**Comment by di-iode** [comment]
haha it's that I have find.
Thank you

**Comment by di-iode** [comment]
It's more verbose that odl `search_index` but it's work.
