### ISSUE TITLE
No email notification after publish event

### ISSUE THREAD

**Issue by 6Xkljk8Vj7Tk1k4** [MISP/PyMISP#541]
Hi,

In latest version i have problem with email notification with following python code:

> pymisp = PyMISP(misp_url, misp_key)
        event = MISPEvent()
        event.info = threatName
        event.analysis = 2
        event.distribution = 0
        event.threat_level_id = 3
        event.add_attribute('target-user', userName)
        event.add_attribute('text', contentVersion)
        event.add_attribute('text', osType)
        event.add_attribute('datetime', detectedUTC)
        event.add_attribute('target-location', nodeTextPath)
        event.add_attribute('target-machine', hostName)
        event.add_attribute('ip-src', ipv4)
        event.add_attribute('mac-address', mac)
        event.add_attribute('port', port)
        event.add_attribute('malware-type', threatType)
        event.add_attribute('filename', fileName)
        x = pymisp.add_event(event)
        pymisp.publish(x)

event added successfully but no email notification:
![image](https://user-images.githubusercontent.com/754027/74533912-fe33fb00-4f32-11ea-8f98-7f58a73c64a3.png)

However adding event manually via gui trigger email notification:
![image](https://user-images.githubusercontent.com/754027/74534001-27ed2200-4f33-11ea-89b1-89878dc43c37.png)

Please advise.

**Comment by Rafiot** [comment]
`pymisp.publish(x, alert=True)` should do the trick.
