### ISSUE TITLE
add_event weird reaction: returning an list of ALL existing events but none new one

### ISSUE THREAD

**Issue by dragonyy** [MISP/PyMISP#542]
using MISP 2.4.117, with PyMISP 2.4.117, two months ago the code below worked correctly

```python
misp = ExpandedPyMISP(misp_url, misp_key, False)
e = MISPEvent()
e.info = 'ONE'
e.threat_level_id = 4
e.set_date('2020-02-24')
ekkk = misp.add_event(e)
```

I remember the variable 'ekkk' contained ONE instance of MISPEvent/dict. But today ekkk is a LIST of ALL existing events (5470 events); and no new event has been created.

I tried another chance (listed in [tutorial](https://github.com/MISP/PyMISP/blob/master/docs/tutorial/FullOverview.ipynb) )

```python
event = misp.add_event({'distribution': 1, "threat_level_id": 1, "analysis": 1, 'info':"Event from notebook"})
```

But the condition remains. Someone else encounters this?

**Comment by Rafiot** [comment]
This is super weird, and I can't reproduce it on MISP 2.4.121 with PyMISP 2.4.121.1.

**Comment by dragonyy** [comment]
Last night I download another VirtualboxVM MISP_v2.4.121@0f63223.ova and import to run.
I specifically installed Python 3.7.1 (Anaconda) and Python 3.6.9 (with Ubuntu). Following the [tutorial](https://github.com/MISP/PyMISP/blob/master/docs/tutorial/FullOverview.ipynb) , in the "Full Example, New API" section, I try the code below (It's a totally new install, so there's no event/attribute inside the database):

```python
event = MISPEvent()
event.info = 'This is my new MISP event'  # Required
event.distribution = 0  # Optional, defaults to MISP.default_event_distribution in MISP config
event.threat_level_id = 2  # Optional, defaults to MISP.default_event_threat_level in MISP config
event.analysis = 1  # Optional, defaults to 0 (initial analysis)

mispObject = MISPObject('file')
mispObject.add_attribute('filename', type='filename',
                         value='filename.exe',
                         Tag=[{'name': 'tlp:amber'}])

event.add_object(mispObject)

print(misp)
existing_event = misp.add_event(event, pythonify=True)

```

This throws an exception: pymisp.exceptions.PyMISPError: Invalid event

To have a control group, I tried this

```python
ekkk = misp.add_event(event)     # without pythonify=True
# ekkk show as [], an empty list
```

So I guess

* Even the formal tutorial instruction wouldn't let the "add_event" move correctly
* "add_event" still try to return ALL existing events, and there's none here. So it returns an empty list
* pythonify=True can't act correctly where the input is an empty list

**Comment by dragonyy** [comment]
### Conclusion

I misconfigure the misp_url to http, instead of httpS !!! That's why.

When 

```python
misp_url = 'http://192.168.56.112/'
```

PyMISP acts like what I mentioned in this issue.

While

```python
misp_url = 'https://192.168.56.112/'  # Note: httpS
```

PyMISP acts normally. I'm sorry to waste your time, pardon me.
