### ISSUE TITLE
How to preserve publishment timestamp

### ISSUE THREAD

**Issue by sustefil** [MISP/PyMISP#543]
Hi guys!

I am using PyMISP to alter some events (adding tags/comments to attributes). When I update the event, I do **not** want to republish it and keep the current publish timestamp (so I don't want to unpublish). Is there a way to do this please?

From what I understood so far, an altered event is automatically republished (when was published before), unless explicitly set to unpublished.

Thanks in advance!

**Comment by Rafiot** [comment]
When you modify an already published event, you *have to* republish it, that's how the synchronization is triggered.
