### ISSUE TITLE
Question: Is pagination handled by the pymisp.PyMISP.search function? 

### ISSUE THREAD

**Issue by fhightower** [MISP/PyMISP#544]
# Background

I'm using the `pymisp.PyMISP.search` function to pull data from a misp instance. I've tried with pymisp versions `2.4.95.1` and `2.4.119.1`.

# The Problem

When running the `search` function to pull all of the data:

```
d = {
    'published': 0,
    'date_from': '1970-01-01'
}
e = p.search(**d)
```

I get a 500 error:

```
{'errors': ["500 exception: {'name': 'An Internal Error Has Occurred.', 'message': 'An Internal Error Has Occurred.', 'url': '/events/restSearch/download'}"],
 'message': 'An Internal Error Has Occurred.',
 'name': 'An Internal Error Has Occurred.',
 'url': '/events/restSearch/download'}
```

There is a lot of data in the instance, so I'm guessing the 500 error is caused because I'm trying to get too much data from the instance. Is there any way to test this hypothesis?

If the problem is indeed that my search is requesting too much data, is there a way to paginate through the results in a way that won't error out?

Thanks in advance!

**Comment by iglocska** [comment]
First of all, make sure you update your misp. The later versions have much better handling if large data set fetching internally and you will probably altogether avoid memory exhaustions.

Pymisp should be able to take any additional parameters known to misp, so just pass limit and page along with the query.

To debug the exact cause of failure, check `/var/www/MISP/app/tmp/logs/error.log`

**Comment by fhightower** [comment]
Wonderful, thanks @iglocska !
