### ISSUE TITLE
Unable to return misp_types 

### ISSUE THREAD

**Issue by hongkiatsim** [MISP/PyMISP#545]
Hi,

I am new to python and have just attempted to use PyMISP to pull from our MISP provider. There is an example named get_csv.py.

When I used get_csv.py -e <eventid> -t url -a value, it returns all the value of all types. But I only needed URL. Am i doing something wrong or is it a bug?

Regards,
Isaac

**Comment by Rafiot** [comment]
One way to solve that is to edit the example script by adding `controller='attributes'`: 
```
response = pymisp.search(controller='attributes', return_format='csv', eventid=args.event_id, requested_attributes=attr, type_attribute=args.misp_types, include_context=args.context)
```
