### ISSUE TITLE
Update misp-objects to current

### ISSUE THREAD

**Issue by pettai** [MISP/PyMISP#549]
Please update misp-objects to current for this update https://github.com/MISP/misp-objects/commit/b457df2a3631c20f0daf34bac3fc7ae0ef69ebb9

**Comment by Rafiot** [comment]
Will do on monday, but feel free to do a PR.

**Comment by pettai** [comment]
short PR: the current intelmq_event object definition (v3), has text format on attributes used for RPZ data collection & generation, but those have been changed to be strictly typed in the new definition (v4).

**Comment by pettai** [comment]
ok this has been done now, closing
