### ISSUE TITLE
Suricata_search.py : MISPServerError: Error Code 500

### ISSUE THREAD

**Issue by KZcsirtCY** [MISP/PyMISP#555]
Dear Team,

Please, check the below error that appears:

Running the below command, results to Error 500
python3.6 suricata_search.py -p 'malware' -s 'APT25' - o msip_nids.rules
........
........
File "/home/../PyMISP/pymisp/api.py" line 2169, in _check_response
    raise MISPServerError(f'Error code 500:\n{response.text}')
pymisp.exceptions.MISPServerError: Error code 500:
{"name":"An Internal Error Has Occurred.","message": "An Internal Error Has Occurred.","url":"\/events\/restSearch"}

Added to the above, when running curl command, we get he below:
curl -k -H 'Accept:application/json' -H 'Authorization:-Our_API_Key' -H 'enforceWarninglist: 1' https://misp.xxxx.xxx/events/nids/suricata/download 
{"name":"An Internal Error Has Occurred.","message": "An Internal Error Has Occurred.","url":"\/events\/nids\/suricata\/download"}

Thank you

**Comment by iglocska** [comment]
Could you check the output of your error log right after running that query? Internal errors generate stack traces there:

`/var/www/MISP/app/tmp/logs/error.log `

**Comment by KZcsirtCY** [comment]
About the /var/www/MISP
I am running the suricata_search command in a different machine than the MISP one
So, there is no such folder on my /var/www/MISP

**Comment by KZcsirtCY** [comment]
According to error.log (finally found it), we have:
 Allowed memory size of 2[.]097[.]152[.]000 bytes exhausted (tried to allocate 1[.]465[.]988[.]032 bytes)

**Comment by KZcsirtCY** [comment]
According to error.log (finally found it), we have:
 Allowed memory size of 2[.]097[.]152[.]000 bytes exhausted (tried to allocate 1[.]465[.]988[.]032 bytes)

**Comment by Rafiot** [comment]
That script was broken beyond repair and relying on piece of code that don't exist anymore in PyMISP The new recommended approach is the one mentioned here: https://github.com/MISP/PyMISP/issues/561#issuecomment-607803229

**Comment by KZcsirtCY** [comment]
Great!
Thank you both for the great support!
I confirm that this issue is closed.
