### ISSUE TITLE
concurrent.futures and pymisp question... possible?

### ISSUE THREAD

**Issue by mathurin68** [MISP/PyMISP#559]
I was looking to speed up code like this... it does a search and either adds event or just a tag to an event; it works, but it's 1,000's of CEF events and its sooooo slow.  

Can MISP api handle concurrent.futures for adding events?  Full disclosure I could have it totally wrong my python is terrible. 

When I run it, it _seems_ to work buuuut the MISP instance has to catch up with everything.  

I'd definitely appreciate any thoughts or help.  

```
#My generic create_event
def create_misp_event(ioc, misp):
    date = datetime.datetime.utcnow()
    event = MISPEvent()
    event.distribution = 0 # This organization onl
    event.threat_level_id = 1 
    event.analysis = 2 # Completed
    event.info = "see Attr for details"
    event.date = date
    my_event = misp.add_event(event, pythonify=True)
    misp.tag(my_event, 'Generic')
    misp.tag(my_event, tag)
    misp.add_attribute(my_event, {'category': 'Network activity', 'type': 'ip-dst', 'to_ids': True,
                                                'comment': comment,'value': ioc}, pythonify=True)
#open list of CEF events
n_lgcef = open('new_lg.cef', 'r+')
def mispwork(n_lgcef):
	#move CEF to python dict
    d = pycef.parse(n_lgcef)
    ioc = dict.get(d,"src", "None")
	tag = dict.get(d,"deviceFacility", "None")
	comment = dict.get(d,"msg", "None")
	category = dict.get(d,"cat", "None")
	threatlevel = dict.get(d,"DeviceSeverity", "None")
	source = dict.get(d,"deviceFacility", "None")
	#search for current value in misp 
	response = misp.search(value=ioc)	
	#search for current value AND tag in MISP
	response2 = misp.search(value=ioc, tags=tag)	
	if(len(response)==0):
		#if value doesn't exist at all go ahead and create event
		create_misp_event(ioc, misp)
	elif(len(response)!=0 and len(response2)==0):
		#if value does exist and doesn't have tag just add the tag
		event_id = response[0]['Event']['id']
		event = misp.get_event(event_id)
		misp.add_attribute(event, {'category': 'Internal reference', 'type': 'other', 'value': tag,
											'comment': comment, 'disable_correlation':True}, pythonify=True)
		uuid = response[0]['Event']['uuid']
		misp.tag(uuid,tag)
	else:
		pass

with ThreadPoolExecutor(max_workers = 5) as executor:
    executor.map(mispwork, n_lgcef)
```

**Comment by Rafiot** [comment]
So it *should* work, but if you hammer MISP with too many query, you may have other issues (timeout, too much ram used, ...). 
I'll try to look at the code at some point next week.

**Comment by mathurin68** [comment]
Thanks!  I ended up removing the concurrent.futures and just tuning the database and it seems to be rolling now...

#Check What you've got
CPU:
cat /proc/cpuinfo | grep processor | wc -l

Swappiness:
cat /proc/sys/vm/swappiness

Memory:
free

###Tune MISP database###
/etc/mysql/mariadb.conf.d/50-server.cnf

innodb_buffer_pool_size = 2G
max_heap_table_size= 64M
tmp_table_size= 64M


#Swappiness
sysctl -w vm.swappiness=0

LINKS
http://linuxpitstop.com/tips-to-improve-mariadb-performance/
