### ISSUE TITLE
Suricata_search.py - list indices error 

### ISSUE THREAD

**Issue by erosseleth** [MISP/PyMISP#561]
The following command: 

(PyMISP) root@kali:~/PyMISP/examples/suricata_search# python3 suricata_search.py -p tags -s 'APT' -o misp_ids.rules -t 5

Brings me this error:

Traceback (most recent call last):
  File "suricata_search.py", line 213, in <module>
    format_request(args.param, args.search, misp, args.quiet, args.output, args.thread, args.noevent)
  File "suricata_search.py", line 163, in format_request
    search(misp, quiet, noevent, **kwargs)
 File "suricata_search.py", line 70, in search
    for event in result['response']:
TypeError: list indices must be integers or slices, not str**

Some help? Thanks

**Comment by Rafiot** [comment]
That script it completely outdated and used the old version of the API.

Now, the recommended way is to use `misp.search()` with `return_format='suricata'`, see https://pymisp.readthedocs.io/en/latest/modules.html#pymisp.PyMISP.search

I'll try to write a new script.
