### ISSUE TITLE
Unable to update event attributes (info, analysis, etc.)

### ISSUE THREAD

**Issue by bit111** [MISP/PyMISP#563]
Hello,
I'm using PyMISP 2.4.119 with a test instance of MISP v. 2.4.102.
When I try to update an event, basic informations are not updated:
```
misp = ExpandedPyMISP(MISP_URL,MISP_API,VERIFY_SSL,debug = DEBUG)
event = misp.get_event(EVENT_ID)
temp_event = MISPEvent()
temp_event.load(event)
# tag addition works
misp.tag(event.get('Event').get('uuid'), 'myTag')

temp_event.info = "New title"
temp_event.threat_level_id = 2 
temp_event.analysis = 2    
temp_event.distribution = 2

misp.publish(temp_event)
updated_event = misp.update_event(EVENT_ID, temp_event)
```

Where is the error?

**Comment by Rafiot** [comment]
Hello,

What is the content of `updated_event`? Also, the MISP instance you're using was released on Feb 1, 2019, so you should very much update it.

**Comment by bit111** [comment]
Hello,
the code `print("Event content: %s" % updated_event['Event']['info'])` gives the old title.
So, I have done other tests with a more recent MISP version:
- PyMISP 2.4.119 and MISP 2.4.123
- PyMISP 2.4.124 and MISP 2.4.123
but the result is the same. Tags and attributes are added, but basic informations (info, analysis, etc.)  are not.

**Comment by Rafiot** [comment]
Please try ` misp.update_event(temp_event, EVENT_ID)` -> 
https://pymisp.readthedocs.io/en/latest/modules.html#pymisp.PyMISP.update_event

**Comment by bit111** [comment]
Yes, it works!
This example had confused me: https://github.com/MISP/PyMISP/blob/master/examples/up.py#L21

**Comment by Rafiot** [comment]
Woops, right, that's one of the old examples I never updated... Thank you!
