### ISSUE TITLE
Many AttributeError

### ISSUE THREAD

**Issue by jack51706** [MISP/PyMISP#564]
I use python3.6 and git clond --recursive https://github.com/MISP/PyMISP.git
When I use pymisp/example/searchall.py
get error message like
AttributeError: 'PyMISP' object has no attribute 'search_all'

Is there anything wrong?

**Comment by Rafiot** [comment]
This call was deprecated over a year ago, and was removed on January 2020.

This is the documentation of the method you want to use: https://pymisp.readthedocs.io/en/latest/modules.html#pymisp.PyMISP.search
