### ISSUE TITLE
Publish_timestamp not work

### ISSUE THREAD

**Issue by lprat** [MISP/PyMISP#566]
Hi,
I try tu use publish_timestamp in search(), but it's not work correctly.
(i use last version of pymisp)
Exemple (tested on misp.circl):
>>> ret=misp.search(publish_timestamp='45d', value='X.X.X.X', to_ids='1', pythonify=true)
>>> ret
[]
>>> ret=misp.search(value='X.X.X.X', to_ids='1', pythonify=true)
>>> ret[0]['date']
datetime.date(2020, 3, 25)
>>>
I'm sorry, i thinking that publish_timestamp give all event between now() and now()-45days, i am wrong?
Thank for you help.
Lionel

**Comment by Rafiot** [comment]
So is the event `ret[0]` published? If it is not, it won't be returned.

Also the test is not done on the date you're printing, but against `publish_timestamp`

**Comment by lprat** [comment]
Hi Rafi,
I'am sorry! You are right, the event isn't published! I feel idiot ... publish_timestamp..publish!! Sorry! After reading manual (https://buildmedia.readthedocs.org/media/pdf/pymisp/latest/pymisp.pdf) , i found 'timestamp' parameter that work fine! 
Thanks for you help, and sorry yet!
Lionel

**Comment by Rafiot** [comment]
Yeah, it is not the most obvious thing: we have 3 different time-based search which all have different meanings ;)
