### ISSUE TITLE
Maybe invalid `test_user_settings` test

### ISSUE THREAD

**Issue by JakubOnderka** [MISP/PyMISP#568]
Hi,

I am trying to figure out why `test_user_settings` is failing after my change in MISP https://github.com/MISP/MISP/pull/5240.

If I understand correctly, this test sets user setting to receive alert mails just for events containing tag `test_publish_filter`, then is creates and publish two events, one with this tag and then without and change user password.

But this test asserts that 3 mails should be generated:

https://github.com/MISP/PyMISP/blob/5a78b63d9b7b2ee6751e1fae5e3aa65a5626b871/tests/testlive_comprehensive.py#L2033-L2036

But in reality two mails are generated (see https://travis-ci.org/github/MISP/MISP/jobs/679840838#L3401):

```
+------+---------------------------------------------------------------------------------------+---------------------+-------+----------+--------+---------+--------+--------------------+--------+-------------+----+
| id   | title                                                                                 | created             | model | model_id | action | user_id | change | email              | org    | description | ip |
+------+---------------------------------------------------------------------------------------+---------------------+-------+----------+--------+---------+--------+--------------------+--------+-------------+----+
| 1612 | Email to testusr@user.local sent, titled "[ORGNAME MISP] Event 71 - Low - tlp:amber". | 2020-04-26 21:16:45 | User  |        2 | email  |       0 |        | testusr@user.local | SYSTEM |             |    |
| 1613 | Email to testusr@user.local sent, titled "[ORGNAME MISP] Event 72 - Low - tlp:amber". | 2020-04-26 21:16:46 | User  |        2 | email  |       0 |        | testusr@user.local | SYSTEM |             |    |
+------+---------------------------------------------------------------------------------------+---------------------+-------+----------+--------+---------+--------+--------------------+--------+-------------+----+
```

So my questions are:
* why test asserts that 3 e-mails should be generated?
* why e-mail is send for both events, when just one contains tag from filter?

**Comment by Rafiot** [comment]
We're working with two different users in the test: 
* `self.user_misp_connector` with no filters
* `self.admin_misp_connector` with a filter 

`self.admin_misp_connector` will only receive a mail for one of the two published events, when `self.user_misp_connector` receives one email for each. So I think the test is correct.

**Comment by JakubOnderka** [comment]
Aha, I see now. 

But the problem is that admin user has disabled autoalert so no e-mails should be send to him. So maybe first step in test should be enable autoalert to admin user?

**Comment by Rafiot** [comment]
Hmmm but was it enabled by default, and you disabled it in your PR? I can definitely enforce the autoalert on the admin in the test case (but as we would change the default behaviors, I'll ping @iglocska)
Also, it doesn't explains why the test pass on PHP8, bit not on 7.x.

**Comment by JakubOnderka** [comment]
I think it is disabled by default. User table definition contains 
```
`autoalert` tinyint(1) NOT NULL DEFAULT 0,` 
```
and during creating admin user this value is not changed (see https://github.com/MISP/MISP/blob/6bff2397406f5fee3d395e7fab98f14e4f3ab4fc/app/Model/User.php#L1226).

And for PHP8, the test pass probably because no e-mail is sent (now I don't know why).

**Comment by Rafiot** [comment]
Alright, it was probably passing on travis because no mails were sent at all. And my test environment has mails enabled on the admin user for some reason.

I'll bump the test case to fix that.

**Comment by Rafiot** [comment]
That should fix it: https://github.com/MISP/PyMISP/commit/0faa75824f4dbac2b14919bb17e9d0fef79026d7

**Comment by JakubOnderka** [comment]
Fixed, thanks!
