### ISSUE TITLE
PyMISP.add_event(MISPEvent) - Orgc_id cannot be empty

### ISSUE THREAD

**Issue by JoeP-oss** [MISP/PyMISP#569]
# Server
MISP: 2.4.124 (via https://github.com/amuehlem/MISP-RPM/)

# Client
PyMISP: 2.4.124 (via pip3)
Python: 3.8.2

# Goal
I have an external feed that arrives as XML, i'm filtering this down to relevant IPs and splitting those by event; I'm then trying to add the events into MISP via PyMISP, once created I want to update the same events (adding and removing attributes) based on the feed.

# Error
I keep getting `Orgc_id cannot be empty` when adding despite setting Orgc and Orgc_id too; just setting Orgc has the same issue and just setting Orgc_id adds the event but the creator is set to the local org not the feed provider. 

I assume I'm missing something; but cannot work out what from the documentation.

# Sample Script
```python
#!/usr/bin/env python3
from datetime import datetime
from json import load, dump
from uuid import uuid4
from xml.dom.minidom import parse
from pymisp import PyMISP, MISPEvent

# code which filters and sorts events into a dict (eventIps) with str keys and list values

pymisp = PyMISP('http://misp/',
                "123456789012345678901234567890", tool="XMLFeedProcessor")
localOrg = pymisp.get_organisation('00000000-0000-0000-0000-000000000000')
feedProvider = pymisp.get_organisation('11111111-1111-1111-1111-111111111111')
with open('eventIds.json', 'r') as idFile:
    # file containing event name to UUID mappings
    eventIds = load(idFile)
for eventName, ips in eventIps.items():
    if eventName not in eventIds:
        # new event from feed
        eventIds[eventName] = str(uuid4())
        with open('eventIds.json', 'w') as idFile:
            dump(eventIds, idFile)
    mispEvent = MISPEvent()
    mispEvent.analysis = 1
    mispEvent.date = datetime.now()
    mispEvent.distribution = 0
    mispEvent.info = eventName
    mispEvent.Org = localOrg
    mispEvent.Org_id = localOrg['Organisation']['id']
    mispEvent.Orgc = feedProvider
    mispEvent.Orgc_id = feedProvider['Organisation']['id']
    mispEvent.add_tag('local:tag:here')
    mispEvent.threat_level_id = 2
    mispEvent.timestamp = datetime.now()
    mispEvent.uuid = eventIds[eventName]
    for ip in ips:
        mispEvent.add_attribute('ip-dst', to_ids=True, value=ip)
    mispEvent.publish()
    existingEvent = pymisp.search(uuid=mispEvent.uuid)
    if type(existingEvent) == list and len(existingEvent) == 0:
        # Search succeeded and event doesn't exist
        add = pymisp.add_event(mispEvent)
        if 'errors' in add:
            # This is always reached
            exit(2)
    elif type(existingEvent) == list:
       # search succeeded and event exists
        update = pymisp.update_event(mispEvent)
        if 'errors' in update:
            exit(3)
    else:
        exit(4)
```

**Comment by Rafiot** [comment]
Ok, so you're not supposed to set the organization yourself. Instead, the expected way is to push the feed as a user **member of the organization** you want to use. We do not allow impersonating other organization as a normal user.

**Comment by JoeP-oss** [comment]
Owner org should be my organisaiton, however, creator org should be the feed provider, if that makes sense.

**Comment by Rafiot** [comment]
yeah, you cannot do that unless you're a sync user, and we strongly recommend not to do that.

One way to do it is to create a dummy org and use it for encoding the data, but creator and owner will be the same. 

@iglocska any further remarks on that?

**Comment by mokaddem** [comment]
My 2 cents here..
I would avoid playing around with organisation and let MISP do the job.

What you could do:
- Create a *sync_user* in the Organisation that will own the event
- Use this *sync_user* to push the data
```
{
     "info": "The Event Name ",
     "Orgc": {
        "uuid": "5ea7e731-e164-4ae3-938b-600c0a21020f",
        "name": "The name of the Org that will be marked as the creator of the data. If the UUID does not exists in MISP yet, it will create a `local` Organisation on the fly which will be reused on subsequent queries."
    }
}
```

**Comment by Rafiot** [comment]
Excellent :)

**Comment by JoeP-oss** [comment]
Thanks I'll try setting up another local org, adding a sync user to it and getting the sharing right back to the 'real' local organisation.

The error I was getting was due to `get_organisation()` returning a `dict` object and not a `MISPOrganisation` object, the fix for that was this (successfully adds as admin user):

```python
FeedProvider = MISPOrganisation()
FeedProvider.from_json(dumps(pymisp.get_organisation('11111111-1111-1111-1111-111111111111')))
```

I couldn't get `from_dict()` to work

**Comment by Rafiot** [comment]
yes, you need to pass `pythonify=True` to get the `MISPOrganisation`
