### ISSUE TITLE
Increase Resources for PyMisp Search

### ISSUE THREAD

**Issue by nbyt3** [MISP/PyMISP#570]
Currently installed version… v2.4.124 (fb26771e6c68005310bb51250b463a49ffee96a4)
Ubuintu 18.04
32GB RAM
10CPU
max_execution_time (1200)… OK (recommended: 300)
memory_limit (16032M)… OK (recommended: 2048M)
upload_max_filesize (50M)… OK (recommended: 50M)
post_max_size (50M)… OK (recommended: 50M)

Is there a way to increase the resources for PyMisp Search? We are moving to the search APIin order to backup the events and attributes, as well as export the effective Attributes. Are there settings on MISP to give those services more resources?

**Comment by Rafiot** [comment]
Not sure what you mean by "increase the resources for PyMisp Search". You can for example use pagination (page and limit keys) if the response of the server it too big.

**Comment by mokaddem** [comment]
Also, if you would like to increase these values, you'll have to edit your `php.ini`

**Comment by nbyt3** [comment]
I am exporting all events and attributes from MISP as a means to create feeds for various tools. I was wondering if there was any way to increase the resources used in the rest search API endpoint. I've increased the Execution Time and Memory limit (16GB). Are there any other configuration settings that would increase the response time from the rest API endpoint "Search"? Im also using the export Events Rest Search as a means to export all events and back them up in an external Storage resource. 

Thanks.

**Comment by Rafiot** [comment]
Sorry, I forgot about this issue.

Yes, you can use the pagination feature (keys `page` and `limit`)
