### ISSUE TITLE
question re' pymisp.update_feed treatment of settings

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#574]
2.4.125

We are attempting to enable/disable Default Feeds via `PyMISP.update_feed` and are seeing the content of the `feeds.settings` column changing different than expected. Would appreciate the right way to make cases 1 and 3 below work as expected. **Thanks**...

1. **Disable with a mostly barren `MISPFeed` -- `settings` becomes `[]`**:
* 1.1 Code:
```
mispFeed = MISPFeed()
mispFeed.id      = 1
mispFeed.enabled = False
pymisp.update_feed(mispFeed)
```
* 1.2 Before
```
MariaDB [misp]> select settings from feeds where id=1;
+------------------------------------------------------------------+
| settings                                                         |
+------------------------------------------------------------------+
| {"csv":{"value":"","delimiter":""},"common":{"excluderegex":""}} |
+------------------------------------------------------------------+
```
* 1.3 After
```
MariaDB [misp]> select settings from feeds where id=1;
+----------+
| settings |
+----------+
| []       |
+----------+
```

---- o ----

2. **Disable with a fully populated `MISPFeed` -- works well**:
* 2.1 Code:
```
mispFeed = pymisp.get_feed(1)
mispFeed.enabled  = False
mispFeed = pymisp.update_feed(mispFeed)
```
* 2.2 This works: `settings` Before and After are UNCHANGED as expected

---- o ----

3. **Related: Defining `settings` -- escapes the JSON quotes with backslashes**:
* 3.1 Code
```
mispFeed = MISPFeed()
mispFeed.id       = mispFeed.id
mispFeed.enabled  = False
mispFeed.settings = '{"csv":{"value":"","delimiter":""},"common":{"excluderegex":""}}'
mispFeed = pymisp.update_feed(mispFeed)
```
* 3.2 Before
```
MariaDB [misp]> select settings from feeds where id=1;
+------------------------------------------------------------------+
| settings                                                         |
+------------------------------------------------------------------+
| {"csv":{"value":"","delimiter":""},"common":{"excluderegex":""}} |
+------------------------------------------------------------------+
```
* 3.3 After
```
MariaDB [misp]> select settings from feeds where id=1;
+------------------------------------------------------------------------------------+
| settings                                                                           |
+------------------------------------------------------------------------------------+
| "{\"csv\":{\"value\":\"\",\"delimiter\":\"\"},\"common\":{\"excluderegex\":\"\"}}" |
+------------------------------------------------------------------------------------+
```

**Comment by Rafiot** [comment]
1. is a bug -> https://github.com/MISP/MISP/issues/5896 
The work around for now it to enable/disable fully populated feeds only

3. The solution for you is to pass a python dictionary to the `settings` parameter, and not a json string. There was a bug in PyMISP where I wasn't json decoding the value when while loading an existing feed into `MISPFeed`, it is fixed now in PyMISP master branch and will be in next release of the package.

**Comment by github-germ** [comment]
Thanks @Rafiot !!
