### ISSUE TITLE
search for tags and specific attribute values

### ISSUE THREAD

**Issue by bernhardreiter** [MISP/PyMISP#575]
It is interesting to search for tags and if several attributes have special values.

For example how can misp.search() be used to get events where attribute `source.ip == "192.168.10.1"' and 'feed.provider == "OpenFish"' and not the ones where one of the strings is in a different attribute. And then only if one or several tags are present as well.

The documentation  and examples I've found do not show such a possibility.
If it is there, how is is used? Maybe an example can be added to the documentation.

Checked:
 * https://github.com/MISP/PyMISP/blob/master/docs/tutorial/Search-FullOverview.ipynb
 * https://pymisp.readthedocs.io/en/latest/modules.html?highlight=search#pymisp.PyMISP.search
 * https://pymisp.readthedocs.io/en/latest/modules.html?highlight=build#pymisp.PyMISP.build_complex_query

**Comment by Rafiot** [comment]
Just to make sure I understand what you want to do: You want to do a query where you search for a list of of different types (say a hash, a domain and a bitcoin address), and a list of tags?

**Comment by bernhardreiter** [comment]
The use case comes from the IntelMQ MISP API Output bot, where we want to identify if a certain
intelmq event has already made it into MISP. Right now the code searches for a special tag and then just for the combined existance of several values.  But as I understand it, the values can be anywhere in the found MISP events. As I understood the tutorial and documentation I could search for controllers=attribute, but still I could not search for a special atttribute with (a certain object_relation like feed.provider) and its value.

Maybe my understanding of MISP is too limited, so I had to ask. :)

**Comment by Rafiot** [comment]
object_relation is specially for an object, and in order to search for that, you will need to use the `controller=objects`, and this one is far from being ready for prime time.

I started to write a couple test cases here: https://github.com/MISP/PyMISP/blob/master/tests/testlive_comprehensive.py#L297
But it will need lot more work.

**Comment by parosio** [comment]
Hello, I'm new to MISP complex query too... 
Need to find attibutes of specified type with / without specific tags.
I found a useful example [here ](https://github.com/MISP/PyMISP/issues/316#issuecomment-528000957). 
Hope this would be helpful to you too.

**Comment by bernhardreiter** [comment]
@parosio thanks for the hint!

I took a short look and as far as I understand, this does not solve my use case. I think that one way resolving this issue would be to write more examples or documentation. So I leave it to the MISP devs what to do with the issue.

**Comment by mokaddem** [comment]
@bernhardreiter I'm sure to understand what type of you are dealing with. I you wish to search for Attribute value with some tags, you can do something like this:
```
/attributes/restSearch
{
    "returnFormat": "json",
    "value": ["192.168.10.1"],
    "tags": {
        "AND": ["tlp:green", "C2", "feedProvider:OpenFish"],
        "NOT": ["%feedProvider:CIRCL%"]
    }
}
```
So if you have tagged the Attribute or Event with a `feedProvider` tag, you will be able to find i back.
You can find more example here: [MISP API examples](https://github.com/MISP/misp-training/blob/master/a.7-rest-API/Training%20-%20Using%20the%20API%20in%20MISP.ipynb)

However, if you have truly created an `ObjectReference` between a **MISP Object** and a **MISP Attribute**, we are indeed lacking the search feature.
