### ISSUE TITLE
PyMISP version

### ISSUE THREAD

**Issue by Rickozono** [MISP/PyMISP#576]
I having trouble with the PyMISP version.
I updated following the commands in this link: https://www.circl.lu/doc/misp/updating-python/
# Update PyMISP
cd /var/www/MISP/PyMISP
sudo -H /var/www/MISP/venv/bin/pip install -U .
the output said: Successfully installed pymisp-2.4.125
But in my misp instance, in the Server Settings & Maintenance section, doesn´t appear my PyMISP version
![Issue](https://user-images.githubusercontent.com/51711170/81826506-3c2ec400-950e-11ea-9aee-c84b49f76a79.jpg)

Any ideas how to solve this?
Thanks for any reply

**Comment by bernhardreiter** [comment]
Did you restart your misp instance. (So that importing of the modules is tried again?)

**Comment by Rickozono** [comment]
How do I restart my misp instance?

**Comment by bernhardreiter** [comment]
Restarting probably depends on how you've installed it in the first place. In some settings a `apachectl graceful` maybe enough, but I'm just guessing.

**Comment by Rickozono** [comment]
I tried restarting apache but didn't work.
I 've installed MISP this way:

wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh
wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -A

**Comment by Rafiot** [comment]
This is weird, because it seems to be completely failing.

can you try the following: 
`sudo -H /var/www/MISP/venv/bin/python /var/www/MISP/app/files/scripts/generate_file_objects.py -c`

It is the command MISP is running, and it should return a json blob.

**Comment by Rickozono** [comment]
Here is the error it returned that command
![Issue](https://user-images.githubusercontent.com/51711170/81934923-28469900-95c6-11ea-824f-55fb16bb341f.jpg)

**Comment by Rafiot** [comment]
aha, makes sense, that's a bug we found a couple of days ago... that's annoying.
This command should fix it: 
`sudo -H /var/www/MISP/venv/bin/pip install -U pyfaup`

**Comment by Rickozono** [comment]
That fixed it! Thanks you for your help!

**Comment by Rafiot** [comment]
Excellent! Thank you for the feedback.
