### ISSUE TITLE
search: be robust against empty AND strings to search for

### ISSUE THREAD

**Issue by bernhardreiter** [MISP/PyMISP#577]
Using pymsip  '2.4.125', when searching the following  way:

```python3
l = ["bad.example.org",""]
q = misp.build_complex_query(and_parameters=l)
print(q)
# {'AND': ['bad.example.org', '']}
r = misp.search(tags="Inserted-by:IntelMQ", value=q)
```

will lead to r having all events, not just the ones that match "bad.example.org".
(And it takes a long time as well.)

Expected behaviour:
 * only the ones matching a non-empty string will be returned
 * (alternatively) throws an exeception which is documented in search()

**Comment by Rafiot** [comment]
I will remove the empty string(s) in the search query, this is the easiest (on PyMISP side). We may want to filter that out on MISP side, but the clean solution to that is to use limit/page if you do not have a control on the request passed by a user.

**Comment by bernhardreiter** [comment]
Thanks, there is a second bad case, closely related:

```python3
l = []
q = misp.build_complex_query(and_parameters=l)
print(q)
# {}
r = misp.search(tags="Inserted-by:IntelMQ", value=q)
```
It runs a very long time (measuring still ongoing almost 30 minutes now)

**Comment by Rafiot** [comment]
Well, in that case, the solution for PyMISP is to just strip the value parameter (that would be the same): it is a valid query, even if it takes a very long time. We cannot forbid these queries all together.
In that situation, you *really* want to pass the limit and page parameters. I could potentially add a default limit to something like 1000, maybe. But it will totally depend on the resources you have available server side.

**Comment by bernhardreiter** [comment]
There were only <780 events in this MISP VM, but it was a small VM. 
It is a bit unclear why finding and returning 780 events would take more than 30 minutes and lots of memory. (of course we are using `misp.toggle_global_pythonify()`, which says that it needs lots of memory). Thanks for the hint with the limit.

**Comment by Rafiot** [comment]
30 min is very long, that's in fact weird. How big are the events? 

pythonify is only done at the end, and shouldn't take a lot of time (just a substantial amount of memory).

**Comment by bernhardreiter** [comment]
What is a good measure for the size of events (and how should I measure them?)

**Comment by Rafiot** [comment]
I'd start with the statistics page: https://<MISP>/users/statistics

It will give you an idea on how many attributes you have on the platform. @iglocska do you have an other idea?

**Comment by bernhardreiter** [comment]
It's not a lot

Events 948 (+659)
Attributes15475 (+10524) 
Attributes / event 16 
Correlations found593617

**Comment by Rafiot** [comment]
No, but that's *a lot* of correlations.

How is the system coping right now?

**Comment by bernhardreiter** [comment]
It is a test system, some events with many correlations are probably bogus. I was just wondering about the non-linearity of the performance. I guess I'll clear out the system at some point. So consider this resolved for now and thanks for the assistance. (I'll just wanted to make sure that there is not something bad going on.)

**Comment by Rafiot** [comment]
You're welcome. 

Yeah, I'd investigate the load on the system, because I don't see obvious reason it would take so much time.
