### ISSUE TITLE
search(controller='attributes', eventid=id, timestamp=t) no matches when should be?

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#578]
2.4.125

am i doing something silly? thx...

```pymisp.search(controller='attributes', eventid=id, timestamp=t)```

where `t` could be something like `'1d'` or an epoch `int`, and there are definitely attributes that are newer than that `t`, i get no matches. same on 2.4.118 does yield attrs that match.

**Comment by github-germ** [comment]
btw, setting `timestamp=0` as above does return all the attributes within that event as expected.

**Comment by packet-rat** [comment]
Folks - if confirmed this seems like a 'show-stopper' for 2.4.125?

**Comment by mokaddem** [comment]
Hey, such query is working as excepted for me (2.4.125)
```
/attributes/restSearch
{
    "returnFormat": "json",
    "eventid": 413,
    "timestamp": 1588847809
}
```
Could you provide more details so that I can reproduce it?
Thanks in advance

**Comment by iglocska** [comment]
Confirmed, just tested it too. Took a 2.4.125 instance. Data is a few days old all around, updated a single attribute, searched for it the same way as @mokaddem, only difference was that timetamp was set to "1d". It correctly returned 1 attribute as expected.

**Comment by Rafiot** [comment]
For the records, this is a test case that does exactly what you want to do: https://github.com/MISP/PyMISP/blob/master/tests/testlive_comprehensive.py#L2217

With one single difference (unless you're using PyMISP from the repository):
This line:
`first_meta_only[0].add_attribute(**attr_to_update)`
needs to be replaced by
`first_meta_only[0].add_attribute(**attr_to_update.jsonable())`

**Comment by github-germ** [comment]
Interesting... Let me re-test on my end. Appreciate everyone jumping in!!

Before I get started... Our 2.4.125 is the "official" without any patches. Thanks!

**Comment by Rafiot** [comment]
If you still have it on your end, we need a sample script (with a MISP event) that shows the issue. Otherwise, there is nothing we can do.

**Comment by github-germ** [comment]
After constructing a more detailed test script I have the same strange, unexpected results with the timestamp no seemingly retrieving the attributes that meet the criterion.

Here's the test results. I'll also attach the test script.

### 1. **Test on 2.4.125 (this is the official release with no patches)**

1.1 **FAILURE**: `timestamp` criteria not matching when expected it to match
```
$ python3 ./github-578.py AUTHKEY  174064 1589386000
eventId: 174064, timestamp: 1589386000

MISP: 2.4.125, PyMISP: 2.4.125

retrieve all attrs in event
---------------------------
search(controller='attributes', eventid=174064): 4 attrs
attr: id=95535886, value=111.111.111.112, timestamp=1589387000, >=True
attr: id=95535887, value=111.111.111.113, timestamp=1589298518, >=False
attr: id=95535888, value=111.111.111.114, timestamp=1589290000, >=False
attr: id=95535889, value=111.111.111.111, timestamp=1589387000, >=True

retrieve attr newer than timestamp
----------------------------------
search(controller='attributes', eventId=174064, timestamp=1589386000): 0 attrs
$ 
```

1.2 **SUCCESS**: get matches when `timestamp=0`
```
mg973b@misp-930:~/src/misp/test python3 ./github-578.py AUTHKEY  174064 0
eventId: 174064, timestamp: 0

MISP: 2.4.125, PyMISP: 2.4.125

retrieve all attrs in event
---------------------------
search(controller='attributes', eventid=174064): 4 attrs
attr: id=95535886, value=111.111.111.112, timestamp=1589387000, >=True
attr: id=95535887, value=111.111.111.113, timestamp=1589298518, >=True
attr: id=95535888, value=111.111.111.114, timestamp=1589290000, >=True
attr: id=95535889, value=111.111.111.111, timestamp=1589387000, >=True

retrieve attr newer than timestamp
----------------------------------
search(controller='attributes', eventId=174064, timestamp=0): 4 attrs
attrTs: id=95535886, value=111.111.111.112, timestamp=1589387000
attrTs: id=95535887, value=111.111.111.113, timestamp=1589387000
attrTs: id=95535888, value=111.111.111.114, timestamp=1589387000
attrTs: id=95535889, value=111.111.111.111, timestamp=1589387000
$ 
```

### 2. **Test on 2.4.121 (this is the official release with no patches)**

2.1 **SUCCESS**: `timestamp` criteria matches as expected
```
$ python3 ./github-578.py AUTHKEY 587379 1589386000
eventId: 587379, timestamp: 1589386000

MISP: 2.4.121.1, PyMISP: 2.4.121.1

retrieve all attrs in event
---------------------------
search(controller='attributes', eventid=587379): 4 attrs
attr: id=21102607, value=111.111.111.111, timestamp=1589387000, >=True
attr: id=21102608, value=111.111.111.112, timestamp=1589387000, >=True
attr: id=21102609, value=111.111.111.113, timestamp=1589298518, >=False
attr: id=21102610, value=111.111.111.114, timestamp=1589290000, >=False

retrieve attr newer than timestamp
----------------------------------
search(controller='attributes', eventId=587379, timestamp=1589386000): 2 attrs
attrTs: id=21102607, value=111.111.111.111, timestamp=1589290000
attrTs: id=21102608, value=111.111.111.112, timestamp=1589290000
$ 
```

2.2 **SUCCESS**: `timestamp=0` also works as expected
```
$ python3 ./github-578.py AUTHKEY 587379 0
eventId: 587379, timestamp: 0

MISP: 2.4.121.1, PyMISP: 2.4.121.1

retrieve all attrs in event
---------------------------
search(controller='attributes', eventid=587379): 4 attrs
attr: id=21102607, value=111.111.111.111, timestamp=1589387000, >=True
attr: id=21102608, value=111.111.111.112, timestamp=1589387000, >=True
attr: id=21102609, value=111.111.111.113, timestamp=1589298518, >=True
attr: id=21102610, value=111.111.111.114, timestamp=1589290000, >=True

retrieve attr newer than timestamp
----------------------------------
search(controller='attributes', eventId=587379, timestamp=0): 4 attrs
attrTs: id=21102607, value=111.111.111.111, timestamp=1589290000
attrTs: id=21102608, value=111.111.111.112, timestamp=1589290000
attrTs: id=21102609, value=111.111.111.113, timestamp=1589290000
attrTs: id=21102610, value=111.111.111.114, timestamp=1589290000
$ 
```

**Comment by github-germ** [comment]
Here's my test script:
```
$ python3 ./github-578.py
Usage: github-578.py authkey eventId timestamp
$ 
```

[github-578.py.txt](https://github.com/MISP/PyMISP/files/4630619/github-578.py.txt)

**Comment by Rafiot** [comment]
As far as I can tell, it is exactly what I'm doing here: https://github.com/MISP/PyMISP/blob/master/tests/testlive_comprehensive.py#L2287

And this test pass fine.

**Comment by github-germ** [comment]
So... then what are possible diffs to cause my behavior? Are you testing on the 2.4.125 as released without any patches? If so, what else can I do to try to isolate what's going on here? THANKS!!

**Comment by github-germ** [comment]
Can you run my script to be sure?

**Comment by Rafiot** [comment]
Yes, this script is in the CI suite, it runs against the HEAD, with no patch.

the following snippet is definitely incoherent btw, 1589386000 > 1589290000, you should receive the two other attributes.

```
retrieve attr newer than timestamp
----------------------------------
search(controller='attributes', eventId=587379, timestamp=1589386000): 2 attrs
attrTs: id=21102607, value=111.111.111.111, timestamp=1589290000
attrTs: id=21102608, value=111.111.111.112, timestamp=1589290000
$ 
```

I'll let you investigate that further.

**Comment by github-germ** [comment]
> the following snippet is definitely incoherent btw, 1589386000 > 1589290000, you should receive the two other attributes.

True, true. That was merely a typo in the script. I'll attache the correct ony.
```
diff github-578.py github-578-typo.py
95c95
<         ts = int(attrTsDict['timestamp'].timestamp())
---
>         ts = int(attrDict['timestamp'].timestamp())
```

So, the cosmetically corrected WORKING output on 2.4.121 is:
```
retrieve attr newer than timestamp
----------------------------------
search(controller='attributes', eventId=587379, timestamp=1589386000): 2 attrs
attrTs: id=21102607, value=111.111.111.111, timestamp=1589387000
attrTs: id=21102608, value=111.111.111.112, timestamp=1589387000
```

> I'll let you investigate that further.

OK, can you tell me how I can see the MySQL `select` that the `pymisp.search` triggers on the server side please?

**Comment by github-germ** [comment]
[github-578.py.txt](https://github.com/MISP/PyMISP/files/4634967/github-578.py.txt)

**Comment by Rafiot** [comment]
```bash
$ (git::master) python 578.py <key> 885 1589554180
eventId: 885, timestamp: 1589554180

MISP: 2.4.125, PyMISP: 2.4.125

retrieve all attrs in event
---------------------------
search(controller='attributes', eventid=885): 2 attrs
attr: id=5077, value=1.2.3.4, timestamp=1589554178, >=False
attr: id=5078, value=6.7.8.9, timestamp=1589554189, >=True

retrieve attr newer than timestamp
----------------------------------
search(controller='attributes', eventId=885, timestamp=1589554180): 1 attrs
attrTs: id=5078, value=6.7.8.9, timestamp=1589554189

```

**Comment by Rafiot** [comment]
No idea what is happening on your side, but your script work for me.

**Comment by Rafiot** [comment]
Oh, and your other question, the search query. You need to do the following:
1. enable sql debug in the configuration
2. append `/sql:1` to the URL (you need to do that manually in PyMISP library)
3. re-run your query, the sql output will be in the response

**Comment by github-germ** [comment]
### I KNOW WHY THIS HAS BEEN FAILING NOW!!!

Thank you for working this thru with me. So sorry to steal your valuable cycles. A teachable moment for me. :-)

In working thru the use case I was actually trying to prototype (but I never really got to that with i now understand to be a _false discovery_), I had setup these events via the WebUI, and then updated the `attributes.timestamp` columns for those attrs in the db to model my use case.

* I did NOT update the `events.timestamp`.
* the actual db `select` as you will see below looks not only at `attributes.timestamp` **but also `AND`s `events.timestamp`**.

**I ran my test script again with `events.timestamp` updated (which is clearly what the MISP server code does, but not my manual setup), and all is happy now :-)**

### Details
> OK, can you tell me how I can see the MySQL select that the pymisp.search triggers on the server side please?

OK, got it... Turned on MySQL logging with:
```
SET GLOBAL log_output = 'TABLE';
SET GLOBAL general_log = 'ON';
```

And then got the query with:
```
SELECT * FROM mysql.general_log where argument like '%174064%';
```

This is the query which I than ran manually to see no results as per my script:




```
MariaDB [misp]> SELECT `Attribute`.*, `Event`.`org_id`, `Event`.`distribution`, `Event`.`id`, `Event`.`info`, `Event`.`orgc_id`, `Event`.`uuid`, `Object`.`id`, `Object`.`distribution`, `Object`.`sharing_group_id`, (CASE WHEN `Attribute`.`value2` = '' THEN `Attribute`.`value1` ELSE CONCAT(`Attribute`.`value1`, '|', `Attribute`.`value2`) END) AS  `Attribute__value`, `Attribute`.`id` FROM `misp`.`attributes` AS `Attribute` LEFT JOIN `misp`.`events` AS `Event` ON (`Attribute`.`event_id` = `Event`.`id`) LEFT JOIN `misp`.`objects` AS `Object` ON (`Attribute`.`object_id` = `Object`.`id`)  WHERE ((((`Event`.`id` = (174064)) AND (`Attribute`.`timestamp` >= 1589386000) AND (`Event`.`timestamp` >= 1589386000))) AND ((`Attribute`.`deleted` + 0) = 0))    LIMIT 10485760;
Empty set (0.00 sec)

MariaDB [misp]> 
```

**Comment by Rafiot** [comment]
... Next time, please, start by saying that you messed up with the database, that would in fact spare everyone lots of cycles.

**Comment by iglocska** [comment]
I wonder how you've managed to update an attribute's timestamp in MISP without updating the event timestamp. Was it through the MISP API? If the answer is no and you directly updated data in the db - please do not open any more issues without pre-facing with this and even in those cases our answer will most likely be that we cannot help you until you stop circumventing the MISP mechanisms.

**Comment by github-germ** [comment]
Yes, I agree!!

Mea culpa... As I apologized and stated above
> A teachable moment for me. :-)

I did not expect that the query would `AND` in `events.timestamp`. My bad.

**Comment by Rafiot** [comment]
For future reference: do not ever touch the database, easy, simple, and reproducible rule.
