### ISSUE TITLE
Misbehaving event

### ISSUE THREAD

**Issue by sustefil** [MISP/PyMISP#581]
Hi guys,

we have some weird problem with specific events. We are running a constant enrichment script which attaches tags to events (calls update_event), and worked pretty fine until it encountered specific feed of events. If an update_event method is called upon one of these events, on the client-side, I get this error:

```
Traceback (most recent call last):
  File "/home/administrator/git/misp-g2-enricher/misp_g2_enricher.py", line 231, in submit_g2_data_to_misp
    misp.update_event(event_to_update)
  File "/home/administrator/git/misp-g2-enricher/venv/lib/python3.6/site-packages/pymisp/aping.py", line 235, in update_event
    updated_event = self._check_response(updated_event, expect_json=True)
  File "/home/administrator/git/misp-g2-enricher/venv/lib/python3.6/site-packages/pymisp/aping.py", line 2160, in _check_response
    raise MISPServerError(f'Error code 500:\n{response.text}')
pymisp.exceptions.MISPServerError: Error code 500:
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/5ec1eaf9-5bfc-4d79-988d-a8a9c0a8f02c"}

```

On the server-side, I can see a bunch of errors like this one.
```
2020-05-18 23:52:47 Error: [PDOException] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
Request URL: /events/5ec0f609-f98c-4a1b-b750-146cc0a8f02c
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('UPDATE `misp`.`...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(425): DboSource->execute('UPDATE `misp`.`...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1926): Mysql->update(Object(Event), '`id` = 1180624,...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Model/Event.php(5651): Model->save(Array)
#6 /var/www/MISP/app/Model/MispObject.php(696): Event->unpublishEvent('1180624')
#7 /var/www/MISP/app/Model/Event.php(3713): MispObject->editObject(Array, '1180624', Array, Object(Log))
#8 /var/www/MISP/app/Controller/EventsController.php(2338): Event->_edit(Array, Array, '1180624')
#9 [internal function]: EventsController->edit('1180624')
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
```

The same errors are observed when creating this event's Objects, where they are just catched and ignored. As a result, the event then has some empty objects, like here:

![image](https://user-images.githubusercontent.com/32512488/82341649-fd5aab80-99f0-11ea-93dc-5e9c79f8eb83.png)

Any ideas how to tackle the error?
 `Error: [PDOException] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction`

The MISP instance is pretty heavy. Can the DB be overloaded?

Thanks in advance!

**Comment by Rafiot** [comment]
yeah, it is generally the BD being overloaded. 
Are you pushing lots of events at the same time?

**Comment by sustefil** [comment]
Well, not really, I would say few dozens in few minutes, but this hasn't been a problem since this event came up.

And the error is always occurring with these particular event and not with other events,
so it doesn't seem to be caused by general DB overload.

Truth is, that these particular events are heavy (have few thousands attributes).

Any idea how to resolve this?

**Comment by Rafiot** [comment]
A few thousands of attributes (or is it objects?) shouldn't be a problem, unless the machine MISP is running on is severely limited in ram.

**Comment by sustefil** [comment]
There are lots of objects indeed (the attributes are grouped in domain-ip manner, to have the ability to have distinct tags for ip/domain), could that be a problem?

#Attributes 4394 (3090 Objects)

the RAM is fine, 24 GB and it rarely exceeds 50 % usage.

**Comment by Rafiot** [comment]
Hmmmm this should definitely not be an issue then. And the I/O are also fine?

**Comment by sustefil** [comment]
Closing issue, we just temporarily disabled these events. If we find the cause/solution, I will let you know :) 
Thanks
