### ISSUE TITLE
allow configurable timeout

### ISSUE THREAD

**Issue by cvandeplas** [MISP/PyMISP#584]
PyMISP assumes the server configured in the URL is up and running.
When connecting to a server that does not respond to a TCP handshake PyMISP waits about 120 seconds before raising a `PyMISPError`: `PyMISPError: Unable to connect to MISP (https://1.2.3.4). Please make sure the API key and the URL are correct (http/https is required): HTTPSConnectionPool(host='1.2.3.4', port=443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f796dda16d8>: Failed to establish a new connection: [Errno 110] Connection timed out',))`

It would be very nice if we could configure a timeout when initiating the connection to MISP:
```
misp = PyMISP(url='https://1.2.3.4', key='ajfljlds', timeout=2)
```
This way we don't have to wait for so long to get our error thrown at us.

This is annoying for use-cases such as https://github.com/MISP/MISP-maltego/issues/31.

**Comment by Rafiot** [comment]
I'll not do it today, but here, for reference: https://requests.readthedocs.io/en/master/user/quickstart/#timeouts

**Comment by cvandeplas** [comment]
No worries, I was working on the PR :-)
