### ISSUE TITLE
MISPEvent.delete_attribute(uuid) doesn't work with feeds

### ISSUE THREAD

**Issue by ivocarv** [MISP/PyMISP#586]
Deleting an attribute in a JSON event from a feed don't work. To reproduce this:

1. Load a MISPEvent() object from a json with attributes:
event.from_dict(**loadEvent(result_uuid)) # loadEvent uses json.load(file)

2. Delete an attribute from the event (given it's uuid or id):
event.delete_attribute(uuid)

3. Save event
e_feed = event.to_feed(with_meta=True)
saveEvent(e_feed) # uses json.dump to write back to file

Seems like the problem is with the "soft delete" feature from pymisp (to_feed doesn't care about self.deleted in attributes):

def delete_attribute(self, attribute_id: str):
        """Delete an attribute, you can search by ID or UUID"""
        found = False
        for a in self.attributes:
            if ((hasattr(a, 'id') and a.id == attribute_id)
                    or (hasattr(a, 'uuid') and a.uuid == attribute_id)):
                **a.delete()**
                found = True
                break
        if not found:
            raise PyMISPError('No attribute with UUID/ID {} found.'.format(attribute_id))

def delete(self):
        """Mark the attribute as deleted (soft delete)"""
        **self.deleted = True**

**Comment by Rafiot** [comment]
Hmmm that's true, it doesn't. I'd need to add it there: https://github.com/MISP/PyMISP/blob/master/pymisp/mispevent.py#L173


But before doing so, @iglocska is there a reason I skip it? As the format of the feed is pretty strict, I just want to make sure it is not expected.
