### ISSUE TITLE
'change_user_password' does not use 'user' parameter

### ISSUE THREAD

**Issue by jagprog5** [MISP/PyMISP#588]
https://github.com/MISP/PyMISP/blob/1e9eed198eba65d829d7211b6d5fea3d435b169e/pymisp/api.py#L1379

This is misleading. e.g. If PyMISP is instantiated with an admin's auth key, and this function is used to change a different user's password, not only will an ok response be given despite the user's password not changing, it will instead have change the admin's password.

**Comment by Rafiot** [comment]
Woops. I changed PyMISP, but it is also a bug on MISP side: https://github.com/MISP/MISP/issues/5962

**Comment by Rafiot** [comment]
Okay, so you should use the user edit call instead: https://github.com/MISP/MISP/issues/5962#issuecomment-637360506

And I remove the user parameter in PyMISP.
