### ISSUE TITLE
misp_update for unaltered event unpublishes it

### ISSUE THREAD

**Issue by sustefil** [MISP/PyMISP#589]
Hi guys,

So I noticed this thing, If I call the misp_update method on an unaltered event (like this),
the event actually gets unpublished, is that a bug or feature?

```
        jevent = misp.get_event(item['id'])
        event = pymisp.MISPEvent()
        event.load(jevent)
        misp.update_event(item['id'])
```

Also I get this error from pymisp:
```
ERROR [api.py:2178 - _check_response() ] Something went wrong (403): {'saved': False, 'name': 'Could not edit Event', 'message': 'Could not edit Event', 'url': '/events/edit/25619', 'errors': 'Event could not be saved: Event in the request not newer than the local copy.'}
```
I would then assume that the event won't be touched at all..

Thanks in advance

**Comment by Rafiot** [comment]
The error message is expected: MISP will reject an unmodified event. Are you getting that message, **and** the event in unpublished? It that's the case, we have a bug on MISP side.

**Comment by sustefil** [comment]
Yes, I get the expected error message **and** the event gets unpublished, tested twice.

**Comment by Rafiot** [comment]
Wait,

`misp.update_event(item['id'])` it definitely incorrect. should be `misp.update_event(event)`. You get the error message, and the event is not changed.

**Comment by iglocska** [comment]
So tl;dr: 

posted payload for the edit ends up being item['id']. MISP sees that the formatting is invalid and tries to be lenient by wrapping it in an "Event" container - at which point the data becomes a valid event edit object, just with no actual fields to update. Nice catch.

**Comment by sustefil** [comment]
Thanks guys,

So is it worth fixing? Or the library user should be more careful when passing parameters? :)

**Comment by Rafiot** [comment]
MISP should definitely not unpublish the event, and @iglocska fixed that.

From PyMISP, I could add a check to make it fail client side, but the current approach is that it expects a MISPEvent. But if the user passes a subset of an event, and know what they are doing, it may be more efficient.

Generally, I recomend you to stick to the typing meta information.

**Comment by sustefil** [comment]
Ok, thanks. closing
