### ISSUE TITLE
restSearch add include_event_correlation Toggle

### ISSUE THREAD

**Issue by nbyt3** [MISP/PyMISP#590]
I think I figured out one of the issues I've been having trying to export our events. Is there a way to include new parameter in the rest search that can remove the event correlation from the return search results? We have some events with very high correlations and it is causing a 8x increase in the document size for some of the events. If I was able to pass a "include_event_correlation=False" in the rest API call I wouldn't have to turn off event correlation on the entire MISP server.

Thanks!

**Comment by Rafiot** [comment]
@iglocska @mokaddem is it something supported on MISP side?

**Comment by mokaddem** [comment]
There is the `includeEventCorrelations` parameter that you can use in restSearch.
The following will not attach correlating events to the result
```json
{
    "includeEventCorrelations": 0
}
```
