### ISSUE TITLE
ImportError: cannot import name 'ExpandedPyMISP'

### ISSUE THREAD

**Issue by dmolina213** [MISP/PyMISP#594]
I am getting the error. I wasnt getting the error the other day. I am using python3

**Comment by Rafiot** [comment]
Well, nothing changed recently. My guess is that you're not in the virtual environment? Have you tried to re-rerun `pip3 install pymisp`?

Note that `ExpandedPyMISP` is an alias for `PyMISP`

**Comment by dmolina213** [comment]
I did still erroring out. Is this the correct import statement? I may have capitalized or not capitalized the module names, etc
from pymisp import ExpandedPyMISP, MISPEvent, MISPObject

**Comment by Rafiot** [comment]
Yes, it is correct.

Can you do `from pymisp import PyMISP`?

**Comment by dmolina213** [comment]
will that import the other libraries as well?

**Comment by Rafiot** [comment]
no, it won't, but I'm trying to figure out if the module isn't installed at all, or if it is something else.

**Comment by dmolina213** [comment]
here is the error that i get. I have been running scripts here atleast 2 days ago. 
![image](https://user-images.githubusercontent.com/42444130/85743893-0dd60400-b6ca-11ea-87bc-8ab98e642458.png)

**Comment by Rafiot** [comment]
Right, the issue is that you cannot import `JSONEncoder`.

Why it is so is a good question, as `JSONEncoder` is a standard Python module. Try doing `from json import JSONEncoder`, and it may give you more details.

**Comment by dmolina213** [comment]
Same issue

![image](https://user-images.githubusercontent.com/42444130/85748668-d9fcdd80-b6cd-11ea-8d23-48e0a230759d.png)


here are my import statements

![image](https://user-images.githubusercontent.com/42444130/85749174-3eb83800-b6ce-11ea-81e7-8b701fb38ef4.png)

**Comment by Rafiot** [comment]
Yes, sorry, I was unclear. You need to try to import `JSONEncoder` **before** `PyMISP`. As the call fails and raises an exception, it doesn't go further.

Note that it won't solve out problem, but simply tell you (hopefully) why the import of `JSONEncoder` fails

**Comment by dmolina213** [comment]
same error, Is there an order these modules have to be imported?

**Comment by Rafiot** [comment]
Yes, can you show me the full stack trace?

`from pymisp import PyMISP` is supposed to work, I'm trying to figure out what is going on with your system.

**Comment by dmolina213** [comment]
Is this what you are looking for ? I do apologize, I am learning as I am going here. Not a Python developer by trade. But i can pick up on a few stuff. Also that dictionary that is returned with the id_number. I dont recognize, that idk where it is getting tha from.

![image](https://user-images.githubusercontent.com/42444130/85759739-cf931180-b6d6-11ea-8e8d-816c5c19d613.png)

**Comment by Rafiot** [comment]
I cannot reproduce your error.

```
$  python3 
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from json import JSONEncoder
```

**Comment by dmolina213** [comment]
![image](https://user-images.githubusercontent.com/42444130/85762410-50eba380-b6d9-11ea-9f1c-2524364267a6.png)

**Comment by Rafiot** [comment]
ok, same python version:
```
$ (git::master) python3.6
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from json import JSONEncoder
```

I don't get it.

**Comment by dmolina213** [comment]
idk where that stuff comes from. this is what is supposed to be retrieved: when i plug the authenticated url into my browser. My script caluculates the hashes and appends it to the url 

{"TotalCount":4442,"Description":"doctype:paste AND entitytype:hash","Items":[{"EntityReference":"alisiataylorvagov-11_213219852","DocumentFrequency":1,"Id":"11_213219852","Description":"alisia.taylor@va.gov","Type":"Email","LocalizedType":"Email","Extras":{"DocVolume-1":{"Volume":0},"DocVolume-7":{"Volume":0},"DocVolume-30":{"Volume":0},"Heat-1/30":{"Heat":0.0},"Heat-7/30":{"Heat":0.0}}},{"EntityReference":"adampetersen1vagov-11_319050258","DocumentFrequency":1,"Id":"11_319050258","Description":"adam.petersen1@va.gov","Type":"Email","LocalizedType":"Email","Extras":{"DocVolume-1":{"Volume":0},"DocVolume-7":{"Volume":0},"DocVolume-30":{"Volume":0},"Heat-1/30":{"Heat":0.0},"Heat-7/30":{"Heat":0.0}}},{"EntityReference":"josephmarinellovagov-11_1122704105","DocumentFrequency":1,"Id":"11_1122704105","Description":"joseph.marinello@va.gov","Type":"Email","LocalizedType":"Email","Extras":{"DocVolume-1":{"Volume":0},"DocVolume-7":{"Volume":0},"DocVolume-30":{"Volume":0},"Heat-1/30":{"Heat":0.0},"Heat-7/30":{"Heat":0.0}}},{"EntityReference":"johnlawtonvagov-11_1159468939","DocumentFrequency":3,"Id":"11_1159468939","Description":"john.lawton@va.gov","Type":"Email","LocalizedType":"Email","Extras":{"DocVolume-1":{"Volume":0},"DocVolume-7":{"Volume":0},"DocVolume-30":{"Volume":0},"Heat-1/30":{"Heat":0.0},"Heat-7/30":{"Heat":0.0}}},{"EntityReference":"melissekuhnvagov-11_1508674768","DocumentFrequency":1,"Id":"11_1508674768","Description":"melisse.kuhn@va.gov","Type":"Email","LocalizedType":"Email","Extras":{"DocVolume-1":{"Volume":0},"DocVolume-7":{"Volume":0},"DocVolume-30":{"Volume":0},"Heat-1/30":{"Heat":0.0},"Heat-7/30":{"Heat":0.0}}}],"Source":"InMem"}

**Comment by dmolina213** [comment]
Maybe it had to do with cloning it from github. i will try to but into a new file. Doesnt makes sense. But none of it does

**Comment by Rafiot** [comment]
For me, it means that your python installation is very broken, but I cannot figure out how that could have happened.

**Comment by dmolina213** [comment]
It was just working yesterday.

V/R
Help Me, Help You
Douglas P Molina, MBA, CISSP, C|EH, CySA+,CCSK,GCTI
U.S. Department of Veterans Affairs
Office of Information Security (OIS)
Cyber Threat Intelligence (CTI)
Work Phone: 708-938-2720
Mobile Phone: 202 779 2034
UNCLASS: douglas.molina@va.gov<mailto:douglas.molina@va.gov>
[cid:image001.jpg@01D64AED.0E9293C0]

**Comment by dmolina213** [comment]
ok so i found the error. I was working on debugging json and i accidentally created a file named json.py in my working directory. This is what my script was importing

**Comment by Rafiot** [comment]
oh, right, that makes sense!
