### ISSUE TITLE
Unexpected response from server: 

### ISSUE THREAD

**Issue by nbyt3** [MISP/PyMISP#596]
Ubuntu 18.04 
32GB Ram
10 CPU
MISP 2.4.124
19453 Events
218895 Attributes

I am getting the following error when running:
r = misp.search(controller='events', includeDecayScore=True)

Is there somewhere on the MISP server where I can see the error message from either Apache2 or the MISP logging found in /var/www/MISP/app/tmp/logs?

Error:
  File "/home/_/.local/lib/python3.6/site-packages/pymisp/api.py", line 1524, in search
    normalized_response = self._check_json_response(response)
  File "/home/_/.local/lib/python3.6/site-packages/pymisp/api.py", line 2160, in _check_json_response
    r = self._check_response(response, expect_json=True)
  File "/home/_/.local/lib/python3.6/site-packages/pymisp/api.py", line 2195, in _check_response
    raise PyMISPUnexpectedResponse(f'Unexpected response from server: {response.text}')
pymisp.exceptions.PyMISPUnexpectedResponse: Unexpected response from server:

**Comment by Rafiot** [comment]
Yeah, it should not raise an exception, but you're not saying what you search for. You need to give time interval, or an event ID for example.

Also, please update your MISP instance.

**Comment by smclinden** [comment]
I'm seeing the same issue with the MISP collector from OpenCTI. PyMISP on both MISP and OpenCTI are current (from GitHub) and I set the start date to be yesterday but the first event is still from 2017-01-18 and there over 11,000 entries in the response.

Could this result from corruption of the MISP database?

**Comment by smclinden** [comment]
I answered my own question. I ran tools/misp-wipe.sh and let MISP repopulate the data and everything is working. Somehow the MISP database was corrupted but MISP reported no errors.

**Comment by Rafiot** [comment]
This is super weird, but if it is sorted, I'm closing this issue.
