### ISSUE TITLE
Unable to build doc with epydoc

### ISSUE THREAD

**Issue by paalbra** [MISP/PyMISP#599]
https://github.com/MISP/PyMISP/blob/main/README.md says that you may build documentation with:

`epydoc --url https://github.com/MISP/PyMISP --graph all --name PyMISP --pdf pymisp -o doc`

This fails with python3 because of incompatibility (epydoc 3.0.1).

Is epydoc abandoned?

Are there any good alternatives?

**Comment by Rafiot** [comment]
I need to update readme, I didn't use epydoc is years. 

The documentation (https://pymisp.readthedocs.io/en/latest/?badge=latest) is generated with sphinx by readthedocs.org, and I'm not totally sure how it is done, but it should be default sphinx.
