### ISSUE TITLE
Export Events in STIX v1 in XML

### ISSUE THREAD

**Issue by matthiascroos4888** [MISP/PyMISP#600]
It is currently not possible to get STIX as return type in XML format from the `events/restSearch` endpoint.
I use the `search(controller="events", return_format="stix")` method of the `PyMISPExpanded` class.

This is caused by an invalid `Accept` header which gets set to `Accept: application/json` instead of `Accept: application/xml`.
Thus, the STIX content returned is a JSON object and not an XML as in prior MISP releases. 

This issue is referenced to the following issue in the MISP project https://github.com/MISP/MISP/issues/5618.

**Comment by Rafiot** [comment]
I fixed it by allowing to pass `return_format='stix-xml'`to the search method. Note that it will be in the package on PyPifor the next release of PyMISP.
