### ISSUE TITLE
Error when adding named attributes to event in MISP (Need category?)

### ISSUE THREAD

**Issue by laostmann** [MISP/PyMISP#601]
Below is the error thrown, 

"ERROR [api.py:2297 - _check_response() ] Something went wrong (403): {'saved': False, 'name': 'Could not add Attribute', 'message': 'Could not add Attribute', 'url': '/attributes/add', 'errors': {'category': ['Options : Payload delivery, Antivirus detection, Payload installation, Files dropped ...'], 'type': ['Options depend on the selected category.'], 'value': ['Value not in the right type/format. Please double check the value or select type "other".']}}
{'errors': (403, {'saved': False, 'name': 'Could not add Attribute', 'message': 'Could not add Attribute', 'url': '/attributes/add', 'errors': {'category': ['Options : Payload delivery, Antivirus detection, Payload installation, Files dropped ...'], 'type': ['Options depend on the selected category.'], 'value': ['Value not in the right type/format. Please double check the value or select type "other".']}})}"

Command ran "python3 add_named_attribute.py -e 6 -t ip-dist -v 112.217.108.138"

**Comment by Rafiot** [comment]
The type `ip-dist` is incorrect, it should be `ip-dst`.

**Comment by laostmann** [comment]
Rewrote the command and produced a new error below:


ERROR [api.py:2297 - _check_response() ] Something went wrong (403): {'saved': False, 'name': 'Could not add Attribute', 'message': 'Could not add Attribute', 'url': '/attributes/add', 'errors': {'value': ['A similar attribute already exists for this event.']}}
{'errors': (403, {'saved': False, 'name': 'Could not add Attribute', 'message': 'Could not add Attribute', 'url': '/attributes/add', 'errors': {'value': ['A similar attribute already exists for this event.']}})}

**Comment by laostmann** [comment]
Got the issue fixed on our side, appreciate the help

**Comment by Rafiot** [comment]
All good, thanks for the update!
