### ISSUE TITLE
Addtag and Addtag2 error

### ISSUE THREAD

**Issue by laostmann** [MISP/PyMISP#603]
After running the following command, received the error below: "python3 addtag2.py -e 8 -t 5"

File "addtag2.py", line 32, in <module>
    data = result['response']
TypeError: list indices must be integers or slices, not str

**Comment by Rafiot** [comment]
If you're using the repository, your line 32 should be this one: https://github.com/MISP/PyMISP/blob/main/examples/addtag2.py#L32 

If you're using the package, the one in PyPi will be updated with the next release of MISP.

**Comment by laostmann** [comment]
Using repository examples, but the package seems to throw this error when we added attribute id along with the addtag2 script

Traceback (most recent call last):
  File "addtag2.py", line 41, in <module>
    data = result['response']
TypeError: list indices must be integers or slices, not str

Command run: python3 addtag2.py -e 8 -a 19210 -t 5

**Comment by laostmann** [comment]
Git pull worked, issue can be closed
