### ISSUE TITLE
Adding tags to attributes within events Question

### ISSUE THREAD

**Issue by laostmann** [MISP/PyMISP#611]
This is more so a question rather than an issue, but how is it possible to locate the attribute id argument to include in the command below where the underscores are:

python3 addtag.py -e 8 -a ______ -t 5

I'm having a hard time locating these id's; hence making a tenfold scenario each time I make an event and have to go looking for the attribute id attached to that event.

Appreciate any guidance.

**Comment by Rafiot** [comment]
Can you give me more context on what you're trying to do? The files in the example directory are examples, and aimed at helping you write your own instrumentation, not being used in production.

Typically, the tag method is supposed to receive a `MISPEvent` or a `MISPAttribute` that was returned by an search query for example.

**Comment by laostmann** [comment]
My goal is to add tags using traffic light protocol and I have the tag id and the event info yet I'm not sure what to put as the attribute id

**Comment by Rafiot** [comment]
Okay, so my next question is: How do you know which TLP tag do you want to put on which Attribute? Or you want to add the same tag on every attributes of the event?

**Comment by laostmann** [comment]
It was hard for me to read in the info from the event so I went ahead and installed jq to help with managing all the content into a readable json format. I was able to then use the addtag2.py to successfully add the tag to the attribute. Might want to remove the addtag.py as it might cause some future users confusion when adding attributes. Thank you for the eager responses

**Comment by Rafiot** [comment]
Right, `addtag.py` creates a new tag on the  the misp instance, while `addtag2.py` tags an event/attribute.

I'll rename it.

**Comment by Rafiot** [comment]
Woops, right, `addtag.py` is gone.
