### ISSUE TITLE
Correlation issues - ssdeep on .rsrc

### ISSUE THREAD

**Issue by imidoriya** [MISP/PyMISP#614]
Most ssdeep correlations on the PE sections add value, but `.rsrc` seems to be an exception.  Can this be excluded or have an option to exclude it from correlation on that section?  If correlation can't be controlled when adding that attribute, I'd skip the ssdeep hash on that section.  For us, it is creating way too many correlations to be useful for anything and it's growing the correlation table quickly.  I think I have about 300 million correlations associated with the ssdeep of the `.rsrc` section, with many events listing 12,000+ correlations each.  It's drowning out anything else.
https://github.com/MISP/PyMISP/blob/a5ff0b850e5c38f22b8230e40e5eb2a3f8987dd8/pymisp/tools/peobject.py#L145

As an additional though, any suggestions on how best to delete those correlations from the existing system? :)

**Comment by imidoriya** [comment]
For now, I ended up doing this.  I'll leave the request open for you to consider as it would probably be a good default based on my experience, but feel free to close.
```
fo, peo, seos = make_binary_objects(
    filename=filename, pseudofile=io.BytesIO(file)
)
if seos:
    # Section Objects
    for s in seos:
        attributes = s.get("Attribute")
        if attributes[0].get("value") == ".rsrc":
            for attrib in attributes:
                if attrib.get("type") == "ssdeep":
                    attrib.disable_correlation = True
        self.client.add_object(event, s)
```
Now I just need to figure out how to delete the correlation from a 100,000 events. lol

**Comment by Rafiot** [comment]
I'd suggest to do the change directly in the `PESectionObject` here: https://github.com/MISP/PyMISP/blob/main/pymisp/tools/peobject.py#L125

And based on your experience, I think it makes sense. Do you want to do a PR?

To delete the correlation on all the attributes, you can use the search interface, and POST an update on the relevant attributes... but it will take a while.

**Comment by imidoriya** [comment]
Yeah, I can create a PR for that.  What do you think about zero-filled sections - if it has an entropy of `0.0`, should it be tagged for correlation and ids?  I had about 12 million of those on the standard hashing and 40 million ssdeep, which looked like `3::` (no chunk).  The .rsrc and zero-filled hashes were the main contributors to my oversized correlation table.

**Comment by imidoriya** [comment]
I see you check the size, but you can still have a section with no data in it.  Was the intent to skip hashing in that situation?
https://github.com/MISP/PyMISP/blob/821a4f539813a2ee7305e1c77dde6197d9782454/pymisp/tools/peobject.py#L138

**Comment by Rafiot** [comment]
yeah, if the entropy is 0.0, we should skip the correlation on ssdeep and all the other hashes.

**Comment by imidoriya** [comment]
No, I think it was a good choice.  I was wondering if you had intended to also include an empty section.  Something like this:

`if int(size.value) > 0 and float(self.__section.entropy) > 0:`

I guess the question is which do you want for an zero-filled section:
1) hash the zeros, but no correlation and no ids
2) don't hash it

**Comment by imidoriya** [comment]
Actually, if you were to exclude the hashes, the `float(self.__section.entropy) > 0:` might be better placed after writing the entropy value to the attrib so there is an indicator as to why a section with a size of 512 for example, has no hashes.

**Comment by Rafiot** [comment]
So my question regarding the 0 filled sections is to know if this filling can still be used for correlation? It sounds like a long shot, but if we can use this hash (not ssdeep) to identify a family, it is relevant.

You seem to have a big collection of samples, so I'll trust your expertise on that: if you think we should disable correlation and to_ids on empty files, and files with 0 entropy, let's do it. As long as we keep the hashes (except ssdeep)

**Comment by imidoriya** [comment]
Yes, I agree that the absence of data could be used as an indicator (more so if combined with other factors), so it makes sense to keep the hash.  That way if someone did want to correlate it, it's there, but for most cases and the sanity of the correlation table, we should exclude them.

As a side note, correlations seem to take way more space and rows than I would think.  It even seems more than `n*(n-1)/2`, like x = y and y=x are both in there, so more like `n*(n-1)`.  It's a crazy way to do correlations.  A graph database structure could probably do it with n+1.  And then it includes the damn info column on each one.  They need to fix it overall - it's a bad design for large datasets.

**Comment by Rafiot** [comment]
Yeah, at some point, we want to get the correlations out of MySQL, but it is pretty difficult to do it in a sane way when with the user base we have right now.
