### ISSUE TITLE
bulk change to_ids for an event

### ISSUE THREAD

**Issue by clucas-gh** [MISP/PyMISP#616]
This might be similar to the bulk tagging issues in https://github.com/MISP/MISP/issues/3985, but I was hoping to find a way to hit the API to bulk change attributes to_ids values in a field. Right now I am looping through update_attribute but that is slower than doing it by hand. I have a large amount that at this rate would take a week or so to change as it creates a new post request for each attribute change. Is there a way to add functionality to pass a large set of attribute uuids and change the to_ids or any other way to do this other than iterating through each attribute in each event and creating a new post request for each? Perhaps even a bulk change to_ids for all attributes in an event would be really welcome? Going through the GUI I know i can change one page at a time, but when I'm dealing with sometimes 60,000+ attributes in an event and I'm trying to change several hundred events that takes a little while :).

**Comment by Rafiot** [comment]
You could get the whole event with `get_event` iterate through the attributes, update the to_ids field, and push the event pack with `update_event`. Or Am I missing something?

**Comment by clucas-gh** [comment]
right now I'm using get_event and iterating through the attributes in the event. As I iterate through the list of attributes and checking the conditions, i use misp.update_attribute({'to_ids':False}, attribute_id=uuid, pythonify=False). I'm not quite sure how else I can update the to_ids fields without doing update_attribute and how to utilize update_event. Thanks for your help!

**Comment by Rafiot** [comment]
well, if you do something like that, you will do 2 requests:

```
event = pymisp.get_event(123, pythonify=True)
for a in event.attributes:
    a.to_ids = False
event = pymisp.update_event(event)
```

**Comment by clucas-gh** [comment]
Ok that worked much much much better thank you! I just need to adjust the ['timestamp'] check I had in there since it's in datetime.datetime instead of epoch, but other than that this was much easier! Thank you!!

**Comment by Rafiot** [comment]
Excellent!
