### ISSUE TITLE
How to solve this issue related to comments?

### ISSUE THREAD

**Issue by JoaoPauloF** [MISP/PyMISP#618]
Hello Guys! 

I started my work with pymisp last week and I am doing some tests to know more about the tool.

Currently, I am trying to add an event in my misp instance, but every time I try to add a comment, it goes to the value field and the comment is written to the type field.
I would like to populate the "Comment" field with some description, not in other part. 

How do I do that? 

The code I am using:

misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert)
event = MISPEvent()
event.distribution = args.distrib
event.threat_level_id = args.threat
event.analysis = args.analysis
event.info = args.info
event.comment = args.comment -> Tried to use this but didnt work, the field was blank

Then I tried to:

def create_attribute(info):                                                                                                           
    attribute = MISPEvent()                                                                                                           
    attribute.info = info                                                                                                             
    attribute.add_attribute("comment", value="Test") -> This test is written in the value field, not in the Comment

**Comment by Rafiot** [comment]
Right, there is a lot going on there, let's do it in order.

1. Attributes have an optional `comment` field, not events. The `comment` key will be ignored when you push the event to MISP. 

2. What do you mean by `Tried to use this but didnt work, the field was blank` - there is no comment field in the event. Can you please send us a screenshot of the empty field you're talking about on the web interface?

3. Then, you have a method called `create_attribute` that creates an event, and adds an attribute to it. That's also not going to do what you want to do.

4. The `add_attribute` method adds an attribute to a MISPEvent (in memory, locally, not pushed to a MISP instance). The attribute has a value field (in your case, it will contain the string `comment`). A correct use of that method would be the following:
`event.add_attribute('8.8.8.8', type='ip-dst', comment="comment")`

Can you give us more details on what you're trying to accomplish? I cannot really tell right now.
