### ISSUE TITLE
MISPObjectAttribute - Ability to parse first_seen and last_seen from dict when adding MISPAttribute to MISPObject

### ISSUE THREAD

**Issue by pwrenn** [MISP/PyMISP#619]
I am integrating IOCs as attributes within MISPObjects and noticed that the MISPObjectAttribute from_dict() method does not have a way to parse in the first_seen and last_seen of an indicator when passed through in the value dict adding a MISPAttribute to a MISPObject. I made a small tweak to the from_dict() method in the MISPObjectAttribute class within mispevent.py to fix this, and will be submitting my PR from a fork.

**Comment by Rafiot** [comment]
Sounds good, I'll review and merge the PR as soon as it is available.

**Comment by pwrenn** [comment]
@Rafiot I went ahead and changed my local code back to the original state and it looks like I am getting errors still.

If you remember, the original suggested code snippet was:
```
obj = MISPObject("trustar_report", standalone=False, strict=True)
indicator = {
  "value": "https://sampleioc.com",
  "object_relation": "URL",
  "first_seen": '2020-08-15T00:00:51.552000'
  "last_seen": '2020-08-15T00:00:51.552000'
}
obj.add_attribute(**indicator)
```

When I tried that I get an AttributeError saying MISPObjectAttribute has no attribute 'value'

**Comment by Rafiot** [comment]
it is generally because PyMISP doesn't has the the template available. Are you using PyMISP from the repository or from the package? If you use it from the repository, don't forget to pull the submodules.

**Comment by pwrenn** [comment]
I use PyMISP from the package, I got it to work by creating a dictionary representation of the trustar_report `definition.json` file and then mapping the ioc type to the misp-attribute within the definition file. I *think* this should be ok to close if you wouldn't mind verifying.

**Comment by Rafiot** [comment]
I'm not sure to follow.

Did you change this file: https://github.com/MISP/misp-objects/blob/main/objects/trustar_report/definition.json
Or is it something else?
