### ISSUE TITLE
Unable to add attributes after creating new event

### ISSUE THREAD

**Issue by TheDr1ver** [MISP/PyMISP#62]
I'm in the process of trying to convert a large amount of data from a csv into MISP, creating brand new events based on combinations of specific fields (e.g. Reporting_Org+Report_Number = Event description).

When I call misp.new_event(info=event['info']), it creates the new event just fine, but when I try to search it via search('events', **kwargs), it tells me there are no results. I've tried multiple search params (org, from, values), and still am getting a response that it doesn't exist. I have even tried manually creating an event through the web UI, and then searching it, but the API still says it can't find the event I'm looking for.

The strange thing is, once I add an attribute through the web UI and run the exact same search, I get the results I'm looking for. Because of this, I've tried calling add_named_attribute() immediately after creating the new event, but when I pass the new event to add_named_attribute() it says "Invalid event".

Since the MISP API can't seem to find my newly created events until I add an attribute to them, and I apparently can't add an attribute right off the bat through new_event(), what is the best way to go about creating a new event and then immediately adding an attribute to it?

Thanks in advance!

Version: 2.4.34

Code snippet:

    def send_to_misp(misp, misp_url, events):
        
        # Loop throuhgh each event
        for event in events:
            # Search for existing event
            kwargs={'values': event['info']
                    }
            result = search(misp, misp_url, **kwargs)
            # ^^^ Never finds results, until an attribute is added manually through web UI

            if result['message']=="No matches.":
                #Add new event
                result = misp.new_event(info=event['info'])
                
                # Add Searchable comment
                
                #eid= misp.get_event(result['Event']['id'])
                #print "eid: "+str(eid)
                # Turns out get_event() gives me the same thing that's already in result

                #comment_res = misp.add_named_attribute(result, 'other', result['Event']['info'])            
                comment_res = misp.add_named_attribute(result, 'other', result['Event']['info'], "Other")
                #^^^ Both return 'Invalid event' even though the event exists

**Comment by Rafiot** [comment]
The version you're using is extremely old. 

I see two options:
* use an older version of PyMISP (maybe v2.4.36)
* update MISP

**Comment by adulau** [comment]
Upgrading to the latest MISP is more than recommended especially as security vulnerabilities were fixed in addition to many bug fixes on the API side too.

**Comment by TheDr1ver** [comment]
Thanks for the quick replies. Unfortunately, I just upgraded to MISP 2.4.69, and I'm still having the same problem. Here's a link to a screenshot of the PCAP I pulled while testing (http://i.imgur.com/wRd6a94.jpg).

There are 5 events belonging to the 'test' org. In the top stream, all events were brand new, none of the events had any attributes assigned to them, and the search returned "No matches." 

I then added a single attribute to one of the events in the 'test' org, and ran the exact same search again. This time I got a response, but it only contained the event that I added an attribute to.

Again, any help you could provide would be greatly appreciated.

**Comment by iglocska** [comment]
Oh it's empty events that aren't being returned? That could be a bug on MISP's side. Will look into it!

**Comment by TheDr1ver** [comment]
Yup - the more I look into it, the more I'm thinking it's very similar to MISP issue #1021 (https://github.com/MISP/MISP/issues/1021).

As a potential workaround, what would be the best way to take the following data and create a brand new event from scratch, using PyMISP?

Event Description: "Test Event"
Attribute #1: MD5 = 93b885adfe0da089cdf634904fd59f71

The only way I could find to potentially do that without being able to search/modify empty events would be to create a full MISP-formatted XML/JSON file and import it using add_event(), but wouldn't that require knowing an Event_ID and UUID ahead of time? Since I'll be generating these events based off a massive CSV, I'd much rather have MISP handle the event numbering and UUID assignments for me, like it does in new_event()... But new_event() doesn't appear to have an option to add an attribute when it's called.

**Comment by Rafiot** [comment]
Sorry for the late answer.

If you want to create a full event and add it to MISP, the easiest way it to use MISPEvent: https://github.com/MISP/PyMISP/blob/master/pymisp/mispevent.py

and then `add_event(json.dumps(mispevent, cls=EncodeUpdate))`

**Comment by Rafiot** [comment]
you can now pass a MISPEvent to add_event (if you use the HEAD of PyMISP)

**Comment by TheDr1ver** [comment]
Thanks! I'm not yet seeing anything in the examples dir that uses mispevent.py in that way, but I'm sure I'll be able to figure it out.

In `add_event(json.dumps(mispevent, cls=EncodeUpdate))` is `mispevent` just a regular dictionary that looks like this?

    {'Event': {'Attribute': [],
               'analysis': '0',
               'info': 'Test event',
               'distribution': '3',
               'threat_level_id': '2'}

My main concern is being able to add a new event and all its attributes without having to define the event ID or the UUID manually.

**Comment by Rafiot** [comment]
Sorry, it is fact badly documented.

You can do something like that for example:

```
from pymisp import MISPEvent, PyMISP

pymisp = PyMISP(<url>, <key>)

event = MISPEvent()
event.info = 'Test event'
event.analysis = 0
event.distribution = 3
event.threat_level_id = 2

event.add_attribute('md5', <md5>)
<add more attributes>

pymisp.add_event(event)
```

**Comment by TheDr1ver** [comment]
Awesome - I can definitely run with that, thanks!

**Comment by Rafiot** [comment]
Great, closing then :)
