### ISSUE TITLE
Search on attributes by datetime?

### ISSUE THREAD

**Issue by parosio** [MISP/PyMISP#622]
Hello,

I have to extract attributes (type "md5") with a specific tag and modified within a specified datetime range.
I used date_from and date_to parameters, but they apply to event, and, more important, do not consider the time portion of datetime parameter.

Then I added a timestamp parameter, but in that case the date_to parameter seems to be disregarded: the query returns attributes also from events more recent than the date_to.

Do you have any suggestion?

**Comment by Rafiot** [comment]
`date_from` and `date_to` are only applying to the date field in the metadata of the event.

The field you want to use is `timestamp`, to which you can pass a list with two values (from/to).

**Comment by parosio** [comment]
Thank you, @Rafiot. 
`timestamp` is definitely what I was looking for.
