### ISSUE TITLE
CRITICAL: Unknown Error, response is not in JSON

### ISSUE THREAD

**Issue by pwrenn** [MISP/PyMISP#627]
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.131 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '4668', 'Authorization': '<AUTH>', 'content-type': 'application/json'}
Request body:
{"uuid": "7a98b651-12d9-40ca-b18f-57aa3a52e440", "Object": [{"name": "trustar_report", "meta-category": "network", "template_uuid": "8ff46cf1-db04-4453-ba46-d004e1ef6b7a", "description": "TruStar Report", "template_version": "1", "uuid": "c6d05da9-edfe-4537-b781-73b682ead9dd",}
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/add"}
Traceback (most recent call last):
  File "ts-misp.py", line 548, in <module>
    main()
  File "ts-misp.py", line 518, in main
    ts_misp.ts_reports_to_misp()
  File "ts-misp.py", line 442, in ts_reports_to_misp
    self.misp.add_event(event)
  File "/usr/lib/python3.6/site-packages/pymisp-2.4.131-py3.6.egg/pymisp/api.py", line 284, in add_event
    new_event = self._check_json_response(r)
  File "/usr/lib/python3.6/site-packages/pymisp-2.4.131-py3.6.egg/pymisp/api.py", line 2428, in _check_json_response
    r = self._check_response(response, expect_json=True)
  File "/usr/lib/python3.6/site-packages/pymisp-2.4.131-py3.6.egg/pymisp/api.py", line 2437, in _check_response
    raise MISPServerError(f'Error code 500:\n{response.text}')
pymisp.exceptions.MISPServerError: Error code 500:
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/add"}

**Comment by Rafiot** [comment]
Can you have look the errors logs in  `<install_path>/MISP/app/tmp/logs/`?

**Comment by packet-rat** [comment]
FYSA:  There's nothing in the Error, Debug, or resque logs.

**Comment by JakubOnderka** [comment]
Maybe typo in request body? (see last `,`)

{"uuid": "7a98b651-12d9-40ca-b18f-57aa3a52e440", "Object": [{"name": "trustar_report", "meta-category": "network", "template_uuid": "8ff46cf1-db04-4453-ba46-d004e1ef6b7a", "description": "TruStar Report", "template_version": "1", "uuid": "c6d05da9-edfe-4537-b781-73b682ead9dd",}

**Comment by Rafiot** [comment]
Oh wow, yeah... I'm very curious how that could happen when using PyMISP: it is not something `json.dumps` should be doing...

**Comment by adulau** [comment]
@pwrenn @packet-rat Can we safely assume that the JSON was malformed?
