### ISSUE TITLE
State clearly that PyMISP asserts the BSD two-clause simplified license

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/PyMISP#628]
Please consider asserting a well-known license like Apache, BSD, MIT, GPL, AGPL etc. on PyMISP.  Today the license file has the following custom text.  This sort of custom license causes most corporate legal departments some heartache when they encounter it.  The lawyers don't want to expend the effort required to analyze your language.  If you assert a well-known license, something they have seen before, it's SO much easier to discuss.  Thanks for considering it.

```
Copyright (c) 2013, 2014 Raphaël Vinot
Copyright (c) 2013, 2014 Alexandre Dulaunoy
Copyright (c) 2013, 2014 CIRCL - Computer Incident Response Center Luxembourg
                         (c/o smile, security made in Lëtzebuerg, Groupement
                         d'Intérêt Economique)
Copyright (c)       2014 Koen Van Impe

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

    1. Redistributions of source code must retain the above copyright notice,
       this list of conditions and the following disclaimer.
    2. Redistributions in binary form must reproduce the above copyright notice,
       this list of conditions and the following disclaimer in the documentation
       and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
LICENSE (END)
```

**Comment by Rafiot** [comment]
It is the BSD 2 clauses as listed here: 

https://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_(%22Simplified_BSD_License%22_or_%22FreeBSD_License%22)

**Comment by Rafiot** [comment]
... for some reason, is says `THE COPYRIGHT HOLDER` instead of `THE COPYRIGHT OWNER`. Changing that.

**Comment by chrisinmtown** [comment]
Thanks so much for the quick reply.  I'm looking at file PyMISP/LICENSE.  The string "BSD" does not occur in the file.  It would be ENORMOUSLY helpful if you add that link to the file. That way you, the authors, state clearly and unambiguously that you are asserting the BSD license, just reproducing the text for convenience. Lawyers don't want software engineers like me doing any interpretation :)

**Comment by chrisinmtown** [comment]
Perhaps a solution, if you find it helpful, you might just add this link to the top or bottom of the LICENSE file:

    https://spdx.org/licenses/BSD-2-Clause.html

But if you don't want to make any changes to the file, I will close this issue now.

**Comment by adulau** [comment]
I think we will close the issue as putting a reference link to website that is not under our control is not really a good legal practice. It's like adding a clause in a legal document without knowing what will be the clause. The text is clearly a BSD 2 clause.

So I simplified this issue by adding a reference in the README:

https://github.com/MISP/PyMISP/commit/ba1e394d24a16588fec29d6efb9dc000f3cf6ece

I suppose it's solving the issue. Don't hesitate to reopen the issue if your lawyer has some additional questions ;-) Thanks a lot.
