### ISSUE TITLE
Removing IDS flag from object leads to "Something went wrong (403)"

### ISSUE THREAD

**Issue by baderj** [MISP/PyMISP#634]
This minimal example tries to remove the IDS flag from all domains ``notmalicious.com``:

```
import pymisp

KEY = "<API KEY>"
URL = "<MISP URL>"

entry = "notmalicious.com"
misp = pymisp.ExpandedPyMISP(URL, KEY)
events = misp.search(value=entry, pythonify=True)

for event in events:
    nr = 0
    for obj in event.Object:
        for attribute in obj.Attribute:
            if attribute.to_ids:
                nr += 1
                attribute.to_ids = False

    print(f"removed {nr} ids flags")
    if nr:
        misp.update_event(event)
        misp.publish(event, alert=False)
```

Event though the API key used is for an admin account (for testing purposes), it triggers a ``not authorized`` error:

```
ERROR [api.py:2446 - _check_response() ] Something went wrong (403): {'name': 'You are not authorised to do that.', 'message': 'You are not authorised to do that.', 'url': '/events/edit/<redacted uuid>'}
ERROR [api.py:2446 - _check_response() ] Something went wrong (405): {'name': 'You do not have the permission to do that.', 'message': 'You do not have the permission to do that.', 'url': '/events/publish/<redacted uuid>'}
```

If I were to modify the IDS flags of ``MISPAttributes`` (so attributes not within an object) like that:

```
for attribute in event.Attribute:
    if attribute.to_ids:
        ...
```
     
Then the ``update_event`` call works and the IDS flag is removed.

| | |
| --- | --- |
| MISP Version | 2.4.132 |
| PyMISP Version | 2.4.131 |
| OS | Ubuntu 20.04 |

Is there another way to remove the IDS flag from attributes within objects?

**Comment by Rafiot** [comment]
Are the events with attributes you're trying to edit owned by the same organization as the user of the key? If it is not the case, the 403 is expected.

**Comment by baderj** [comment]
Yes and no. The result is the same for both types of events, either owned by me or by other organisations. So there is at least some inconsistency between the permissions needed to modify attributes and object attributes:

1. As an admin I CAN remove IDS flags from attributes in events.
2. As an admin I CANNOT remove IDS flags from object attributes in events.

Since the user is admin, I think she should also be able to also modify objects.

**Comment by Rafiot** [comment]
yes, an admin should in fact be able to do all that.

Ping @mokaddem @iglocska

**Comment by baderj** [comment]
I just tested ``misp.update_attribute( { 'uuid': attribute.uuid, 'to_ids': 0})`` and it shows the same behaviour (works for MISPAttribute, fails for MISPObjectAttribute)

**Comment by Rafiot** [comment]
Okay, that's weird: I have no problem updating the attribute (same call as you) when the user is owning the event. I'll try as admin.

**Comment by baderj** [comment]
Sorry, I can also no longer reproduce the error. Now everything works as expected. Also when I add a non admin user, he gets the permission error for both attribute types. I tried different type of objects, with different distribution levels but it worked all the time.

So I most definitively messed up something and there is no issue at all in PyMISP. Since the script will run daily on multiple instances, I will report back if the problem happens again.

**Comment by Rafiot** [comment]
Excellent, thank you for the update!
