### ISSUE TITLE
Is PyMISP connecting with local instance of MISP ?

### ISSUE THREAD

**Issue by faizanfareed** [MISP/PyMISP#636]
I'm new to MISP i have some questions related to PyMISP that's why I'm here 

1. - Can we directly connect with Global MISP instead of the local instance of MISP to fetch threat feeds using PyMISP? 
2. - Is PyMISP only working with the local instance of MISP to fetch feeds? 
3. - And the last one is any way to direct fetch feeds from global MISP?

Local means MISP instance running on my system.
I need some help to understand PyMISP. 
Thanks

**Comment by adulau** [comment]
There is no such thing as "Global MISP".  Not sure where you got that naming.

You have to configure your code (API Key and url)  to connect to one or more MISP (own or other instances from third parties). 

Check the examples directory and especially the [keys.py](https://github.com/MISP/PyMISP/blob/main/examples/keys.py.sample) file.
