### ISSUE TITLE
Correlate toggle dialog doesn't display if clicked after attribute add

### ISSUE THREAD

**Issue by dspruell-rs** [MISP/PyMISP#64]
* Ubuntu Linux 14.04.5 LTS
* PHP 5.5.9-1ubuntu4.21
* MISP 2.4.69

Having some trouble with a behavior that I think shows up like this:

1. Add new attribute to an event
2. Click to toggle the Correlate checkbox on the new attribute
3. The screen dims as the confirmation dialog renders, but the dialog (modal?) is not rendered. Hit escape to dismiss the invisible dialog. Any number of attempts to display dialog upon checking box fail.
4. To fix, reload the event URL and allow page to re-render
5. Click the Correlate checkbox and the confirmation dialog renders and functions correctly

**Comment by Rafiot** [comment]
Oo this is weird, I'll try out but I think it is more MISP than PyMISP related.

**Comment by dspruell-rs** [comment]
> Oo this is weird, I'll try out but I think it is more MISP than PyMISP
> related.

D'oh, sorry, added to wrong project without realizing.

**Comment by cristianbell** [comment]
related to https://github.com/MISP/MISP/issues/1753.
