### ISSUE TITLE
Attribute add_tag not working

### ISSUE THREAD

**Issue by imidoriya** [MISP/PyMISP#641]
I'm creating an attribute, which returns `pythonify=True`.  The attribute is created in MISP.  I then run:
```
attrib.add_tag("mytag", local=True)
```
But the tag doesn't get added.  I've also tried without the local.
I've also tried:
```
attrib.tag("mytag", local=True)
```
But that doesn't exist.

Looking at the code, it seems `add_tag` tries to create a new tag at a higher level?  Is that right?  I'm a bit confused on the way to do this.

Thanks!

**Comment by imidoriya** [comment]
Figured it out.. sorry
```
client.tag(attrib, "mytag", local=True)
```

**Comment by imidoriya** [comment]
If the attrib.add_tag (`_add_tag` in MISPAbstract) is suppose to add a tag to the attribute, I couldn't get it to work.  So maybe this is something to look at as a possible bug.

**Comment by Rafiot** [comment]
How were you using it? This is an example in the test suite that definitely works: https://github.com/MISP/PyMISP/blob/main/tests/testlive_comprehensive.py#L1300

**Comment by imidoriya** [comment]
It essentially looked like this...
```
attribute = MISPAttribute()
.. build out attribute ..
attrib = misp.add_attribute(event, attribute, pythonify=True)
attrib.add_tag("mytag")
```

**Comment by Rafiot** [comment]
oh yeah, `MISPAttribute.add_tag is` purely in memory and doesn't push anything to MISP (all the methods in MISPEvent/MISPAttribute, ... are in memory, and need to be pushed to your MISP instance).

Unless I'm mistaken (ping @mokaddem), I think you can now do `misp.update_attribute(attrib)`, and it will update the attribute on your MISP instance.
