### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by tinamina12** [MISP/PyMISP#642]
i am doing a restsearch on events using following:

relative_path = 'events/restSearch/'
    body = {
        "returnFormat": returnFormat,
         "enforceWarninglist": "True",
         "type": attribute_type,
         "last": "5h"    
    }

and i am getting internal server error. the logs are as below:

2020-10-23 15:58:22 Error: Fatal Error (1): Maximum execution time of 300 seconds exceeded in [/var/www/MISP/app/Model/Whitelist.php, line 107]
2020-10-23 15:58:22 Error: [InternalErrorException] Internal Server Error
Request URL: /events/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Maximum executi...', '/var/www/MISP/a...', 107)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Maximum executi...', '/var/www/MISP/a...', 107, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}

Please help.

**Comment by tinamina12** [comment]
@iglocska  @Rafiot  please help

**Comment by Rafiot** [comment]
You should use pagination if the response it too big/takes too much time. Add `page` and `limit` in your request.
