### ISSUE TITLE
Json Keyerror 

### ISSUE THREAD

**Issue by tinamina12** [MISP/PyMISP#644]
I have installed MISP and pymisp today. Now i want to return the result in suricata format. But when i run the code, KeyError: 'accept' error appears. This works only when i write returnformat as json. No other format is working. My code and error are as below:

Code: 

from pymisp import ExpandedPyMISP

def get_data(returnFormat,attribute_type):
    misp_url = 'xxxx'
    misp_key = 'xxxx'
    misp_verifycert = False
    relative_path = 'events/restSearch'
    body = {      
      "returnFormat": returnFormat,
            "enforceWarninglist": "True",
            "type": attribute_type,
            "last": "1h"
    }
    misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert)
    misp.direct_call(relative_path, body)

    alerts=misp.direct_call(relative_path, body)
    print(alerts)
get_data("suricata", "ip-dst")

Error: 

Traceback (most recent call last):
  File "test.py", line 25, in <module>
    get_data("suricata", "ip-dst")
  File "test.py", line 20, in get_data
    misp.direct_call(relative_path, body)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pymisp/api.py", line 2468, in direct_call
    return self._check_response(response, lenient_response_type=True)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pymisp/api.py", line 2976, in _check_response
    if lenient_response_type and not response.headers['Accept'].startswith('application/json'):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'accept'

**Comment by tinamina12** [comment]
@iglocska  @Rafiot  please help

**Comment by Rafiot** [comment]
This error has been fixed in this commit: https://github.com/MISP/PyMISP/commit/d428858f1ed43e36f3190ff9324b9b8cda07bbd3

It will be in the next release.
