### ISSUE TITLE
How to search for tag by name, or partial name, in PyMISP?

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/PyMISP#648]
I have the same question as raised on the last line of #638: how to use PyMISP to find tags by name?  The web UI tags page lets me filter the list of tags by partial string match on the name just beautifully, so I'm pretty confident the back-end supports this feature just fine.  But I'm baffled which search or other method to call from PyMISP.  If this feature is there already but a bit  under-documented, I promise to submit a PR adding the answer to the relevant docstring(s). Thanks in advance.

**Comment by chrisinmtown** [comment]
I'm guessing that the community does not know the answer here, so I'll have to wait for the PyMISP maintainers to find time to reply.

**Comment by iglocska** [comment]
@chrisinmtown - do you mean searching for actual tags, or searching for data with certain tags attached?

If you want to search for events/attributes, you can search for "tags": ["my_taxonomy:predicate=%"] for example and it will find all tags starting with `my_taxonomy:predicate=`

If you just want to query a list of tags that match a pattern, not associated data, the MISP api way of doing it is:

`/tags/index/searchall:keylogger` where keylogger is a substring (Thanks @mokaddem for the hint)

This needs to be exposed via the PyMISP api still though, as discussed with @Rafiot

**Comment by chrisinmtown** [comment]
Right, just searching for bare naked tags w/o regard to their use in any other MISP data elements.

Please let me know if I can help extend PyMISP to call the /tags/index/searchall:STRING endpoint. I can at least test it :)
