### ISSUE TITLE
Sample file altered when using upload_sample

### ISSUE THREAD

**Issue by jymcheong** [MISP/PyMISP#65]
<img width="1090" alt="screenshot 2017-03-20 13 08 38" src="https://cloud.githubusercontent.com/assets/11232021/24089163/681485e4-0d6e-11e7-8175-6de9dc463461.png">

The sample with correct hash '5dbf819539ae860f0d52797ebf0a3a5f' is uploaded via 'Add Attachment' whereas the other one is via PyMISP upload_sample. 

Code used:
`r = m.upload_sample(sample_fname, '/some/path/' + sample_fname, None, None, True, None, None, row[1], None, severity)`

Code works since a new event is created with attributes related to the uploaded file.

MISP 2.4.67
pymisp-2.4.67-py3.4

**Comment by Rafiot** [comment]
Repose of https://github.com/CIRCL/PyMISP/issues/91
