### ISSUE TITLE
update upload_stix api to send data directly

### ISSUE THREAD

**Issue by remydewa** [MISP/PyMISP#652]
Hello,

The goal here is simple. Allow the upload_stix API to send the stix object without having to go through the upload of a file

**Comment by Rafiot** [comment]
You can already pass a pseudofile (BytesIO/StringsIO) to the method, so no need to read a file on the disk.

Just making sure: are you working on a PR? Or waiting on us to do so? Either is fine, just making sure we're not duplicating work.

**Comment by Rafiot** [comment]
oh, right, the PR was on the way ;)

**Comment by remydewa** [comment]
Oh thx Rafiot. You are right. I tried:

`f = io.StringIO(json.dumps(bundle))`

and it works

Thanks!

**Comment by Rafiot** [comment]
It makes sense to have a way to do it directly on PyMISP, with an other keyword. Your PR is merged :)

**Comment by remydewa** [comment]
Yes, thanks a lot!

Rémy
