### ISSUE TITLE
Upgrade from 2.4.119.1 to 2.4.133 - misp_client.search() data structure changed

### ISSUE THREAD

**Issue by LFED-FP** [MISP/PyMISP#654]
As the title indicates, I have upgrade my version of misp to `2.4.133` from my previously used version of `2.4.119.1`. 

Whenever I want to search misp [misp_client.search()](https://github.com/MISP/PyMISP/blob/main/pymisp/api.py#L1876) I notice that the search object being returned has a changed structure. 

In version `2.4.119.1` the structure of the response object was 
```
{'response': [{ 'Event': {}, 'Event': {}, }] }
```

Whereas in version `2.4.133` the structure of the response object is
```
[{ 'Event': {}, 'Event': {}, }]
```

This change in the response object is having detrimental affects on my code. Is there a way to return to the old data structure? I am curious why this change was made and is needed?

Thank you

**Comment by Rafiot** [comment]
Yes, it was part of the normalization of the output that happen when we removed python 2.7 support, in January 2020.

There is no way to get the old format with the search method. If you absolutely want the old format, you can use direct_call, and build the query manually.

**Comment by LFED-FP** [comment]
Thanks for the swift reply @Rafiot ! What do you mean by
```
it was part of the normalization of the output that happen when we removed python 2.7 support
```

I dont understand what this means. Did the upgrade to Python3 from 2 force this change in the return object. What is meant by `normalization of the output`?

Is there any documentation in the docs on this change?


Thanks again :-)

**Comment by Rafiot** [comment]
I assume you were using this method: 
https://github.com/MISP/PyMISP/blob/97a706a361913152cfb33bcbb0153814072c62d3/pymisp/api.py#L1252 
if yes, it was marked as deprecated since 2.4.111, and removed in 2.4.119.1 (by renaming aping.py to api.py).

Normalization as when you search for events, you get a list of event. Same for Attributes. No need of a confusing wrapper.

**Comment by LFED-FP** [comment]
Thanks for the feedback
