### ISSUE TITLE
Error adding event, after upgrading to PyMISP 2.4.134

### ISSUE THREAD

**Issue by mhpchaves** [MISP/PyMISP#657]
Hello,

After upgrading to pymisp v2.4.134, I've tryed to run the following code from the pymisp examples repository (create_events.py):

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pymisp import ExpandedPyMISP, MISPEvent
from keys import misp_url, misp_key, misp_verifycert
import argparse


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Create an event on MISP.')
    parser.add_argument("-d", "--distrib", type=int, help="The distribution setting used for the attributes and for the newly created event, if relevant. [0-3].")
    parser.add_argument("-i", "--info", help="Used to populate the event info field if no event ID supplied.")
    parser.add_argument("-a", "--analysis", type=int, help="The analysis level of the newly created event, if applicable. [0-2]")
    parser.add_argument("-t", "--threat", type=int, help="The threat level ID of the newly created event, if applicable. [1-4]")
    args = parser.parse_args()

    misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert)

    event = MISPEvent()
    event.distribution = args.distrib
    event.threat_level_id = args.threat
    event.analysis = args.analysis
    event.info = args.info

    event = misp.add_event(event, pythonify=True)
    print(event)
```

And it is generating the following errors:

$ ./create_events.py -i "Test event"
Traceback (most recent call last):
  File "./create_events.py", line 25, in <module>
    event = misp.add_event(event, pythonify=True)
  File "/home/mhp/MISP/PyMISP/pymisp/api.py", line 332, in add_event
    e.load(new_event)
  File "/home/mhp/MISP/PyMISP/pymisp/mispevent.py", line 1168, in load
    self.from_dict(**event)
TypeError: from_dict() argument after ** must be a mapping, not list

./create_events.py -i "Test event" -d 0 -a 0 -t 1              
Traceback (most recent call last):
  File "./create_events.py", line 25, in <module>
    event = misp.add_event(event, pythonify=True)
  File "/home/mhp/MISP/PyMISP/pymisp/api.py", line 332, in add_event
    e.load(new_event)
  File "/home/mhp/MISP/PyMISP/pymisp/mispevent.py", line 1164, in load
    raise PyMISPError('Invalid event')
pymisp.exceptions.PyMISPError: Invalid event

Please, can you check this issue?

Thanks,
Marcelo.

**Comment by Rafiot** [comment]
So for some reason, POST of the following on `events/add`:
```json
{
  "uuid": "1e34f52e-5615-43bc-9c9f-dccc18c8ab94",
  "info": "test"
}
```

returns 

`[]`

@iglocska @JakubOnderka @mokaddem Any idea why?

**Comment by mokaddem** [comment]
It's working for me on MISP's 5a29fcc3703af536ce27eec436ee396e807d7b83 ... :/

**Comment by JakubOnderka** [comment]
Fixed now by https://github.com/MISP/PyMISP/pull/660

**Comment by chrisinmtown** [comment]
It sounds like this bug blocks adding events using PyMISP version 2.4.134.  If that's correct, maybe this is worth mentioning in the [release notes](https://github.com/MISP/MISP/releases) ?

**Comment by Rafiot** [comment]
The bug shouldn't be part of the v2.4.134 release published on pypi, as the PR was merged after.

This is the faulty commit: https://github.com/MISP/PyMISP/commit/5e4dd2b974569032087d0035c8085f3865b3f3e8

This is why I would like to make sure there isn't something else I'm missing.

**Comment by chrisinmtown** [comment]
Thanks for clarifying.  Glad to hear it.  So the title here probably should be something like "... after upgrading to PyMISP 2.4.134++ " with the actual commit hash they're using.

**Comment by mhpchaves** [comment]
It's working for me now. Thank's.

**Comment by Rafiot** [comment]
:+1:
