### ISSUE TITLE
Error when adding custom MISPObject

### ISSUE THREAD

**Issue by ticentra** [MISP/PyMISP#658]
Hello, I've seen similar issues brought up already, but even with their content I can't figure out how to fix my code so...

PyMISP version:  2.4.134
MISP version: 2.4.134

I've created custom objects templates, and they work flawless in MISP web interface, but I can't add the object via PyMISP. The code works with predefined templates just fine. 

Error:
```
    raise NewAttributeError("The type of the attribute is required. Is the object template missing?")
pymisp.exceptions.NewAttributeError: The type of the attribute is required. Is the object template missing?
```

Code:
```
misp = ExpandedPyMISP(misp_url, misp_key, False)
[...]
misp_obj = MISPObject(name='domain-ip-test-copy')
misp_obj.add_attribute('domain', value='test.domain')
misp_obj.add_attribute('ip', value='1.1.1.1')
misp.add_object(event_uuid, misp_obj)
```

After some digging I've also tried a version with **misp_objects_path_custom** set, but no matter what path I give it's still the same error. The files are in the same folder that predefined templates:

**/var/www/MISP/app/files/misp-objects/objects**

but no matter if I set 

`misp_obj = MISPObject(name='domain-ip-test-copy', misp_objects_path_custom='objects')`

or 

`misp_obj = MISPObject(name='domain-ip-test-copy', misp_objects_path_custom='var/www/MISP/app/files/misp-objects/objects')`

or anything in between.... the error is still the same. 

Can you help me? Is it just the matter of setting the misp_objects_path_custom correctly - in this case please instruct me what it should be. Or am I missing something else? I did check the permissions on files and they're the same as other templates. What is the reason for this variable if the files are in the same folder as all the other templates?

**Comment by Rafiot** [comment]
The 2nd example should work, but there is a missing `/` at the beginning of your snippet. Can you try again with the following:

`misp_obj = MISPObject(name='domain-ip-test-copy', misp_objects_path_custom='/var/www/MISP/app/files/misp-objects/objects')`

And the name of the object is `domain-ip-test-copy`. Do you have a directory with that name in the path you're using?

Can you do `ls /var/www/MISP/app/files/misp-objects/objects/domain-ip-test-copy` and give me the output? It should have a file `definition.json`.

**Comment by ticentra** [comment]
I've tried 
`misp_obj = MISPObject(name='domain-ip-test-copy', misp_objects_path_custom='/var/www/MISP/app/files/misp-objects/objects')`

as well as `/objects` and anything in between as well... Same error.

There are `definition.json` files in all custom templates folders I've tried. First I created a fully custom one for my needs. Worked in WebUI so I wanted to implement it in my script but got that error... I tried with an exact copy (changing name and UUID) of domain-ip object template, in case there is something wrong in the template itself - but the same outcome... Works no problem in WebUI.... 

I have PyMISP installed with pip both in PyCharm and in virtualenv on server... I'll try to install it with `-e` in a new venv and see if it works without the `misp_objects_path_custom` variable there. But it's really frustrating that I can't get it to work normally :T

**Comment by Rafiot** [comment]
There are a few moving parts, but this feature it part of the test suite, so it may help:

https://github.com/MISP/PyMISP/blob/main/tests/testlive_comprehensive.py#L1229

**Comment by ticentra** [comment]
I'm having issues with installing PyMISP in editable mode due to proxy restrictions... will try to figure that out but it would be ideal for me to get it to work without it. Especially that it will be used in production if it finally works... 

Could the path problem be caused by my MISP instance being deployed in docker? I tried creating a directory with a copy of the template in /home/misp-objects/ - and put `domain-ip-test-copy` directory with `definition.json` there, and gave path to it, but to no avail... Just in case, I even tried to put the file locally where I run my script... I was relieved THAT didn't work ;)

Is there a specific way I should give path variable if the MISP instance is running on docker? From which directory exactly does the library try to access the file via path?

**Comment by Rafiot** [comment]
So I have absolutely no idea how the docker package is working, so maybe? Which one did you use? Either way, I'd recommend you to open an issue in the docker repo.

The test suite works without the editable setting, so you can definitely get it to work directly. It is very confusing that it doesn't work for you.

**Comment by chrisinmtown** [comment]
Please forgive if this is a dumb question, do you have the object definition file locally -- in site packages where you are running the client program?  I don't think the add_attribute method makes a request to the MISP server to get the object def.  It appears to me that for PyMISP to create an instance of an object, the object template must be available in the filesystem where you run the client program. When I tried this, PyMISP tries to find the object definition below where PyMISP is installed, which for me is directory /Users/my-name-goes-here/.virtualenvs/py36/lib/python3.6/site-packages/pymisp/data/misp-objects/objects/.

**Comment by ticentra** [comment]
That's................... wow. Okay, yeah, I put the copy of the template locally and gave the function full path to it - before I tried with the path starting where the library file that runs this function is located. And now it finally worked.

Why is it necessary to have the file locally? It's not necessary with adding custom galaxies to events. Or tags.

I work with couple MISP instances and I run my scripts from couple places - this means I have to have files of custom objects for each instance in every place I run the scripts. And I have to keep track of the changes and apply updates manually? What if I don't have access to the template source file but still want to add a custom object? What if two MISP instances have custom objects of the same name but different `definition.json` file - I have to keep them in different folders and change the `misp_objects_path_custom ` accordingly. What if the script doesn't necessary run as a simple script but in some other application and I can't just add the files to its environment?

I see now that all the templates for build in objects are in PyMISP folder as well... Since the files are on MISP server, isn't it possible to forgo having the files locally as an improvement? If the script would try to add an object that MISP doesn't have - then trow an error. Would you consider it as a future improvement? Or would it have to be improved on MISP side first? It will really be a pain to keep track of the custom template files - especially during their development.

**Comment by chrisinmtown** [comment]
Please comment on #659

**Comment by Rafiot** [comment]
@ticentra Does the comment there help: https://github.com/MISP/PyMISP/issues/659#issuecomment-727927476

tl;rd: you do not need to have the file locally, but if you don't, you need to pass a `type` when adding an attribute to an object. The template is just an helper.

**Comment by ticentra** [comment]
Thank you all for your help :) I've commented on the second issue as well, closing this one since it's solved.

**Comment by chrisinmtown** [comment]
I reproduced the error that @ticentra  reported when adding an object using a custom object template. I have an object template that is defined on the server but is not in the local PyMISP client site-packages area.  I used "strict=False" on the MISPObject() invocation, and added an attribute with a type='text' invocation.  The server rejects the add attempt with a 403 (Forbidden) which is baffling; my script (shown above) creates an event just fine, so I'm pretty confident the auth key is right. Here's the error I see on the client:
```
ERROR [api.py:2960 - _check_response() ] Something went wrong (403): {'saved': False, 'name': 'Could not add Object', 'message': 'Could not add Object', 'url': '/objects/add', 'errors': 'Object could not be saved.\n'}
add_object failed: (403, {'saved': False, 'name': 'Could not add Object', 'message': 'Could not add Object', 'url': '/objects/add', 'errors': 'Object could not be saved.\n'})
```
Here's the error from the server-side error.log file:
```
2020-11-16 16:26:12 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/Controller/ObjectsController.php, line 275]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 232
ObjectsController::add() - APP/Controller/ObjectsController.php, line 275
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```

**Comment by Rafiot** [comment]
Alright, you're correct, there are a few extra fields that are extracted from the template and injected in the `MISPObject`, when the template is known.

`meta-category` in one of then, and you also need `uuid`, `description`, and `version` (see https://github.com/MISP/PyMISP/blob/4e830a435b5408a01dcb8d69bc4ead6c687a221b/pymisp/mispevent.py#L671). 

And it's already a bit more tricky to use the class without a template to massage the data for you, but if you have no choice, this is the way to do: add these keys manually in the newly created `MISPObject`. Note that you have to be super careful with the UUID, and it absolutely has to be unique (never pick the UUID of an existing template). 
For the version, it should to be bumped every time you change the template (or at least you need to have a version number higher than the highest you have in your dataset if you publish the data to 3rd parties). An easier way to get around that is to use the day in isoformat as a version (`20201117`), so this way, you're assured to always increment it during the test phase.

**Comment by ticentra** [comment]
Alright, thank you. I can confirm that for an example template:
```
{
  "attributes": {
    "domain": {
      "categories": [
        "Network activity",
        "External analysis"
      ],
      "description": "Domain name",
      "misp-attribute": "domain",
      "multiple": true,
      "ui-priority": 1
    },
    "first-seen": {
      "description": "First time the tuple has been seen",
      "disable_correlation": true,
      "misp-attribute": "datetime",
      "ui-priority": 0
    },
    "ip": {
      "categories": [
        "Network activity",
        "External analysis"
      ],
      "description": "IP Address",
      "misp-attribute": "ip-dst",
      "multiple": true,
      "ui-priority": 1
    },
    "last-seen": {
      "description": "Last time the tuple has been seen",
      "disable_correlation": true,
      "misp-attribute": "datetime",
      "ui-priority": 0
    },
    "port": {
      "categories": [
        "Network activity",
        "External analysis"
      ],
      "description": "Associated TCP port with the domain",
      "misp-attribute": "port",
      "multiple": true,
      "ui-priority": 1
    },
    "registration-date": {
      "description": "Registration date of domain",
      "disable_correlation": false,
      "misp-attribute": "datetime",
      "ui-priority": 0
    },
    "text": {
      "description": "A description of the tuple",
      "disable_correlation": true,
      "misp-attribute": "text",
      "recommended": false,
      "ui-priority": 1
    }
  },
  "description": "A domain and IP address seen as a tuple in a specific time frame.",
  "meta-category": "network",
  "name": "domain-ip-test-copy",
  "required": [
    "ip",
    "domain"
  ],
  "uuid": "2cc56437-97ed-4a83-b643-7848d78dc96f",
  "version": 1
}
```

Code:

```
    misp_obj = MISPObject(name='domain-ip-test-copy', strict=False)
    setattr(misp_obj, 'meta-category', 'network')
    misp_obj.template_uuid = '2cc56437-97ed-4a83-b643-7848d78dc96f',
    misp_obj.description = 'A domain and IP address seen as a tuple in a specific time frame.',
    misp_obj.template_version = 1
    misp_obj.add_attribute('domain', type='domain', value='test.domain')
    misp_obj.add_attribute('ip', type='ip-dst', value='1.1.1.1')
    misp.add_object(event_uuid, misp_obj)
```

is working.

I really hope this will be improved in the future because it doesn't look pretty at all. The description field especially feels unnecessary - uuids are unique and I can understand version for checking the template hasn't changed... but why description :D If an object has a long one it would really look unclean in the code.

**Comment by chrisinmtown** [comment]
Thanks @Rafiot for the detail and thanks @ticentra especially for posting working code. But this is so tricky that I think we can safely say, PyMISP version 2.4.133 requires a template locally (and the MISP instance must have same) to create a new object-attribute.

I hope the CIRCL team will look favorably upon #659  :)

**Comment by Rafiot** [comment]
Absolutely, we need to have a way to get the template from a MISP instance.

Note that if the template is not known on the MISP instance, you can still push the object, but it won't be editable via the UI.

In the meantime, I'm closing this issue, as it requires changes on MISP side (getting a template in a usable format).
