### ISSUE TITLE
Consider deleting object if all member attributes are deleted?

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#668]
I notice if all `MISPObjectAttribute` within a `MISPObject` are deleted with `pymisp.delete_attribute`, that the remaining parent `MISPObject` still is set to `deleted 0`. This permits the WebUI to display that now empty object in the Event view, and other REST retrievals will return that empty object.

I understand that client code is better served by using `pymisp.delete_object`; however, I am wondering if it makes sense for the Attribute Controller to delete the object when all the attributes are deleted perhaps offering cleaner integrity.

I may be misunderstanding this use case and am open to your wisdom. Thanks.

**Comment by Rafiot** [comment]
On the UI, an empty object for you may not be empty for other (it depends on the sharing parameters of each individual attribute in the object), so we can definitely not just delete it.

What could be done on the web interface is to not show it to you if it is empty (please open a feature request in the MISP repo), but marking it as deleted is definitely not an option.

On PyMISP side, I could potentially skip them from the structure, but again, it doesn't mean they don't exist (with content) for an other user. And I see a case where an empty object is created somewhere and populated somewhere else. Not being able to access the empty object would be a problem.

**Comment by github-germ** [comment]
Spun out to https://github.com/MISP/MISP/issues/6692
