### ISSUE TITLE
How to know if a event has been deleted or updated?

### ISSUE THREAD

**Issue by kalyanbhetwal** [MISP/PyMISP#67]
I have fetched 1 month data using PyMISP and stored locally. Now I want to fetch incremental data only eg. 1 day. This can be easily done using _**download_last('time_interval')**_ functionality given by the API. I want to know is there anyway to find out whether the events in last month data has been updated or deleted so that I can change my locally stored data. 

Thanking in advance. Please let me know if the question needs further explanation.

**Comment by kalyanbhetwal** [comment]
Hi Rafiot, Is there anyway? Am I missing something?

**Comment by Rafiot** [comment]
Sorry, I forgot to answer.

You can use the search command, the `last` parameter let you do exactly that :)

**Comment by kalyanbhetwal** [comment]
Thank you very much for your time and effort. 

I think this solves my problem.  :)

**Comment by Rafiot** [comment]
Great, closing then, reopen if it doesn't work as expected :)
