### ISSUE TITLE
Unexpected behavior when when posting email body with the registered trademark character 

### ISSUE THREAD

**Issue by nighttardis** [MISP/PyMISP#671]
Ran into this issue today. Not sure if this is an issue with the "emailobject" script or the MISP API itself.

I was processing an email that had the registered trademark character in the signature. Line 138 of the EMailObject class was converting this character to "\udcea" and python refuses to print the string and the MISP API just threw a "this isn't valid json" error. The odd thing to me is if I used the "to_json()" function on the MISP event I was trying to post it would print out the JSON just fine and was valid JSON. 

To get around this I temporary changed line 138 of the EMailObject from
`self.add_attribute("email-body", body.get_payload(decode=True).decode('utf8', 'surrogateescape'))`
to
`self.add_attribute("email-body", body.get_payload(decode=True).decode('utf8', 'replace'))`
which got me pass the problem, but I'm not sure that is a great fix overall.

Anyone else have any thoughts on this?

**Comment by chrisinmtown** [comment]
happy new year, you might post as an attachment here a sanitized version of that email. Maybe EMailObject doesn't follow all the guidelines?  https://docs.python.org/3/howto/unicode.html

**Comment by Rafiot** [comment]
It resolves the problem by modifying the input, which is suboptimal. `surrogateescape` should keep the initial input (see reference of @chrisinmtown)

Can you share a sample? Also, I'd be interested to know which version of python you're using.

**Comment by nighttardis** [comment]
Well for whatever reason github isn't letting me upload a file. So...hopefully it doesn't ruin this code block
```
Date: Mon, 07 Dec 2020 00:28:29 +0000
From: "user1" <b@b.com>
To: user2 <a@b.com>
Subject: SUBJECT
Mime-Version: 1.0
Content-Type: text/plain;
 charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable


=AE
```
I'm running python 3.8 with pymisp 3.4.135.

**Comment by Rafiot** [comment]
This is the object generated by `EMailObject` [obj.txt](https://github.com/MISP/PyMISP/files/5795592/obj.txt). It is a valid json generated by json.dumps.

**Comment by Rafiot** [comment]
That should be fixed now (see commit). It will be in the next release of PyMISP.

**Comment by nighttardis** [comment]
Thanks, just tested the update and it is working as I would have expected.

**Comment by Rafiot** [comment]
Great! Thank you for the report, and let us know if you have any questions.
