### ISSUE TITLE
Add image in MISPObject attachment

### ISSUE THREAD

**Issue by EduardoSartorii** [MISP/PyMISP#672]
When I use the following code: `self.misp_object.add_attribute("attachment", value=f'{photo}', expand='binary')`

The image never loads on the portal.

**Comment by Rafiot** [comment]
yes, you need to pass the binary (`BytesIO`) of the picture this way:

```
self.misp_object.add_attribute("attachment", value='photo.jpg', data=<photo_as_BytesIO>, expand='binary')
```

**Comment by EduardoSartorii** [comment]
Thank you!!, it worked. <3

**Comment by EduardoSartorii** [comment]
In case anyone has difficulty with BytesIO
` 
from io import BytesIO
       with open(photo,'rb') as f:
            data = BytesIO(f.read())
misp_object.add_attribute("attachment", value=f'{photo}',data=data, expand='binary')
`
