### ISSUE TITLE
get_csv.py -t parameter error

### ISSUE THREAD

**Issue by erkamcetiner** [MISP/PyMISP#673]
I'm trying to use get_csv.py. Everything works great but -t parameter is not working. Here my try:

`python3 get_csv.py -e 1211 -t ip-src -a value -f deneme.csv`

There is no error or something. It's not working. It fetchs all types from event.

**Comment by Rafiot** [comment]
Okay, that one is weird: it works properly if you run the query against `/attributes/restSearch`, but not against `/events/restSearch` (they should both work the same way, afaik). 

For reference, that's the query sent to MISP:

```json
{
    "returnFormat": "csv",
    "type": ["ip-dst|port"],
    "eventid": "81809",
    "requested_attributes": ["value"]
}
```

@iglocska if you have an idea, I'm all ear.

**Comment by iglocska** [comment]
So after a discussion with @Rafiot, the explanation is simple:

When searching /attributes/restsearch, we search for any attribute that matches a list of query criteria. In this case, we want any attribute in event 81809 that is of type ip-dst|port. All good so far.

If we were to search /events/restsearch, we'd be searching for any `events` that match a list of query criteria. In this case, we search for events that have an ID of 81809 and contain at least one ip-dst|port, which gives us the full contents of 81809.

Both scopes have different objectives, in some cases we're interested in individual attributes that strictly match what we're looking for, in some cases we want to extract the full collections that relate to our search.

**Comment by Rafiot** [comment]
https://github.com/MISP/PyMISP/commit/c50bbd5d1c0a0303ab36b7e1ed2bb732c9f66b83 <= feature added to the example script, and defaulting to attributes.
