### ISSUE TITLE
What is limit on event size in attributes etc. for methods like get_event?

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/PyMISP#685]
I'm using PyMISP 2.4.133 to access a MISP 2.4.133 server.  This problem occurs with Python 3.6 and 3.8.  Our database has an event with hundreds of thousands of attributes, many of them deleted. The get_event() method fails with the following error then dumps tens of thousands of lines of JSON (so it's hard to scroll back and find the error):
```
Getting event ID 180277
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymisp/api.py", line 3077, in _check_response
    response_json = response.json()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Unterminated string starting at: line 26340270 column 21 (char 1153953117)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "getEvent.py", line 12, in <module>
    resp = misp.get_event(event=eid, deleted=True, pythonify=False)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymisp/api.py", line 304, in get_event
    event_r = self._check_json_response(r)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymisp/api.py", line 3045, in _check_json_response
    r = self._check_response(response, expect_json=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymisp/api.py", line 3086, in _check_response
    raise PyMISPUnexpectedResponse(f'Unexpected response from server: {response.text}')
pymisp.exceptions.PyMISPUnexpectedResponse: Unexpected response from server: {
    "Event": {

... zillions of lines deleted ...
```
If this is a known problem, let's document it in the get_event docstring - I'll submit a proposal. Or if there's a hidden secret argument I need to supply, please explain. Thanks.

**Comment by Rafiot** [comment]
I'd guess it is because the server closes the connection? What is the max size configured on your webserver?

**Comment by chrisinmtown** [comment]
I'll be glad to check that, is that value a MISP app setting, a PHP setting, an Apache setting, or all of the above?

**Comment by Rafiot** [comment]
I was thinking of memory_limit in the PHP config. But in the response, but it seems you get a json blob, and that one is truncated (?), witch causes the json.load to fail. I'm not totally sure on the config that could cause that, but I'd assume the blob sent back is properly huge. Just in case, I'm adding the size of the response in the message on PyMISP side (https://github.com/MISP/PyMISP/commit/411104bc831cabd1b997384abc92153aa502d85c), but I wouldn't be surprised that we're hitting a limit on the system.

The php settings are visible there: `<MISP_Instance>servers/serverSettings/diagnostics` (section **PHP Settings**). You can configure the max memory and max time by editing the file mentioned in the section.

**Comment by chrisinmtown** [comment]
thanks @Rafiot the server's web UI at the path you mention yields the following limits. This seems to have revealed a bug.  The UI shows the memory_limit of 128M, but our php ini file actually sets 128*G*.  Maybe I should open an issue for that.
```
max_execution_time (7200)… OK (recommended: 300)
memory_limit (128M)… Low (recommended: 2048M)
upload_max_filesize (50M)… OK (recommended: 50M)
post_max_size (50M)… OK (recommended: 50M)
```
But going back to the error message, the failure occurred after reading 1,153,953,117 bytes.  That's about a gigabyte of a JSON response string, and it's more than the trivial translation of 1GB to decimal (1,073,741,824).  I don't see an obvious match with any of the PHP limits shown here.  But there's always the chance that a proxy server in between has its OWN limit, which is another thing I have to check into.

**Comment by chrisinmtown** [comment]
https://github.com/MISP/MISP/issues/6886

**Comment by chrisinmtown** [comment]
I think the conclusion here is that there is no set limit on the response as far as MISP or PHP are concerned. I need to keep digging to find the cause of this failure, likely something local.
