### ISSUE TITLE
Add local tag instead of global tag via PyMISP

### ISSUE THREAD

**Issue by naacbin** [MISP/PyMISP#688]
Hi,

I didn't find a way to add local tag in the documentation, is there a official way to do this ?

Thank you.

**Comment by Rafiot** [comment]
Just making sure what you're aiming for: 
* Create a local tag on your MISP instance? 
* Add an already existing tag to a MISP event/attribute, and this tag should not be synchtonized?

**Comment by naacbin** [comment]
Add an already existing tag to a MISP event/attribute, and this tag should not be synchtonized

**Comment by Rafiot** [comment]
ok, then you need to modify the tags settings: https://<domain>/tags/edit/<tagid> and untick the `exportable` box

If you want to do it with the API, you can do the following:

```python
to_post = {"exportable": False}

pymisp.update_tag(to_post, <tagid>)
```

For automation purposes, you can do something like that:

```python
tag = pymisp.get_tag(<tagname>, pythonify=True)

tag.exportable = False

pymisp.update_tag(tag)
```

**Comment by naacbin** [comment]
I try to do it via UI and the tag isn't add to the event as a local tag but as a global tag. 

I'm probably not clear enough. Currently, I use a JSON file to have a private taxonomy for my organization (available at https://url.tld/taxonomies/index), some of its tags need to be added to an event/attribute as local tag. Like in this picture :
![image](https://user-images.githubusercontent.com/58483316/105189731-8eac8f80-5b35-11eb-9a7b-dc3c1105ebdb.png). But I haven't find a way to do it without UI.

**Comment by Rafiot** [comment]
Oh, right, sorry, I misunderstood.

The following should do the trick:

```python
pymisp.tag(<MISPEvent or MISPAttribute>, <tagname>, local=True)

```

**Comment by naacbin** [comment]
Thank you very much it works. Is there a way to do it at the creation of the event instead of updating the event ?

**Comment by Rafiot** [comment]
If I'm not mistaken, you can pass the key `local: 1` when you add the tag, so depending how you do that, it can be something like:
```python
tag = MISPTag()
tag.name = 'tlp:red'
tag.local = 1

<MISPEvent>.add_tag(tag)
```

**Comment by naacbin** [comment]
The following code didn't work (didn't tag the event at all) : 
```
tag = MISPTag()
tag.local = 1      
for tags in self.config['tags']:
    tag.name = tags
    misp_event_obj.add_tag(tag)
```

**Comment by Rafiot** [comment]
`misp_event_obj` is a MISPObject, right?

`MISPObject.add_tag` doesn't talk to your MISP instance, it only adds it to the local object you're currently creating. You need to do `PyMISP.add_object(misp_event_obj)` or `PyMISP.update_object(misp_event_obj)` to push it to your MISP instance.

**Comment by naacbin** [comment]
> `misp_event_obj` is a MISPObject, right? No it's a MISPEvent. `misp_event_obj = MISPEvent()`
When I do that, tags are added to the event but not locally :  
```python
for tags in self.config['tags']:
    misp_event_obj.add_tag(tags) 
```

**Comment by Rafiot** [comment]
ok, same thing then, sorry: `MISPEvent` is also not talking to your MISP instance. You need to call add/update_event in order to interact with the instance.

**Comment by dewu1994** [comment]
> The following should do the trick:
> 
> ```python
> pymisp.tag(<MISPEvent or MISPAttribute>, <tagname>, local=True)
> ```

For me it's not working. I get an error "Local tags can only be added by users of the host organization", but I already belong to the host organization. I can see that _tag_ function refers to _tags/attachTagToObject_ URL and I had the same issue when I was trying to do this via API requests directly, not with pymisp. And the workaround then was to use this URL instead: _/events/addTag/[event_id]/[tag_id]/local:1_
But what is the workaround for using pymisp in such case?

**Comment by Rafiot** [comment]
Alright, that's a but on MISP side then. cc @iglocska @mokaddem

**Comment by mokaddem** [comment]
Hey @dewu1994,
I see you have the `Local tags can only be added by users of the host organisation` error.
Could you please make sure the user performing the request belongs to the same organisation as the one defined in the `MISP.host_org_id` setting?
Thanks!

**Comment by dewu1994** [comment]
Yes, it belongs to the correct one. I've already tried to switch between organizations but no difference. Also, this account is an administrator, so it seems to be some bug from MISP side. Is local tagging via pymisp working for you properly?

**Comment by mokaddem** [comment]
Tried with both PyMISP
```python
api.tag('eca55530-a09e-4833-81cc-446e6e32db04', 'tlp:red', local=True)
```
and via the API
```json
// /tags/attachTagToObject/
{
    "uuid": "eca55530-a09e-4833-81cc-446e6e32db04",
    "tag": "tlp:red",
    "local": true
}
```
with different user roles and both approach work as intended.
Could you please check the following:
1. Your MISP is up-to-date to the latest available version
2. You are using the correct `host_org` (you have to make sure that the ID are the same, and not the name)
    - To check for the IDs, check the `User.org_id` field at `/users/view/me.json`
    - And the actual ID of the `MISP.host_org_id` field at `/servers/serverSettings/MISP.json`
3. You don't have errors in your logs (located at `/MISP/app/tmp/logs/error.log`)

Thanks!

**Comment by dewu1994** [comment]
It looks like you've discovered the root cause! It seems that no host organization is selected. We have 2 organizations set in MISP, but any of them is set to host. How I can change this, as I don't see such option in organization edit view?

**Comment by mokaddem** [comment]
Glad the issue is solved!
The reason is PyMISP uses a different endpoint than the GUI.
Also, if the user is an admin, some ACL checks are not performed. ;)

**Comment by crfrancesco** [comment]
hi, i can't add local tag to an attribute with PyMISP. I'm reciving the same error : 403 Local tags can only be added by users of the host organisation. How can i configure an organization as host organization ? can i use MISP GUI?
