### ISSUE TITLE
Importing PyMISP fails due to lief not having logging attribute

### ISSUE THREAD

**Issue by rkokkelk** [MISP/PyMISP#690]
Hi guys,

First of all thanks for this project. Recently I tried to import PyMISP which fails because `logging` attribute is requisted from `lief` which does not exist. See stacktrace:

```python
    from pymisp import PyMISP
  File "/usr/local/lib/python3.8/site-packages/pymisp/__init__.py", line 28, in <module>
    from .tools import AbstractMISPObjectGenerator  # noqa
  File "/usr/local/lib/python3.8/site-packages/pymisp/tools/__init__.py", line 4, in <module>
    from .create_misp_object import make_binary_objects  # noqa
  File "/usr/local/lib/python3.8/site-packages/pymisp/tools/create_misp_object.py", line 16, in <module>
    lief.logging.disable()
AttributeError: module 'lief' has no attribute 'logging'
```

Dependencies:
```
pymisp==2.4.137
lief==0.10.1
```

Probably related to changes made in: 76c4f92

**Comment by Rafiot** [comment]
We forgot to update dependencies somewhere, because the PyPi package requires lief 0.11.0, and so does the pyproject file.
So short answer is to update lief, but I'm wondering where the dependencies you listed come from?

**Comment by rkokkelk** [comment]
This specific dependency is used by other packages integrated in the same Celery worker. This indeed could result in some conflicts. The reason I've mentioned it because when I looked in the `setup.py` file the dependency for lief is still:

https://github.com/MISP/PyMISP/blob/e5152167a3b67e553dd85c0bd0ce4bff02aec72c/setup.py#L49

But thanks for the quick fix.

**Comment by Rafiot** [comment]
Right, thank you for the reference. Updating this one, and very much looking forward to be able to get rid of the setup.py file...

**Comment by Rafiot** [comment]
Fix: https://github.com/MISP/PyMISP/commit/80eea5665f84e820144874ede4c8a541bd8fd482
