### ISSUE TITLE
how do i get specific attributes (value,type,category) of an misp event

### ISSUE THREAD

**Issue by sirio771** [MISP/PyMISP#691]

**Comment by Rafiot** [comment]
You will need to give me a little bit more to work with. You can search by value, event ID, look at the response and extract the value.

The documentation of the module is there: https://pymisp.readthedocs.io/en/latest/

**Comment by sirio771** [comment]
I have an event that contains 500 attributes for example, of these attributes I am only interested
the "category, value, type" fields and I have to write it to a JSON file.

**Comment by Rafiot** [comment]
you can get the event, pass pythonify=True, iterate over the attributes, and generate the json.

If you use the search method to get the attribute youré interested in, you can get the CSV output, and do the same.

**Comment by sirio771** [comment]
can you show me the code, please help me

**Comment by sirio771** [comment]
i am beginner in python language.

**Comment by chrisinmtown** [comment]
here's most of what you want. This does not use the Pythonify=True argument that @Rafiot suggested, but the result is similar.
```
#!/usr/bin/env python3
from datetime import datetime
import urllib3
from pymisp import PyMISP


urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
misp = PyMISP(
    url='https://my-company.com:48752',
    key='my-misp-key',
    ssl=False)
eid = '180277'
print('{}: Getting event ID {}'.format(datetime.now(), eid))
resp = misp.get_event(event=eid, deleted=True, pythonify=False)
if 'errors' in resp:
    raise Exception('failed: {}'.format(resp['errors']))
event = resp['Event']
print('{}: Event key=val:'.format(datetime.now()))
for key, val in event.items():
    if key in ['Attribute', 'Feed', 'Object', 'RelatedEvent', 'SharingGroup', 'Tag']:
        print('\t**Skipping {} of len {}'.format(key, len(val)))
        continue
    print("\t{}={}".format(key, event[key]))
ac=0
dc=0
for a in event['Attribute']:
    if a['deleted']:
        dc += 1
    else:
        ac += 1
print('\tattribute count: {} active, {} deleted'.format(ac, dc))
# you can get attribute facets like category, type, value by using the right key
```

**Comment by Rafiot** [comment]
Sorry, I didn't have time to answer yesterday. @chrisinmtown's solution will do the trick, thank you very much!

**Comment by chrisinmtown** [comment]
@sirio771 if your question has been answered, please close this issue, thanks.
