### ISSUE TITLE
PyMISP __init__ assumes user can access Role and UserSettings info, which is not always the case

### ISSUE THREAD

**Issue by JesseMorrison** [MISP/PyMISP#692]
The base __init__ function of class PyMISP calls self.get_user() with Expanded=True, which means it attempts to fill Role and UserSettings info as well.

I have an account with limited permissions on a MISP instance where querying /users/view/me ONLY returns User info, and does NOT return Role, UserSettings, Organization, etc. info. This causes a KeyError exception to bubble up when get_user() tries to index into user_j['Role'], which means I can't use PyMISP to connect to that MISP instance with my user.

My personal workaround is just to comment out the line in __init__ that calls get_user(), since I don't need that info for my use case.

Suggest not calling get_user() until that info is needed, or maybe failing more gracefully until that info is needed.

**Comment by Rafiot** [comment]
It initializes a few variables that are handy to have, and afaik, it was all required.

@iglocska @mokaddem @JakubOnderka is it normal behavior that a MISP instance doesn't return Role, UserSettings, Organization, etc? If yes, what is the minimal I have to expect on PyMISP side?

**Comment by JakubOnderka** [comment]
@Rafiot No, according to MISP code, these fields are always included.

@JesseMorrison Can you please describe, what MISP version do you use and when `/users/view/me` returns just User info?

**Comment by Rafiot** [comment]
Thank you for the feedback, that's what I thought. As you said, the other possibility is a very old MISP instance.

**Comment by JesseMorrison** [comment]
This MISP instance is on version 2.4.110.

Unfortunately, my organization doesn't own this instance, so I don't have much insight into what settings/roles they have set up to return only User info. I can contact them and see how much information they're willing to share.

**Comment by Rafiot** [comment]
That makes sense then.

The instance is vulnerable to a very long list of vulnerabilities and I very strongly recommend you to upgrade it asap (the release was Jul 8, 2019): https://cvepremium.circl.lu/search/misp/misp

If it absolutely impossible, you need to use an older version of PyMISP (version v2.4.106 or v2.4.111.2 should work).
