### ISSUE TITLE
Adding Brotli support has broken PyMisp setup.py

### ISSUE THREAD

**Issue by chmason13** [MISP/PyMISP#695]
Issue: Running setup.py results in error: Failed building wheel for brotlipy

Recreate: ```python3.7 -m pip install -e git+https://github.com/MISP/PyMISP.git#egg=pymisp```

Terminal Output: 
![Screen Shot 2021-02-01 at 4 59 52 PM](https://user-images.githubusercontent.com/17955575/106524072-0cff1f00-64b0-11eb-9f79-6b84dfcbcf91.png)
![Screen Shot 2021-02-01 at 5 02 06 PM](https://user-images.githubusercontent.com/17955575/106524234-45066200-64b0-11eb-90c6-550cadeac2c2.png)
![Screen Shot 2021-02-01 at 5 02 42 PM](https://user-images.githubusercontent.com/17955575/106524248-4a63ac80-64b0-11eb-8e3c-ef0d78cfbd75.png)

**Comment by Rafiot** [comment]
Right, I should probably keep that optional.

What happen if you just do `pip install pymisp`?

**Comment by chmason13** [comment]
```pip install pymisp``` results in the same error

**Comment by Rafiot** [comment]
Out or curiosity, which OS are you on? Because it works just fine on recent ubuntu. 

If you want a quick fix, just install the previous version.

**Comment by chmason13** [comment]
RHEL 7

**Comment by Rafiot** [comment]
right. And Python 3.6?

**Comment by chmason13** [comment]
3.7

**Comment by Rafiot** [comment]
okay, no idea why you don't get a wheel and need to compile it, but I I'll revert that change and make it optional in the next package.

**Comment by Rafiot** [comment]
New package released, thank you for the notification!
