### ISSUE TITLE
Unable to search events from MISP server. Getting Error

### ISSUE THREAD

**Issue by anuashokas** [MISP/PyMISP#697]
CRITICAL [api.py:3180 - _check_response() ] Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.137.3 - Python 3.8', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Cookie': 'MISP-bca85b04-4c47-4750-9d5b-76eedc05ddbc=d3rmu0nd16dq0tstrhq2o7rnfn', 'Content-Length': '265', 'Authorization': '4CXXXXXXXXXXXXXXXXXXXXXXXF', 'content-type': 'application/json'}
Request body:
{"returnFormat": "json", "withAttachments": 0, "metadata": 0, "enforceWarninglist": 0, "includeEventUuid": 0, "includeEventTags": 0, "sgReferenceOnly": 0, "includeContext": 0, "headerless": 0, "includeSightings": 0, "includeDecayScore": 0, "includeCorrelations": 0}
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/restSearch"}
Traceback (most recent call last):
  File "script.py", line 102, in <module>
    main()
  File "script.py", line 71, in main
    events = _get_events()
  File "script.py", line 18, in _get_events
    return [event['Event'] for event in misp.search(controller='events', return_format='json')]
  File "/root/mispToSentinel/lib/python3.8/site-packages/pymisp/api.py", line 2227, in search
    normalized_response = self._check_json_response(response)
  File "/root/mispToSentinel/lib/python3.8/site-packages/pymisp/api.py", line 3164, in _check_json_response
    r = self._check_response(response, expect_json=True)
  File "/root/mispToSentinel/lib/python3.8/site-packages/pymisp/api.py", line 3181, in _check_response
    raise MISPServerError(f'Error code 500:\n{response.text}')
pymisp.exceptions.MISPServerError: Error code 500:
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/restSearch"}

**Comment by Rafiot** [comment]
I'm not sure what you're trying to do there, but `misp.search(controller='events', return_format='json')` will try to return every MISP event you have access to on the platform (you're not passing anything to search), so the error is probably because your server runs out of ram.

**Comment by anuashokas** [comment]
Yes, You are right. it is consuming more RAM. I have increased the memory_limit in php.ini file and fixed the issue. Thanks for the support
