### ISSUE TITLE
Should pymisp.__version__ be bumped now to 2.4.139?

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#699]
With 2.4.139 I still see `pymisp.__version__` as `2.4.138`.

https://github.com/MISP/PyMISP/blob/main/pymisp/__init__.py#L1

**Comment by Rafiot** [comment]
The changes between MISP version `2.4.138` and `2.4.139` didn't require any update on PyMISP side, and there were only two very specific changes in PyMISP in the meantime, so none of that required to package a new release of PyMISP.

The next release of PyMISP will be `2.4.140` (unless there is an urgent fix in the meantime).
