### ISSUE TITLE
search: page broken?

### ISSUE THREAD

**Issue by imidoriya** [MISP/PyMISP#702]
I don't think this is a PyMISP issue as I rolled back to prior versions and it does the same thing, but I'm perplexed.  I also used the REST client in MISP GUI and it returns page 2 without issue.  Could you test this and see if you have any issues?  This is returning 0 for me.  I can't get anything beyond page 1 for some reason.  

`MISP version: 2.4.139, PyMISP 2.4.138`

```py
events = pymisp.search(limit=1, page=2)
print(len(events))
```
> 0

**Comment by imidoriya** [comment]
This works fine:
```py
events = misp.client.direct_call('',{'limit':1,'page':2})
```

**Comment by imidoriya** [comment]
Further testing comparing `search` to `direct_call`, maybe something happened to `events/restSearch`?

This works:
```py
query = {'limit':1,'page':2}
url = 'https://localhost/'
response = misp.client._prepare_request('POST', url, data=query)
events = misp.client._check_json_response(response)
```
This returns `[]`:
```py
query = {'limit':1,'page':2}
url = 'https://localhost/events/restSearch'
response = misp.client._prepare_request('POST', url, data=query)
events = misp.client._check_json_response(response)
```

**Comment by imidoriya** [comment]
I was able to reproduce this directly via the MISP gui.  I think it's this commit that broke it. https://github.com/MISP/MISP/commit/6112c0d4068c0ebcef49da9c7f8646a12f3abd90
If I checkout before that commit, it works fine.  If I checkout that commit, it breaks.

**Comment by iglocska** [comment]
Thanks for the report @imidoriya - nice find!
