### ISSUE TITLE
MISPEvent has methods add_attribute, delete_attribute and add_object - but not delete_object

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/PyMISP#706]
Please tell me if PyMISP's MISPEvent class needs to be extended with the delete_object method.  Attributes are a lot like ObjectAttributes, you add and remove them from an event.  But the MISPEvent class provides no obvious method for removing an objectAttribute:

https://pymisp.readthedocs.io/en/latest/modules.html#mispevent

https://github.com/MISP/PyMISP/blob/2ceb38c741f9432432114998d0c0f8fa36686083/pymisp/mispevent.py#L1470

https://github.com/MISP/PyMISP/blob/2ceb38c741f9432432114998d0c0f8fa36686083/pymisp/mispevent.py#L1483

https://github.com/MISP/PyMISP/blob/2ceb38c741f9432432114998d0c0f8fa36686083/pymisp/mispevent.py#L1535

Am I overlooking something totally obvious? Thanks in advance.

**Comment by chrisinmtown** [comment]
hi @PROTechThor I'm not 100% convinced this is a support request, I can use PyMISP just fine, I think the absence of this method might be a bug, but I want to make sure.

**Comment by Rafiot** [comment]
Let's call it an enhancement.

I'll add it soon, I just forgot to implement it.

**Comment by chrisinmtown** [comment]
Thanks for confirming. I propose:
```
diff --git a/pymisp/mispevent.py b/pymisp/mispevent.py
index ade1172..7249a30 100644
--- a/pymisp/mispevent.py
+++ b/pymisp/mispevent.py
@@ -1549,6 +1549,19 @@ class MISPEvent(AbstractMISP):
         self.edited = True
         return misp_obj
 
+    def delete_object(self, object_id: str):
+        """Delete an object
+
+        :param object_id: ID or UUID
+        """
+        for o in self.objects:
+            if ((hasattr(o, 'id') and o.id == object_id)
+                    or (hasattr(o, 'uuid') and o.uuid == object_id)):
+                o.delete()
+                break
+        else:
+            raise PyMISPError('No object with UUID/ID {} found.'.format(object_id))
+
```

**Comment by chrisinmtown** [comment]
But I'm not quite certain how to add the automated test, which is critical.

**Comment by Rafiot** [comment]
Thanks, done!

**Comment by chrisinmtown** [comment]
Glad to see the automated test!
