### ISSUE TITLE
I wanna test if my URL and AuthetKey are correct t

### ISSUE THREAD

**Issue by aymenbnl** [MISP/PyMISP#710]
I wanna test if my URL and AuthetKey are correct to connet my Instance MISP with PyMISP
i try to update Misp version and PyMISP version and it didn't work
so any one can help me please thank you.
![Capture d’écran du 2021-03-03 16-39-15](https://user-images.githubusercontent.com/76562306/109830768-17dbd980-7c3f-11eb-91fe-ef24c55f3a78.png)

**Comment by Rafiot** [comment]
You get a connection refused, the URL is incorrect. It needs to be in that format: `https://localhost/`

**Comment by aymenbnl** [comment]
thanks a lot it's work

**Comment by Rafiot** [comment]
:+1:
