### ISSUE TITLE
search_all() is missing?

### ISSUE THREAD

**Issue by jryberg** [MISP/PyMISP#712]
I'm trying to use search_all but it's removed?

`AttributeError: 'PyMISP' object has no attribute 'search_all'
`

It exist in examples but I can't find any related code. 

Has it been removed? How do I search for everything using search? 

Thanks!

**Comment by Rafiot** [comment]
It's been deprecated and removed more than 12 month ago. It's still in a few examples that need to be updated.

The problem of searchall is that is was not actually searching on everything, and returning way too much data, when it was returning anything.

This is the method you want to use, depending on what you're looking for: https://pymisp.readthedocs.io/en/latest/modules.html#pymisp.PyMISP.search

**Comment by jryberg** [comment]
Thank you
