### ISSUE TITLE
Trying to add events into MISP via PyMISP

### ISSUE THREAD

**Issue by aymenbnl** [MISP/PyMISP#713]
I'm new with MISP and i'm trying to add events with PyMISP from **create_events.py** but i don't know how !!
if someone can help me with giving me an exemple of script how i adding an event to MISP from **create_events.py** and with which cmd i can **run** the script. 
I've tried to solve this for a long time now without success as I find the documentation not very clear on this and it's getting very frustrating.
thank you.
![Capture d’écran du 2021-03-04 **16-35-16](https://user-images.githubusercontent.com/76562306/109988244-a451cf00-7d07-11eb-831c-c5371dda4696.png)**

**Comment by chrisinmtown** [comment]
well, you should run the script with python3.  When you do that, what happens?  Please post the output, but keep your authkey private.

**Comment by aymenbnl** [comment]
sorry but i don't know with wich command i run the script and can you give in exemple how i can add event because i've tried but i don't know how
thank you

**Comment by Rafiot** [comment]
I really don't get what you mean @aymenbnl. `python3` is the command you need on your system to run the script.
