### ISSUE TITLE
AV triggers on viper-test-files

### ISSUE THREAD

**Issue by IanGabes** [MISP/PyMISP#715]
Hi! 

My organization's AV engines are triggering on files in the `tests/viper-test-files` folder. The repository itself claims that real malware is contained withing that repository, but it seems like many of the files are neutered or testing samples (e.g `EICAR.com`)? This is not problematic for a simple clone of PyMISP (if one removes the reference to that sub-module), but does present itself with repositories higher up the dependency chain when initializing sub-modules recursively. I see references to testing the Viper framework, but only see a few usages of  `whoami.exe`. `sample2.pe` and  `chromeinstall-8u31.exe`  in the tests themselves. 

It is possible that the above files are benign, and we triggered on other files in the sub repo. I have a reporting tool that depends on PyMISP,  used on analyst workstations, and there is a certain element of surprise having suspicious binaries cloned with the dependencies :D 

What are your thoughts on removing this sub-module, and replacing the instances of the above binaries with benign binaries local to the repository itself?

Thanks!

**Comment by Rafiot** [comment]
Is you clone PyMISP and then remove the reference to `viper-test-files` in `.gitmodules`, you should be fine. Of course the test suite won work.

If you just want pymisp, you can also just do `pip install pymisp`.
