### ISSUE TITLE
[Question] Why do you set a default logging handler?

### ISSUE THREAD

**Issue by jloehel** [MISP/PyMISP#716]
https://github.com/MISP/PyMISP/blob/aee6945e95c647cf01d04fdf1282b6887744e041/pymisp/__init__.py#L6-L13

It's some kind of confusing if I configure logging on CLI level. [Python](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library) does not recommend to use any handler other than a NullHandler for libraries. Is there any special reason for it?

**Comment by jloehel** [comment]
Moved it to a discussion: https://github.com/MISP/PyMISP/discussions/717

**Comment by chrisinmtown** [comment]
I think the comment about not adding a handler is correct.  But IMHO you went a bit too far when you also removed the setLevel call.
