### ISSUE TITLE
get events filtered by tags

### ISSUE THREAD

**Issue by V0lundr** [MISP/PyMISP#720]
Hi,

I was wondering if it's possible to use an example script like ".\get_network_activity.py" or ".\get_csv.py" from examples to fetch different attributes (url, domain, ips, etc ... ) by using tags and not event IDs?

**Comment by Rafiot** [comment]
The scripts are examples, so yes, you can adapt them at will. The easiest one to change it probably `get_csv.py`, as it uses the `search` method, documented [there](https://pymisp.readthedocs.io/en/latest/modules.html#pymisp.PyMISP.search).

In your case, you want to pass a list of tags to the `tags` parameter.
