### ISSUE TITLE
problem to find my Automation key

### ISSUE THREAD

**Issue by aymenbnl** [MISP/PyMISP#724]
I install MISP today in virtual machine "ubuntu 20.04" but i don't find my Automation key, i try to find it by search in "/users/view/me" but i find nothing.
can someone help me where i can find it.
Thank you.
![166527802_194227205542362_629113327925059717_n](https://user-images.githubusercontent.com/76562306/112832319-0eeaf600-908d-11eb-9353-c7568da8f79a.png)
![167310319_145865047445134_6388934331351352654_n](https://user-images.githubusercontent.com/76562306/112832322-101c2300-908d-11eb-9b03-652868eb6be8.png)

**Comment by mokaddem** [comment]
Hey,
Based on the first screenshot you provided, I can see that you have the *advanced authkey* system enabled on your instance.
This system lets you create multiple API keys and potentially assign an expiration date on them.
You can do it by expanding the **Auth keys** tab of the `/users/view/me` url.
Cheers!
