### ISSUE TITLE
PyMISP 2.4.141 - when?

### ISSUE THREAD

**Issue by lu-chi** [MISP/PyMISP#728]
Hi. I just wanted to ask - what is a mean time to next pyMISP udpate following the one for MISP?

**Comment by Rafiot** [comment]
I can do one tomorrow, it doesn't matter much as most of the changes are bugfixes and the version 2.4.140 is compatible with MISP 2.4.141 (you can generally assume that for every MISP release).

**Comment by lu-chi** [comment]
Thanks for reply. It's just due to version difference I saw mulitple times warnings in my logs. Due to a correlation between two different teams managing services I wanted to get some info on a mean time between MISP and pyMISP updates. I guess the difference is tiny however I wanted to confirm it's fine. Thanks once more.

**Comment by Rafiot** [comment]
Done, release out!
