### ISSUE TITLE
Search for "something.xml" leads to error

### ISSUE THREAD

**Issue by zeroq** [MISP/PyMISP#73]
When I try a misp.search_index(eventinfo="something.xml") the search fails:

Traceback (most recent call last):
  File "api.py", line 130, in <module>
    result = misp.search_index(eventinfo=title)
  File "/Users/jgo/git/PyMISP/pymisp/api.py", line 814, in search_index
    return self._check_response(response)
  File "/Users/jgo/git/PyMISP/pymisp/api.py", line 198, in _check_response
    raise PyMISPError('Unknown error: {}'.format(response.text))

It seems like MISP is returning XML instead of JSON in case the event title ends with ".xml". I did not expect output formating parameters to be part of the search string itself.

**Comment by Rafiot** [comment]
woah, this is weird.

**Comment by zeroq** [comment]
looks like it is more a MISP problem than a problem of the actual PyMISP, because if you type ".xml" in the filter input in list events view of MISP you also get an XML output with internal error. Are you also in touch with the MISP developers?

**Comment by Rafiot** [comment]
My bad, `search_index` is somewhat buggy, patching.
