### ISSUE TITLE
Update event with custom object

### ISSUE THREAD

**Issue by csirt-pj** [MISP/PyMISP#733]
Hi,
I come with a known problem regarding custom objects.

I created a custom object call cobaltstrike:
- OK in the UI
- manually populated in an event no problem

But in pymisp, I cannot use it with:
`obj = MISPObject('cobaltstrike')`
`obj.add_attribute('ip', '8.8.8.8')`

When I look at:
`obj._definition`
it is empty while it should contain object description.

Custom objects seem not being updated or propagated in some ways.
I looked at:
https://github.com/MISP/PyMISP/issues/462
but no solution either.

On the other side,, when I do:
`misp.get_object_template('cobaltstrike')`
I get the template properties fine.

If you have any clue, it will help a lot !

**Comment by Rafiot** [comment]
Just making sure: is the object template (the json file in the format used in this repository: https://github.com/MISP/misp-objects)

Simply doing `misp.get_object_template('cobaltstrike')` doesn't help, PyMISP/MISPObject need to be able to load the template in order to populate `obj._definition`.

For that to work you need to pass one of the two parameters:
* `misp_objects_path_custom`: path to a clone of the `misp-object` repo that contains your custom template
* `misp_objects_template_custom`: the template itself, as a python dictionary

Note that what you get from `misp.get_object_template('cobaltstrike')` is not template in the format in the template repository. It needs to be fixed, but isn't at this point.

**Comment by csirt-pj** [comment]
Hi, 
thank you for your (very prompt) answer !
the json is here:
`{
  "attributes": {

    "ip": {
      "categories": [
        "Network activity",
        "External analysis"
      ],
      "description": "IP Address",
      "misp-attribute": "ip-dst",
      "multiple": true,
      "ui-priority": 1
    },
    "nom-resolver": {
      "description": "Nom du resolver",
      "disable_correlation": false,
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "en-tete-serveur": {
      "description": "En-tête serveur",
      "disable_correlation": false,
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "format-certificat": {
      "description": "Format du certificat",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "nom-de-domaine": {
      "description": "Nom du domaine associé au certificat",
      "misp-attribute": "domain",
      "multiple": true,
      "ui-priority": 1
    },
    "date-enregistrement": {
      "description": "date d'enregistrement",
      "disable_correlation": true,
      "misp-attribute": "datetime",
      "ui-priority": 0
    },    
    "registrar": {
      "description": "Nom du resolver",
      "disable_correlation": false,
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "serveur-de-nom": {
      "description": "Serveur de nom",
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 1
    }
  },
  "description": "Tableau ANSSI CobaltStrike",
  "meta-category": "network",
  "name": "cobaltstrike",
  "requiredOneOf": [
    "ip"
  ],
  "uuid": "9a89d394-58d5-489c-bd58-1257974c295f",
  "version": 1
}`

Since MISP accepted it, I thought it was good.
I will try implement the solution, thanks !

**Comment by Rafiot** [comment]
That makes sense, `misp.get_object_template('cobaltstrike')` is just getting the template and it doesn't do anything else with it. if you just pass that to the `MISPObject` call, it should do the trick.

**Comment by chrisinmtown** [comment]
Or maybe someday, if https://github.com/MISP/PyMISP/issues/659 gets some attention, PyMISP will no longer require the custom object definition on the client side :)

**Comment by Rafiot** [comment]
Yes and no: you don't want to query a remote instance every time you create an object.

So yes, I need to add a method to do that when I find the time, but the recommended approach is and will always be to have the templates locally: it is faster and more relieble.

**Comment by chrisinmtown** [comment]
I agree, don't fetch an object definition at each create, definitely should be cached in the PyMISP object.  That seems to me the fastest and most reliable :)

**Comment by chrisinmtown** [comment]
@Rafiot tried to explain a few comments ago that the object template must be available to the PyMISP client code. One way is as a file on the filesystem. All the standard object templates are in a directory like ~/.virtualenvs/py36/lib/python3.6/site-packages/pymisp/data/misp-objects/objects. So your new object could have its own directory below that with a definition.json file.  Another gotcha - the format of the definition.json file there is NOT what the server hands back.  Check one out; for example here is the first part of the yara object's definition.json file:
```
{
  "attributes": {
    "comment": {
      "description": "A description of the YARA rule.",
      "misp-attribute": "comment",
      "ui-priority": 0
    },
```

**Comment by Rafiot** [comment]
Right, yes, as @chrisinmtown says, this method isn't usable for this usecase, sorry.

**Comment by csirt-pj** [comment]
Perfect !
I sumup for further reference:

- create object on server
- `tmp = misp.get_object_template(tmp_id, pythonify=True)`
- get the local template path with: `tmp.misp_objects_path`
- go to this path and put the objet (folder+definition.json)
- kill python
- `from pymisp import MISPObject`
- `myobj = MISPObject('mycustomobject')`
- `myobj.add_attribute(type, value)`
- `misp.add_object(event_id, myobj, pythonify=True)`

Thank you very much !
