### ISSUE TITLE
Unkown Error: "no reason specify"

### ISSUE THREAD

**Issue by itruivitorino** [MISP/PyMISP#735]
When  running "python3 misp.py" I get the following error: (the connector still runs but I can't send events or anything)

```
ERROR:root:No reason specify
Traceback (most recent call last):
  File "misp.py", line 1299, in <module>
    mispConnector.run()
  File "misp.py", line 160, in run
    self.helper.connect_id, friendly_name
  File "/usr/local/lib/python3.6/site-packages/pycti/api/opencti_api_work.py", line 72, in initiate_work
    query, {"connectorId": connector_id, "friendlyName": friendly_name}
  File "/usr/local/lib/python3.6/site-packages/pycti/api/opencti_api_client.py", line 275, in query
    {"name": error_name, "message": main_error["data"]["reason"]}
ValueError: {'name': 'UnknownError', 'message': 'No reason specify'}
```

Python: 3.6.8
OpenCTI: 2.4.141
MISP: {"major":2, "minor":4, "hotfix":142}

I also get a warning because of the version, I downloaded the new version (2.4.142) but for some reason it appears that the connector is still running the (2.4.137.1).

I'm completely lost on this.

**Comment by adulau** [comment]
Thanks for your issue but It seems that you are using another library "pycti" https://github.com/OpenCTI-Platform/client-python -  Can you open an issue there?
