### ISSUE TITLE
Help with paginated attribute search specifying tags returning some with no tags

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#740]
MISP 2.4.140, PyMISP 2.4.140

Any idea why when I perform paginated `pymsip.search` calls for attributes with page size 10,000 as below specifying tags, the final results have many attributes returned without any tags?

Here's the args for the first call, and so on incrementing `page`...
```
{
  'controller': 'attributes',
  'tags': {
    'OR': [
      'nist-cyber-framework:function="protect"',
      'nist-cyber-framework:function="detect"'
    ]
  },
  'timestamp': ('2021-02-03', '2021-04-05'),
  'limit': 10000,
  'page': 1
}
```

**Comment by Rafiot** [comment]
Just checking: are the events the attributes are part of tagged with one of the two tags?

**Comment by github-germ** [comment]
Yes!! I should've thought of that. Mystery solved. Thanks.

**Comment by github-germ** [comment]
Hmmm.... let me try adding `include_event_tags` to my search query. Stay tuned.

**Comment by github-germ** [comment]
Of course that works fine!

_Note to self: RTFM_
