### ISSUE TITLE
pymisp.exceptions.PyMISPError: last_seen has to be after first_seen

### ISSUE THREAD

**Issue by cudeso** [MISP/PyMISP#742]
Hello,

When using PyMISP to fetch a list of events and pythonify them I get this error message

```
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 2411, in search
    me.load(e)
  File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 1611, in load
    self.from_dict(**event)
  File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 1683, in from_dict
    [self.add_attribute(**a) for a in kwargs.pop('Attribute')]
  File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 1683, in <listcomp>
    [self.add_attribute(**a) for a in kwargs.pop('Attribute')]
  File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 1822, in add_attribute
    attribute.from_dict(type=type, value=value, **kwargs)
  File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 493, in from_dict
    self.last_seen = ls
  File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 264, in __setattr__
    raise PyMISPError(f'last_seen ({value}) has to be after first_seen ({self.first_seen})')
pymisp.exceptions.PyMISPError: last_seen (2021-04-16T00:00:00.000000+00:00) has to be after first_seen (2021-04-16 08:35:00+00:00)
```

This concerns the CIRCL event uuid **d6b4bb0d-07bc-4834-9811-e0e642a5b492** where there is indeed a last seen before a first seen.

![MISP](https://user-images.githubusercontent.com/256028/118012719-a3fe3180-b351-11eb-86fb-ed21691d51d8.png)

Although the initial error comes from MISP accepting a last_seen before a first_seen, PyMISP should not stop processing the rest of the data

PyMISP & MISP 2.4.140

**Comment by chrisinmtown** [comment]
The PyMISP code checks for this condition here, seems kind of reasonable that a query would never succeed:

https://github.com/MISP/PyMISP/blob/db1ffe7be63567a81fddd62fb3054f46c46e7acd/pymisp/mispevent.py#L272

I don't know but a first-seen value that occurs *after* the last-seen value seems like a case of egregiously bad data.

**Comment by Rafiot** [comment]
yep, it was a bug on MISP side (also fixed), and this commit removes the exception: https://github.com/MISP/PyMISP/commit/286712d0e1cb152f9b0f75b213bbadcd2434eaed

It will be in next PyMISP release.

**Comment by cudeso** [comment]
Thank you! Appreciate the quick response!
