### ISSUE TITLE
Inquiry - Looking for automated import of stix 1.1

### ISSUE THREAD

**Issue by NetEyes** [MISP/PyMISP#746]
Greetings,

In MISP dashboard, it has a GUI in which I can import stix 1.1 manually. I wonder if there is a feature that it can do this automatically? I can put all the stix files in a folder, and MISP can pick it up automatically. Please advise.

Regards,
Orlando

**Comment by NetEyes** [comment]
I'm not very familiar with python ... how this script works?

# STIX 1
python3 ingest_stix.py --version 1 --path _PATH_TO_YOUR_FILES_/stix_files*.xml

- do i have to run this every time?
- if i exit the session, does the script will continue to run? 

I would like this script that will run in a schedule time and keeps monitoring files in a specific folder.
Please advise.

**Comment by adulau** [comment]
It depends of your configuration. Yes you can run this script in a crontab entry, move the imported files. It's more depending of your local setup.
