### ISSUE TITLE
which python script has this function - "upload_stix"?

### ISSUE THREAD

**Issue by NetEyes** [MISP/PyMISP#748]
which python script has this function - "upload_stix"?
I'm not very familiar with python and I would like to attempt to develop a similar function in C#.

My objective is to upload stix 1.1 files to MISP (https://[ip]/events/upload_stix/) in C#. 
If you can guide me on how C# able to talk to MISP that would be great.

Thanks.

**Comment by adulau** [comment]
Maybe you want to have a look at https://github.com/MISP/MISP/tree/2.4/tools/ingest_stix which is the recent version for import STIX in MISP. You can call the Python script from C#.
