### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by wagner-certat** [MISP/PyMISP#75]
Is there a changelog somewhere?

It'd be nice to have this as packager/developer to see if there are any changes affecting me.

**Comment by adulau** [comment]
In addition to the standard [MISP Changelog](https://www.misp.software/Changelog.txt), I just added the PyMISP Changelog at the following location:

http://www.misp.software/PyMISP-Changelog.txt

I hope this helps.

**Comment by wagner-certat** [comment]
If it was in the repo itself, it would be much easier.

**Comment by FloatingGhost** [comment]
There ya go

**Comment by wagner-certat** [comment]
Thanks!
