### ISSUE TITLE
PyMISP missing tags 2.4.145, 2.4.146, 2.4.147

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/PyMISP#772]
Please keep up with MISP project!

We instruct our users to install the PyMISP that matches the MISP server version.  So for example our server shows 2.4.145, so our users try to find that PyMISP package. But PyPI doesn't have it. Then we get a lot of confused questions and have to try to make a recommendation, just how old of a PyMISP is ok to use with the latest server.

Thanks in advance!

**Comment by Rafiot** [comment]
As long as you have no warning when you connect to MISP, you're cool. There were barely any changes in PyMISP for the last couple of months, so it's not a problem.

The next one will be released early August.

**Comment by Rafiot** [comment]
Done.
