### ISSUE TITLE
Malware in package

### ISSUE THREAD

**Issue by UrmelAusDemEis** [MISP/PyMISP#778]
Hello Everyone,

I started working with PyMisp and a Misp-Docker-Container to develop an automated tool. It came to my attention, that due to the tests relying on viper-test-files, there is Malware pulled into the repository.

I think it would be wise, to at least encrypt the malware and decrypt them, when they are needed for the tests. Besides generating AntiVirus-Warning in our IT-Department, it is also a severe security risk, as even viper-test-files states "This repository contains malwares used for testing, do not just run them for fun."! 

Please consider removing the tests or encrypting the malware and decrypting them on demand when the tests are run.

Thank you!

**Comment by Rafiot** [comment]
I'd recommend not to run test on a prod environment (they pull extra deps you don't need for production use). Encrypting the files won't help if you run the tests anyway, as they will definitely need to be decrypted.

Maybe you want to skip the tests in https://github.com/MISP/PyMISP/blob/main/tests/testlive_comprehensive.py?

**Comment by UrmelAusDemEis** [comment]
Hey Rafiot,

thank you for your answer! I do not want to run the tests. The problem is merely the malware being present on the machine, which is a security risk.
This leads me to a question: Is PyMISP needed in the main repository? Recursive cloning of the repository leads to the download of the malware.

**Comment by Rafiot** [comment]
Well, your AV says it's a security risk. It will only be one if you run the files on windows.

PyMISP is required, yes, but this submodule isn't required. Let me sort it out.

**Comment by Rafiot** [comment]
That should be fixed, let me know how it goes.

**Comment by UrmelAusDemEis** [comment]
That's awesome! Thank you very much!
