### ISSUE TITLE
Is there a PyMISP 2.4.149?

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#798]
```
$ git checkout v2.4.149
error: pathspec 'v2.4.149' did not match any file(s) known to git.
$
```

https://github.com/MISP/PyMISP/blob/main/pymisp/__init__.py#L1
```
__version__ = '2.4.148'
```

**Comment by Rafiot** [comment]
There will be a v 2.4.250.

As each time we don't bump PyMISP for a MISP release, it means there were no changes or new features that required a new release.

**Comment by github-germ** [comment]
thx
