### ISSUE TITLE
Tag attributes in memory for better performance

### ISSUE THREAD

**Issue by naacbin** [MISP/PyMISP#801]
Hi,

I would like to know if it's possible to tag attributes in memory with their uuids ? These attributes can be from multiple event at the same time.

Currently I'm doing it like below, however it takes too much time since there is 1 API call per uuid.
```python
for uuid in uuids:
    for tag in tags:
        result.append(misp.tag(uuid, tag, local=local_tags))
```

Tags used are already created in MISP.

Thank you.

**Comment by naacbin** [comment]
Any news ?

**Comment by Rafiot** [comment]
I don't think there is a way to tag multiple UUIDs are the time on MISP side, but I might be wrong. @iglocska @mokaddem might be able to answer that one.
