### ISSUE TITLE
jsonschema requirement update?

### ISSUE THREAD

**Issue by juju4** [MISP/PyMISP#815]
While working on ail framework, I identified a dependency conflict:

`pymisp 2.4.152 has requirement jsonschema<4.0.0,>=3.2.0, but you'll have jsonschema 4.3.2 which is incompatible.`
`pymispgalaxies 0.2 has requirement jsonschema<5.0,>=4.3, but you'll have jsonschema 3.2.0 which is incompatible.`

Can those two aligned on current latest? 4.3.2 per https://pypi.org/project/jsonschema/#history

Thanks

**Comment by Rafiot** [comment]
jsonschema 4+ isn't compatible with python 3.6. The bump on pymispgalaxies was a mistake, updating it now.

**Comment by Rafiot** [comment]
Fixed: https://github.com/MISP/PyMISPGalaxies/commit/e9cf3b2ba0cd4368b5e9543b2159de944ce7568a
