### ISSUE TITLE
PyMISP.get_object() does not include object references

### ISSUE THREAD

**Issue by 3c7** [MISP/PyMISP#830]
The method `get_object()` returns only objects without references:

```
>>> misp = pymisp.PyMISP(<URL>, <KEY>)
>>> misp.global_pythonify = True
>>> e = p.get_event("156465d0-1a67-4c89-9901-9580211460b1")
>>> for obj in e.objects:
...    if len(obj.references) > 0:
...        print(obj.uuid)
af5a7db8-4d1a-4197-8a60-5deb09a07fbb
8ec46daf-d766-4a2d-89f3-f08cf5335a3b
df762176-e491-437e-b07d-0c1ca86633a8
524944f8-4d7f-468d-976c-317fa53c9e01
4664eda1-d8f2-4eae-8d73-f4381fba5b12
26367e99-394c-4737-bba5-db97681916fe
1b853536-181b-438c-a55e-0730ae96dbe3
7bfc6885-3cb2-4d96-9fdf-994ee8148987
bc51ca3a-1ed8-41bf-bfc2-71e95336a4ac
ae326104-bc70-4410-8189-e48f45e0d812
>>> o = misp.get_object("af5a7db8-4d1a-4197-8a60-5deb09a07fbb")
>>> o.references
[]
```

It would be great to have references included. This would allow easy grabbing of objects and their references without looping over all objects of an event.

**Comment by 3c7** [comment]
Just found out that `MISPEvent.get_object_by_uuid()` allows this, however, I think it would be useful to include references in the above mentioned method as well.

**Comment by Rafiot** [comment]
Yeah, that's a limitation on MISP side, a reference is not part of an object, so the object controller doesn't have access to them.

**Comment by 3c7** [comment]
Ah okay, makes sense. Well, in my use case, I already have the event object anyway, so I can access the "complete" objects via `MISPEvent.get_object_by_uuid()`, but missed it before.
