### ISSUE TITLE
Add custom object attribute to specific event using PyMISP

### ISSUE THREAD

**Issue by woodonggyu** [MISP/PyMISP#852]
Hello.

I hope to add custom object attribute to specific event using PyMISP.
When i tried it, it didn't work.

I did something like below first.
* Create Custom Object (/var/www/MISP/app/files/misp-objects/objects/test)

```code
{
  "attributes": {
    "stie": {
      "description": "Leaked site.",
      "misp-attribute": "domain",
      "multiple": true,
      "ui-priority": 0
    },
    "exposed": {
      "description": "When the leak has been exposed",
      "disable_correlation": true,
      "misp-attribute": "datetime",
      "ui-priority": 0
    },
    "leaked": {
      "description": "When the leak has been accessible or seen for the first time.",
      "disable_correlation": true,
      "misp-attribute": "datetime",
      "ui-priority": 0
    },
    "victim": {
      "description": "Victim IP Address",
      "misp-attribute": "ip-dst",
      "ui-priority": 1
    },
    "source": {
      "description": "Source information",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "username": {
      "description": "Leaked username",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 0
    }
  },
  "description": "Leaked crendentials",
  "meta-category": "misc",
  "name": "test",
  "required": [
    "site",
    "username",
    "leaked",
    "exposed",
    "victim",
    "source"
  ],
  "uuid": "98f7e7dd-c6ce-4620-9670-f595d1abced7",
  "version": 1
}
```

* Request add_object
```python
for credential in leaked_credentials:
    test = MISPObject(name="test", misp_objects_path_custom="/var/www/MISP/app/files/misp-objects/objects", strict=True)

    test.add_attribute(object_relation="site", value=credential["site"], type="domain")
    test.add_attribute(object_relation="leaked", value=credential["leaked"], type="text")
    test.add_attribute(object_relation="exposed", value=credential["exposed"], type="text")
    test.add_attribute(object_relation="source", value=credential["source"], type="text")
    test.add_attribute(object_relation="victim", value=credential["victim"], type="ip-dst")
    test.add_attribute(object_relation="username", value=credential["username"], type="text")

    tip = ExpandedPyMISP(url="url", key="key")
    event_object = tip.get_event(event="event_id")
    event_object.add_object(test)

AttributeError: 'dict' object has no attribute 'add_object'
```

**Comment by Rafiot** [comment]
Assuming the `url`, `key` and `event_id` are set to valid values, you're almost there. 

You need to add `pythonify=True` to the `get_event` call, so PyMISP turns the dict into a MISPEvent object:
```event_object = tip.get_event(event="event_id", pythonify=True)```

Then, `event_object.add_object(test)` will work (assuming the `event_id` you passed along exists). 

And finally, in order to populate the event on your MISP instance, you need to do `tip.update_event(event_object)`.

And no need to use `ExpandedPyMISP` anymore, it is an alias for `PyMISP`.

------

If you want to make it slightly faster, you can also directly call `tip.add_object("event_id", test)`, and it will directly add the object to MISP without the need to fetch the existing event.

**Comment by woodonggyu** [comment]
@Rafiot  Thanks for answer. But it doesn't work.

The code tried like this:

```
  test = MISPObject(name="test", misp_objects_path_custom="/var/www/MISP/app/files/misp-objects/objects")

  test.add_attribute(object_relation="site", value=credential["site"], type="domain")
  test.add_attribute(object_relation="leaked", value=credential["leaked"], type="text")
  test.add_attribute(object_relation="exposed", value=credential["exposed"], type="text")
  test.add_attribute(object_relation="source", value=credential["source"], type="text")
  test.add_attribute(object_relation="victim", value=credential["victim"], type="ip-dst")
  test.add_attribute(object_relation="username", value=credential["username"], type="text")

  # case 1
  print(tip.add_object(event=event["event_id"], misp_object=woowa_credentials))
  
  # case 1. result

  Something went wrong (405): {'name': 'You do not have permission to use this functionality.', 'message': 'You do not have permission to use this functionality.', 'url': '/objects/add/6a28ab87-16ae-40d4-8f51-9aa85a3e23ea'}
  {'errors': (405, {'name': 'You do not have permission to use this functionality.', 'message': 'You do not have permission to use this functionality.', 'url': '/objects/add/6a28ab87-16ae-40d4-8f51-9aa85a3e23ea'})}

  # case 2
  event_object = tip.get_event(event=event["event_id"], pythonify=True)
  print(event_object.add_object(test))

  # case 2. result : If you check the corresponding event, no object attributes have been added.
  <MISPObject(name=test)
```

**Comment by Rafiot** [comment]
case 1: it says you do not have the permission to do that. My guess is that the event is owned by an other org than yours?

case 2: `event_object.add_object(test)` adds the object to the event in memory, not on the MISP instance. You can try `tip.update_event(event_object)` after you did `event_object.add_object(test)` But you seem to have a permission issue, it will still be there.

**Comment by woodonggyu** [comment]
@Rafiot 

In my Instsance, There is only one organization. So, I think these issue is strange.
and then I tried use new `API KEY` (for Admin Role). but still it doesn't work.

```python
event_object = tip.get_event(event=event["event_id"], pythonify=True)
tip.update_event(event_object)
tip.add_object(event_object, woowa_credentials)

# result
Something went wrong (403): {'saved': False, 'name': 'Could not edit Event', 'message': 'Could not edit Event', 'url': '/events/edit/202', 'errors': 'Event could not be saved: Event in the request not newer than the local copy.', 'id': '202'}
Something went wrong (403): {'saved': False, 'name': 'Could not add Object', 'message': 'Could not add Object', 'url': '/objects/add', 'errors': 'Object could not be saved.\ntemplate: No valid template found and object lacking template information. (meta-category)'}
```


I think when I get MISPObject(), Information is not received normally.

Should I add the `misp_objects_template_custom` parameter? 
If "yes", What value should be entered? (ex. custom template directory name or definition.json)

```python

# success
woowa_credentials = MISPObject(name=event["object"],
                               misp_objects_path_custom="/var/www/MISP/app/files/misp-objects/objects")

# fail
woowa_credentials = MISPObject(name=event["object"],
                               misp_objects_path_custom="/var/www/MISP/app/files/misp-objects/objects", strict=True)
```

**Comment by Rafiot** [comment]
You keep getting different messages, so it's a good sign.

The first error (`Could not edit`): you're fetching the event, and pushing it straight back without changing it. MISP refuses it because as you're not changing anything in the event, the timestamps are not modified and it raises the error `'Event could not be saved: Event in the request not newer than the local copy.'`.

The 2nd error: This one is a bit weirder (assuming the template you're using is the one in the first message in this thread) because it seems MISP thinks the template is missing the `meta-category` key.
After creating the object, can you to the following: `print(event_object.to_json(indent=2))`, and share it? 

Regarding passing `misp_objects_path_custom` to `MISPObject`, if you have a valid template, you should be able to pass `strict=True`. What is the error message you're getting when you say it fails?

**Comment by woodonggyu** [comment]
@Rafiot Thanks your answer. The resulting values ​​are as follows.

```python
print(MISPObject(name="test", misp_objects_path_custom="/var/www/MISP/app/files/misp-objects/objects", strict=True))

result : pymisp.exceptions.UnknownMISPObjectTemplate: test is unknown in the MISP object directory.

+ info. Already made a directory and 'definition.json' file.
```

**Comment by Rafiot** [comment]
Just making sure, try to run the following command with the same user as the one you use to run your script:

`ls -la /var/www/MISP/app/files/misp-objects/objects/test/definition.json`

Because if the file exists, it should work fine, so I'm suspecting (?) a permission issue.

**Comment by woodonggyu** [comment]
@Rafiot I already checked.

```
$ ls -al /var/www/MISP/app/files/misp-objects/objects/test
drwxr-sr-x   2 www-data www-data  6144 Jul 28 02:23 .
drwxrwsr-x 289 www-data www-data 14336 Jul 27 00:44 ..
-rw-r--r--   1 www-data www-data  1255 Jul 27 06:09 definition.json
```

**Comment by Rafiot** [comment]
And the script is running as www-data on the same machine as where the template lives, right?

**Comment by woodonggyu** [comment]
yes right. now the permissions of the script file are the same.
but when I tried it, it doesn't work.

```python
print(MISPObject(name="test", misp_objects_path_custom="/var/www/MISP/app/files/misp-objects/objects/", strict=True))

result : pymisp.exceptions.UnknownMISPObjectTemplate: woowa-credentials is unknown in the MISP object directory.

```

**Comment by woodonggyu** [comment]
when I try this, it is work.

```python
  custom_template = tip.get_object_template(object_template=event["object_identifier"], pythonify=True)
  test = MISPObject(name="test", misp_objects_template_custom=custom_template, strict=True)
  
  print(test)
  print(test.to_json(indent=2))

  result : 
  
  <MISPObject(name=test)
  {
    "name": "test",
    "meta-category": "misc",
    "template_uuid": "98f7e7dd-c6ce-4620-9670-f595d1abced7",
    "description": "Leaked test",
    "template_version": "1",
    "uuid": "b1540131-1880-42be-a839-5f1d6e1ad09e",
    "distribution": "5",
    "sharing_group_id": "0"
  }

```

**Comment by woodonggyu** [comment]
now, it occur new problem.

```python
  custom_template = tip.get_object_template(object_template=event["object_identifier"], pythonify=True)
  test = MISPObject(name="test", misp_objects_template_custom=custom_template, strict=True)
  test.add_attribute(object_relation="site", value=credential["site"], type="domain")
  
  # result
  KeyError: 'attributes'

```

**Comment by Rafiot** [comment]
can you give me the whole stacktrace, please? not sure where the `KeyError: 'attributes'` exception comes from.

**Comment by woodonggyu** [comment]
Of course.

When I run the following code, an error occurs.
`test.add_attribute(object_relation="site", value=credential["site"], type="domain")`

```python
in. add_attribute()

1022. if object_relation in self._definition['attributes']:


self._definition = <MISPObjectTemplate(self.name)
self._definition hasn't 'attribute' key.
```

<img width="1331" alt="스크린샷 2022-07-29 오전 12 08 08" src="https://user-images.githubusercontent.com/43948634/181572778-6555923c-623e-4476-ab93-710f2ebb283c.png">

**Comment by woodonggyu** [comment]
@Rafiot 
I wonder, the script means "python script"? if "yes", it is not.
MISP instance is running in AWS. and I test to my laptop.

`And the script is running as www-data on the same machine as where the template lives, right?`

**Comment by Rafiot** [comment]
Alright, two options there:
1. ignore the template all together and initialize the object manually (you'll need to pass the type of each attribute)
2. get the template on the same operating system you're running the script on (your laptop), update the path accordingly, and try again. 

The 2nd option is how you're supposed to use `misp_objects_template_custom`

**Comment by woodonggyu** [comment]
It helped a lot. Thank you so much.

In case 1. If you have example code, Could you give me the example code?

**Comment by Rafiot** [comment]
yes, look at the section `User defined objects` here: https://github.com/MISP/PyMISP/blob/main/docs/tutorial/FullOverview.ipynb 

```
misp_object = GenericObjectGenerator('my-cool-template')
# The parameters below are required if no template is provided.
misp_object.template_uuid = uuid4()
misp_object.templade_id = 1
misp_object.description = "foo"
setattr(misp_object, 'meta-category', 'bar')

misp_object.add_attribute(object_relation="site", value=credential["site"], type="domain")
misp_object.add_attribute(object_relation="leaked", value=credential["leaked"], type="text")
...

tip.add_object(<eventID>, misp_object)
````

Not having a template is considered bad practice, but it will work.

**Comment by woodonggyu** [comment]
@Rafiot I really appreciate your help in resolving the problem.

I just created a custom template locally and tried it, and it works fine.

**Comment by Rafiot** [comment]
Excellent! And if you just grab your template from the server, you can just get it all working as it is recommended.

**Comment by simillo01** [comment]
Hi everyone, @Rafiot just a comment to add to this dicussion that helped me a lot.
**Steps to reproduce:**
1) create the custom object folder and definition.json file in path `/var/www/MISP/app/files/misp-objects/objects` 
2) name the folder like your custom object name, see below the example.
Sample custom object:
`
{
    "name": "same-name-as-the-custom-object-misp-folder",
    "uuid": "give-it-a-UUID",
    "description": "lalalalala",
    "meta-category": "misc",
    "version": 20250123,
    "attributes": {
        "example-attribute": {
            "description": "Sample attribute",
            "misp-attribute": "text",
            "ui-priority": 1, #order of the attribute in the UI
            "values_list": [ #list of acceptable values that you want the UI user to select from
                "one",
                "two etc.",
            ]            
        }
    }
}
`
3) chmod the folder and the file with same permission as the other folders and files inside /object
4) In my case i was running the following script in local on my machine, so not in the MISP server:

`

    MISP_BASEURL = ""

    MISP_KEY = ""

    VERIFY_CERT = False  # Change to True if your MISP instance uses a valid certificate
    
    misp = PyMISP(MISP_BASEURL, MISP_KEY, VERIFY_CERT)
    
    distribution = 0
    threat_level = 4
    analysis = 0
    
    event_data = {
        "info": "event title",
        "tags": [
            #list of tags
        ],
        "custom_object": {
            "name": "custom-obj",
            "attributes": {
                 #custom attributes list
            }
        }
    }
    create_and_upload_event(event_data, misp, distribution, threat_level, analysis)
`

function code:

`

    import json
    from pymisp import MISPEvent, MISPObject
    
    def create_and_upload_event(event_data, misp, distribution=0, threat_level=4, analysis=0):
        try:
            event = MISPEvent()
            event.info = event_data['info']
            event.distribution = event_data.get('distribution', distribution)
            event.threat_level_id = event_data.get('threat_level_id', threat_level)
            event.analysis = event_data.get('analysis', analysis)
                 
            for tag in event_data.get('tags', []):
                event.add_tag(tag)
                #print("Tag added: ", tag)
    
            attribute_type_mapping = {
                #omitted code
                #sample: "attribute-name": "text",
            }
    
            if 'custom_object' in event_data:
                obj_data = event_data['custom_object']
                custom_template = json.loads("".join(open(f"LOCAL_PATH_OF_CUSTOM_MISP_JSON_OBJECT.json").readlines()))
                misp_object = MISPObject(obj_data['name'], misp_objects_template_custom=custom_template, Strict=True)
                for attribute, value in obj_data['attributes'].items():
                    attr_type = attribute_type_mapping.get(attribute, "text")
                    misp_object.add_attribute(attribute, value, type=attr_type)
                    #print(f"Attribute added: {attribute} = {value}")
                event.add_object(misp_object)
    
            #print(misp_object.to_json(indent=2))
    
            uploaded_event = misp.add_event(event)
            print(f"Event created successfully: {uploaded_event['Event']['id']}")
    
            #misp.publish(uploaded_event['id'])
            #print(f"Event published successfully: {uploaded_event['Event']['id']}")
    
            event = misp.get_event(uploaded_event['Event']['id'])
            print(f"Event published status: {event['Event']['published']}")
        except Exception as e:
            print(f"Error uploading event: {e}")
`

5) As you can see from the code, i instead give the script, since it is running locally and not on the MISP server, a LOCAL path of the custom object json, so you need to have a local copy of that file in order to reference it easily from the main script.

Hope it's clear for someone who has a slightly different case from theirs and anyway as @Rafiot said, you have always two options:
`1. ignore the template all together and initialize the object manually (you'll need to pass the type of each attribute).` BAD BOY
`2. get the template on the same operating system you're running the script on (your laptop), update the path accordingly, and try again.` GOOD BOY :)

Thank you for the great job you MISP guys do on keeping this project UP and RUNNING!

PS. Please @Rafiot tell the devs that MISP MUST HAVE the "AND" option when i search for attributes in the GUI! C'mon!

**Comment by RR19MR** [comment]
So, is it possible with pymisp script  use a custom object  which is successfully loaded in a MISP instance? I've tried, but I get the same error as here https://github.com/MISP/PyMISP/issues/852#issuecomment-1198202700 explains

**Comment by simillo01** [comment]
@RR19MR short answer: yes.

Long answer: i've wrote the following code on MISP 2.5 on Ubuntu 24.04

Here's my section of code:

`obj_data = event_object['custom_object']
            custom_template = json.loads("".join(open(f'custom-obj.json').readlines()))
            misp_object = MISPObject(obj_data['name'], misp_objects_template_custom=custom_template, Strict=True)

            for attribute, value in obj_data['attributes'].items():
                # get custom_template attribute type
                attr_type = custom_template['attributes'][attribute]['misp-attribute']

                if value:
                    misp_object.add_attribute(attribute, value, type=attr_type)
                    print(f"Attribute added: {attribute} = {value}")
            event.add_object(misp_object)
            print(misp_object.to_json(indent=2))`

My event_object['custom_object'] is:

`event_data = {
    "info": "event title",
    "tags": [
        #list of tags
    ],
    "custom_object": {
        "name": "custom-obj",
        "attributes": {
             #custom attributes list
        }
    }
}`

As said before, you have to have the json for the custom object already uploaded on "/var/www/MISP/app/files/misp-objects/objects" inside a folder and in a file named exactly "definition.json" with chown as www-data:www-data.

Hope that it's clear now.
