### ISSUE TITLE
Setting published=True on PyMISP.new_event() does not work

### ISSUE THREAD

**Issue by kralca** [MISP/PyMISP#86]
After adding attributes to the newly created Event no REST call to update the "published" status is made.

**Comment by FloatingGhost** [comment]
what, like doing
```python
n = pymisp.new_event(info="test")
# add attribs
pymisp.publish(n)
```
doesn't work?

**Comment by kralca** [comment]
Can we do it as follows?

n = pymisp.new_event(published=True)
# add attributes

Thanks



Sent with Good (www.good.com)

________________________________

**Comment by FloatingGhost** [comment]
```python
p = PyMISP(...)
event = p.new_event(info="some published event", published=True)
```

![works](https://i.gyazo.com/25b09faa2553d74571a7c8e7f44bf1e8.png)

Works as intended. Publishes event upon creation.

**Comment by kralca** [comment]
Sorry. I will test again and confirm.


________________________________

**Comment by FloatingGhost** [comment]
I think this is a MISP-side bug, lemme go check that :)

**Comment by FloatingGhost** [comment]
Ok yep, pretty sure this is a MISP-side bug
Have raised it on the main repo - give it a little while :)

**Comment by kralca** [comment]
I wonder if this behaviour in MISP (i.e. 'unpublish' after adding new attributes) is intended so that there needs to be a concsious decision to publish the new attributes.

Perhaps it is better to use PyMISP as follows (for example):

```
p = PyMISP(...)
event = p.new_event(info="some published event", published=False)
p.add_filename(event, 'some_file_name')
p.publish(event)
```

This seems to work.

Note there is a bug in PyMISP with the above approach when you set 'published=True' in the call to new_event() and later call p.publish(event) PyMISP thinks the event is already published and doesn't update the event in MISP.

**Comment by iglocska** [comment]
That is indeed correct, adding any attributes to an event should unpublish
the event.

**Comment by Rafiot** [comment]
I added a method that will solve your problem and doesn't expect you to have the whole MISP event in memory to publish.
