### ISSUE TITLE
Update event set_date 

### ISSUE THREAD

**Issue by toolost9** [MISP/PyMISP#884]
Hello, when i upload a json event i can't update the date.

This is my code:

```
d = time.strftime("%Y-%m-%d") #i also tried with d = time.strftime("%Y%m%d")
misp.add_event(event, pythonify=False) #it's ok i can see the event
misp.tag(event,'Test') #it's ok i can see the tag
event.set_date = d #date is not updated
misp.publish(event, alert=False) #it's ok the event is publish
```

Any suggestions?

**Comment by Rafiot** [comment]
Yes, `set_date` is a method. You need to do that: `event.set_date(d)`, then call `misp.update_event(event)`, and publish.

**Comment by toolost9** [comment]
Tried but nothing.

```
misp.add_event(event, pythonify=False)
misp.tag(event,'Test') 
event.set_date = ('2018-04-13') #put this date for example
misp.update_event(event)
misp.publish(event, alert=False)
```

![image](https://user-images.githubusercontent.com/87522813/204621349-931338c2-3bf7-4754-847e-c6952a098161.png)

**Comment by adulau** [comment]
Read your line 3 and read what @Rafiot wrote. It’s a method not a assignment to a variable.

**Comment by toolost9** [comment]
Fixed and it works. Thanks and @adulau, @Rafiot
