### ISSUE TITLE
Update event if already exists is not possible any more with add_event

### ISSUE THREAD

**Issue by beberlacrapule** [MISP/PyMISP#89]
Hi,

I was using until now a pretty old version of PyMISP until now.
The function add_event used to return a requests Response object. This allowed me to get the existing event id when I tried to add an event that already exists (using the Location header).

Now, the add_event return only json body using Response.json() so I'm not able to get the event id in order to update it any more.
What is returned:
`{u'url': u'/events', u'message': u'Event already exists, if you would like to edit it, use the url in the location header.', 'errors': [u'Event already exists, if you would like to edit it, use the url in the location header.'], u'name': u'Event already exists, if you would like to edit it, use the url in the location header.'}`

Am I doing something wrong ?

**Comment by beberlacrapule** [comment]
Ok thanks :+1:

**Comment by FloatingGhost** [comment]
w-what? That won't work, I was just tagging this issue to remind people to stop using an outdated language.

**Comment by beberlacrapule** [comment]
Ho I thought it was a known Python2 issue and since I'm still using Python2 ...

**Comment by FloatingGhost** [comment]
Yes it's very, very obvious that you're using py2 because of the `u'string'` format. However for some absolutely retarded reason we do support python2, so it is still a valid thing

**Comment by beberlacrapule** [comment]
Ok and were you aware of the issue ? Does a (temporary) workaround exist ?

**Comment by FloatingGhost** [comment]
What's your use case? The easiest thing would be to use `new_event` rather than building a local JSON

**Comment by beberlacrapule** [comment]
Hi,
Sorry for my late answering.
My use case was the following:
1. Get event from instance A,
2. Perform some processing,
3. Add or update event to instance B.

With the previous versions, the update was made using the Location header from the response of MISP. The script in examples/copy_list.py is acting this way but has no been updated with current versions.

In fact I found the solution by myself :
`
event = source.get(event_id)
r = destination.add_event(event)
if 'errors' in r and 'Event already exists' in r['message']:
        print "Event already exists, performing an update ..."
        r = destination.update(event)
`

It is easier ...
I close the issue.

**Comment by iglocska** [comment]
Hmm interesting find. So the copy_list.py example is now broken? We should look into this.

Nice solution to your issue though!

Ping @Rafiot ;)

**Comment by beberlacrapule** [comment]
Yes, totally broken. The example is still using the HTTP Location header, which can not work any more.

I'm glad to help you!

**Comment by iglocska** [comment]
Interesting. Is the location header no longer returned by MISP?

**Comment by beberlacrapule** [comment]
No longer returned by PyMISP.
That is what I wrote in my first post.
The return is now always a dict(), containing either the requested MISP event or something like that if an error occurs:
```
{u'url': u'/events', u'message': u'Event already exists, if you would like to edit it, use the url in the location header.', 'errors': [u'Event already exists, if you would like to edit it, use the url in the location header.'], u'name': u'Event already exists, if you would like to edit it, use the url in the location header.'}
```

**Comment by iglocska** [comment]
Ah I see, thanks for the heads-up!
