### ISSUE TITLE
Is it possible to get the number of sightings for an attribute?

### ISSUE THREAD

**Issue by bdenning** [MISP/PyMISP#91]
I can see a number of methods available here: https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L1122

but all appear to add a sighting to an attribute, I can't find any obvious way in PyMISP to get the number of sightings for a given attribute (both positive and false-positive).

If it's not currently possible to do so, could someone just confirm that's the case?

**Comment by cudeso** [comment]
You can use search_sightings(context='attribute', context_id=attribute_id)
 
`
    def search_sightings(self, context='', async_callback=None, **kwargs):
        """Search sightings via the REST API
        :context: The context of the search, could be attribute, event or False
        :param context_id: ID of the attribute or event if context is specified
        :param type_sighting: Type of the sighting
        :param date_from: From date
        :param date_to: To date
        :param publish_timestamp: Last published sighting (e.g. 5m, 3h, 7d)
        :param org_id: The org_id
        :param source: The source of the sighting
        :param include_attribute: Should the result include attribute data
        :param include_event: Should the result include event data
        :param async_callback: The function to run when results are returned
`
