### ISSUE TITLE
Code hints don't show up

### ISSUE THREAD

**Issue by frank7y** [MISP/PyMISP#910]
Is it just me, can someone else confirm? In the latest release 2.4.168 method hints seem missing. I've tried installing an older version, such as 2.4.166 and it worked fine. So I guess it is an issue related to the latest release.
For reference, with this code I won't get any method suggestion at line 4:
```
event = MISPEvent()
event.info = 'Dummy event'
event = misp.add_event(event, pythonify=True)
event.
```

**Comment by Rafiot** [comment]
I haven't changed anything that should impact that, the hints should still be proposed. What are you using for the hinting?

**Comment by Rafiot** [comment]
Not sure either. The most recent change that might have an impact is that we require python 3.8 and recommend python 3.10, but I guess VSCode ships a recent version of Python (?)
