### ISSUE TITLE
MISPObject built with PyMISP are not following the Object template

### ISSUE THREAD

**Issue by minisephirot** [MISP/PyMISP#920]
Spoiled : Bear with me, I'm not a MISP aficionado, so this could be a case of 'yet another user being a donkey'

MISP Version : 2.4.167
PyMISP Version : 2.4.167
OS : Ubuntu 18.02

I've noticed that some objects I've automated to be pushed in MISP were correlated on attributes it shouldn't be :
![image](https://user-images.githubusercontent.com/22344585/217304892-c366cd16-5799-44ce-9964-d1dfafd8c86f.png)

Example : https://github.com/MISP/misp-objects/blob/main/objects/file/definition.json
The state attribute should not be correlated, but it is on my side. I've seen multiple objects being correlated this way, I could add correlations bans, but this feels weird.

I'm building the objects in a quite standard way :
```
new_misp_object: MISPObject = MISPObject(json_object[MISP_CATEGORY], strict=True, standalone=False)
misp_object.add_attribute(attribute_dictionnary[MISP_CATEGORY],value)
```
Am I doing something wrong there ?
Thank you

**Comment by Rafiot** [comment]
No worries, let's figure that one out.

Can you paste more of your code? For example, what is the content of `json_object`, `attribute_dictionnary`, and what is `MISP_CATEGORY`?

As you're passing `strict=True`, I think you're properly loading the template, and what you're doing should work just fine and use the default setting (and the default setting for `state` is to disable the correlation, *unless* it is overwritten).

**Comment by minisephirot** [comment]
Hi @Rafiot, thank you for your time.

As suspected (thank you for pointing me in the good direction) I've been silently overwriting the disable_correlation field on some objects. I thought the strict boolean would enforce the template on all fields.
