### ISSUE TITLE
Can I do a 'CONTAINS' type search on an attribute

### ISSUE THREAD

**Issue by amrroq** [MISP/PyMISP#922]
Hi,

New to PyMISP, but starting to get the hang of it...I have a script that outputs a list of domains that are in the format 'domain.tld', i.e. no preceding 'www' or appended path like 'domain.tld/.../' .  I want to check these domains against url and hostname indicator types, but I only get a match if I search for the attribute exactly how it appears in the event.  I want to be able to search a domain, like 'github.com' and have it return any url or hostname type event where 'github.com' appears.  If I search Events for domains like this in the GUI, it does what I want (see screenshot)--can this be accomplished w/ PyMISP as well?

Here is how I'm searching:
`misp.search(controller='attributes', type_attribute=['url', 'hostname'], value='domain')`
<img width="575" alt="GUI_eventsearch" src="https://user-images.githubusercontent.com/90286431/217682907-52fc4685-9b7e-4fec-b6d6-5f3be8070ea2.png">

**Comment by Rafiot** [comment]
Hi, try passing `'%domain%'` in the search query, I think it will work. But be careful, the request might take a while.

**Comment by amrroq** [comment]
Yep, that did the trick--thank you so much!
