### ISSUE TITLE
ModuleNotFoundError: No module named 'pymisp'

### ISSUE THREAD

**Issue by pelletier6666** [MISP/PyMISP#929]
Hello, 
I don't understand why python3 doesn't find the package pymisp when i tried to execute a simple python script with ```from pymisp import PyMISP``` although ```pip3 list/show 'pymisp'```  find it. 
 
![image](https://user-images.githubusercontent.com/51533854/219463192-b77f192c-bf68-4106-a913-cb998ce3f9b9.png)

However i get the following error from the ```python3 -m pymisp``` command. I don't know if it's linked.

![image](https://user-images.githubusercontent.com/51533854/219462265-a40b8be3-18a0-4580-8c1f-17d6f00c0e00.png)

**Comment by pelletier6666** [comment]
However it works with the latest install from github repository 
![image](https://user-images.githubusercontent.com/51533854/219464870-e10c617f-2012-43d9-9db9-e04d89351063.png)

**Comment by Rafiot** [comment]
The reason is that you run it with sudo and sudo changes the PATH. 

What happens if you run `python3 test.py`?

**Comment by pelletier6666** [comment]
Thanks for the answer, 
Actually now it works maybe because i've installed it with the latest install. 

But from my memories, i think it didn't works because i needed priviledge to execute someting in the ```/var/www/MISP/PyMISP/examples``` repository.

Maybe it should work with the www-data user but i can't find the password

**Comment by Rafiot** [comment]
yeah, it should have worked as `www-data`, I think.

Glad it works now!

**Comment by Nicolas-Pellletier** [comment]
No unfortunately it doesn't work with `sudo -u www-data` :(. 
I don't know how I ended up in the same situation as above. But anyway as above I got out of this error by reinstalling `pymisp` with github.

**Comment by Rafiot** [comment]
what do you mean by "reinstalling pymisp with github"?

**Comment by Nicolas-Pellletier** [comment]
I mean doing this: 
```
git clone https://github.com/MISP/PyMISP.git && cd PyMISP // not this part as i've already clone it
python3 setup.py install
```

**Comment by Rafiot** [comment]
every time you run that command, you'll break the perms unless you run it as www-data. 

What are you trying to achieve? And why are you running the example scripts from the webserver? You whould be running them locally from your own machine.

**Comment by Nicolas-Pellletier** [comment]
I'm trying to run an example script in the `PyMISP/example/*`. 
My server and client are on the same host same machine (locally) on localhost. I'm trying to launch the script via the terminal. 
But it didn't work with `sudo -u www-data python3 examples/last.py`. 

Nevertheless i came back to the `PyMISP` repository and then after doing a `python3 setup.py install` I could again make a `sudo -u www-data python3 examples/last.py`

**Comment by Rafiot** [comment]
I'd recommend you to clone the PyMISP repository somewhere else on the machine where it won't be impacted by updating MISP, initialize a new virtual environment, and run the script as your normal from there.

**Comment by Nicolas-Pellletier** [comment]
Ok thank you
