### ISSUE TITLE
load_csv.py - TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by pelletier6666** [MISP/PyMISP#931]
Hello,

For a reason that i don't know, the python script ```load_csv.py``` in ```examples``` directory doesn't work with the sample file given in the ```test``` folder.

**Command executed:** ```sudo python3 examples/load_csv.py -n file -p ./tests/csv_testfiles/valid_fieldnames.csv```

**Error:** ```TypeError: argument of type 'NoneType' is not iterable```

**Traceback:**
```
Traceback (most recent call last):
  File "/var/www/MISP/PyMISP/examples/load_csv.py", line 85, in <module>
    new_object = misp.add_object(args.update_event, o, pythonify=True)
  File "/usr/local/lib/python3.10/dist-packages/pymisp/api.py", line 581, in add_object
    event_id = get_uuid_or_id_from_abstract_misp(event)
  File "/usr/local/lib/python3.10/dist-packages/pymisp/api.py", line 87, in get_uuid_or_id_from_abstract_misp
    if 'uuid' in obj:  # type: ignore
 ```
  
It seems that the error is comming from this part (l87, apy.py): 
```
def get_uuid_or_id_from_abstract_misp(obj: Union[AbstractMISP, int, str, UUID, dict]) -> Union[str, int]:
 ....
 ....
# at this point, we must have an 
if 'uuid' in obj:  # type:          <-- error
  return obj['uuid']  # type: ignore
return obj['id']  # type: ignore
 ```
![image](https://user-images.githubusercontent.com/51533854/219880534-bbb98cd0-0177-4a34-aece-72331a524eb6.png)

**Comment by Rafiot** [comment]
The example script doesn't properly raises an exception, I'm fixing that.

The exception you're getting is because you're not passing the `-u <event_ID>` (where the `<event_ID>` is a valid event ID in the instance you're connecting to).

If you want to create a new event, you need to pass `-i <Info field>` and it will create a new event on the MISP instance.

**Comment by pelletier6666** [comment]
Thank you for these informations, 
Maybe you could put the ```event_ID``` as a required argument into ```argparse``` and update the example. I will open a pull request for that

**Comment by Rafiot** [comment]
Note that it is only required if no info field is given. But sure, please propose a PR that require one or the other.
