### ISSUE TITLE
sighting_per_uuid returning error with wrong URL

### ISSUE THREAD

**Issue by SparkyNZL** [MISP/PyMISP#94]
Hi 

Im adding some functionality to an application im using, but when i pass the uuid to add a sighting i get this

misp.sighting_per_uuid('290cfb09-702d-4a1a-92e6-b2f10d857695')
{u'url': u'/sighting/add/290cfb09-702d-4a1a-92e6-b2f10d857695', u'message': u'Could not add Sighting', u'errors': [u'Could not add Sighting'], u'name': u'Could not add Sighting'}

I had a look in the pymisp api and it should be posting to /sightings/add/[uuid] but the error im getting seems to be missing th "S" from sightings and im wondering if this may be a bug ?

im using 
pymisp 2.4.56 
ubuntu 16.04
misp 2.4.75

Cheers.

**Comment by FloatingGhost** [comment]
```
>>> p.sighting_per_uuid("5954e0fa-a70c-4d78-bd00-0796818694e2")
{'url': '/sighting/add/5954e0fa-a70c-4d78-bd00-0796818694e2', 'message': '1 sighting successfuly added.', 'name': '1 sighting successfuly added.'}
```

Seems to work just fine - attrib updates and all that

**Comment by FloatingGhost** [comment]
```python
def sighting_per_uuid(self, attribute_uuid):
        session = self.__prepare_session()
        url = urljoin(self.root_url, 'sightings/add/{}'.format(attribute_uuid))
        response = session.post(url)
        return self._check_response(response)
```

it actually uses the right endpoint - idk how the output changes though

**Comment by SparkyNZL** [comment]
ok so it could be a bug in the version im using then ? I have checked the
UUID and it matches. The user that is posting as has rights to be able to
do this,. it just all seems a little odd. I am using python 2.7 , but
everything else seems to work ok with the API ,  I gather the UUIDs in this
picture are the correct ones i should be using and not something im missing
?




[image: Inline image 1]

**Comment by FloatingGhost** [comment]
The fact that you get 
```{u'url': u'/sighting/add/290cfb09-702d-4a1a-92e6-b2f10d857695', u'message': u'Could not add Sighting', u'errors': [u'Could not add Sighting'], u'name': u'Could not add Sighting'}
```

seems to imply that it's reaching MISP but failing on that end - are you able to add a sighting via the UI?

**Comment by SparkyNZL** [comment]
OK bingo, im pulling the UUID of the event, not of the attribute :(

I think i need to go get some sleep :(

**Comment by FloatingGhost** [comment]
Cool cool, nice to know it's not totally broke~

Go get some sleep!
