### ISSUE TITLE
Provide add and remove functionality to `_fields_for_feed`

### ISSUE THREAD

**Issue by dragsu** [MISP/PyMISP#947]
`_fields_for_feed` property tracks what attributes to be exported when `_to_feed` function is called. When we want to add or remove values from this set, either we have to extend the relevant class or we can do `<class_instance>._fields_for_feed` and use `add` or `remove` functionality provided by `set` class (Linter won't be happy).

I think it is more appropriate to provide this functionality in AbstractMISP class.

**Comment by dragsu** [comment]
@Rafiot I'm happy to implement this.

**Comment by Rafiot** [comment]
The format for feeds is pretty static, why do you want to do that?

**Comment by dragsu** [comment]
An example use case would be, if I'm calling `_to_feed`  in MISPTag class the exported feed doesn't tell me whether the tag's local value is `true` or `false`. When I try to inject that data into another MISP it will get created as a global tag (since the default bool is False). This is not the expected behaviour.

**Comment by Rafiot** [comment]
Oh, right. Yeah, a local tag should really not be in a feed, it really doesn't make a lot of sense. I think PyMISP should strip them automatically.

Let me check that with my colleagues first, but I think this is the proper solution.

**Comment by Rafiot** [comment]
So yeah, confirmed, this need should be changed. @dragsu do you want to implement the fix? Or should I do it?

**Comment by dragsu** [comment]
@Rafiot Sorry,  are you suggesting to strip local tags from exporting? If that is the case I think there is  a param called `export_local` or similar to control that.

**Comment by Rafiot** [comment]
oh yeah, there is... totally forgot about it. Is it solving your problem?

**Comment by dragsu** [comment]
Not exactly. I want to export local tags. This can be done using the `with_local` flag. When local tags get exported, I also want to export `local` field as well. So I can import them correctly to another MISP instance.

**Comment by Rafiot** [comment]
Oh, right, this is an easy fix.

**Comment by dragsu** [comment]
Looks good to me.

**Comment by Rafiot** [comment]
Great, it will be in the upcoming release.
