### ISSUE TITLE
Update misp-objects to support new greynoise-ip object

### ISSUE THREAD

**Issue by bradchiappetta** [MISP/PyMISP#951]
Hello - I believe I need to request that pyMisp be updated to include our contribution to misp-objects: https://github.com/MISP/misp-objects/pull/387

Apologies if this isn't needed and this process is automatic.

**Comment by Rafiot** [comment]
It was missing in the package, I'm release a quick update and it will be available on pypi in a few min. Sorry for that.

**Comment by bradchiappetta** [comment]
Thank you!
