### ISSUE TITLE
ExpandedPyMISP.search() sneaky partial response

### ISSUE THREAD

**Issue by baphael** [MISP/PyMISP#956]
Hello,
is there some sort of known limitation for the `search()` method that could explain a incomplete response ? Here is my example : 

### First approach
```
from pymisp import ExpandedPyMISP
[...]
misp = ExpandedPyMISP(...)
search = misp.search(
    controller="attributes",
    type_attribute=["ip-dst", "ip-src", "domain", "hostname", "email-src", "email-dst", "url", "sha256", "user-agent"],
    pythonify = 1,
    [...]
)
```
Here, `len(search) > 500000`. And none of those attributes are of type `ip-src`, `url` or `sha256`.

### Second approach
```
from pymisp import ExpandedPyMISP
[...]
misp = ExpandedPyMISP(...)
search = {}
for type in ["ip-dst", "ip-src", "domain", "hostname", "email-src", "email-dst", "url", "sha256", "user-agent"]:
    search[type] = misp.search(
        controller="attributes",
        type_attribute=type,
        pythonify = 1,
        [...]
    )
```
Here, `len(search.values()) > 1000000` and none of the `search` keys are empty.

___

With the first approach, no exception are risen and I couldn't find anything that could explain a partial result in error logs. Some attributes (almost half of them actually) are just silently ommited !

Any ideas of what could be the reason for this sneaky behavior ?

**Comment by adulau** [comment]
You have to paginate with `page` and `limit`. 

https://www.misp-project.org/openapi/#tag/Attributes
