### ISSUE TITLE
attempts to add MISP exports into MISP via python result in empty event

### ISSUE THREAD

**Issue by maisenhe** [MISP/PyMISP#97]
I use the following code to upload either of the attached files and I end up with an empty event in MISP.

MISP
Currently installed version..... v2.4.77 (272d8930944c9e57812e256e4dd72136fef3fd7a)

`import json
from pymisp import PyMISP
from pprint import pprint
misp_url = "http://"
misp_key = "<redacted"
def init(url, key):
return PyMISP(url, key, 'misp')
misp = init(misp_url, misp_key)

#with open('MISP-test-files/vx-misp.xml', 'r') as f:
with open('MISP-test-files/vx-json.json', 'r') as f:
data = json.load(f)
test = misp.add_event(data)

#print(test)
print(json.dumps(data))`

I would prefer to be able to to feed MISP XML directly to the add_event() function but it only accepts json objects. Let me know what other info you require.
[Archive.zip](https://github.com/MISP/PyMISP/files/1160334/Archive.zip)

**Comment by Rafiot** [comment]
The XML format is deprecated in the API (and has been for years), It is only supported by MISP core (web interface) for legacy reasons but we strongly recommend you not to rely on it as it may be removed.

The JSON export you attached isn't in MISP format, so it won't work.

I can recommend the following options: 
* You import the XML file directly on MISP web interface (be careful, the document provided by hybrid analysis is very incomplete in comparison to the data they provide in the json export)
* Using free text import on the JSON export 
* Writing a converter hybrid analysis JSON to MISP JSON
* Getting hybrid analysis to propose a JSON MISP export

**Comment by adulau** [comment]
Maybe we should get in touch with hybrid analysis to update to the MISP JSON format?

**Comment by millerjkd** [comment]
Hello everyone. Attention has been brought to us and will transition to the JSON format asap (one week I hope).

**Comment by Rafiot** [comment]
@millerjkd Nice, thanks! And do not hesitate to get in touch if you have any questions

**Comment by adulau** [comment]
@millerjkd Let us know when it's available. Then, we can update the misp-project website and tweet about it ;-) Thanks a lot.

**Comment by millerjkd** [comment]
Alright, it is available now: 
![image](https://user-images.githubusercontent.com/20181242/28674731-8e08c9ee-72e6-11e7-9e0f-7f87ff04baf3.png)

I think this can be closed.

**Comment by Rafiot** [comment]
Thank you very much!
