### ISSUE TITLE
2.4.170 pymisp(controller='attributes', eventid=e) does NOT include category='Internal reference', type='link' attributes

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#973]
Hi @Rafiot !! ... With 2.4.170 `pymisp.search('controller=attributes')` does not include `category='Internal reference', type='link'` attributes. Likewise, in the WebUI `Download as...` into MISP JSON also does NOT include that attribute type.

When same tested in 2.4.167, both `pymisp.search` and `Download as...` do include that type. We no longer have 2.4.168 or 2.4.169 easily installed here to test when what appears to be an adverse change occurred.

If this is a MISP server-side issue, let me know if you want me to create a MISP/MISP issue.

Thanks!

**Comment by Rafiot** [comment]
That sounds like a bug on MISP side, yes.

**Comment by github-germ** [comment]
OK, I'll open an issue in MISP/MISP. Thanks!

**Comment by github-germ** [comment]
https://github.com/MISP/MISP/issues/9032
