### ISSUE TITLE
MISP Version problems 

### ISSUE THREAD

**Issue by crazypeter10** [MISP/PyMISP#980]
I made a script to send data from my honeypot to MISP server but i get 
![image](https://user-images.githubusercontent.com/76117464/235355401-0f9ddffd-559a-45bc-9a90-483272332669.png)

Then when i try to upgrade the version that i have  i get: 
![image](https://user-images.githubusercontent.com/76117464/235355439-d06ba795-7af0-430c-813a-b76c158df8ba.png)
Even if 
![image](https://user-images.githubusercontent.com/76117464/235355456-db05909a-dce5-4a6c-8eaf-86f971c217d7.png)

**Comment by Rafiot** [comment]
Are you using python 2.7? That would be my guess based on the list of versions it proposes.

PyMISP requires python 3.8 or more recent.

**Comment by crazypeter10** [comment]
I'm using 3+ i managed to get it to work with pip3 install git+https://github.com/MISP/PyMISP.git@tags/v2.4.170.1
